### ISSUE TITLE
r5107 boots to black screen

### ISSUE THREAD

**Issue by sprtm** [CloverHackyColor/CloverBootloader#101]
I updated to r5107 and now I get nothing but a black screen when Clover loads. I also tried to downgrade to r5102, r5103 and r5106, but same issue.

One time the GUI loaded, but stuck after I chose the startup disk. At some boots the theme startup chime plays, but still a black screen.

I have now downgraded to Dids' r5103 Clover build. For some reason Dids' automated Clover builds works without issues on my machine (but r5107 isn't available there).

[debug.log](https://github.com/CloverHackyColor/CloverBootloader/files/4381091/debug.log)

**Comment by gianfigueroa** [comment]
I have the same error, I need any fast solutions, can I downgrade clover??

**Comment by vectorsigma72** [comment]
> I updated to r5107 and now I get nothing but a black screen when Clover loads. I also tried to downgrade to r5102, r5103 and r5106, but same issue.
> 
> One time the GUI loaded, but stuck after I chose the startup disk. At some boots the theme startup chime plays, but still a black screen.
> 
> I have now downgraded to Dids' r5103 Clover build. For some reason Dids' automated Clover builds works without issues on my machine (but r5107 isn't available there).
> 
> [debug.log](https://github.com/CloverHackyColor/CloverBootloader/files/4381091/debug.log)

66 Themes??

**Comment by sprtm** [comment]
Dunno. Guess from CloverThemeManager. Will it affect performance?

**Comment by gianfigueroa** [comment]
How I can downgrade clover ??, please

**Comment by sprtm** [comment]
So, I trashed all themes except the one I use, and now r5107 boots!

**Comment by gianfigueroa** [comment]
How you trashed??

**Comment by sprtm** [comment]
Just delete them from /Volumes/EFI/EFI/CLOVER/themes.

**Comment by SergeySlice** [comment]
Sorry, but official Clover supports 50 themes. If more then crash.

**Comment by gianfigueroa** [comment]
> Just delete them from /Volumes/EFI/EFI/CLOVER/themes.

For where??

Shell efi??

**Comment by vectorsigma72** [comment]
> > Just delete them from /Volumes/EFI/EFI/CLOVER/themes.
> 
> For where??
> 
> Shell efi??

Use Clover.app (look at releases) and open the ESP (EFI System Partition) and delete the themes manually (i.e. with the Finder).

**Comment by gianfigueroa** [comment]
> > > Just delete them from /Volumes/EFI/EFI/CLOVER/themes.
> > 
> > 
> > For where??
> > Shell efi??
> 
> Use Clover.app (look at releases) and open the ESP (EFI System Partition) and delete the themes manually (i.e. with the Finder).

My system is not running always screen black, I can't access to finder

**Comment by gianfigueroa** [comment]
or How I can se the log for detect anthoer error.I Never have been installed themes
