### ISSUE TITLE
About apple warning about future kext incompatibility

### ISSUE THREAD

**Issue by DMNerd** [CloverHackyColor/CloverBootloader#102]
Hello, I was wandering if you have noticed the situation with the newest macos update and if you are planning to do anything about it
![Error](https://images.macrumors.com/t/tfdDAtIqqpHyYI5WAjtTXUMr0-4=/800x0/article-new/2020/03/macos-catalina-legacy-system-extension-alert.jpg)

**Comment by Jacksonzwang** [comment]
I guess it might be refer to the extension which is provided by applications such as "Intel Gadget" and so on. Rather than system-level extensions.

**Comment by DMNerd** [comment]
Hopefully, tohugh there has been a debate about it. The question is still valid though. Is there any plan B for clover, just so users don`t have to switch to OC in the future

**Comment by roddy20** [comment]
> Hopefully, tohugh there has been a debate about it. The question is still valid though. Is there any plan B for clover, just so users don`t have to switch to OC in the future

How is it related to Clover and OC ?

**Comment by DMNerd** [comment]
> > Hopefully, tohugh there has been a debate about it. The question is still valid though. Is there any plan B for clover, just so users don`t have to switch to OC in the future
> 
> How is incompatible KEXT related to Clover and/or OC ?

I the way the kext injection works. Both clover and OC use fundamentaly different techniques to inject kexts on boot. All I wanted with this issue to start conversation about future of clover if apple starts blocking external kexts. That`s all

**Comment by SergeySlice** [comment]
Apple will block old kexts created by old technology.
No problem nowadays so no issue.
