### ISSUE TITLE
r5108: Blackscreen when booting Catalina 10.15.3 with NVidia Graphics

### ISSUE THREAD

**Issue by TonyC5** [CloverHackyColor/CloverBootloader#110]
EDIT: I have confirmed that this issue was introduced in r5108.  r5107 does not have this problem.

-------------------------------

I have Catalina 10.15.3 running without issues on a Dell Latitude E6410 (NVidia Graphics) after installing Catalina with DosDude Catalina patcher.  The Catalina installation and subsequent operation of Catalina are without issues when using CLOVER bootloader R5103.

After upgrading to CLOVER R5108, booting Catalina results in blackscreen.  Reverting to R5103 restores normal graphics operation.  My configuration uses CLOVER's "Inject NVidia" graphics option.

I upgraded from CLOVER R5103 to CLOVER R5108 by completely deleting R5103 EFI, installing CLOVER R5108 and restoring patched ACPI, config.plist and E/C/k/O.

My CLOVER installation is as follows:

- Install Clover in the ESP
- Boot Sectors: Install boot0af in MBR
- Clover for BIOS (legacy) booting: Clover EFI 64-bits SATA
- BIOS Drivers, 64-bit: Recommended drivers: FSInject, File System drivers: ApfsDriverLoader
- Install RC scripts on target volume
- Themes: BGM
- Install Clover Preference Pane

**Comment by TonyC5** [comment]
Not certain, but I suspect that [this commit ](https://github.com/CloverHackyColor/CloverBootloader/commit/e149dafe4d198ca557b85e95e08be21b844dd0e3) since r5108 is intended to address this problem.

**Comment by SergeySlice** [comment]
This is the commit that fix the issue.

**Comment by TonyC5** [comment]
@SergeySlice - Thank you!
