### ISSUE TITLE
r5109 verbose boot not working

### ISSUE THREAD

**Issue by MysticalOS** [CloverHackyColor/CloverBootloader#112]
with r5103 and lower, verbose boot was fine with -v but now after installing 5109 (skipped 5104-5108 because I wanted to avoid beta testing the C++ rewrite code til it was more stable)

Now, regardless of verbose boot arg, it always boots in apple logo only. Boot also seems quite a bit slower, but can't find reason why, because no verbose mode.
[bootlog.txt](https://github.com/CloverHackyColor/CloverBootloader/files/4440470/bootlog.txt)

**Comment by BlvckBytes** [comment]
Same for me, mine actually gets stuck, LOL.
First of all, my theme is completely corrupted (forgot to make a photo before reverting, sry...), and after selecting OSX to boot, the row of plus symbols appears top left and the apple logo shows, but the verbose output just does not make it to my screen.

Looks like the frame memory from the plus row just gets the apple logo added, and now I ended up with a merge. Going to try to re-install clover, but I think this wont change much, this just does not seem to work with my system.

**Comment by BlvckBytes** [comment]
Just tried to reinstall clover, same results (or even worse): Now the boot doesn't work at all. Photos included. When reverting to r5108 everything works fine, tho.

![20200407_011231](https://user-images.githubusercontent.com/20688817/78614085-e6f7f680-786d-11ea-9eea-e397a5617f48.jpg)

![20200407_010919](https://user-images.githubusercontent.com/20688817/78614110-f70fd600-786d-11ea-90c1-e8116ff066bd.jpg)

**Comment by mackonsti** [comment]
I would like to also confirm that, just updated from r5107 to r5109 and I cannot boot in Single mode, the Verbose mode shows the Clover output over the Apple boot screen and Themes are not taken into consideration from config.plist

**Comment by LeeBinder** [comment]
ditto

**Comment by makito89** [comment]
I also have the same issue.
I've updated from 5108 to 5109 and the only difference between without and with verbose is that with verbose active I see only the text output from loading kernel and after that it switches to graphical mode and I see the Apple logo with progress bar but the text from kernel load still present on screen until framebuffer gets initialized.

**Comment by makito89** [comment]
I've tested with the build d74b431 that I found on a post on InsanelyMac "Clover General discussion" thread and the issue with verbose is gone.
https://www.insanelymac.com/forum/applications/core/interface/file/attachment.php?id=346456

**Comment by corint1** [comment]
> I've tested with the build [d74b431](https://github.com/CloverHackyColor/CloverBootloader/commit/d74b431b6fb7729a8a484211ef79582d10730f17) that I found on a post on InsanelyMac "Clover General discussion" thread and the issue with verbose is gone.
> https://www.insanelymac.com/forum/applications/core/interface/file/attachment.php?id=346456

issue is here ... no change anything

**Comment by makito89** [comment]
just updated to r5110 and I can confirm that the issue is still present
![P_20200411_114611](https://user-images.githubusercontent.com/11616610/79039518-6e38c780-7bea-11ea-8a73-c959f08e82ce.jpg)

**Comment by SergeySlice** [comment]
all questions about 5109 closed
