### ISSUE TITLE
Minimalism theme (among others) broken in 5109

### ISSUE THREAD

**Issue by pit512** [CloverHackyColor/CloverBootloader#113]
New Clover GUI issue with 5109...
This theme is supposed to be white on black.

![screenshot0](https://user-images.githubusercontent.com/56659777/78612870-ad71bc00-786a-11ea-96ee-12c0f7e3c455.png)

**Comment by CMMChris** [comment]
Catalina Theme that I use looks screwed up as well.

**Comment by mifjpn** [comment]
Hello pit512
me too.
Brue-backscreen is on the screen at minimalinsm & BGM256.

**Comment by vectorsigma72** [comment]
minimalism blue, green or orange?

**Comment by mifjpn** [comment]
A little while ago, I launched a thread on this situation in a Japanese forum.
I was surprised at the user's response in the forum.
I was told that Minimalism2 that I made had no problems.
I tried it and it was fine.
If you like, please try it.
I will link again.
[minimalism2.zip](http://mifmif.mydns.jp/pcpc/public/minimalism2.zip)

**Comment by pit512** [comment]
> minimalism blue, green or orange?

Black

**Comment by aptonline** [comment]
Can also confirm 'embedded' theme the same blue background as opposed to black.

**Comment by pit512** [comment]
Look! Many themes are broken, even the vector ones...

Christmas theme
![christmas](https://user-images.githubusercontent.com/56659777/78811295-ed02ea00-79c9-11ea-96a5-8a9a86a40470.jpg)

Clovy theme (vector)
![Clovy](https://user-images.githubusercontent.com/56659777/78811298-ee341700-79c9-11ea-8c4b-914088ad0f22.jpg)

Embedded theme
![embedded](https://user-images.githubusercontent.com/56659777/78811300-eeccad80-79c9-11ea-8f7e-6de08ebb7c7f.jpg)

Newyear theme
![newyear](https://user-images.githubusercontent.com/56659777/78811304-ef654400-79c9-11ea-8b3f-2469348b87e7.jpg)

**Comment by BrushXue** [comment]
Same problem here.

**Comment by SergeySlice** [comment]
all questions about 5109 closed
