### ISSUE TITLE
New theme engine reports wrong disk logos for windows 10 and ubuntu partitions

### ISSUE THREAD

**Issue by jtash** [CloverHackyColor/CloverBootloader#115]
On r5108 and earlier windows and ubuntu partitions gave the correct logos in the clover boot screen. In r5109 they now both show as portable drive logos

**Comment by Flowwwww** [comment]
Same problem here. Windows entry show as a mac logo.
Even specifying custom logo path in GUI > Custom Entries doesn't work.

**Comment by mackonsti** [comment]
I would like to confirm that too, updated from r5107 to r5109 and the theme also seems totally not taken into consideration.

**Comment by LeeBinder** [comment]
me.too

**Comment by najeebanwer** [comment]
Yes, here is a selection of what the themes look like with r5109. They all looked a lot better with r5108.
Catalina:
![Catalina](https://user-images.githubusercontent.com/34123660/78743331-f33e8b00-7923-11ea-974d-381bdb6816df.png)
Mojave:
![Mojave](https://user-images.githubusercontent.com/34123660/78743357-02253d80-7924-11ea-964c-362fcf81ed46.png)
Retina:
![Retina](https://user-images.githubusercontent.com/34123660/78743390-123d1d00-7924-11ea-92d6-9a6963c9d5bd.png)

**Comment by SergeySlice** [comment]
Test 5111
