### ISSUE TITLE
Help page corrupted, old themes are broken

### ISSUE THREAD

**Issue by azmut** [CloverHackyColor/CloverBootloader#116]
Help page corrupted:
![screenshot2](https://user-images.githubusercontent.com/14005695/78752243-65db5500-797c-11ea-8f73-ba1f6469bc9b.png)
Old themes are broken:
![screenshot0](https://user-images.githubusercontent.com/14005695/78752293-81466000-797c-11ea-9380-96ca97d44214.png)

**Comment by SergeySlice** [comment]
Resolved
