### ISSUE TITLE
System halted after updating 5109 from 5107

### ISSUE THREAD

**Issue by hoanngothanh** [CloverHackyColor/CloverBootloader#118]
After restart doesn't show the list of disks but this error.

XArray::ElementAt(xsize) -> Operator [] : index > m_lenA fatal error happened. System halted.

I have to downgrade to 5108

**Comment by milmber** [comment]
I got the same error with 5109. Reverted to 5108.

**Comment by SergeySlice** [comment]
Release 5109 was wrong
