### ISSUE TITLE
Windows Icon error

### ISSUE THREAD

**Issue by ghost** [CloverHackyColor/CloverBootloader#119]
Release v2.5k-5105——5109
Windows Icon error
Release v2.5k-5104
Return to normal
![QQ截图20200410143024](https://user-images.githubusercontent.com/55861418/78969082-bac3ca80-7b38-11ea-947f-c1dc1e7bd992.png)

**Comment by Yaya48** [comment]
Same

**Comment by Yaya48** [comment]
Yep Same

**Comment by juliantoledo** [comment]
I had the same issue in 5109, I reverted to 5108.

**Comment by SergeySlice** [comment]
It is wrong theme
