### ISSUE TITLE
BDUtility.exe cannot get last Clover releases

### ISSUE THREAD

**Issue by Sterpa** [CloverHackyColor/CloverBootloader#12]
Dear SergeySlice,
do you have communication with cVad from [Boot Disk Utility](http://cvad-mac.narod.ru/index/bootdiskutility_exe/0-5) (aka BDU)?
Unfortunately, BDU stopped downloading releases after 5070, because You have migrated development to GitHub from sourceforge.net.
Could you help with the contacts of the BDU-utility developer to upgrade it to work with Clover on GitHub?
Thx a lot!

**Comment by SergeySlice** [comment]
cVad have been informed
