### ISSUE TITLE
5110 Theme rendering errors Minimalism theme

### ISSUE THREAD

**Issue by shrubberies** [CloverHackyColor/CloverBootloader#121]
5110 shows different render errors than 5109 with Mininmalism (black) theme. Blue bar persists at bottom of screen. Background image is not using bg from theme but a larger background image with a clover on it.

**Comment by shrubberies** [comment]
looks like its using the bg from the embedded theme but tiled and not scaled,

**Comment by GCPDetective** [comment]
I’m experiencing the same issue except it’s with the OSS theme. I’ve tried a few other themes and still get the same thing.

**Comment by juliantoledo** [comment]
I think images are not scaling well, I have the same issue in 5109. I had to copy a different background image from another theme.

**Comment by mifjpn** [comment]
Me too.
The background doesn't seem to scale well.
I use BGM256 theme. I matched the background PNG file to the display resolution.
Then, it goes well.

**Comment by theliamllyd** [comment]
Having issues here with 5109 / 5110. Just displays as a blue background.

![CDF08730-1D3A-49B2-BFA8-1BBF3354ECE3](https://user-images.githubusercontent.com/63418737/79049226-3e091d00-7c1a-11ea-85e3-5353c6a6908a.jpg)

**Comment by BrushXue** [comment]
Still same issue with r5110. Resolution 3840*2160
![IMG_0297](https://user-images.githubusercontent.com/12702149/79055108-406a7780-7c18-11ea-8bd9-012bca7fde5b.jpg)

**Comment by sryze** [comment]
I have a similar problem with the BGM theme after updating to 5110:

![screenshot0](https://user-images.githubusercontent.com/4525736/79061939-38ade000-7cb7-11ea-9e13-5f4935addfed.png)

**Comment by SergeySlice** [comment]
Resolved
