### ISSUE TITLE
consecutive 5109.  5110 boot USB freeze and more errors on High Sierra we need VALIDATION mechanism plz

### ISSUE THREAD

**Issue by vacarogit** [CloverHackyColor/CloverBootloader#122]
Boot Intel USB freeze, thus KB, mouse not accessible (have to hook mouse to PXSX),  release after validation is advisable.

**Comment by danieldabate** [comment]
I'm having the same issue, rollbacking to 5108 for now.

**Comment by vacarogit** [comment]
> I'm having the same issue, rollbacking to 5108 for now.

we need qty control

**Comment by SergeySlice** [comment]
The issue about USB or about validation mechanism?

**Comment by danieldabate** [comment]
Originally it was about the USB freeze, but @vacarogit changed the title. I don't think the new title helps to understand the real problem.

**Comment by vacarogit** [comment]
> The issue about USB or about validation mechanism?

it's about validation in the root, because of that since 5008, multiple version, 5009 n 5011 both have boot issue, cause inconvenience.

**Comment by SergeySlice** [comment]
If someone will develop new project somehow validation of you USB sticks then he will open new github project.
I see no what I shall do with Clover.
