### ISSUE TITLE
Update 5108 to 5110 no boot

### ISSUE THREAD

**Issue by pagimamaun** [CloverHackyColor/CloverBootloader#123]
After updating from 5108 to 5110 i was not able to boot catalina (10.15.4)
UI was longer to appear.
Nothing on verbose boot stop instantanely with the apple forbiden logo
Back to 1008 for the moment

**Comment by vacarogit** [comment]
> After updating from 5108 to 5110 i was not able to boot catalina (10.15.4)
> UI was longer to appear.
> Nothing on verbose boot stop instantanely with the apple forbiden logo
> Back to 1008 for the moment

You have to resort to system restore? Sad for you, good luck of you
and 5108 you mean..

**Comment by pagimamaun** [comment]
5111 resolve the problem
