### ISSUE TITLE
Clover builds past 5099 break booting. Catalina 10.15.3

### ISSUE THREAD

**Issue by acdop100** [CloverHackyColor/CloverBootloader#125]
Hey there,

I have repeatedly tried to update my clover install over the past few months with no success. You can see the verbose output in the picture below. Does anyone know what could be causing this? All of my kexts are up to date and I updated my extra files/drivers from within the clover installer too. 

Installed on Dell XPS 15 9560. 
![IMG_0967](https://user-images.githubusercontent.com/11857861/79058351-e62ede00-7c3a-11ea-8930-a1fe6975f082.jpg)

Here is my config, I had to change it to .txt to upload it but it's the same file. 
[config.txt](https://github.com/CloverHackyColor/CloverBootloader/files/4466562/config.txt)

**Comment by vacarogit** [comment]
You don’t “read” previous comments don’t you?

**Comment by acdop100** [comment]
> You don’t “read” previous comments don’t you?

What do you mean? It doesn't look like there are any other issues that are directly related to this from the past 4 months or so.

**Comment by SergeySlice** [comment]
You should provede a little more information if this is a Clover issue and not user.

**Comment by acdop100** [comment]
> You should provide a little more information if this is a Clover issue and not user mistake.

I understand. What would be most helpful for you to help me? I will attach my config.plist to the top.

**Comment by vectorsigma72** [comment]
> > You should provide a little more information if this is a Clover issue and not user mistake.
> 
> I understand. What would be most helpful for you to help me? I will attach my config.plist to the top.

a preboot.log will be also nice

**Comment by SergeySlice** [comment]
The issue tracker is not for helping new users.
Opening an issue you have to provide a proof what you say.
