### ISSUE TITLE
v5109 breaks USB devices/Boot graphics

### ISSUE THREAD

**Issue by umangloria** [CloverHackyColor/CloverBootloader#126]
- I was on clover 5107 and got a new 10.15.4 supplement update notification so as always I opened up a clover configurator and updated the clover version to 5109 and updated kexts under other folder.
- On reboot first thing I noticed was totally messed up clover boot screen still I am able to read the text and selected proper partition during the update process
- After the final restart, I landed on the lock screen and to my surprise, no USB ports seems working, I tried other things but no luck 
NOTE: I was able to fix the issue by replacing cloverx64.efi from clover 5108 on my EFI partition and now all seems to work fine.

**Comment by SergeySlice** [comment]
Test 5111
