### ISSUE TITLE
5111 : custom entries not displayed

### ISSUE THREAD

**Issue by lemascaret** [CloverHackyColor/CloverBootloader#127]
Hello!

I have an old gear (Ivy bridge) with latest Catalina.
Starting with clover 5007 (not sure), most icons (to the exception of Mac icons) where not displayed (my favorite theme being gold_clover). 
Now, with 5111, my custom linux entries are not displayed (manjaro, solus).
Reverted to 5102 and everything back to normal.

Thks for reading!

**Comment by lemascaret** [comment]
BUMP 
Just discovered the move of /themes to github.
Clover Theme manager is still pointing to sourceforge?
Just for now, I stick with 5102 (with updated gold_clover though).
Sorry!

**Comment by vectorsigma72** [comment]
Clover.app handles github theme repositories
