### ISSUE TITLE
Big Bug Clover r5110

### ISSUE THREAD

**Issue by Yaya48** [CloverHackyColor/CloverBootloader#130]
Hello I report you two bug I have with clover r5110

1) Mac OS Catalina Wont boot is directly return to clover
2) Custom Entrie Dont Work

**Comment by vacarogit** [comment]
Agree, Do not put our system at RISK!! Some of us don't backup that often

**Comment by vectorsigma72** [comment]
> Agree, Do not put our system at RISK!! Some of us don't backup that often

Are you saying that you install prerelease software without be sure to have a fall back?

**Comment by Yaya48** [comment]
Personally I have Windows so I was able to mount the efi portion and put back the 5110 version.

**Comment by SergeySlice** [comment]
Repaired in 5112
