### ISSUE TITLE
Clover r5111 does not create backup of previous version in /EFI-Backups

### ISSUE THREAD

**Issue by najeebanwer** [CloverHackyColor/CloverBootloader#131]
I upgraded to Clover r5111 and it did not create a backup of my previous version (r5109) in the /EFI-Backups folder.

**Comment by najeebanwer** [comment]
I upgraded to Clover r5112 and it did create a backup of the previous version, but the folder name is strange (see snapshot below).
![Screen Shot 2020-04-15 at 12 19 12 PM](https://user-images.githubusercontent.com/34123660/79367535-a7877500-7f13-11ea-981e-34218527c663.png)

**Comment by vectorsigma72** [comment]
try with r5113

**Comment by najeebanwer** [comment]
Fixed in Clover r5113.
