### ISSUE TITLE
Clover r5111 still has problems with some themes

### ISSUE THREAD

**Issue by najeebanwer** [CloverHackyColor/CloverBootloader#132]
I am still having an issue with the Catalina theme after installing r5111 (see the blue region at the bottom of the picture below). Unless this is a feature and not a bug? My screen resolution is 1920x1200. This used to work correctly in r5108.
![Catalina r5111](https://user-images.githubusercontent.com/34123660/79166111-1e086380-7daa-11ea-915e-b84e608a7459.png)

**Comment by pit512** [comment]
I managed to completely fill the Minimalism theme background by changing the type from _Scale_ to _Tile_...

`		<key>Background</key>`
`		<dict>`
`			<key>Type</key>`
`			<string>Tile</string>`
`		</dict>`

It seems newest Clover can only scale the background horizontally!
Hope it helps...

**Comment by najeebanwer** [comment]
This appears to be fixed in Clover r5112. See screenshots below.
Catalina theme:
![Catalina r5112](https://user-images.githubusercontent.com/34123660/79611837-135b1080-80c1-11ea-8947-5824cd6f485b.png)
Retina theme:
![Retina r5112](https://user-images.githubusercontent.com/34123660/79611862-2077ff80-80c1-11ea-85f0-b184afa5b348.png)
