### ISSUE TITLE
UEFI shell -  wireless keyboard - shift key

### ISSUE THREAD

**Issue by itsjimbo** [CloverHackyColor/CloverBootloader#134]
Shift key is not working for wireless bluetooth A1314 apple keyboard.  It works fine with wired USB/PS2.  I have had this problem for many releases (back from older clover r2.4k versions) and I am sure the shift key never worked making it impossible to change drives eg. from FS0: or FS1: because you cannot type the colon key.

I have read previous issues that referenced the cause as the **BIOS**, but I am not surethis diagnosis is correct because within the gigabyte bios there  is a profile textbox that you can have upper/lowercase letters and shift appears to work within the bios itself just fine.

MOBO: Gigabyte GA-Z170X-UD5-TH F21

Clover version
```
➜ ~ /Applications/Clover.app/Contents/MacOS/CloverDaemonNew 
--------------------------------------------
- CloverDaemonNew v1.1.2
- macOS Version 10.15.4 (Build 19E287)
- System start at 2020-04-14 03:05:18
------
root mount point is '/Volumes/MacintoshHD'
Started with Clover r5112.
```

**Comment by SergeySlice** [comment]
Clover uses BIOS driver for keyboards, for bluetooth, for USB.
We have nothing to do to make a support for bad keyboard.
