### ISSUE TITLE
Theme issue with BootCampStyle and Indicator

### ISSUE THREAD

**Issue by forumi0721** [CloverHackyColor/CloverBootloader#136]
Hi,
After 5109(New theme engine), BootCampStyle indicator does not works correctly.

When i have 2 (or more) boot entry, indicator works but not clear when move cursor.
Always remains indicator.

I tested some theme (mac_s, mimi black, etc..), always remain indicator likes multiple selection.

Please check and fix this issue.

Thanks.

**Comment by allegrox** [comment]
> Hi,
> After 5109(New theme engine), BootCampStyle indicator does not works correctly.
> 
> When i have 2 (or more) boot entry, indicator works but not clear when move cursor.
> Always remains indicator.
> 
> I tested some theme (mac_s, mimi black, etc..), always remain indicator likes multiple selection.
> 
> Please check and fix this issue.
> 
> Thanks.

I had the same problem

**Comment by asava** [comment]
Please try with current changes (from source), see if issue is resolved.
