### ISSUE TITLE
Bluetooth problem

### ISSUE THREAD

**Issue by OvidiuNetcu** [CloverHackyColor/CloverBootloader#137]
From version Release v5.0 r5107, all version have bluetooth problem. Is lost conection and is not work to pair mous and keyboards over buetooth.
I use a airport from a Imac 2014. Is work very well with version r5107.

**Comment by OvidiuNetcu** [comment]
0:100  0:100  MemLog inited, TSC freq: 3600484080
0:100  0:000  CPU was calibrated with RTC
0:100  0:000  
0:100  0:000  Now is 14.02.2020,  19:10:02 (GMT)
0:100  0:000  Starting Clover revision: 5103 (master, commit 3f3b85da0) on American Megatrends EFI
0:100  0:000  Build with: [Args: -D NO_GRUB_DRIVERS_EMBEDDED -t GCC53 | -D NO_GRUB_DRIVERS_EMBEDDED --conf=/Users/sergey/src/CloverHackyColor/Conf -D USE_LOW_EBDA -a X64 -b RELEASE -t GCC53 -n 5 | OS: 10.14.6]
0:100  0:000  SelfDevicePath=PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)\HD(1,GPT,10CD5D8B-83A4-4DE2-ADBA-98A16D93EBE4,0x28,0x64000) @358A2C18
0:100  0:000  SelfDirPath = \EFI\BOOT
0:100  0:000  SimpleTextEx Status=Success
0:100  0:000  === [ Get Smbios ] ========================================
0:100  0:000  Type 16 Index = 0
0:100  0:000  Total Memory Slots Count = 4
0:100  0:000  Type 17 Index = 0
0:100  0:000  SmbiosTable.Type17->Speed = 3000MHz
0:100  0:000  SmbiosTable.Type17->Size = 8192MB
0:100  0:000  SmbiosTable.Type17->Bank/Device = BANK 0 ChannelA-DIMM0
0:100  0:000  SmbiosTable.Type17->Vendor = 04CB
0:100  0:000  SmbiosTable.Type17->SerialNumber = 564D0000
0:100  0:000  SmbiosTable.Type17->PartNumber = DDR4 3000 2OZ       
0:100  0:000  Type 17 Index = 1
0:100  0:000  SmbiosTable.Type17->Speed = 3000MHz
0:100  0:000  SmbiosTable.Type17->Size = 8192MB
0:100  0:000  SmbiosTable.Type17->Bank/Device = BANK 1 ChannelA-DIMM1
0:100  0:000  SmbiosTable.Type17->Vendor = 04CB
0:100  0:000  SmbiosTable.Type17->SerialNumber = 713A0400
0:100  0:000  SmbiosTable.Type17->PartNumber = DDR4 3000 2OZ       
0:100  0:000  Type 17 Index = 2
0:100  0:000  SmbiosTable.Type17->Speed = 3000MHz
0:100  0:000  SmbiosTable.Type17->Size = 8192MB
0:100  0:000  SmbiosTable.Type17->Bank/Device = BANK 2 ChannelB-DIMM0
0:100  0:000  SmbiosTable.Type17->Vendor = 04CB
0:100  0:000  SmbiosTable.Type17->SerialNumber = 90320400
0:100  0:000  SmbiosTable.Type17->PartNumber = DDR4 3000 2OZ       
0:100  0:000  Type 17 Index = 3
0:100  0:000  SmbiosTable.Type17->Speed = 3000MHz
0:100  0:000  SmbiosTable.Type17->Size = 8192MB
0:100  0:000  SmbiosTable.Type17->Bank/Device = BANK 3 ChannelB-DIMM1
0:100  0:000  SmbiosTable.Type17->Vendor = 04CB
0:100  0:000  SmbiosTable.Type17->SerialNumber = 5A4D0000
0:100  0:000  SmbiosTable.Type17->PartNumber = DDR4 3000 2OZ       
0:100  0:000  Boot status=0
0:100  0:000  Running on: 'Z390 AORUS PRO' with board 'Z390 AORUS PRO-CF'
0:100  0:000  === [ GetCPUProperties ] ==================================
0:100  0:000  CPU Vendor = 756E6547 Model=906ED
0:100  0:000   The CPU supported SSE4.1
0:100  0:000  BrandString = Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
0:100  0:000   The CPU supported turbo
0:100  0:000  MSR 0x35               80008
0:100  0:000   TSC/CCC Information Leaf:
0:100  0:000    numerator     : 300
0:100  0:000    denominator   : 2
0:100  0:000   Calibrated ARTFrequency: 24003227
0:100  0:000   Rounded ARTFrequency: 24000000
0:100  0:000  MSR 0xE2 before patch 1E008000
0:100  0:000  MSR 0xE2 is locked, PM patches will be turned on
0:100  0:000  MSR 0xCE              08080838_F1012400
0:100  0:000  corrected FLEX_RATIO = E0000
0:100  0:000  FSBFrequency = 127 MHz, DMI FSBFrequency = 100 MHz, Corrected FSBFrequency = 100 MHz
0:100  0:000  MaxDiv/MinDiv: 36.0/8
0:100  0:000  Turbo: 47/48/48/49
0:100  0:000  Features: 0xBFEBFBFF
0:100  0:000  Threads: 8
0:100  0:000  Cores: 8
0:100  0:000  FSB: 100 MHz
0:100  0:000  CPU: 4554 MHz
0:100  0:000  TSC: 4554 MHz
0:100  0:000  PIS: 100 MHz
0:100  0:000  ExternalClock: 25 MHz
0:100  0:000  === [ GetDevices ] ========================================
0:100  0:000  PCI (00|00:00.00) : 8086 3E30 class=060000
0:100  0:000  PCI (00|00:01.00) : 8086 1901 class=060400
0:100  0:000  PCI (00|01:00.00) : 1022 1470 class=060400
0:101  0:000  PCI (00|02:00.00) : 1022 1471 class=060400
0:101  0:000  PCI (00|03:00.00) : 1002 687F class=030000
0:101  0:000   - GFX: Model=AMD Radeon Vega 64 (ATI/AMD)
0:101  0:000  PCI (00|03:00.01) : 1002 AAF8 class=040300
0:101  0:000   - HDMI Audio: 
0:101  0:000  PCI (00|00:02.00) : 8086 3E98 class=038000
0:101  0:000   - GFX: Model=Intel UHD Graphics 630 (Intel)
0:101  0:000  PCI (00|00:12.00) : 8086 A379 class=118000
0:101  0:000  PCI (00|00:14.00) : 8086 A36D class=0C0330
0:101  0:000  PCI (00|00:14.02) : 8086 A36F class=050000
0:101  0:000  PCI (00|00:16.00) : 8086 A360 class=078000
0:101  0:000  PCI (00|00:17.00) : 8086 A352 class=010601
0:101  0:000  PCI (00|00:1B.00) : 8086 A340 class=060400
0:101  0:000  PCI (00|04:00.00) : 144D A808 class=010802
0:101  0:000  PCI (00|00:1C.00) : 8086 A338 class=060400
0:101  0:000  PCI (00|00:1C.07) : 8086 A33F class=060400
0:101  0:000  PCI (00|06:00.00) : 14E4 43A0 class=028000
0:101  0:000   - WIFI: Vendor=Broadcom
0:101  0:000  PCI (00|00:1D.00) : 8086 A330 class=060400
0:101  0:000  PCI (00|07:00.00) : 1987 5016 class=010802
0:101  0:000  PCI (00|00:1F.00) : 8086 A305 class=060100
0:101  0:000  PCI (00|00:1F.03) : 8086 A348 class=040300
0:101  0:000  PCI (00|00:1F.04) : 8086 A323 class=0C0500
0:101  0:000  PCI (00|00:1F.05) : 8086 A324 class=0C8000
0:101  0:000  PCI (00|00:1F.06) : 8086 15BC class=020000
0:101  0:000   - LAN: 0 Vendor=Intel
0:101  0:000  === [ GetDefaultSettings ] ================================
0:101  0:000  Clover load options size = 0 bytes
0:102  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\Z390 AORUS PRO--00-00-00-00-00-00. Dir not exists
0:102  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\Z390 AORUS PRO-CF\UEFI. Dir not exists
0:102  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\Z390 AORUS PRO. Dir not exists
0:102  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\Z390 AORUS PRO-4554. Dir not exists
0:102  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\Z390 AORUS PRO-CF. Dir not exists
0:102  0:000  CheckOEMPathExists tried EFI\CLOVER\OEM\Z390 AORUS PRO-CF-4554. Dir not exists
0:102  0:000  set OEMPath by default: EFI\CLOVER
0:104  0:001  EFI\CLOVER\config.plist loaded: Success
0:108  0:004  === [ GetListOfThemes ] ===================================
0:109  0:000  - [00]: embedded
0:109  0:000  - [00]: random
0:110  0:000  - [00]: tonymacx86
0:110  0:000  === [ Found config plists ] ===============================
0:111  0:000  - config.plist
0:111  0:000  === [ GetEarlyUserSettings ] ==============================
0:111  0:000  timeout set to 4
0:111  0:000  Custom boot CUSTOM_BOOT_DISABLED (0x0)
0:111  0:000  KextsToPatch: 2 requested
0:111  0:000   - [00]: com.apple.iokit.IOUSBHostFamily (USB port limit patch #1 10.15.x by pmheart, daliansky and ydeng) :: MatchOS: 10.15.x :: BinPatch :: data len: 4
0:111  0:000   - [01]: com.apple.driver.usb.AppleUSBXHCI (USB port limit patch #2 10.15.x by pmheart, daliansky and ydeng) :: MatchOS: 10.15.x :: BinPatch :: data len: 4
0:111  0:000  Default theme: embedded
0:111  0:000  Hiding entries with string Windows
0:111  0:000  Hiding entries with string BOOTX64.EFI
0:111  0:000  Hiding entries with string Preboot
0:111  0:000  Hiding entries with string Recovery
0:111  0:000  === [ LoadDrivers ] =======================================
0:112  0:000  Loading ApfsDriverLoader.efi  status=Success
0:113  0:001   - driver needs connecting
0:113  0:000  Loading AptioMemoryFix.efi  status=Success
0:114  0:000  Loading AudioDxe.efi  status=Success
0:115  0:000   - driver needs connecting
0:115  0:000  Loading DataHubDxe.efi  status=Success
0:117  0:001  Loading FSInject.efi  status=Success
0:118  0:001  Loading VBoxHfs.efi  status=Success
0:119  0:000   - driver needs connecting
0:119  0:000  Loading VirtualSmc.efi  status=Success
0:121  0:001  Loading EmuVariableUefi.efi  status=Success
0:122  0:000  EmuVariableUefi Initialize: VariableCommonInitialize = Success, orig services stored, install gEmuVariableControlProtocolGuid = Success
0:122  0:000  3 drivers needs connecting ...
0:122  0:000  PlatformDriverOverrideProtocol not found. Installing ... Success
0:122  0:000  APFS driver loaded
0:122  0:000  Searching for invalid DiskIo BY_DRIVER connects: not found, all ok
6:319  6:197  EmuVariable InstallEmulation: orig vars copied, emu.var.services installed, CreateEvent VirtualAddressChange = Success, CreateEvent ExitBootServices = Success, set Status=Success
6:339  0:020  === [ InitScreen ] ========================================
6:339  0:000  Console modes reported: 1, available modes:
6:339  0:000  reinit: self device path=PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)\HD(1,GPT,10CD5D8B-83A4-4DE2-ADBA-98A16D93EBE4,0x28,0x64000)
6:341  0:001  Using embedded font: Success
6:341  0:000  === [ GetMacAddress ] =====================================
6:341  0:000  MAC address of LAN #0= B4:2E:99:D1:24:96:
6:341  0:000  === [ ScanSPD ] ===========================================
6:341  0:000  Scanning SMBus [8086:A323], mmio: 0x62838004, ioport: 0xEFA0, hostc: 0x11
6:360  0:018  Slot: 0 Type 26 8192MB 2666MHz Vendor=A-DATA Technology PartNo=DDR430002OZ SerialNo=0506040D00000000
6:379  0:018  Slot: 1 Type 26 8192MB 2666MHz Vendor=A-DATA Technology PartNo=DDR430002OZ SerialNo=0701030A00040000
6:397  0:018  Slot: 2 Type 26 8192MB 2666MHz Vendor=A-DATA Technology PartNo=DDR430002OZ SerialNo=0900030200040000
6:416  0:018  Slot: 3 Type 26 8192MB 2666MHz Vendor=A-DATA Technology PartNo=DDR430002OZ SerialNo=050A040D00000000
6:416  0:000  === [ GetAcpiTablesList ] =================================
6:421  0:004  Get Acpi Tables List from RSDT:
6:421  0:000   - [00]: FACP  A M I len=132
6:421  0:000   - [01]: APIC  A M I len=188
6:421  0:000   - [02]: FPDT  A M I len=68
6:421  0:000   - [03]: FIDT  A M I len=156
6:421  0:000   - [04]: MCFG  A M I len=60
6:421  0:000   - [05]: SSDT  A M I len=516
6:421  0:000   - [06]: SSDT  A M I len=6101
6:421  0:000   - [07]: SSDT  A M I len=30778
6:421  0:000   - [08]: SSDT  A M I len=12743
6:421  0:000   - [09]: SSDT  A M I len=9048
6:421  0:000   - [10]: HPET  A M I len=56
6:421  0:000   - [11]: SSDT  A M I len=3998
6:421  0:000   - [12]: SSDT  A M I len=11547
6:421  0:000   - [13]: UEFI  A M I len=66
6:421  0:000   - [14]: LPIT  A M I len=92
6:421  0:000   - [15]: SSDT  A M I len=10206
6:421  0:000   - [16]: SSDT  A M I len=4094
6:421  0:000   - [17]: DBGP  A M I len=52
6:421  0:000   - [18]: DBG2  A M I len=84
6:421  0:000   - [19]: VFCT  A M I len=61060
6:421  0:000   - [20]: WSMT  A M I len=40
6:421  0:000  Calibrated TSC Frequency = 3600484080 = 3600MHz
6:421  0:000  === [ GetUserSettings ] ===================================
6:421  0:000  Add 1 devices:
6:421  0:000  USB FixOwnership: yes
6:421  0:000  Dropping 2 tables:
6:421  0:000   - [00]: Drop table  signature="MATS" (5354414D)
6:421  0:000           - set table: 5354414D,                0 to drop: no
6:421  0:000   - [01]: Drop table  signature="DMAR" (52414D44)
6:421  0:000           - set table: 52414D44,                0 to drop: no
6:421  0:000   - final DSDT Fix mask=00000000
6:421  0:000  PatchesDSDT: 7 requested
6:421  0:000   - [00]: (change GFX0 to IGPU) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:421  0:000   - [01]: (change PEGP to GFX0) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:421  0:000   - [02]: (change XHCI to XHC) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:421  0:000   - [03]: (change XHC1 to XHC) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:421  0:000   - [04]: (Fix 300-series RTC Bug) lenToFind: 8, lenToReplace: 8, Target Bridge: <null string>
6:421  0:000    patch disabled at config
6:421  0:000   - [05]: (change EHC1 to EH01) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:421  0:000   - [06]: (change EHC2 to EH02) lenToFind: 4, lenToReplace: 4, Target Bridge: <null string>
6:421  0:000  Using ProductName from config: iMac19,1
6:421  0:000  Using latest BiosVersion from config
6:421  0:000  BiosVersion: IM191.88Z.F000.B00.1912181732
6:421  0:000  BiosReleaseDate: 12/18/2019
6:421  0:000  Using latest EfiVersion from config: 1037.80.34.0.0
6:421  0:000  Using FirmwareFeatures from config: 0xFD8FF576
6:421  0:000  Using FirmwareFeaturesMask from config: 0xFFDFFF7F
6:421  0:000  Board-ID set from config as Mac-AA95B1DDAB278B95
6:421  0:000  BoardType: 0xA
6:421  0:000  ChassisType: 0x9
6:422  0:000  === [ Found DSDT tables ] =================================
6:626  0:204  === [ ScanVolumes ] =======================================
6:626  0:000  Found 11 volumes with blockIO
6:626  0:000  - [00]: Volume: PciRoot(0x0)\Pci(0x1B,0x0)\Pci(0x0,0x0)\NVMe(0x1,73-97-B3-91-58-38-25-00)
6:626  0:000  - [01]: Volume: PciRoot(0x0)\Pci(0x1B,0x0)\Pci(0x0,0x0)\NVMe(0x1,73-97-B3-91-58-38-25-00)\HD(1,GPT,6D2E879E-606D-4D3E-8025-5D0EDED3F8DB,0x28,0x64000)
6:626  0:000          Result of bootcode detection: bootable unknown (legacy)
6:627  0:000  - [02]: Volume: PciRoot(0x0)\Pci(0x1B,0x0)\Pci(0x0,0x0)\NVMe(0x1,73-97-B3-91-58-38-25-00)\HD(2,GPT,5216EC40-EEE1-4949-A0DA-CEE073B7A0BD,0x64028,0x3B97D260)
6:627  0:000          Result of bootcode detection: bootable unknown (legacy)
6:627  0:000  - [03]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)
6:627  0:000  - [04]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)\HD(1,GPT,10CD5D8B-83A4-4DE2-ADBA-98A16D93EBE4,0x28,0x64000)
6:627  0:000          Result of bootcode detection: bootable unknown (legacy)
6:627  0:000          This is SelfVolume !!
6:627  0:000  - [05]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)\HD(2,GPT,7AF64392-48A7-4385-8FBE-86692E114EFB,0x64028,0x746A2D60)
6:627  0:000          Result of bootcode detection: bootable unknown (legacy)
6:627  0:000  - [06]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)\HD(2,GPT,7AF64392-48A7-4385-8FBE-86692E114EFB,0x64028,0x746A2D60)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,EAFF2A499BE0D248BCD429B6A37A14E9)
6:627  0:000          hiding this volume
6:627  0:000  - [07]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)\HD(2,GPT,7AF64392-48A7-4385-8FBE-86692E114EFB,0x64028,0x746A2D60)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,48A79DFA2BEF66498EDFFFC4989F6DE1)
6:627  0:000  - [08]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)\HD(2,GPT,7AF64392-48A7-4385-8FBE-86692E114EFB,0x64028,0x746A2D60)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,A2995325C4D0AC40A56ABF9764D5927D)
6:627  0:000          hiding this volume
6:627  0:000  - [09]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)\HD(2,GPT,7AF64392-48A7-4385-8FBE-86692E114EFB,0x64028,0x746A2D60)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,AFAF7F3606710E41A44C5C8FD92E08E3)
6:627  0:000  - [10]: Volume: PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)\HD(2,GPT,7AF64392-48A7-4385-8FBE-86692E114EFB,0x64028,0x746A2D60)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,701184A8B638F4498C781DF7EF55993B)
6:628  0:000  Loading nvram.plist from Vol 'EFI' - loaded, size=2612
6:631  0:003  === [ PutNvramPlistToRtVars ] =============================
6:631  0:000   Adding Key: EFIBluetoothDelay: Size = 2, Data: B8 0B 
6:632  0:000   Adding Key: EFILoginHiDPI: Size = 4, Data: 00 00 00 00 
6:632  0:000   Skipping EmuVariableUefiPresent
6:632  0:000   Adding Key: LocationServicesEnabled: Size = 1, Data: 01 
6:632  0:000   Adding Key: SystemAudioVolume: Size = 1, Data: 26 
6:632  0:000   Adding Key: SystemAudioVolumeDB: Size = 1, Data: DC 
6:632  0:000   Adding Key: bluetoothActiveControllerInfo: Size = 16, Data: 8D 82 AC 05 00 00 00 30 B2 14 B4 18 D1 E3 C8 70 
6:632  0:000   Adding Key: bluetoothInternalControllerInfo: Size = 14, Data: 8D 82 AC 05 00 30 B2 14 B4 18 D1 E3 C8 70 
6:632  0:000   Adding Key: csr-active-config: Size = 4, Data: E7 03 00 00 
6:632  0:000   Adding Key: flagstate: Size = 32, Data: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
6:632  0:000   Adding Key: fmm-computer-name: Size = 20, Data: 6F 76 69 64 69 75 E2 80 99 73 20 69 4D 61 63 20 32 30 31 39 
6:632  0:000   Adding Key: fmm-mobileme-token-FMM: Size = 937, Data: 62 70 6C 69 73 74 30 30 DD 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 16 17 0E 18 0E 19 1A 1B 1C 1D 1F 5F 10 0F 75 6E 72 65 67 69 73 74 65 72 53 74 61 74 65 58 75 73 65 72 49 6E 66 6F 59 61 75 74 68 54 6F 6B 65 6E 5E 72 6F 6F 74 56 6F 6C 75 6D 65 55 55 49 44 5E 64 69 73 61 62 6C 65 43 6F 6E 74 65 78 74 56 75 73 65 72 69 64 5D 65 6E 61 62 6C 65 43 6F 6E 74 65 78 74 58 75 73 65 72 6E 61 6D 65 58 70 65 72 73 6F 6E 49 44 54 67 75 69 64 57 61 64 64 54 69 6D 65 5F 10 12 65 6E 61 62 6C 65 64 44 61 74 61 63 6C 61 73 73 65 73 5F 10 13 64 61 74 61 63 6C 61 73 73 50 72 6F 70 65 72 74 69 65 73 10 00 D3 10 11 12 13 14 15 5F 10 15 49 6E 55 73 65 4F 77 6E 65 72 44 69 73 70 6C 61 79 4E 61 6D 65 5F 10 13 49 6E 55 73 65 4F 77 6E 65 72 46 69 72 73 74 4E 61 6D 65 5F 10 12 49 6E 55 73 65 4F 77 6E 65 72 4C 61 73 74 4E 61 6D 65 5C 4F 76 69 64 69 75 20 4E 65 74 63 75 56 4F 76 69 64 69 75 55 4E 65 74 63 75 5F 10 CC 45 41 42 49 41 41 41 41 42 4C 77 49 41 41 41 41 41 46 35 41 48 75 45 52 44 6D 64 7A 4C 6D 6C 6A 62 47 39 31 5A 43 35 68 64 58 52 6F 76 51 44 64 43 68 56 46 41 31 44 49 44 74 45 68 32 30 72 77 67 75 58 62 30 7A 68 79 4D 6E 72 58 70 68 72 58 75 4C 79 4E 4A 35 4A 51 76 2D 56 47 5F 66 70 5F 48 61 67 30 46 58 6F 58 43 75 4A 55 51 78 6C 4E 43 54 59 42 34 7A 41 43 61 69 58 6E 56 46 79 50 47 54 50 41 7A 46 77 7A 30 44 7A 59 35 63 59 61 57 45 4C 75 49 74 56 47 42 44 6C 62 4D 71 64 79 4D 6C 46 57 38 6E 30 64 52 42 45 75 6D 78 33 5A 6A 37 35 5F 51 55 68 76 36 56 32 48 41 4F 30 4A 37 76 39 39 38 74 53 41 6F 67 7E 7E 5F 10 24 41 38 38 34 31 31 37 30 2D 33 38 42 36 2D 34 39 46 34 2D 38 43 37 38 2D 31 44 46 37 45 46 35 35 39 39 33 42 11 01 F5 5F 10 17 6E 65 74 5F 63 75 5F 6F 76 69 64 69 75 40 79 61 68 6F 6F 2E 63 6F 6D 59 32 38 31 31 38 39 34 33 34 5F 10 24 31 42 30 39 42 31 30 45 2D 39 38 43 30 2D 34 32 37 36 2D 39 36 43 41 2D 35 41 45 44 32 33 30 42 32 33 45 44 23 41 D7 90 07 B9 BA C0 A0 A1 1E 5F 10 21 63 6F 6D 2E 61 70 70 6C 65 2E 44 61 74 61 63 6C 61 73 73 2E 44 65 76 69 63 65 4C 6F 63 61 74 6F 72 D1 1E 20 D5 21 22 23 24 25 26 27 28 29 2A 56 61 70 73 45 6E 76 58 68 6F 73 74 6E 61 6D 65 5D 69 64 73 49 64 65 6E 74 69 66 69 65 72 56 73 63 68 65 6D 65 5D 61 75 74 68 4D 65 63 68 61 6E 69 73 6D 5A 50 72 6F 64 75 63 74 69 6F 6E 5F 10 13 70 32 37 2D 66 6D 69 70 2E 69 63 6C 6F 75 64 2E 63 6F 6D 5F 10 24 34 43 33 35 30 39 46 37 2D 42 39 39 34 2D 34 30 30 30 2D 41 45 39 45 2D 37 35 37 43 36 35 30 41 35 46 44 30 55 68 74 74 70 73 55 74 6F 6B 65 6E 00 08 00 23 00 35 00 3E 00 48 00 57 00 66 00 6D 00 7B 00 84 00 8D 00 92 00 9A 00 AF 00 C5 00 C7 00 CE 00 E6 00 FC 01 11 01 1E 01 25 01 2B 01 FA 02 21 02 24 02 3E 02 48 02 6F 02 78 02 7A 02 9E 02 A1 02 AC 02 B3 02 BC 02 CA 02 D1 02 DF 02 EA 03 00 03 27 03 2D 00 00 00 00 00 00 02 01 00 00 00 00 00 00 00 2B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 03 33 
6:632  0:000   Adding Key: fmm-mobileme-token-FMM-BridgeHasAccount: Size = 21, Data: 42 72 69 64 67 65 48 61 73 41 63 63 6F 75 6E 74 56 61 6C 75 65 
6:632  0:000   Adding Key: security-mode: String: Size = 4, Val = 'none'
6:632  0:000   Adding Key: specialbootdevice: Size = 122, Data: 02 01 0C 00 D0 41 03 0A 00 00 00 00 01 01 06 00 00 1D 01 01 06 00 00 00 03 17 10 00 01 00 00 00 64 79 A7 29 31 20 31 31 04 01 2A 00 02 00 00 00 28 40 06 00 00 00 00 00 60 2D 6A 74 00 00 00 00 92 43 F6 7A A7 48 85 43 8F BE 86 69 2E 11 4E FB 02 02 04 03 24 00 F7 FC 74 BE 7C 0B F3 49 91 47 01 F4 04 2E 68 42 70 11 84 A8 B6 38 F4 49 8C 78 1D F7 EF 55 99 3B 7F FF 04 00 
6:632  0:000  found 3 handles with audio
6:632  0:000  No AudioIoDevice stored
6:632  0:000  no stored audio parameters
6:632  0:000  Found Audio Device AMD (Unknown) (HDMI) at index 0
6:632  0:000  Found Audio Device AMD (Unknown) (HDMI) at index 1
6:632  0:000  Found Audio Device AMD (Unknown) (HDMI) at index 2
6:632  0:000  Found Audio Device AMD (Unknown) (HDMI) at index 3
6:632  0:000  Found Audio Device AMD (Unknown) (HDMI) at index 4
6:632  0:000  Found Audio Device AMD (Unknown) (HDMI) at index 5
6:632  0:000  Found Audio Device Realtek ALC1220 (LineOut) at index 6
6:632  0:000  Found Audio Device Realtek ALC1220 (LineOut) at index 7
6:632  0:000  Found Audio Device Realtek ALC1220 (LineOut) at index 8
6:632  0:000  Found Audio Device Realtek ALC1220 (Headphones) at index 9
6:632  0:000  Found Audio Device Realtek ALC1220 (SPDIF) at index 10
6:632  0:000  Found Audio Device Intel Kaby Lake HDMI (HDMI) at index 11
6:632  0:000  === [ InitTheme ] =========================================
6:632  0:000  use daylight theme
6:632  0:000   using embedded theme
6:632  0:000  got embedded sound
6:632  0:000    Channels: 2  Sample rate: 8000 Hz  Bits: 16
6:632  0:000  output to channel 0 with volume 70, len=25600
6:632  0:000   sound channels=2 bits=16 freq=8000
6:632  0:000  sound converted to 48kHz
6:632  0:000  not found AudioIo to play
6:632  0:000  sound play end with status=Not Found
6:633  0:000  Using embedded font: Success
6:633  0:000  theme inited
6:633  0:000  Chosen embedded theme
6:633  0:000  after NVRAM boot-args=dart=0 -v slide=0
6:633  0:000  Scanning legacy ...
6:633  0:000  === [ Dump SMC keys from NVRAM ] ==========================
6:633  0:000  found AppleSMC protocol
6:633  0:000  === [ ScanLoader ] ========================================
6:633  0:000  - [01]: 'EFI'
6:636  0:003  - [04]: 'EFI'
6:642  0:005          AddLoaderEntry for Volume Name=EFI
6:642  0:000          skipped because entry is hidden
6:642  0:000  - [06]: 'Preboot', hidden
6:642  0:000  - [07]: 'Machintosh - Data'
6:643  0:000  - [08]: 'Recovery', hidden
6:643  0:000  - [09]: 'VM'
6:643  0:000  - [10]: 'Machintosh'
6:648  0:004          AddLoaderEntry for Volume Name=Machintosh
6:650  0:001      Check if volume Is Hibernated:
6:650  0:000      Check sleep image 'by signature':
6:650  0:000      using default sleep image name = \private\var\vm\sleepimage
6:650  0:000      sleepimage not found -> Not Found
6:650  0:000      hibernated: no - sign
6:651  0:001  === [ AddCustomTool ] =====================================
6:652  0:000  found tool \EFI\CLOVER\tools\Shell64U.efi
6:652  0:000  Checking EFI partition Volume 1 for Clover
6:652  0:000  Checking EFI partition Volume 4 for Clover
6:652  0:000   Found Clover
6:652  0:000  EmuVariable UninstallEmulation: CloseEvent = Success, original var services restored
6:653  0:000  EmuVariable InstallEmulation: orig vars copied, emu.var.services installed, CreateEvent VirtualAddressChange = Success, CreateEvent ExitBootServices = Success, set Status=Success
6:673  0:020  === [ GetEfiBootDeviceFromNvram ] =========================
6:673  0:000   - found entry 0. 'Boot macOS from Machintosh', Volume 'Machintosh', DevicePath 'PciRoot(0x0)\Pci(0x1D,0x0)\Pci(0x0,0x0)\NVMe(0x1,31-31-20-31-29-A7-79-64)\HD(2,GPT,7AF64392-48A7-4385-8FBE-86692E114EFB,0x64028,0x746A2D60)\VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,701184A8B638F4498C781DF7EF55993B)\System\Library\CoreServices\boot.efii'
6:673  0:000  EmuVariable UninstallEmulation: CloseEvent = Success, original var services restored
6:673  0:000  DefaultIndex=0 and MainMenu.EntryCount=7
7:173  0:500  GUI ready

**Comment by SergeySlice** [comment]
All is good here.

**Comment by asava** [comment]
There was an error that could have affected it. Please try again with latest sources.

**Comment by OvidiuNetcu** [comment]
I try and ai notice

**Comment by OvidiuNetcu** [comment]
Install last version, test on start up and sleep. Its ok now. Thx
