### ISSUE TITLE
Trackpad low sensibility when booting windows from clover

### ISSUE THREAD

**Issue by AlbertoHugonin** [CloverHackyColor/CloverBootloader#14]
Every time I boot windows from clover (efi) the trackpad pointer move very slowly so I have to suspend and restart or reinstalling the driver to get my trackpad working again.
I don’t know if this is a clover issue or mine, if it is me I am sorry
[preboot.log](https://github.com/CloverHackyColor/CloverBootloader/files/3764733/preboot.log)

**Comment by AlbertoHugonin** [comment]
I tried but still the same

**Comment by Erictoby** [comment]
There is a possibility that dsdt.aml in E/C/ACPI/Patched has errors if you have edited it for the trackpad in macOS.

**Comment by real-cereal-boy** [comment]
You a mouse instead
