### ISSUE TITLE
GUI – Text Only

### ISSUE THREAD

**Issue by apfelnico** [CloverHackyColor/CloverBootloader#140]
Please take a look at the current Clover menu (r5112) with the option "Text Only" (without CloverTheme). Until recently, everything was fine. White writing on a black background. Now it's a strange mix with background graphics (CloverTheme "Embedded"?).

**Comment by asava** [comment]
Did you test with the latest commits? It's probably already corrected.

**Comment by SergeySlice** [comment]
I will delete TextOnly option in future. Clover must be graphical bootloader.
