### ISSUE TITLE
Clover 5113- Is Badges scale default changed?(Minimalism for clover5113)

### ISSUE THREAD

**Issue by mifjpn** [CloverHackyColor/CloverBootloader#141]
Thanks for the great pkg!

I've modified Minimalism to fit the clover of these days.
After changing Clover from 5112 to 5113, Badges became a small fly.
So I manually adjusted the Badges scale to 12 and cleared the problem.
(From the size, it may be 8.)

I hope this is useful as information.

[Minimalism2-1.zip](https://github.com/CloverHackyColor/CloverBootloader/files/4503564/Minimalism2-1.zip)

**Comment by SergeySlice** [comment]
Resolved
