### ISSUE TITLE
Default boot volume not being observed

### ISSUE THREAD

**Issue by norton287** [CloverHackyColor/CloverBootloader#142]
Instead of the boot volume in the config.plist it just selects the first volume as its choice to boot.  I have double-checked my plist and tried several variations on different bootable volumes but it always defaults to the first volume in the list on the clover menu.

**Comment by SergeySlice** [comment]
It is done by NVRAM.
You have to open System Preferences -> Startup Disk -> chose one and click restsrt.

**Comment by norton287** [comment]
That doesn’t work either, it still selects the first disk in the list in the clover menu.


On April 20, 2020 at 11:47:26 AM, Sergey (notifications@github.com) wrote:

It is done by NVRAM.
You have to open System Preferences -> Startup Disk -> chose one and click restsrt.

**Comment by SergeySlice** [comment]
Type F2, get EFI/CLOVER/misc/preboot.log and show it.
There are information about all your volumes and what clover selected.
I don't understand what you mean. Clover works fine in choosing a volume to boot. It works more then 8 years.

**Comment by norton287** [comment]
I can select any volume to boot, it is just not highlighting the default volume to boot according to the config.plist.  it just highlights by default the first volume.

Here is the reboot


On April 20, 2020 at 1:06:13 PM, Sergey (notifications@github.com) wrote:

Type F2, get EFI/CLOVER/misc/preboot.log and show it.
There are information about all your volumes and what clover selected.
I don't understand what you mean. Clover works fine in choosing a volume to boot. It works more then 8 years.

**Comment by norton287** [comment]
Here is the boot section from my config.plist, Beta should be the default volume selected like it has been for a very long time but instead the volume that appears first in the selection list is selected.

dict>
		<key>Arguments</key>
		<string>dart=0 darkwake=1 -v keepsyms=1 debug=0x100 kext-dev-mode=1</string>
		<key>Debug</key>
		<false/>
		<key>DefaultVolume</key>
		<string>Beta</string>
		<key>Legacy</key>
		<string>PBR</string>
		<key>Secure</key>
		<false/>
		<key>Timeout</key>
		<integer>5</integer>
		<key>XMPDetection</key>
		<integer>1</integer>
	</dict>

**Comment by norton287** [comment]
Try this again

`dict>
		<key>Arguments</key>
		<string>dart=0 darkwake=1 -v keepsyms=1 debug=0x100 kext-dev-mode=1</string>
		<key>Debug</key>
		<false/>
		<key>DefaultVolume</key>
		<string>Beta</string>
		<key>Legacy</key>
		<string>PBR</string>
		<key>Secure</key>
		<false/>
		<key>Timeout</key>
		<integer>5</integer>
		<key>XMPDetection</key>
		<integer>1</integer>
	</dict>`

**Comment by SergeySlice** [comment]
Setting in NVRAM has a priority on config.plist.

**Comment by norton287** [comment]
I tried setting the drive as the boot drive in System Preferences - Startup but I get the error that the NVRAM tool was unable to set a preference when trying that.


On April 21, 2020 at 3:01:42 PM, Sergey (notifications@github.com) wrote:

Setting in NVRAM has a priority on config.plist.

**Comment by norton287** [comment]
Here's is my nvram.plist, everything appears to be in hex.  Is there a way to change the specialbootdrive entry.  I think that is what is selecting macOS as the default volume.  I need it to be Beta instead.
[nvram.plist.zip](https://github.com/CloverHackyColor/CloverBootloader/files/4517757/nvram.plist.zip)

**Comment by SergeySlice** [comment]
Clover works fine in choosing a volume to boot. It works more then 8 years.
