### ISSUE TITLE
No os_icons match for entries like "UEFI internal"

### ISSUE THREAD

**Issue by zty199** [CloverHackyColor/CloverBootloader#146]
I'm sorry for my poor expression in last issue.

I find a strange phenomenon when using Clover 5113.

When I disable all options about os icons in theme.plist, the volume icons show correctly.
However, if I enable "Swap" option in Theme->Badges in theme.plist, only entries for OS show their icons correctly, others like "UEFI internal" still show just a small black-and-yellow square.

Is there any icons for this kind of entries? And how should I name them?

Or, when users enable "Swap" option for os icons, if os_icon which matches the entry exists, the os icon and the vol icon would be swapped. Otherwise the origin volume icon should be shown as default?

I don't know how you make this work, and my English is poor. Hope you can understand what I am talking about.

Thank you.

**Comment by asava** [comment]
Confirmed.

**Comment by asava** [comment]
Corrected in master. It will be os_unknown for unknown OS and os_clover for EFI partition
