### ISSUE TITLE
r5114 breaks my system

### ISSUE THREAD

**Issue by cryptooth** [CloverHackyColor/CloverBootloader#147]
I'm getting "m_lenA fatal error happened. System halted" at boot. And system halted.

**Comment by malhal** [comment]
Thanks, still on 5108 waiting for this to be fixed will keep waiting

**Comment by asava** [comment]
It's probably already corrected in master. An issue that could cause this was identified and fix. It you can compile from sources, please test.

**Comment by TonyC5** [comment]
@asava Can you post a link to the commit that fixes this?  Thank you.

**Comment by asava** [comment]
There were two commits, actually: [this](https://github.com/CloverHackyColor/CloverBootloader/commit/f8c1f08c136e0693dc8a1fce544b3419c488af09) and [this](https://github.com/CloverHackyColor/CloverBootloader/commit/978e35845a42a0b6caf6f18eabaf3db3e0482a99)

And if you want a recent binary, you can find it here: [binary](https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?do=findComment&comment=2718867)

**Comment by cryptooth** [comment]
> It's probably already corrected in master. An issue that could cause this was identified and fix. It you can compile from sources, please test.

Can I update from directly clover menu? I did this operation in the morning. Will it download the corrected version? How can I check build number?

<img width="414" alt="clover" src="https://user-images.githubusercontent.com/28625750/80152727-e200aa00-85c4-11ea-9ec2-c636b05439bf.png">

**Comment by vacarogit** [comment]
> Thanks, still in 5108 waiting for this to be fixed will keep waiting

Yes, I confirm that ever Since 5108, I never get any later rev. right without system halt!
What's going wrong, this really needs a Rework based on 5108 back, not newer ones which are already corrupted in codes

**Comment by asava** [comment]
> > It's probably already corrected in master. An issue that could cause this was identified and fix. It you can compile from sources, please test.
> 
> Can I update from directly clover menu? I did this operation in the morning. Will it download the corrected version? How can I check build number?
No, that will work only after 5115 is released.

**Comment by paaboo** [comment]
> I'm getting "m_lenA fatal error happened. System halted" at boot. And system halted.

Please change other theme in the config.plist file.

**Comment by asava** [comment]
Have the issues been resolved with r5115?

**Comment by cryptooth** [comment]
> Have the issues been resolved with r5115?

not tested yet. little bit busy... I will report.

**Comment by cryptooth** [comment]
Problem solved with r5115. Thanks.

**Comment by asava** [comment]
Thanks for confirming.

**Comment by malhal** [comment]
Just upgraded successfully from the stable 5108 to 5115 so I can also confirm whatever the problem was has now been fixed.

**Comment by asava** [comment]
Thanks for your comment. Glad to hear it's finally working.

**Comment by vacarogit** [comment]
> Thanks, still on 5108 waiting for this to be fixed will keep waiting

Same,  on 5108 since March, any report of instability/errors has been banned by author...any workarounds for you?
