### ISSUE TITLE
clover installation error on a virtual machine

### ISSUE THREAD

**Issue by danipdj13** [CloverHackyColor/CloverBootloader#148]
i cant install clover bootloader into my usb, any solutions for this?
![Captura](https://user-images.githubusercontent.com/64468833/80473965-28e4fb80-8947-11ea-976b-b10164fec76a.PNG)

**Comment by talin3** [comment]
The same issue for me, unfortunately.

**Comment by danipdj13** [comment]
It is on virtual box so I can’t use the recovery drive
I’ve seen that it can be fixed using csrutil disable on the recovery, but I can’t do it

**Comment by vectorsigma72** [comment]
Hi guys, no one tested it on a virtual machine but I'll be happy to help you. Please try attached app and let me 
[Clover.app_v1.19.pkg.zip](https://github.com/CloverHackyColor/CloverBootloader/files/4545730/Clover.app_v1.19.pkg.zip)

know.

**Comment by danipdj13** [comment]
I tried it out, and the message changed
![Captura](https://user-images.githubusercontent.com/64468833/80491773-73747100-8963-11ea-80b6-bca57049f8d5.PNG)

**Comment by vectorsigma72** [comment]
Thanks, now I discovered that this error reported by someone else comes from a virtual machine, finally. But I'm sorry can't do nothing, unless there is something you can do setting up the VM.

**Comment by danipdj13** [comment]
Oh, well, that’s disappointing 
Does anyone have a vmdk or something from a older version of MacOS? I think that it is because Catalina has some kind of protection for the files

**Comment by vectorsigma72** [comment]
Your USB device is not affair of Catalina i guess and I'll be surprised if this will work in Mojave and below.

**Comment by danipdj13** [comment]
How could I fix it?
I’m downloading a high Sierra version to try it

**Comment by vectorsigma72** [comment]
Thanks, but sorry I have no idea right now. At this point I'm not even sure if the volume's mount point is real, it's a sym link or whatever.

**Comment by danipdj13** [comment]
Thanks anyway
I close this post
