### ISSUE TITLE
Memory panic

### ISSUE THREAD

**Issue by danipdj13** [CloverHackyColor/CloverBootloader#149]
Hello everyone
I managed to make a usb bootable but, I have a problem when I load it up 
![image](https://user-images.githubusercontent.com/64468833/80580353-b2f69800-8a0b-11ea-9fef-e6e72367ff02.jpg)
I don’t know what else to do
Thanks in advance

**Comment by CMMChris** [comment]
1st: Not a Clover issue
2nd: Nobody can help you without the relevant information which is entirely cut off in your picture.

**Comment by danipdj13** [comment]
Seems like it disappeared 
Now when it pass the test, it suddenly stops giving video signal

**Comment by SergeySlice** [comment]
Set
		<key>PanicNoKextDump</key>
		<true/>
to see more informative panic.

**Comment by danipdj13** [comment]
Now the panic message doesn’t appear, it just stop sending signal to my monitor

**Comment by asava** [comment]
Did it work with previous Clover or it is the first time you try?

**Comment by danipdj13** [comment]
It’s my first time building a hackintosh

**Comment by asava** [comment]
This is not a support forum. Please visit the forums for that.
