### ISSUE TITLE
What the bug？

### ISSUE THREAD

**Issue by SKT01KP** [CloverHackyColor/CloverBootloader#150]
![3A906424-DD9F-42B5-8F98-2F46CC232C5B](https://user-images.githubusercontent.com/64546333/80618349-1676ca80-89f8-11ea-83d0-564ee1ee80a6.jpeg)

Am I first？

**Comment by asava** [comment]
Some details maybe?
Did it work with previous Clover? if yes, with what revision?
Which system is it?

**Comment by asava** [comment]
If you do not provide further details, I will close this as impossible to reproduce.
