### ISSUE TITLE
Apple Progress Load bar issue

### ISSUE THREAD

**Issue by mehmetyukcell** [CloverHackyColor/CloverBootloader#151]
Clover bootloader issiue: Apple progress load bar not appeared when clover 5107 from to 5115. But, in the clover 5107 is not a problem.

**Comment by asava** [comment]
You have by mistake CustomLogo set anywhere in your config.plist?

**Comment by mehmetyukcell** [comment]
> You have by mistake CustomLogo anywhere in your config.plist (set to anything other than false)?

Sory, I beg your pardon! CustomLogoTheme
![Ekran Resmi 2020-04-30 01 34 31](https://user-images.githubusercontent.com/62822060/80653390-c5f87f00-8a82-11ea-8aba-be5b686cc270.png)

**Comment by mehmetyukcell** [comment]
> You have by mistake CustomLogo anywhere in your config.plist (set to anything other than false)?


[config.plist.zip](https://github.com/CloverHackyColor/CloverBootloader/files/4555140/config.plist.zip)

**Comment by asava** [comment]
So the problem is solved by setting to false?

**Comment by mehmetyukcell** [comment]
> So the problem is solved by setting to false?

which setting should I choose? 
![Ekran Resmi 2020-04-30 01 51 14](https://user-images.githubusercontent.com/62822060/80654525-1c66bd00-8a85-11ea-8c02-e11773c36aff.png)

**Comment by asava** [comment]
None or No
