### ISSUE TITLE
Suggest to reduce CPU load

### ISSUE THREAD

**Issue by allegrox** [CloverHackyColor/CloverBootloader#154]
When staying in the OS selection state, the CPU load remains high and CPU cooling fan runs at high speed. Suggest to reduce CPU load, If there is no operation for a long time, it is better to enter the energy-saving state.

My laptop is HP EliteBook 820 G4, and clover is r5115.

**Comment by asava** [comment]
I don't think it is related to Clover Isn't it the same, for example, if you stay in BIOS?
