### ISSUE TITLE
Shift key doesn't work in Clover

### ISSUE THREAD

**Issue by JingleDjango** [CloverHackyColor/CloverBootloader#16]
Was previously using ver. 5045 and had this issue. Just updated to current stable release (5097) and the issue persists.

In Clover, for example when trying to manually add boot flags in the Options menu, the Shift key does nothing. I've tried two wired USB keyboards: Matias QuietKey Pro (Mac) and a Logitech K120 (Win). 

Searching around I've seen similar reports on various forums but they date back several years and none look to be resolved.

**Comment by SergeySlice** [comment]
It is BIOS feature, not resolvable.

**Comment by JingleDjango** [comment]
Thanks for your reply.

Is the problem specific to certain BIOSs? 
Would it be possible to reassign another key to that character?

**Comment by chrisbutler** [comment]
@SergeySlice if this is true, why does it work fine in some versions of clover?

**Comment by JingleDjango** [comment]
That was my question next question as well.

**Comment by SergeySlice** [comment]
> @SergeySlice if this is true, why does it work fine in some versions of clover?

If it doesn't work with this BIOS then it will not work with other Clover version.
