### ISSUE TITLE
How to make a silm package?

### ISSUE THREAD

**Issue by allegrox** [CloverHackyColor/CloverBootloader#160]
I found that the underlying script has relevant parameters(~/src/CloverBootloader/CloverPackage/makepkg), but no function was found in the menu. How to do it?

**Comment by asava** [comment]
I don't know the answer to that, but this place is for bug reports. For questions, the forums is a better idea. I will close this.

**Comment by allegrox** [comment]
Thanks, but where is the forums to talk about the CloverBootloader?
