### ISSUE TITLE
SMBIOS handling

### ISSUE THREAD

**Issue by sincohen** [CloverHackyColor/CloverBootloader#162]
feature request:

Can SMBIOS data be separated from config.plist (in separate smbios.plist for instance)? separating this out would make EFI much more (fully?) portable. people could post working EFI or config.plist and SMBIOS data will always be secure, persistent, and easy to add and maintain separately.

**Comment by vectorsigma72** [comment]
That make no sense to me. In the event you want to share your configuration there are the exact same chances you forgot to delete your secreted smbios.plist, and otherwise, everyone will wonder which emulation to use. Just don't share the BoardSerialNumber and the MLB (which is under RtVariables).

**Comment by SergeySlice** [comment]
No sense to share config.plist. There are patches for kexts which can be shared somewhere in common place. There are ACPI patches which is BIOS version dependent so will be different for each individual. There are GUI tuning which is individual and not obligatory for success.
