### ISSUE TITLE
Option to Save Clover Preference Pane on USB

### ISSUE THREAD

**Issue by nyhtml** [CloverHackyColor/CloverBootloader#166]
I start to test newer versions of Clover 2.5k after 5093 for a week on USB before adding it to my main system drive and during testing, I saw that I am unable to install the Preference Pane on a USB (as it is greyed out) since it has to be installed in System Preferences on the HDD.

![Clover prefPane](https://user-images.githubusercontent.com/2177262/82131656-7fef2b00-97a5-11ea-94d8-2588ae042800.png)

![CPP2](https://user-images.githubusercontent.com/2177262/82131762-b0839480-97a6-11ea-9073-ed760d8b11ee.png)

**Comment by SergeySlice** [comment]
Clover updater and Clover PreferencePane are not supported with Clover 5097 and up.
You have to install recent Clover (5117 at this moment) manually and use Clover.app for next updating and maintenance.
