### ISSUE TITLE
Entering Windows from Clover, audio driver error

### ISSUE THREAD

**Issue by chiccheung** [CloverHackyColor/CloverBootloader#171]
Entering Windows 10 2004 from Clover r5118, audio driver error；
Entering Windows 10 2004 from Bios, everything OK.

**Comment by SergeySlice** [comment]
Or vice versa?
I entering Windows 10 by Clover 5118 and enjoy my music.

**Comment by chiccheung** [comment]
> Or vice versa?
> I entering Windows 10 by Clover 5118 and enjoy my music.

AudioDxe.efi caused this problem.
After deleting this file, everything works perfectly.
