### ISSUE TITLE
PluginType not working in 5118

### ISSUE THREAD

**Issue by CMMChris** [CloverHackyColor/CloverBootloader#172]
Hi,

I just noticed that PluginType injection stopped working in 5118.
![Bildschirmfoto 2020-05-25 um 10 08 41](https://user-images.githubusercontent.com/58958133/82792585-e512e280-9e6f-11ea-9d0a-fa23e0630fd5.jpg)

Cheers,
Chris

**Comment by SergeySlice** [comment]
May be the problem elsewhere?
![Снимок экрана 2020-05-25 в 12 28 09](https://user-images.githubusercontent.com/485515/82799798-4c865d80-9e83-11ea-8cfd-3245109b9916.png)

**Comment by CMMChris** [comment]
Hm, I will investigate and Report Back. Maybe ist's the latest macOS Beta.

**Comment by CMMChris** [comment]
Yup, latest macOS beta is the culprit. It doesn't even work with SSDT-PLUG. Haven't been able to figure out the reason though. On my MacBook Pro X86PlatformPlugin does load just fine. Strange.

**Comment by CMMChris** [comment]
Okay, issue solved, you can trash this ticket. Issue was invalid signature of X86PlatformPlugin. Somehow got corrupted during the last beta update. I restored the version of my CCC backup and it is working again.
