### ISSUE TITLE
Update 5108 to 5118 kernel panic

### ISSUE THREAD

**Issue by doadin** [CloverHackyColor/CloverBootloader#175]
Tried to update 5108 to 5118 no other changes and wouldn't boot.

**Comment by asava** [comment]
Try to set:

	<key>Devices</key>
	<dict>
		<key>NoDefaultProperties</key>
		<false/>

**Comment by TA2AGV** [comment]
I was stuck at 5108 because of black screen issue after boot menu with 5109.
@asava's suggestion solved it. Now I'm on 5118. Thanks!

**Comment by asava** [comment]
duplicate of #170

**Comment by doadin** [comment]
that actually didn't solve my problem

**Comment by doadin** [comment]
thanks for closing the issue though

**Comment by asava** [comment]
Not sure what you expected, as you provided no further information or response. I will reopen, but provide further detail on the panic you are having.

**Comment by doadin** [comment]
well im just a hackintosh noob so not sure exactly what i should provide. A issue template would help with that. also just cause I didn't provide info instead of requesting more info and helping me know what info to provide, like "please pastebin logs found in xxxx" or something you just close the ticket as if its solved? ok i guess....
