### ISSUE TITLE
Clover update issue in Catalina

### ISSUE THREAD

**Issue by Hillperson** [CloverHackyColor/CloverBootloader#18]
I've updated the clover to 5096 before, and updated my mojave to catalina. Everything is good and no problem. I have updated to supplement version now 19A602.
I just got a notice that clover 5097 is released and it suggested me to update. So I download it from the Github.
When I try to install clover 5097, it said the installer is not compatible with this MacOS, and when I continue, it finally failed. I can still reboot from clover, but the clover control panel disappeared from the system preference. I also tried to install the clover 5096 again, the same error.

I guess reason is about the new system file protection in Catalina, but I don't know how to solve it and update my clover in future.

Any solution to this? Thanks

**Comment by reginastracii** [comment]
read here : [https://www.tonymacx86.com/threads/macos-10-15-catalina-how-to-mount-root-partition-read-write-for-post-installation.283749/](url)

**Comment by Hillperson** [comment]
> read here : `https://www.tonymacx86.com/threads/macos-10-15-catalina-how-to-mount-root-partition-read-write-for-post-installation.283749/`

Thanks for the help, but I tried that command, and make sure there was no error during the command, but the installation is still failed.

I posted the issue in Tonymacx86 as well, I put 2 pictures for my problem. And I double check the real clover version on the EFI partition with restart, it is still 5097 not 5096. Which means the install failed, and no change in EFI, and no control panel in the system preference.

**Comment by wuyuehyang** [comment]
Same issue here. My Catalina was upgraded from Mojave too.

**Comment by barad1tos** [comment]
+1. 

Same issue and the same upgrade to Catalina from Mojave.

**Comment by Hillperson** [comment]
use the new 5098 version. Problem solved.

**Comment by wuyuehyang** [comment]
![Screen Shot 2019-10-31 at 01 00 53](https://user-images.githubusercontent.com/12228763/67880640-fd40ae80-fb79-11e9-95d8-d17eb293e557.png)

r5098 doesn't work either. Root partition is already mounted as r/w.

My Catalina is on 10.15 (19A583).

**Comment by CreativeMK** [comment]
E3-1230 v3 1150 Hasewell CPU, MSI ZH87 motherboard, HD7950 graphics card.

I have the same problem too. And I tried both r5070 and r5097. They all stucked at restart. 
With r5097, it just restart again and again.



<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>#DisableDrivers</key>
	<array>
		<string>CsmVideoDxe</string>
		<string>VBoxExt4</string>
	</array>
	<key>ACPI</key>
	<dict>
		<key>#PatchAPIC</key>
		<false/>
		<key>#ResetAddress</key>
		<string>0x64</string>
		<key>#ResetValue</key>
		<string>0xFE</string>
		<key>#SortedOrder</key>
		<array>
			<string>SSDT-3.aml</string>
			<string>SSDT-1.aml</string>
			<string>SSDT-2.aml</string>
		</array>
		<key>#smartUPS</key>
		<false/>
		<key>AutoMerge</key>
		<false/>
		<key>DSDT</key>
		<dict>
			<key>#DropOEM_DSM</key>
			<dict>
				<key>ATI</key>
				<true/>
				<key>Firewire</key>
				<true/>
				<key>HDA</key>
				<true/>
				<key>HDMI</key>
				<true/>
				<key>IDE</key>
				<true/>
				<key>IntelGFX</key>
				<true/>
				<key>LAN</key>
				<true/>
				<key>LPC</key>
				<false/>
				<key>NVidia</key>
				<true/>
				<key>SATA</key>
				<true/>
				<key>SmBUS</key>
				<false/>
				<key>USB</key>
				<true/>
				<key>WIFI</key>
				<true/>
			</dict>
			<key>#Rtc8Allowed</key>
			<false/>
			<key>#SuspendOverride</key>
			<false/>
			<key>Debug</key>
			<false/>
			<key>DropOEM_DSM</key>
			<dict>
				<key>ATI</key>
				<true/>
				<key>Firewire</key>
				<false/>
				<key>HDA</key>
				<false/>
				<key>HDMI</key>
				<true/>
				<key>IDE</key>
				<false/>
				<key>IntelGFX</key>
				<false/>
				<key>LAN</key>
				<true/>
				<key>LPC</key>
				<false/>
				<key>NVidia</key>
				<false/>
				<key>SATA</key>
				<true/>
				<key>SmBUS</key>
				<false/>
				<key>USB</key>
				<true/>
				<key>WIFI</key>
				<false/>
			</dict>
			<key>Fixes</key>
			<dict>
				<key>AddDTGP</key>
				<true/>
				<key>AddHDMI</key>
				<true/>
				<key>AddIMEI</key>
				<false/>
				<key>AddMCHC</key>
				<false/>
				<key>AddPNLF</key>
				<true/>
				<key>DeleteUnused</key>
				<true/>
				<key>FakeLPC</key>
				<false/>
				<key>FixACST</key>
				<true/>
				<key>FixADP1</key>
				<true/>
				<key>FixDarwin</key>
				<false/>
				<key>FixDarwin7</key>
				<true/>
				<key>FixDisplay</key>
				<true/>
				<key>FixHDA</key>
				<true/>
				<key>FixHPET</key>
				<true/>
				<key>FixHeaders</key>
				<true/>
				<key>FixIPIC</key>
				<true/>
				<key>FixLAN</key>
				<true/>
				<key>FixRTC</key>
				<true/>
				<key>FixRegions</key>
				<true/>
				<key>FixS3D</key>
				<true/>
				<key>FixSATA</key>
				<true/>
				<key>FixSBUS</key>
				<true/>
				<key>FixShutdown</key>
				<true/>
				<key>FixTMR</key>
				<true/>
				<key>FixUSB</key>
				<true/>
				<key>FixWAK</key>
				<true/>
			</dict>
			<key>Name</key>
			<string>DSDT.aml</string>
			<key>Patches</key>
			<array>
				<dict>
					<key>Comment</key>
					<string>Add _SUN property for GIGE</string>
					<key>Disabled</key>
					<true/>
					<key>Find</key>
					<data>
					UFhTWAhfQURSAAhfUFJXEgYC
					</data>
					<key>Replace</key>
					<data>
					UFhTWAhfQURSAAhfU1VOCgQIX1BSVxIGAg==
					</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>Rename GFX0 to IGPU</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					R0ZYMA==
					</data>
					<key>Replace</key>
					<data>
					SUdQVQ==
					</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>Rename HDEF to AZAL</string>
					<key>Disabled</key>
					<true/>
					<key>Find</key>
					<data>
					SERFRg==
					</data>
					<key>Replace</key>
					<data>
					QVpBTA==
					</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>Rename oem _DSM to ZDSM</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					X0RTTQ==
					</data>
					<key>Replace</key>
					<data>
					WkRTTQ==
					</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>Rename HECI to IMEI</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					SEVDSQ==
					</data>
					<key>Replace</key>
					<data>
					SU1FSQ==
					</data>
				</dict>
			</array>
			<key>ReuseFFFF</key>
			<false/>
			<key>SlpSmiAtWake</key>
			<false/>
		</dict>
		<key>DropTables</key>
		<array>
			<dict>
				<key>Signature</key>
				<string>DMAR</string>
			</dict>
			<dict>
				<key>Signature</key>
				<string>SSDT</string>
				<key>TableId</key>
				<string>CpuPm</string>
			</dict>
			<dict>
				<key>#Length</key>
				<integer>720</integer>
				<key>Signature</key>
				<string>SSDT</string>
				<key>TableId</key>
				<string>Cpu0Ist</string>
			</dict>
		</array>
		<key>FixHeaders</key>
		<true/>
		<key>HaltEnabler</key>
		<true/>
		<key>SSDT</key>
		<dict>
			<key>#C3Latency</key>
			<string>0x03E7</string>
			<key>#DoubleFirstState</key>
			<true/>
			<key>#DropOem</key>
			<true/>
			<key>#EnableC2</key>
			<false/>
			<key>#EnableC4</key>
			<false/>
			<key>#EnableC6</key>
			<true/>
			<key>#EnableC7</key>
			<false/>
			<key>#MaxMultiplier</key>
			<integer>12</integer>
			<key>#MinMultiplier</key>
			<integer>8</integer>
			<key>#NoDynamicExtract</key>
			<false/>
			<key>#NoOemTableId</key>
			<false/>
			<key>#PLimitDict</key>
			<integer>1</integer>
			<key>#PluginType</key>
			<integer>0</integer>
			<key>#UnderVoltStep</key>
			<integer>1</integer>
			<key>#UseSystemIO</key>
			<false/>
			<key>DropOem</key>
			<false/>
			<key>Generate</key>
			<dict>
				<key>#APLF</key>
				<false/>
				<key>#APSN</key>
				<false/>
				<key>#PluginType</key>
				<false/>
				<key>CStates</key>
				<true/>
				<key>PStates</key>
				<true/>
				<key>PluginType</key>
				<false/>
			</dict>
		</dict>
	</dict>
	<key>Boot</key>
	<dict>
		<key>#Arguments</key>
		<string>slide=0 darkwake=0</string>
		<key>#DefaultLoader</key>
		<string>boot.efi</string>
		<key>#LegacyBiosDefaultEntry</key>
		<integer>0</integer>
		<key>#XMPDetection</key>
		<string>-1</string>
		<key>Debug</key>
		<false/>
		<key>DefaultVolume</key>
		<string>Mac</string>
		<key>Fast</key>
		<true/>
		<key>HibernationFixup</key>
		<false/>
		<key>Legacy</key>
		<string>PBR</string>
		<key>NeverDoRecovery</key>
		<true/>
		<key>NeverHibernate</key>
		<false/>
		<key>StrictHibernate</key>
		<false/>
	</dict>
	<key>BootGraphics</key>
	<dict>
		<key>#DefaultBackgroundColor</key>
		<string>0xF0F0F0</string>
		<key>EFILoginHiDPI</key>
		<integer>1</integer>
		<key>UIScale</key>
		<integer>1</integer>
	</dict>
	<key>CPU</key>
	<dict>
		<key>#BusSpeedkHz</key>
		<integer>133330</integer>
		<key>#FrequencyMHz</key>
		<integer>3140</integer>
		<key>#HWPEnable</key>
		<true/>
		<key>#HWPValue</key>
		<string>0x30002a01</string>
		<key>#QPI</key>
		<integer>4800</integer>
		<key>#SavingMode</key>
		<integer>7</integer>
		<key>#TDP</key>
		<integer>95</integer>
		<key>#TurboDisable</key>
		<true/>
		<key>#Type</key>
		<string>0x0201</string>
		<key>#UseARTFrequency</key>
		<true/>
		<key>HWPEnable</key>
		<false/>
		<key>UseARTFrequency</key>
		<false/>
	</dict>
	<key>Devices</key>
	<dict>
		<key>#AddProperties</key>
		<array>
			<dict>
				<key>Device</key>
				<string>NVidia</string>
				<key>Key</key>
				<string>AAPL,HasPanel</string>
				<key>Value</key>
				<data>
				AQAAAA==
				</data>
			</dict>
			<dict>
				<key>Device</key>
				<string>NVidia</string>
				<key>Key</key>
				<string>AAPL,Haslid</string>
				<key>Value</key>
				<data>
				AQAAAA==
				</data>
			</dict>
		</array>
		<key>#AirportBridgeDeviceName</key>
		<string>RP02</string>
		<key>#Arbitrary</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>Thunderbolt bridge</string>
				<key>CustomProperties</key>
				<array>
					<dict>
						<key>Disabled</key>
						<true/>
						<key>Key</key>
						<string>PCI-Thunderbolt</string>
						<key>Value</key>
						<integer>3</integer>
					</dict>
				</array>
				<key>PciAddr</key>
				<string>03:00:00</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Thunderbolt device</string>
				<key>CustomProperties</key>
				<array>
					<dict>
						<key>Disabled</key>
						<true/>
						<key>Key</key>
						<string>TBTDPLowToHigh</string>
						<key>Value</key>
						<data>
						AQAAAA==
						</data>
					</dict>
					<dict>
						<key>Disabled</key>
						<true/>
						<key>Key</key>
						<string>ThunderboltUUID</string>
						<key>Value</key>
						<data>
						CO8yvYVBslCHyHKPjwfU/A==
						</data>
					</dict>
				</array>
				<key>PciAddr</key>
				<string>05:00:00</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string>IntelGfx</string>
				<key>CustomProperties</key>
				<array>
					<dict>
						<key>Key</key>
						<string>graphic-options</string>
						<key>Value</key>
						<data>
						DAAAAA==
						</data>
					</dict>
					<dict>
						<key>Key</key>
						<string>hda-gfx</string>
						<key>Value</key>
						<string>onboard-1</string>
					</dict>
					<dict>
						<key>Key</key>
						<string>AAPL,ig-platform-id</string>
						<key>Value</key>
						<data>
						AAASGQ==
						</data>
					</dict>
					<dict>
						<key>Key</key>
						<string>model</string>
						<key>Value</key>
						<string>Intel HD Graphics 7000</string>
					</dict>
					<dict>
						<key>Key</key>
						<string>subsystem-vendor-id</string>
						<key>Value</key>
						<data>
						axAAAA==
						</data>
					</dict>
					<dict>
						<key>Key</key>
						<string>subsystem-id</string>
						<key>Value</key>
						<data>
						hoAAAA==
						</data>
					</dict>
					<dict>
						<key>Disabled</key>
						<true/>
						<key>Key</key>
						<string>@2,AAPL,boot-display</string>
						<key>Value</key>
						<true/>
					</dict>
				</array>
				<key>PciAddr</key>
				<string>00:02:00</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string>HDA Audio</string>
				<key>CustomProperties</key>
				<array>
					<dict>
						<key>Key</key>
						<string>hda-gfx</string>
						<key>Value</key>
						<string>onboard-1</string>
					</dict>
				</array>
				<key>PciAddr</key>
				<string>00:1f:03</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string>ATI Radeon</string>
				<key>CustomProperties</key>
				<array>
					<dict>
						<key>Key</key>
						<string>hda-gfx</string>
						<key>Value</key>
						<string>onboard-2</string>
					</dict>
					<dict>
						<key>Key</key>
						<string>model</string>
						<key>Value</key>
						<string>AMD Radeon HD6450</string>
					</dict>
					<dict>
						<key>Disabled</key>
						<false/>
						<key>Key</key>
						<string>@AAPL,boot-display</string>
						<key>Value</key>
						<true/>
					</dict>
				</array>
				<key>PciAddr</key>
				<string>01:00:00</string>
			</dict>
		</array>
		<key>#DisableFunctions</key>
		<string>0x18F6</string>
		<key>#FakeID</key>
		<dict>
			<key>#ATI</key>
			<string>0x67501002</string>
			<key>#IMEI</key>
			<string>0x1e208086</string>
			<key>#IntelGFX</key>
			<string>0x01268086</string>
			<key>#LAN</key>
			<string>0x100E8086</string>
			<key>#NVidia</key>
			<string>0x11de10de</string>
			<key>#SATA</key>
			<string>0x25628086</string>
			<key>#WIFI</key>
			<string>0x431214e4</string>
			<key>#XHCI</key>
			<string>0x0</string>
		</dict>
		<key>#ForceHPET</key>
		<false/>
		<key>#Inject</key>
		<false/>
		<key>#IntelMaxValue</key>
		<integer>1808</integer>
		<key>#Properties</key>
		<string>7a00000001000000010000006e0000000200000002010c00d041030a0000000001010600001b7fff040028000000500069006e0043006f006e00660069006700750072006100740069006f006e00730000000800000001080100180000006c00610079006f00750074002d00690064000000080000000c000000</string>
		<key>#SetIntelBacklight</key>
		<false/>
		<key>#SetIntelMaxBacklight</key>
		<true/>
		<key>Audio</key>
		<dict>
			<key>#Inject</key>
			<string>0x0887</string>
			<key>AFGLowPowerState</key>
			<true/>
			<key>Inject</key>
			<string>Detect</string>
			<key>ResetHDA</key>
			<true/>
		</dict>
		<key>USB</key>
		<dict>
			<key>AddClockID</key>
			<true/>
			<key>FixOwnership</key>
			<true/>
			<key>Inject</key>
			<true/>
		</dict>
	</dict>
	<key>GUI</key>
	<dict>
		<key>#ConsoleMode</key>
		<string>0</string>
		<key>#Custom</key>
		<dict>
			<key>Entries</key>
			<array>
				<dict>
					<key>AddArguments</key>
					<string>-v</string>
					<key>Arguments</key>
					<string>Kernel=mach_kernel</string>
					<key>Disabled</key>
					<true/>
					<key>Hidden</key>
					<false/>
					<key>Hotkey</key>
					<string>M</string>
					<key>InjectKexts</key>
					<false/>
					<key>NoCaches</key>
					<false/>
					<key>Path</key>
					<string>\EFI\BOOT\BOOTX64.efi</string>
					<key>Title</key>
					<string>MyCustomEntry</string>
					<key>Type</key>
					<string>OSXRecovery</string>
					<key>Volume</key>
					<string>D68F1885-571C-4441-8DD5-F14803EFEF54</string>
				</dict>
				<dict>
					<key>Hidden</key>
					<false/>
					<key>InjectKexts</key>
					<false/>
					<key>NoCaches</key>
					<false/>
					<key>SubEntries</key>
					<array>
						<dict>
							<key>AddArguments</key>
							<string>-v</string>
							<key>Title</key>
							<string>Boot OS X 10.8.5 (12F36) Mountain Lion in Verbose Mode</string>
						</dict>
					</array>
					<key>Title</key>
					<string>OS X 10.8.5 (12F36) Mountain Lion</string>
					<key>Type</key>
					<string>OSX</string>
					<key>Volume</key>
					<string>454794AC-760D-46E8-8F77-D6EB23D2FD32</string>
				</dict>
			</array>
			<key>Legacy</key>
			<array>
				<dict>
					<key>Disabled</key>
					<true/>
					<key>Hidden</key>
					<false/>
					<key>Hotkey</key>
					<string>L</string>
					<key>Title</key>
					<string>MyLegacyEntry</string>
					<key>Type</key>
					<string>Windows</string>
					<key>Volume</key>
					<string>89433CD3-21F2-4D3C-95FC-722C48066D3A</string>
				</dict>
			</array>
			<key>Tool</key>
			<array>
				<dict>
					<key>Arguments</key>
					<string>-b</string>
					<key>Disabled</key>
					<false/>
					<key>Hidden</key>
					<false/>
					<key>Hotkey</key>
					<string>S</string>
					<key>Path</key>
					<string>\EFI\CLOVER\TOOLS\Shell64-v1.efi</string>
					<key>Title</key>
					<string>MyCustomShell</string>
					<key>Volume</key>
					<string>D68F1885-571C-4441-8DD5-F14803EFEF54</string>
				</dict>
			</array>
		</dict>
		<key>#CustomIcons</key>
		<false/>
		<key>#Hide</key>
		<array>
			<string>Windows</string>
			<string>BOOTX64.EFI</string>
		</array>
		<key>#Language</key>
		<string>ru:0</string>
		<key>#Mouse</key>
		<dict>
			<key>Enabled</key>
			<true/>
			<key>Mirror</key>
			<false/>
			<key>Speed</key>
			<integer>2</integer>
		</dict>
		<key>#Scan</key>
		<dict>
			<key>Entries</key>
			<true/>
			<key>Legacy</key>
			<false/>
			<key>Tool</key>
			<true/>
		</dict>
		<key>#TextOnly</key>
		<false/>
		<key>ScreenResolution</key>
		<string>1920x1200</string>
		<key>Theme</key>
		<string>embedded</string>
	</dict>
	<key>Graphics</key>
	<dict>
		<key>#Connectors</key>
		<array/>
		<key>#DualLink</key>
		<integer>0</integer>
		<key>#FBName</key>
		<string>Makakakakala</string>
		<key>#Inject</key>
		<dict>
			<key>ATI</key>
			<true/>
			<key>Intel</key>
			<false/>
			<key>NVidia</key>
			<false/>
		</dict>
		<key>#LoadVBios</key>
		<false/>
		<key>#NVCAP</key>
		<string>04000000000003000C0000000000000A00000000</string>
		<key>#NvidiaGeneric</key>
		<true/>
		<key>#NvidiaNoEFI</key>
		<false/>
		<key>#NvidiaSingle</key>
		<false/>
		<key>#PatchVBios</key>
		<false/>
		<key>#PatchVBiosBytes</key>
		<array>
			<dict>
				<key>Find</key>
				<data>
				gAeoAqAF
				</data>
				<key>Replace</key>
				<data>
				gAeoAjgE
				</data>
			</dict>
		</array>
		<key>#RadeonDeInit</key>
		<true/>
		<key>#VRAM</key>
		<integer>1024</integer>
		<key>#VideoPorts</key>
		<integer>2</integer>
		<key>#display-cfg</key>
		<string>03010300FFFF0001</string>
		<key>#ig-platform-id</key>
		<string>0x01620005</string>
		<key>EDID</key>
		<dict>
			<key>#Custom</key>
			<data>
			AP///////wAGECGSAAAAAAASAQOAIRV4CunVmVlTjigmUFQAAAAB
			AQEBAQEBAQEBAQEBAQEB3iGgcFCEHzAgIFYAS88QAAAY3iGgcFCE
			HzAgIFYAS88QAAAAAAAA/gBXNjU3RwAxNTRXUDEKAAAA/gAjMz1I
			ZYSq/wIBCiAgAJo=
			</data>
			<key>#HorizontalSyncPulseWidth</key>
			<string>0x11</string>
			<key>#Inject</key>
			<true/>
			<key>#ProductID</key>
			<string>0x9221</string>
			<key>#VendorID</key>
			<string>0x1006</string>
			<key>#VideoInputSignal</key>
			<string>0xA1</string>
			<key>Inject</key>
			<false/>
			<key>ProductID</key>
			<string>0x66581002</string>
			<key>VendorID</key>
			<string>0x1002</string>
		</dict>
		<key>Inject</key>
		<dict>
			<key>ATI</key>
			<true/>
			<key>NVidia</key>
			<false/>
		</dict>
		<key>LoadVBios</key>
		<false/>
		<key>PatchVBios</key>
		<false/>
		<key>RadeonDeInit</key>
		<true/>
	</dict>
	<key>KernelAndKextPatches</key>
	<dict>
		<key>#ATIConnectorsController</key>
		<string>6000</string>
		<key>#ATIConnectorsData</key>
		<string>000400000403000000010000210302040400000014020000000100000000040310000000100000000001000000000001</string>
		<key>#ATIConnectorsPatch</key>
		<string>040000001402000000010000000004040004000004030000000100001102010500000000000000000000000000000000</string>
		<key>#BootPatches</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>Example</string>
				<key>Disabled</key>
				<true/>
				<key>Find</key>
				<data>
				RXh0ZXJuYWw=
				</data>
				<key>MatchOS</key>
				<string>All</string>
				<key>Replace</key>
				<data>
				SW50ZXJuYWw=
				</data>
			</dict>
		</array>
		<key>#FakeCPUID</key>
		<string>0x010676</string>
		<key>#ForceKextsToLoad</key>
		<array>
			<string>\System\Library\Extensions\AMD6000Controller.kext</string>
			<string>\System\Library\Extensions\AMDFramebuffer.kext</string>
		</array>
		<key>#KernelToPatch</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>Infinite loop at wake</string>
				<key>Disabled</key>
				<true/>
				<key>Find</key>
				<data>
				TIn/6PXb/v8=
				</data>
				<key>MatchOS</key>
				<string>10.11</string>
				<key>Replace</key>
				<data>
				6/7/6PXb/v8=
				</data>
			</dict>
		</array>
		<key>#KextsToPatch</key>
		<array>
			<dict>
				<key>Disabled</key>
				<true/>
				<key>Find</key>
				<data>
				SGVhZHBob25lcwA=
				</data>
				<key>Name</key>
				<string>VoodooHDA</string>
				<key>Replace</key>
				<data>
				VGVsZXBob25lcwA=
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Patch_to_not_load_this_driver</string>
				<key>Find</key>
				<string>0x04020000</string>
				<key>InfoPlistPatch</key>
				<true/>
				<key>Name</key>
				<string>AppleHDAController</string>
				<key>Replace</key>
				<string>0x44220000</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Make all drives to be internal</string>
				<key>Find</key>
				<data>
				RXh0ZXJuYWw=
				</data>
				<key>Name</key>
				<string>AppleAHCIPort</string>
				<key>Replace</key>
				<data>
				SW50ZXJuYWw=
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>TRIM function for non-Apple SSDs</string>
				<key>Find</key>
				<data>
				QVBQTEUgU1NEAA==
				</data>
				<key>Name</key>
				<string>IOAHCIBlockStorage</string>
				<key>Replace</key>
				<data>
				AAAAAAAAAAAAAA==
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>ATI Connector patch new way</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				AAQAAAQDAAAAAQAAIQMCBAQAAAAUAgAAAAEAAAAABAMQ
				AAAAEAAAAAABAAAAAAAB
				</data>
				<key>MatchOS</key>
				<string>10.9,10.10,10.11</string>
				<key>Name</key>
				<string>AMD6000Controller</string>
				<key>Replace</key>
				<data>
				BAAAABQCAAAAAQAAAAAEBAAEAAAEAwAAAAEAABECAQUA
				AAAAAAAAAAAAAAAAAAAA
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>ATI name HD xxxx -&gt; HD6450</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				SEQgNnh4eA==
				</data>
				<key>MatchOS</key>
				<string>10.12,10.13</string>
				<key>Name</key>
				<string>AMD6000Controller</string>
				<key>Replace</key>
				<data>
				SEQgNjQ1MA==
				</data>
			</dict>
		</array>
		<key>AppleIntelCPUPM</key>
		<true/>
		<key>AppleRTC</key>
		<true/>
		<key>Debug</key>
		<false/>
		<key>DellSMBIOSPatch</key>
		<false/>
		<key>FakeCPUID</key>
		<string>0x0306C0</string>
		<key>KernelCpu</key>
		<false/>
		<key>KernelLapic</key>
		<false/>
		<key>KernelPm</key>
		<true/>
		<key>KernelXCPM</key>
		<false/>
		<key>KextsToPatch</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>Enable TRIM for SSD</string>
				<key>Disabled</key>
				<true/>
				<key>Find</key>
				<data>
				AEFQUExFIFNTRAA=
				</data>
				<key>InfoPlistPatch</key>
				<false/>
				<key>Name</key>
				<string>com.apple.iokit.IOAHCIBlockStorage</string>
				<key>Replace</key>
				<data>
				AAAAAAAAAAAAAAA=
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>External icons patch</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				RXh0ZXJuYWw=
				</data>
				<key>InfoPlistPatch</key>
				<false/>
				<key>Name</key>
				<string>AppleAHCIPort</string>
				<key>Replace</key>
				<data>
				SW50ZXJuYWw=
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Remove USB port limit in XHCI kext</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				g/sPD4MDBQAA
				</data>
				<key>InfoPlistPatch</key>
				<false/>
				<key>MatchOS</key>
				<string>10.14.x</string>
				<key>Name</key>
				<string>com.apple.driver.usb.AppleUSBXHCI</string>
				<key>Replace</key>
				<data>
				g/sPkJCQkJCQ
				</data>
			</dict>
		</array>
	</dict>
	<key>RtVariables</key>
	<dict>
		<key>BooterConfig</key>
		<string>0x28</string>
		<key>CsrActiveConfig</key>
		<string>0x3E7</string>
		<key>MLB</key>
		<string>C02032109R5DC771H</string>
		<key>ROM</key>
		<string>UseMacAddr0</string>
	</dict>
	<key>SMBIOS</key>
	<dict>
		<key>#BiosReleaseDate</key>
		<string>05/03/10</string>
		<key>#BiosVendor</key>
		<string>Apple Inc.</string>
		<key>#BiosVersion</key>
		<string>MB11.88Z.0061.B03.0809221748</string>
		<key>#Board-ID</key>
		<string>Mac-F4208CC8</string>
		<key>#BoardManufacturer</key>
		<string>Apple Inc.</string>
		<key>#BoardSerialNumber</key>
		<string>C02032101R5DC771H</string>
		<key>#BoardType</key>
		<integer>10</integer>
		<key>#BoardVersion</key>
		<string>Proto1</string>
		<key>#ChassisAssetTag</key>
		<string>LatitudeD420</string>
		<key>#ChassisManufacturer</key>
		<string>Apple Inc.</string>
		<key>#ChassisType</key>
		<integer>16</integer>
		<key>#Family</key>
		<string>MacBook</string>
		<key>#FirmwareFeatures</key>
		<string>0xC0001403</string>
		<key>#FirmwareFeaturesMask</key>
		<string>0xFFFFFFFF</string>
		<key>#LocationInChassis</key>
		<string>MLB</string>
		<key>#Memory</key>
		<dict>
			<key>Channels</key>
			<integer>2</integer>
			<key>Modules</key>
			<array>
				<dict>
					<key>Frequency</key>
					<integer>1333</integer>
					<key>Part</key>
					<string>C0001403</string>
					<key>Serial</key>
					<string>00001001</string>
					<key>Size</key>
					<integer>4096</integer>
					<key>Slot</key>
					<integer>0</integer>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>Kingston</string>
				</dict>
				<dict>
					<key>Frequency</key>
					<integer>1333</integer>
					<key>Part</key>
					<string>C0001404</string>
					<key>Serial</key>
					<string>00001002</string>
					<key>Size</key>
					<integer>4096</integer>
					<key>Slot</key>
					<integer>2</integer>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>Kingston</string>
				</dict>
			</array>
			<key>SlotCount</key>
			<integer>4</integer>
		</dict>
		<key>#Mobile</key>
		<true/>
		<key>#PlatformFeature</key>
		<string>0x03</string>
		<key>#ProductName</key>
		<string>MacBook1,1</string>
		<key>#SerialNumber</key>
		<string>4H629LYAU9C</string>
		<key>#Slots</key>
		<array>
			<dict>
				<key>Device</key>
				<string>ATI</string>
				<key>ID</key>
				<integer>1</integer>
				<key>Name</key>
				<string>PCIe Slot 0</string>
				<key>Type</key>
				<integer>16</integer>
			</dict>
			<dict>
				<key>Device</key>
				<string>WIFI</string>
				<key>ID</key>
				<integer>0</integer>
				<key>Name</key>
				<string>Airport</string>
				<key>Type</key>
				<integer>1</integer>
			</dict>
		</array>
		<key>#SmUUID</key>
		<string>00000000-0000-1000-8000-010203040506</string>
		<key>#Trust</key>
		<true/>
		<key>#Version</key>
		<string>1.0</string>
		<key>BiosReleaseDate</key>
		<string>02/02/2018</string>
		<key>BiosVendor</key>
		<string>Apple Inc.</string>
		<key>BiosVersion</key>
		<string>IM142.88Z.0128.B00.1802021101</string>
		<key>Board-ID</key>
		<string>Mac-27ADBB7B4CEE8E61</string>
		<key>BoardManufacturer</key>
		<string>Apple Inc.</string>
		<key>BoardSerialNumber</key>
		<string>D25505207OPF653JC</string>
		<key>BoardType</key>
		<integer>10</integer>
		<key>BoardVersion</key>
		<string>1.0</string>
		<key>ChassisAssetTag</key>
		<string>iMac-Aluminum</string>
		<key>ChassisManufacturer</key>
		<string>Apple Inc.</string>
		<key>ChassisType</key>
		<string>0x0D</string>
		<key>Family</key>
		<string>iMac</string>
		<key>FirmwareFeatures</key>
		<string>0xE00FE137</string>
		<key>FirmwareFeaturesMask</key>
		<string>0xFF1FFF3F</string>
		<key>LocationInChassis</key>
		<string>Part Component</string>
		<key>Manufacturer</key>
		<string>Apple Inc.</string>
		<key>Mobile</key>
		<false/>
		<key>PlatformFeature</key>
		<string>0x01</string>
		<key>ProductName</key>
		<string>iMac14,2</string>
		<key>SerialNumber</key>
		<string>D25P621SF8JC</string>
		<key>Version</key>
		<string>1.0</string>
	</dict>
	<key>SystemParameters</key>
	<dict>
		<key>#BacklightLevel</key>
		<string>0x0501</string>
		<key>#CustomUUID</key>
		<string>511CE201-1000-4000-9999-010203040506</string>
		<key>#NoCaches</key>
		<false/>
		<key>#NvidiaWeb</key>
		<false/>
		<key>InjectKexts</key>
		<string>Yes</string>
		<key>InjectSystemID</key>
		<true/>
	</dict>
</dict>
</plist>

**Comment by CreativeMK** [comment]
E3-1230 v3 1150 Hasewell CPU, MSI ZH87 motherboard, HD7950 graphics card.

I have the same problem too. And I tried both r5070 and r5097. They all stucked at restart.
With r5097, it just restart again and again.

Sorry for uploading error. Something went wrong. Can't process file.

But after SMC sucessfully initialized.....
error: invalid CORB size: 00
error: getCapabilities failed
apfs_module_start:1683: load: com.apple.filesystem.apfs, v1412.41......

end.
