### ISSUE TITLE
Unrecognized SSD

### ISSUE THREAD

**Issue by kang558** [CloverHackyColor/CloverBootloader#181]
Hello，My SSD model is SKHynix_HFS512GD9TNI-L2A0B ，Now installing macos does not seem to recognize the hard drive, the installation fails. I replaced the new SSD and it installed successfully

![image](https://user-images.githubusercontent.com/22288837/83959680-7d6a8780-a8b2-11ea-8f32-e0a62b010389.png)

**Comment by chris1111** [comment]
Try to add this drivers 
[NvmExpressDxe.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/4754583/NvmExpressDxe.efi.zip)

**Comment by SergeySlice** [comment]
Ask OEM driver for this device from the manufacturer.
