### ISSUE TITLE
GUI entry custom icon image overruled by macOS .VolumeIcon.icns

### ISSUE THREAD

**Issue by LeeBinder** [CloverHackyColor/CloverBootloader#182]
From my EFI partition which is mainly meant for Clover I also launch a Linux disk image via a custom entry in Clover's GUI section. Clover only chainloads grubx64.efi so I have copied that file (and a few more required ones) to /EFI/boot because a) this does not influence Clover, and b) I do not want a separate partition just for a few Grub2 files.

(just FYI: the Linux image itself sits on my Windows NTFS partition which has its dedicated icon in macOS, a Windows icon via .VolumeIcon.icns)

I enabled custom volume icons in Clover GUI, and assigned Bliss OS' icon 'Bliss-OS_radiant-128x128.icns' in GUI/ Custom Entry/Custom image:
![1 Bliss-OS_radiant-128x128 icns](https://user-images.githubusercontent.com/39203497/83979625-0bc12680-a910-11ea-8fd8-22ddacc9e9f4.jpg)

That used to get displayed correctly in Clover GUI:
![2  Bliss OS](https://user-images.githubusercontent.com/39203497/83979647-31e6c680-a910-11ea-959c-e0c8c9c5e717.jpg)

But not anymore after adding a icon to the EFI partition in macOS:
![3  EFI](https://user-images.githubusercontent.com/39203497/83979657-41fea600-a910-11ea-8bcd-8701a767940b.jpg)

Now the Bliss OS entry is also displayed with the EFI partition's .VolumeIcon in Clover GUI:
![4  Bliss OS with EFI Icon](https://user-images.githubusercontent.com/39203497/83979664-4f1b9500-a910-11ea-8dcd-be346db8423a.jpg)

Choosing the same 128 x 128 icon as a .png instead of the .icns format
![5  Bliss-OS_radiant-128x128 png](https://user-images.githubusercontent.com/39203497/83979669-5a6ec080-a910-11ea-9bea-d66952a8ab33.jpg)

did not make a difference. But after removing the .VolumeIcon for the EFI partition in macOS, on reboot the Bliss OS icon was again displayed correctly in Clover GUI even as a .png. So the icon format does not matter as long as it's correctly 128 x 128.

Even reverting back to Clover_r5108 (latest with the old GUI theming engine) did not make a difference.

I am filing this as a bug because I am positive that the priority order should be different - that a custom entry's icon image should NOT be influenced AT ALL by the .VolumeIcon of the volume the entry's bootloader is located at, but that the dedicated icon image should ALWAYS be dominant. It's like, when we assign a custom icon to our macOS Volume, we don't want ALL ICONS on our Desktop to be that same icon, so we .. ;) But right now that's what Clover is doing, which is both, counter intuitive and reverse logical.

In case you feel you want to reproduce this, I attached a zipped up .dmg with all related files.

Thanks for your continuous effort on Clover, and making it more professional with each release!

Clover: latest r5119

[EFI (GUI extract).dmg.zip](https://github.com/CloverHackyColor/CloverBootloader/files/4742924/EFI.GUI.extract.dmg.zip)

**Comment by LeeBinder** [comment]
Did any of you devs read this? Would already be great if you simply confirm for now. Thank you 👍

**Comment by vectorsigma72** [comment]
Hi, I'm not used to using these settings, anyway the image is 128x128 whatever you trying to do:
`Entry->Image.Image.LoadIcns(Volume->RootDir, L"\\.VolumeIcon.icns", 128);`
Maybe you have set the desired image as data:
`
		<key>ImageData</key>
		<data></data>`

**Comment by LeeBinder** [comment]
Hi @vectorsigma72 . I converted _Bliss-OS_radiant-128x128.png_ into **base64** via https://www.base64-image.de/ , then in config.plist replaced

```
<key>Image</key>
<string>Bliss-OS_radiant-128x128.png</string>
```

with

```
<key>ImageData</key>
<data>data:image/png;base64,iVBORw0KG[..shortened for readability..]</data>
```

but still the .VolumeIcon.icns of the EFI volume automatically overwrites and is displayed.

Is it correct to insert the string as Base64 or does it have to be something else like e.g. hex? And if Base64 is correct, did I insert the string correctly?

**Comment by SergeySlice** [comment]
Why you didn't delete .VolumeIcon.icns if you want Custom image?

**Comment by LeeBinder** [comment]
Hi @SergeySlice , thank you for looking into this. The reason why I don't delete .VolumeIcon.icns is because I have several EFI partitions on several hard disks all with dedicated icons for quick recogniton, and all together many partitions also all with dedicated icons for the same reason, so I really would like to keep that stringent.

The logic seems simple and straight forward. Would it be a lot of hassle to either prioritize custom icon images in the code over .VolumeIcon.icns, or to add a query into the existing GUI entry icon display function, some algorithm like:

```
if custom image =! '' then display custom image
   else
      try display .VolumeIcon.icns
      yrt
fi
```
?

**Comment by SergeySlice** [comment]
No matter of config.plist VolumeIcon should work so it must be in priority.

**Comment by LeeBinder** [comment]
hm well, with that reasoning everything would be hardcoded into the Clover binary and nothing configurable via config.plist .. ;) Naturally and in general, (almost) any setting could be modified from stock Clover binary default settings from within the config.plist.

This notion of "priority" is where the misinterpretation happens which leads to this bug because .VolumeIcon should ONLY display the icon of the actual physical volume as long as no custom icon image is set in a GUI custom entry, *regardless* of the .VolumeIcon. That does not mean at all that Clover would need to abandon or disregard .VolumeIcon - it would just mean an additional query *only* for GUI entries, that's all :)

**Comment by SergeySlice** [comment]
Creating the VolumeIcon is a right native method for macOS. Copy image and Paste to disk.
Why we should prefer customising through config.plist? The result is the same.

**Comment by LeeBinder** [comment]
sorry but no, it's apparently not the same because you (devs) have coded the custom GUI entry part of Clover in way that allows a custom path to a boot loader file (in this case grub efi), which is a really awesome feature!!! That again reads grub.cgf (also on /EFI) which again can point to not just a partition but (as in this case) to *any* boot image file on *any* partition. Similar to virtualization where you can have xyz VM disk files on one volume, and each VM can have an icon assigned for better recognition. With your current reasoning, **ALL** VM aliases would have the same icon - in this case the one of the EFI partition.

I'm sure you're starting to see now why the current icon image priority for custom GUI entries does not make sense as soon as the entries chainload disk images.

And really, the solution is soooo easy: as soon as a custom (icon) image is set in a custom GUI entry, that overwrites any existing .VolumeIcon **_only for that GUI entry_**. Simple as that :) 🥇

**Comment by LeeBinder** [comment]
Hi Slice. Just wondering - did you put any effort into this issue for the 5120 release?

**Comment by SergeySlice** [comment]
I have more priority tasks.

**Comment by LeeBinder** [comment]
OK. Can you please point me to the two spots in the source code here on github where GUI icons are set in the case of existing
- .VolumeIcon.icns
and
- custom image in a GUI custom entry?

That would be great (if possible even direct links to the two instances).

Thank you Sergey.

**Comment by SergeySlice** [comment]
Again. .VolumeIcon.icns will be in priority else delete it.
