### ISSUE TITLE
Clover will not update; "Installation type" tab not available

### ISSUE THREAD

**Issue by sandymc** [CloverHackyColor/CloverBootloader#186]
1. Attempting to update from 5070 to 5119 using the package from this site

2. Update runs without error, but nothing installed to ESP - files are not updated, and version number on boot remains 5070

3. "Installation type" tab never appears; the installer skips right past

4. Installation refers to doing a "standard install"

It seems that probably the installer is incorrectly doing a non-UEFI install. But there appears to be no (obvious) way to change this.

**Comment by vectorsigma72** [comment]
Use [Clover.app](https://github.com/CloverHackyColor/CloverBootloader/releases/download/5119/Clover.app_v1.23.pkg).

**Comment by sandymc** [comment]
> Use [Clover.app](https://github.com/CloverHackyColor/CloverBootloader/releases/download/5119/Clover.app_v1.23.pkg).

That is what I'm using.

**Comment by vectorsigma72** [comment]
> > Use [Clover.app](https://github.com/CloverHackyColor/CloverBootloader/releases/download/5119/Clover.app_v1.23.pkg).
> 
> That is what I'm using.

Sorry but Clover.app has no "Installation type tab”:
![Screenshot 2020-06-15 at 16 29 16](https://user-images.githubusercontent.com/54890782/84669680-6c122280-af25-11ea-822a-5a221f282c49.png)
As you can see there are no tabs.

**Comment by sandymc** [comment]
That's not what I get.
![Screen Shot 2020-06-15 at 4 36 05 PM](https://user-images.githubusercontent.com/445292/84670393-5ea96800-af26-11ea-854f-0827445a7c87.png)

**Comment by vectorsigma72** [comment]
Did you realize it is an application to install Clover and not a pkg to install Clover? 
After the installation you can find an /Application/Clover.app. Look at the top bar then:
![Screenshot 2020-06-15 at 16 39 18](https://user-images.githubusercontent.com/54890782/84670820-df686400-af26-11ea-8093-02ddf22bb838.png)
then again push on "Install Clover r5xxx” 
![Screenshot 2020-06-15 at 16 42 40](https://user-images.githubusercontent.com/54890782/84671165-530a7100-af27-11ea-9590-1e3c4ef2ff59.png)

P.S. the first time it downloads Clover from Github/releases and then you're ready, so give it the time to download it.

**Comment by sandymc** [comment]
Thank you, that resolved the issue. However, might I suggest that you revert to an installer that directly installs the package. This two-step process is not particularly user friendly.

**Comment by vectorsigma72** [comment]
> Thank you, that resolved the issue. However, might I suggest that you revert to an installer that directly installs the package. This two-step process is not particularly user friendly.

Sorry but both the package and the app are available, so just download what you prefear. Nothing to revert.
