### ISSUE TITLE
Bluetooth error

### ISSUE THREAD

**Issue by OvidiuNetcu** [CloverHackyColor/CloverBootloader#189]
I use a nativ wifi card from imac 2015, but in clover r5119 is stop working, and his simptom is verry lagy control off bluetooth meniu, and is in a off stage.

**Comment by OvidiuNetcu** [comment]
I return to 5118 and is work.

**Comment by DMNerd** [comment]
+1 Noticed issues with file transfer with airdrop on this version of clover

**Comment by SergeySlice** [comment]
These observations are not enough to solve anything.
