### ISSUE TITLE
Can't boot for macOS 10.16 installer

### ISSUE THREAD

**Issue by sopanus2014** [CloverHackyColor/CloverBootloader#190]
Cannot boot for macOS 10.16 installer

**Comment by cubem10** [comment]
Me too.. It stucks on Error 0xE, 0 @ LocHB ~~~ and showing date and +++++... after Err(0xE) @ OPEN (usr\\standalone\\DS.dmg_root_hash)
This EFI worked on Catalina 10.15.5

**Comment by gilberthdez** [comment]
macOS 11* :D

**Comment by DMNerd** [comment]
This might have something to do with the new kernel reworks. Hope this will be able to get resolved :)

**Comment by ManasMalla** [comment]
yah it stops at LOG:EXITBS:START ! Waiting for the fixes ASAP

**Comment by eskimo** [comment]
> macOS 11* :D

[10.16?](https://i.arxius.io/7ac019eb.png)

**Comment by mifjpn** [comment]
mee to!

**Comment by JoyZgq** [comment]
wait for it

**Comment by SalvaMontepaone** [comment]
nothing new?

**Comment by SergeySlice** [comment]
You seems want to be the first who discover America.
Yes, we already known that the Clover can't boot BigSur installer. What is next step? Open the issue???

**Comment by SalvaMontepaone** [comment]
> You seems want to be the first who discover America.
> Yes, we already known that the Clover can't boot BigSur installer. What is next step? Open the issue???

Sorry I just asked if there was nothing new  :(

**Comment by ITzTravelInTime** [comment]
I think that we should leave slice to do his job as clover developer, i just hope that he can figure the new os out before the end of the summer and release an updated clover.

Too bad i know so little about macos architecture and bootloaders, because i know quite well the c languages for low level usage, i have done some standalone ms-dos programs in this way.

**Comment by ITzTravelInTime** [comment]
About the clover issues the new os changed quite a lot about the kernelcache architetcure and how the boot process of the os works, it seems like a lot of stuff about clover and it's uefi drivers needs some very huge rework, so as one of the few developers still working on this project slice has a lot of difficoult stuff to deal with so be gentile with him and don't give him pressure.

I whould also thank slice for all the work he is doing for us.
