### ISSUE TITLE
Clover Technical Documentation

### ISSUE THREAD

**Issue by MasterCna** [CloverHackyColor/CloverBootloader#196]
I trying to find any technical documentation about the project and how it works and this stuff. Is anyone has a recommendation or something?

**Comment by asgmeonerandom** [comment]
You are reverse engineering, can't you figure out?

**Comment by DMNerd** [comment]
> You are reverse engineering, can't you figure out?

Very unhelpful.

**Comment by vectorsigma72** [comment]
Hi guys, I'm closing this issue as duplicate of #183 where you can find the link to the wiki.
