### ISSUE TITLE
.Will not work with eDP Connector

### ISSUE THREAD

**Issue by nicksilverstein** [CloverHackyColor/CloverBootloader#199]
I have two Dell Precision M6700s. One with LVDS and one with the eDP Connector. The one with LVDS works fine but, the one with eDP boots but, before the macOS installer loads the screen turns black.

**Comment by nicksilverstein** [comment]
they both have the NVIDIA Quadra K3000m. The one with the LVDS connector has Optimus it works with Optimus disabled. the one with the eDP has just the NVIDIA Quadra K3000m.

**Comment by SergeySlice** [comment]
Clover provides enough instruments to resolve the problem: device properties, kext patches, ACPI tuning. But to resolve your particular problem you have to use them.
It is not the issue of the Clover itself.
