### ISSUE TITLE
Новый кловер r5120 после обновления ломает загрузку 10.15.6

### ISSUE THREAD

**Issue by feedlike** [CloverHackyColor/CloverBootloader#203]
Почему после обновления кловера он ломает загрузку системы 10.15.6? обновляю путем накатывания через pkg на efi раздел системы

**Comment by vectorsigma72** [comment]
Если у вас был OpenRuntime.efi, pkg удалил его по ошибке. Проблема решена, pkg был заменен.

**Comment by ARGAMX** [comment]
Проапдейтился с r5119 на r5120, macOS 10.15.4 перестала грузится. Висит яблоко бесконечно, прогресса загрузки нет. Откатился обратно - работает.

**Comment by feedlike** [comment]
> Если у вас был OpenRuntime.efi, pkg удалил его по ошибке. Проблема решена, pkg был заменен.

OpenRuntime.efi не было до этого, в чем может быть проблема?

**Comment by vectorsigma72** [comment]
> > Если у вас был OpenRuntime.efi, pkg удалил его по ошибке. Проблема решена, pkg был заменен.
> 
> OpenRuntime.efi не было до этого, в чем может быть проблема?

Возможно некоторые изменения в kernelpatcher, которые работают только для нескольких. Это будет исправлено.

**Comment by LeeBinder** [comment]
see and try what helped me --> https://github.com/CloverHackyColor/CloverBootloader/issues/200#issuecomment-660452197

**Comment by SergeySlice** [comment]
Исправлено

**Comment by feedlike** [comment]
> Исправлено

Протестирую на днях. Спасибо @SergeySlice
