### ISSUE TITLE
Теперь можно запустить Big Sur с установщиком?

### ISSUE THREAD

**Issue by Teledurak** [CloverHackyColor/CloverBootloader#204]
У меня с модом немецкого форумчанина даже предустановленная не запускалась. А теперь полная поддержка?

**Comment by Ubsefor** [comment]
No, at least for me big sur install is not starting… 

And remember: No Russian ©

**Comment by jhsvip** [comment]
I can't boot Bigsur either，Did any one works？

**Comment by Teledurak** [comment]
> No, at least for me big sur install is not starting…
> 
> And remember: No Russian ©

I tried to boot it today too, stuck at ++++++ :/

**Comment by SergeySlice** [comment]
Test updated 5120

**Comment by Teledurak** [comment]
> Test updated 5120

I have no macOS installed - so I can't build clover, can you upload updated 5120 to clover releases?
