### ISSUE TITLE
r5120 hangs at Apple Logo for 10.15.5 - likely I'm confused about OcQuirks changes?

### ISSUE THREAD

**Issue by exquirentibus** [CloverHackyColor/CloverBootloader#205]
I've been running fine with r5119.

Today I updated to the latest kexts in the Other folder	
AppleALC -> 1.5.0
IntelMausiEthernet -> 1.0.3
Lilu - > 1.4.5
WhateverGreen -> 1.4.0
OcQuirks rev#23, used new OcQuirks.plist with slide=0 (had to change new plist to match mine for one value)

This booted fine.

When I tried to upgrade to r5120 by replacing just:
	EFI/BOOT/BOOTX64.efi ->
	EFI/clover/cloverx64.efi ->

Lover came up, but when booting 10.15.5 It showed Apple logo and nothing more, but Never showed the progress bar?

Possibly I need to use Your version of OcQuirks?  

I couldn't see a revision number using getInfo and your OcQuirks were much smaller and without an OcQuirks.plist.

Am I supposed to just copy my existing OcQuirks.plist into config.plist and Only use Your version of OcQuirks.efi and OpenRuntime.efi that come with Clover from now on, and ignore the GitHub repository for OcQuirks entirely?

**Comment by SergeySlice** [comment]
Release 5120 reloaded.
