### ISSUE TITLE
Can't see Internal Drives after Successfully booting to Big Sur installer

### ISSUE THREAD

**Issue by hohoho123456** [CloverHackyColor/CloverBootloader#207]
![20200709_190437 jpg 9d90dfecea0c5f67f1941cbd404f60f8](https://user-images.githubusercontent.com/44559677/88001196-205d2500-cb32-11ea-839b-336847120419.jpg)
I was able to boot to the Big Sur Installer using the latest clover 5120, but once i got into the installer, i can't see my internal drives. i have a 1 TB HD and an Sata ssd and both of them are not present in disk utility and terminal so I can't install Big Sur. I also tried to update my Catalina to Big Sur using the same exact USB, but the update to Big Sur never continues and is just gives me a stop sign. But when i use the same exact USB to boot Catalina it boots Catalina perfectly. This same exact problem also exist when I try to use Opencore to boot to the installer, if that information helps too. Thanks in advance for the help!
[clover 5120 config.zip](https://github.com/CloverHackyColor/CloverBootloader/files/4950679/clover.5120.config.zip)
![20200721_084150](https://user-images.githubusercontent.com/44559677/88000709-ee978e80-cb30-11ea-8367-4396999ad224.jpg)
![20200721_084119](https://user-images.githubusercontent.com/44559677/88000722-f8b98d00-cb30-11ea-9bc5-a6710916e922.jpg)
![Screen Shot 2020-07-21 at 8 45 10 AM](https://user-images.githubusercontent.com/44559677/88000762-1850b580-cb31-11ea-951e-41bc3279aabc.png)
[pcidevices.txt](https://github.com/CloverHackyColor/CloverBootloader/files/4950686/pcidevices.txt)
![20200721_152741](https://user-images.githubusercontent.com/44559677/88025507-f2de9e80-cb66-11ea-8c3e-865fd094c496.jpg)

**Comment by qw7575** [comment]
5120可以装大苏了吗

**Comment by hohoho123456** [comment]
> 5120可以装大苏了吗

No. Can't install Big Sur. Big Sur installer is not detecting my internal Sata SSD.
