### ISSUE TITLE
再次提交的5120可以装大苏吗，是否正常启动卡特琳娜版本

### ISSUE THREAD

**Issue by qw7575** [CloverHackyColor/CloverBootloader#208]
如题
根据上周六取消的5120
现在再次提交的5120可以装大苏吗，
是否正常启动卡特琳娜版本

**Comment by elton11220** [comment]
Catalina正常启动，但是Big Sur我没进去

**Comment by jhsvip** [comment]
> 如题
> 根据上周六取消的5120
> 现在再次提交的5120可以装大苏吗，
> 是否正常启动卡特琳娜版本

Look at my last config.plist, it can boot BigSur normally.
https://github.com/CloverHackyColor/CloverBootloader/issues/200

**Comment by elton11220** [comment]
> > 如题
> > 根据上周六取消的5120
> > 现在再次提交的5120可以装大苏吗，
> > 是否正常启动卡特琳娜版本
> 
> Look at my last config.plist, it can boot BigSur normally.
> #200

How did you apply the features in the 5120 to your original clover configuration?
I replaced clover64.efi, boot64.efi, and added the built in kernel patches to my config.plist.
But it still doesn't work in macOS 10.16(10.15.6 works well)

**Comment by jhsvip** [comment]
> > > 如题
> > > 根据上周六取消的5120
> > > 现在再次提交的5120可以装大苏吗，
> > > 是否正常启动卡特琳娜版本
> > 
> > 
> > Look at my last config.plist, it can boot BigSur normally.
> > #200
> 
> How did you apply the features in the 5120 to your original clover configuration?
> I replaced clover64.efi, boot64.efi, and added the built in kernel patches to my config.plist.
> But it still doesn't work in macOS 10.16(10.15.6 works well)

Plist Editor Or Clover.app
Look at my post
