### ISSUE TITLE
How can i apply the features to my configuration which offer support to big sur?

### ISSUE THREAD

**Issue by elton11220** [CloverHackyColor/CloverBootloader#209]
Yesterday,clover updated to r5120 and claimed offering support to macOS big sur.But i don't know how to apply these features(such as ocquirk).Can you tell me how to do it?

**Comment by LeeBinder** [comment]
For a fresh start, Big Sur is not 10.16 but 11.0 .. ;)

**Comment by elton11220** [comment]
> For a fresh start, Big Sur is not 10.16 but 11.0 .. ;)

thanks

**Comment by stevezhengshiqi** [comment]
@LeeBinder It is 10.16 on our x86 devices if you run sw_vers in Terminal.

**Comment by LeeBinder** [comment]
wow - thanks for the find. Isn't it funny that even peeps @ apple can't make up their mind? So tough to let go of the old LOL

**Comment by SergeySlice** [comment]
It is not an issue. It is a question how to use.
