### ISSUE TITLE
Wake up slow with cpu timing problem.

### ISSUE THREAD

**Issue by CreativeMK** [CloverHackyColor/CloverBootloader#21]
E3-1230 v3 1150 Hasewell CPU, MSI ZH87 motherboard, HD7950 graphics card.

It can sleep or hibernate, but when wake up, cpu behaves working very slow.
The time of cpu is the problem. 
I don't know how to fix it and almost tried every option on motherboard or clover but none of them working.

Thanks for helping.

**Comment by SergeySlice** [comment]
How can I help you?

**Comment by CreativeMK** [comment]
> How can I help you?

I tried to install 10.15.0, but get stuck when restart with tiny progress and hard disk not reading or writing.

**Comment by SergeySlice** [comment]
No informations what is the issue.
