### ISSUE TITLE
Z490 Support?

### ISSUE THREAD

**Issue by drlovedotcom** [CloverHackyColor/CloverBootloader#210]
Hello, 

I have only been able to find a few hints about support for Z490 with Clover. For this reason I am opening this issue ticket. 

Some necessary implementations can be found in OpenCore, but unfortunately not in Clover at this time. Is it something that you are considering for Clover? (I really appreciate all of your the great efforts with Clover and really hate to switch!). 

Thank you very much!

**Comment by SergeySlice** [comment]
Clover already contain OcQuirk and OpenRuntime.
You also need SSDT-PMC.aml find anywhere.
There are full requirements to work Z490.

**Comment by drlovedotcom** [comment]
Thanks! 
I will migrate to OcQuirk and OpenRuntime :-)
