### ISSUE TITLE
Unable to boot Big Sur Beta 3 prebooter/installer

### ISSUE THREAD

**Issue by norton287** [CloverHackyColor/CloverBootloader#212]
It hangs after a bunch of messages about not being able to load kexts and then errors out on loading NVME driver from apple.  Here is a screenshot of my boot screen:

![20200723_065740](https://user-images.githubusercontent.com/42098364/88285061-16632f80-ccb4-11ea-9193-f0a01f1fb5d5.jpg)

This is my EFI

[EFI.zip](https://github.com/CloverHackyColor/CloverBootloader/files/4965793/EFI.zip)

Any help would be appreciated

John

**Comment by ITzTravelInTime** [comment]
You have a CPU pm isse and virtualsmc failed to load, those (expecially the first one) are problems which can cause a system not to boot, probably you cpu power management isn't native or you have configured your clover poorly

**Comment by xiaozhangv** [comment]
me too.any err about can't load kexts

**Comment by norton287** [comment]
My config worked fine for installing Beta 2 no problem, only had to add an NVRAM variable to actually boot into Big Sur.

**Comment by norton287** [comment]
@jhsvip did you have any luck upgrading to Big Sur Beta 3?

**Comment by jhsvip** [comment]
> @jhsvip did you have any luck upgrading to Big Sur Beta 3?

I  have not try to use clover to boot beta3。
Try to use fakesmc to replace virstulSMC。

**Comment by norton287** [comment]
Will try that

**Comment by norton287** [comment]
@jhsvip FakeSMC resulted in the same errors, failed to load one ACPI table and then did not load any boot kexts then failed to load NVME driver.  Did you switch to OpenCore?

**Comment by jhsvip** [comment]
> @jhsvip FakeSMC resulted in the same errors, failed to load one ACPI table and then did not load any boot kexts then failed to load NVME driver. Did you switch to OpenCore?

I suggest to use vmware to update the beta3.

**Comment by norton287** [comment]
@jhsvip do you have a link to a good guide on using VMWare to install it to the drive?

John


On July 24, 2020 at 9:07:47 PM, 小及 (notifications@github.com) wrote:

@jhsvip FakeSMC resulted in the same errors, failed to load one ACPI table and then did not load any boot kexts then failed to load NVME driver. Did you switch to OpenCore?

I suggest to use vmware to update the beta3.

**Comment by serdeliuk** [comment]
It seems that the install process is not supported right now, also pre installed bigsur is not supported, out there exists a patched 5119 to be able to boot with latest OcQuirks.efi not the ones provided by 5120

**Comment by jhsvip** [comment]
Here is the Vmware guide  only chinese version
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1862049

opencore + fakesmc  works fine on beta3 installition
I've used for a while

**Comment by serdeliuk** [comment]
> My config worked fine for installing Beta 2 no problem, only had to add an NVRAM variable to actually boot into Big Sur.

Where did you added the  NVRAM variable? Maybe you used OpenCore? Clover does not have such config, also official Clover is not yet able to boot or install BigSur, here on post #1 is linked a zip file which contain the patched 5119 which can boot preinstalled BigSur, however, it is not able to boot the installer https://www.hackintosh-forum.de/forum/thread/49311-macos-11-bigsur-dev-beta-clover-patch/?pageNo=1

**Comment by norton287** [comment]
@jhsvip gave me the command to execute from my catalina install:

If you enter the desktop after startup, the screen will be blank. Please do the following:
Enter Mac OS 10.15 or enter the installation mode terminal and execute the following command:
sudo nvram booter-fileset-kernel="%00"
Check whether the assignment is successful:
nvram -p |grep booter-fileset-kernel
booter-fileset-kernel %00

**Comment by norton287** [comment]
@jhsvip I used OpenCore to install Beta 3, but I am having difficulty entering the recovery, you know how to fix that?

**Comment by jhsvip** [comment]
> @jhsvip I used OpenCore to install Beta 3, but I am having difficulty entering the recovery, you know how to fix that?
did you add some commands in boot arags？

**Comment by norton287** [comment]
@jhsvip Here is my boot args

![Screen Shot 2020-07-26 at 6 19 21 AM](https://user-images.githubusercontent.com/42098364/88477752-35f29600-cf08-11ea-856f-5da79c8585fc.png)

**Comment by jhsvip** [comment]
> @jhsvip Here is my boot args
> 
> ![Screen Shot 2020-07-26 at 6 19 21 AM](https://user-images.githubusercontent.com/42098364/88477752-35f29600-cf08-11ea-856f-5da79c8585fc.png)

just -lilubetaall 
try csr ：77080000  or E7030000

**Comment by norton287** [comment]
@jhsvip Will give that a try right now.

**Comment by norton287** [comment]
@jhsvip No luck with those changes, gonna dig around inssanelymac.com some more and see.  There were a couple of posts about it with a fix but I cannot find them at all now.

John

**Comment by jhsvip** [comment]
> @jhsvip No luck with those changes, gonna dig around inssanelymac.com some more and see. There were a couple of posts about it with a fix but I cannot find them at all now.
> 
> John

my OC efi here https://github.com/jhsvip/ASROCK-Z370M-Pro4-BigSur/releases/

**Comment by norton287** [comment]
@jhsvip Fixed it! Now I can enter Big Sur Recovery

![Screen Shot 2020-07-26 at 7 25 53 AM](https://user-images.githubusercontent.com/42098364/88479549-7e648080-cf15-11ea-82bd-9b31a69952d1.png)

**Comment by norton287** [comment]
@jhsvip Thanks for the efi I will clean up mine with yours

**Comment by jhsvip** [comment]
> @jhsvip Thanks for the efi I will clean up mine with yours
If you use vsmc to boot 11.0 beta3
remember to add boot arags ：-vsmcgen=1

**Comment by norton287** [comment]
@jhsvip I'm using FakeSMC since that boots fine with BS 3

**Comment by norton287** [comment]
Closing this as I have Beta 3 installed now.
