### ISSUE TITLE
Stuck at ++++++ on Big Sur beta 2 Installer/Preinstalled OS boot

### ISSUE THREAD

**Issue by Teledurak** [CloverHackyColor/CloverBootloader#214]
Tried to use release version - not booting
Tried to build Clover by myself, not booting too

My config: https://gist.github.com/Teledurak/729d785d0f48bbf94d5e2896e433f5ec
My configuration:
CPU: i5 3470
Graphics: GeForce 9600GT (worked perfectly on Catalina)
MB: ASUS P8H61-M Plus V2

On OpenCore I stucked on [ pci configuration start ] on Catalina and Big Sur, npci=0x2000/0x3000 not helped, maybe this info will help :)

Hope that anyone will help me

**Comment by serdeliuk** [comment]
Usually that kind of stuck is when you use old apiomemoryfix  (any variant) you should remove any aptio fix and use provided OcQuirks.efi also you may want to add all configs to clover's config.plist
Also you should replace both BOOT/BOOTX64.efi and CLOVER/CLOVERX64.efi with the provided ones
All those are all available in 5120 zip file.
