### ISSUE TITLE
Invalid device tree for kext injection on r5120 and Big Sur beta 2

### ISSUE THREAD

**Issue by tdrkDev** [CloverHackyColor/CloverBootloader#216]
I removed aptiomemoryfix, added ocquirks to my config.plist. On boot after +++++ it is showing `Invalid device tree for kext injection` and rebooting.

What can I do with this issue?

**Comment by SergeySlice** [comment]
Choose right quirks for you hardware.

**Comment by SergeySlice** [comment]
use 5125
