### ISSUE TITLE
When I boot macOS, it stuck on EB|#LOG:EXITBS:START

### ISSUE THREAD

**Issue by elton11220** [CloverHackyColor/CloverBootloader#217]
macOS 11 beta2
Clover r5120

when I boot the big sur, it stuck on  EB|#LOG:EXITBS:START.
My motherboard cannot control cfg-lock autonomously, i used Grub to disable cfg-lock but it didn't work.

**Comment by SergeySlice** [comment]
Clover is not ready yet for bigsur.
About cfg-lock it is not Clover problem.
