### ISSUE TITLE
Clover r5098 fails to install with "cannot install without ensuring file system is read-write" on Catalina

### ISSUE THREAD

**Issue by douira** [CloverHackyColor/CloverBootloader#22]
I'm on macOS Catalina 10.15 (19A602). I have not updated Clover since I switched to Catalina from Mojave. SIP is on and everything works fine otherwise. I have not had this problem before upgrading. When I open the installer `Clover_v2.5k_r5098.pkg` with right-click and open it goes through these states after interaction:
![Screenshot 2019-10-28 at 19 13 26](https://user-images.githubusercontent.com/17120022/67705622-9e333c00-f9b7-11e9-8497-5cf8b1dee85b.png)
![Screenshot 2019-10-28 at 19 13 32](https://user-images.githubusercontent.com/17120022/67705635-a7240d80-f9b7-11e9-8ab4-8aae602c671b.png)
![Screenshot 2019-10-28 at 19 13 42](https://user-images.githubusercontent.com/17120022/67705640-aa1efe00-f9b7-11e9-9fd8-d6ddd749a6c5.png)
In the end, it shows the error "cannot install without ensuring the file system is read-write" and then quits.

**Comment by valinor61** [comment]
change crsactive config to 0x67

**Comment by douira** [comment]
So this is a SIP issue? I presume I can re-enable it after installing it with SIP disabled?

**Comment by SergeySlice** [comment]
sudo mount -uw /

**Comment by Shaneee92** [comment]
Disable SIP to install pkg. Can enable once installed.

**Comment by rgaufman** [comment]
Same issue here, how do I disable SIP?

**Comment by effektsvk** [comment]
@rgaufman Boot into Recovey Mode (while your Mac is starting, press and hold Command + R. Open Terminal (Utilities -> Terminal) and type `csrutil disable` and press Enter. You can restart now. After you use Clover, you can enable it with `csrutil enable`.

**Comment by douira** [comment]
Another way is to set the CsrActivateConfig value in the RT Variables section of the Clover config to `0x67`. This is best done using CloverConfigurator. I've had problems using `csrutil disable` but that might also have been my mistake. If you can't boot without disabling SIP in order to change the setting, you also find the setting in the menu of the Clover boot screen.

**Comment by dmcnaugh15** [comment]
Thank you douira!  Clover Configurator is the way to go!  Super easy.  Here's a screenshot for anyone else who's interested.

<img width="1279" alt="Image" src="https://user-images.githubusercontent.com/4023680/77578028-ce6b0200-6ea5-11ea-8d79-bae78c7ca804.png">

**Comment by douira** [comment]
I've also found out that setting only the second bit (0x02) which controls "UnrestrictedFS" also works if you're really only installing Clover. This will not work for other operations, like installing kexts.

**Comment by blueberry6401** [comment]
But why clover want system read-write even if I only want to install it on usb?

**Comment by jonasrk** [comment]
Yes, can we re-open this issue please? I, too want to install on an USB, so the clover installer should not need full access to my current system, as outline in the post above. I'm currently stuck for this reason, because I'm prohibited from disabling SIP.

**Comment by mackonsti** [comment]
I would like to report that **r5118** also shows this error "Cannot install without ensuring the file system is read-write." after entering admin password; not sure what the PKG script inside needs to write to / as I can mount EFI partition without problems, and there are really no other stuff to write to main-partition-root that the Installer can't write to the data-partition-root (e.g. EFI Backups, settings PLIST etc.)

Please fix this in the installer?

**Comment by tuyen-vuduc** [comment]
I tried `csrutil disable` but the message is still. 

My MacbookPro is an early 2013, 15" one

@dmcnaugh15 could you advise where is config.plist to edit? 

Thanks.

**Comment by douira** [comment]
@tuyen-vuduc if you're using Clover as the bootloader, disabling SIP is done with `CsrActivateConfig` not `csrutil disable`.

**Comment by TonyC5** [comment]
Those that are experiencing the CLOVER "cannot install without ensuring file system read-write" problem.  Did you by any chance install OC on this volume and now you're trying to install CLOVER?
