### ISSUE TITLE
Can't install the package Clover_r5120.pkg on Big Sur. 

### ISSUE THREAD

**Issue by Daedan17** [CloverHackyColor/CloverBootloader#220]
When I try to install the package the installer say's that the pkg is incompatible with my os.
<img width="620" alt="Screen Shot 2020-08-11 at 1 18 14 PM" src="https://user-images.githubusercontent.com/69530295/89927964-21cfb980-dbd5-11ea-9bf6-e49e3a457745.png">

**Comment by SergeySlice** [comment]
sudo spctl --master-disable

**Comment by SergeySlice** [comment]
sudo mount -uw /

**Comment by flynn-buc** [comment]
Same issue with r5123

**Comment by SergeySlice** [comment]
same as issue 259.
It is BigSur security and not a Clover problem.
