### ISSUE TITLE
Clover_r5120 Graphic boot issue

### ISSUE THREAD

**Issue by robaczek66** [CloverHackyColor/CloverBootloader#222]
Hi everyone, any idea:? After new Clover 5120 boot loader instal my booting screen come to be strange. First there is fast text scrolling which before was not seen. After apple logo appear in strange resolution. After some seconds resolution come to normal and MacOs login screen is also normal plus MacOs 10.15.6 seems to work ok with all components. Until Clover 5107 booting was smooth without any text and with proper resolution from beginning. I attached screen photos to visual what happened.
![IMG_6819](https://user-images.githubusercontent.com/65821119/90313177-aa6a9480-df0a-11ea-914d-5279a439f612.JPG)
![IMG_6820](https://user-images.githubusercontent.com/65821119/90313180-b191a280-df0a-11ea-88a2-7e542c7cc2a6.JPG)
![IMG_6821](https://user-images.githubusercontent.com/65821119/90313182-b6565680-df0a-11ea-90b1-dc81a1dd0be5.JPG)
![IMG_6822](https://user-images.githubusercontent.com/65821119/90313191-c110eb80-df0a-11ea-8f4a-be6aa8717f51.JPG)

**Comment by FrEaK-git** [comment]
The hell... clean your screen... ;-)

Anyways... which hardware do you use? May it is related to CSM "on" or "off".

**Comment by Hackintosh** [comment]
I have a similar issue when trying latest release by building, i get screen but no icons or volumes available
maximus ranger viii

**Comment by BenTalagan** [comment]
> Hi everyone, any idea:? After new Clover 5120 boot loader instal my booting screen come to be strange. First there is fast text scrolling which before was not seen.

You might have accidentally installed the CsmVideoDxe driver when updating. You can try to boot without it.

**Comment by SergeySlice** [comment]
Never saw such screens. Is the issue still valid with 5122?

**Comment by robaczek66** [comment]
Yes I just updated to 5122 and its the same. I use this plist from years, it was used before clover using chimera. It works with all update till 5107 ( I only patched audio many times) Maybe I need to clean everything but not sure what I need from the past drivers

**Comment by robaczek66** [comment]
I found my old legacy bootlog and I compare it with current bootlog. I found difference, but why I don't know maybe someone can look at that, please.
First bootlog when resolution was ok from begining and then current one when resolution during beet is not correct
![Zrzut ekranu 2020-09-3 o 10 14 33](https://user-images.githubusercontent.com/65821119/92090493-c6f24200-edcf-11ea-94d7-b860241024ba.png)
![Zrzut ekranu 2020-09-3 o 10 17 47](https://user-images.githubusercontent.com/65821119/92090511-cc4f8c80-edcf-11ea-8e87-cf8d93bbdbfc.png)

**Comment by SergeySlice** [comment]
It was 1920x1200 and second screen is 1920x1080. There is the difference.
