### ISSUE TITLE
Not boot - „error not found while loading boot.efi press any key continue”

### ISSUE THREAD

**Issue by hackintosh1984pl** [CloverHackyColor/CloverBootloader#227]
I have  problem if boot in clover 5120, 5121 
" error not found while loading boot.efi press any key continue"
And boots clover from fat32 msdos usb stick and also hard disk. I have legacy setup pc no uefi

**Comment by SergeySlice** [comment]
Try to change boot file to older version.

**Comment by SergeySlice** [comment]
abandoned as user mistake
