### ISSUE TITLE
When installing it says to contact the developer.

### ISSUE THREAD

**Issue by Lion4K** [CloverHackyColor/CloverBootloader#232]
is there a way for me to provide you an actual helpful log or something?
https://imgur.com/a/ULPWyiA

**Comment by Lion4K** [comment]
I forgot to mention it was Clover.app 1.17.pkg

**Comment by Lion4K** [comment]
then I tried the Clover_r5111.pkg and it installed. but I cant run it.
https://imgur.com/a/y3nipPq

**Comment by SergeySlice** [comment]
Why 5111? Why 1.17? Actual revision is 5122. Clover.app is 1.24

**Comment by Lion4K** [comment]
I don't know, I got them from the releases page
