### ISSUE TITLE
Clover_r5114-Clover_r5122Graphic boot issue

### ISSUE THREAD

**Issue by jackacc** [CloverHackyColor/CloverBootloader#233]
R5114 or below supports my computer 10.13.6 or below. It has been changed from 10.10 to 10.13 with good clover. 10.14 can also be patched with sse4.2 and N card. Both can run. After the r5115 version is updated, my computer is no longer supported, and the N card gt320 cannot be turned on. It is suggested that the author still use the previous code to find a breakthrough and be compatible with the latest 11

**Comment by jackacc** [comment]
![qq_pic_merged_1599970720807](https://user-images.githubusercontent.com/43131867/93010125-8195f780-f5bb-11ea-85b2-59f96d13b2eb.jpg)
Old kernel not supported?

**Comment by SergeySlice** [comment]
Kernel from 10.7 is still supported.
Search for own mistakes.
