### ISSUE TITLE
Need help re-adding Clover boot entry to BIOS boot menu

### ISSUE THREAD

**Issue by vincentchen666** [CloverHackyColor/CloverBootloader#235]

**Comment by ifamed** [comment]
I have the same problem, the clover boot options don't even appear

**Comment by LeeBinder** [comment]
does the O key still work?

**Comment by LeeBinder** [comment]
all buttons in GUI incl. Options working fine here with the latest updated 5122 release, both click onto button and also via O key

**Comment by vincentchen666** [comment]
@LeeBinder  The option of add Clover boot options  for all entries  does not work.   I could not add Clover bootloader menu into the boot menu of motherboard.

**Comment by LeeBinder** [comment]
oh boy. I doubt this is only a language issue... If you want help with this, please change the title of this issue of yours into

**Need help re-adding Clover boot entry to BIOS boot menu**

Thank you.

**Comment by oldnapalm** [comment]
I have a similar issue with Asus Prime B250M-Plus, the menu "Clover Boot Options" is there but "Add Clover boot options for all entries" does not work.
If I enter shell and run `bcfg boot add 0 cloverx64.efi "Clover"` from EFI/CLOVER it works.

**Comment by SergeySlice** [comment]
It works
