### ISSUE TITLE
NVRAM Emulation

### ISSUE THREAD

**Issue by VisionXi** [CloverHackyColor/CloverBootloader#239]
Did something in NVRAM emulation changed ? With versions < 5120 it worked well, but with 5122 the clover menu doesn't point to the last picked boot item.

CLOVERX64.efi from 5122 => Clover menu always points to the first boot item
CLOVERX64.efi from 5120 => Clover menu always points to the last picked boot item

Nothing else changed. Same EmuVariableUefi.efi still in place, nvram.plist still gets generated and updated through the scripts.

**Comment by SergeySlice** [comment]
Not true.

**Comment by VisionXi** [comment]
What an arrogant answer! You can believe a guy with over 30 years IT experience.
I can reproduce it, vice versa and every time. If you can not then there are other differences in configuration which affect this.

**Comment by asgmeonerandom** [comment]
> What an arrogant answer! You can trust a guy with over 30 years IT experience.
> I can reproduce it, vice versa and every time. If you can not then there are other differences in configuration which have an impact on this.

30 years experience and you can't afford a mac?

**Comment by VisionXi** [comment]
> > What an arrogant answer! You can trust a guy with over 30 years IT experience.
> > I can reproduce it, vice versa and every time. If you can not then there are other differences in configuration which have an impact on this.
> 
> 30 years experience and you can't afford a mac?

It costs a lot if you have kids and support them so that they can write funny notes in the net sometime. Have fun. Goodbye!

**Comment by SergeySlice** [comment]
With Clover 5122 the menu pointed to last booted entry. As well as with all older revisions as never changed.
