### ISSUE TITLE
Dont install NVRAM-Emu with AptioMemoryFix

### ISSUE THREAD

**Issue by t14462** [CloverHackyColor/CloverBootloader#24]
Do not install NVRAM-Emu things when user select AptioMemoryFix.efi in installer

**Comment by t14462** [comment]
AptioMemoryFix.efi — this driver provide native NVRAM

So, without these files:
/Volumes/EFI/EFI/CLOVER/drivers64UEFI/EmuVariableUefi-64.efi
/Volumes/EFI/nvram.plist
/etc/rc.clover.lib
/etc/rc.boot.d/10.save_and_rotate_boot_log.local
/etc/rc.boot.d/20.mount_ESP.local
/etc/rc.boot.d/70.disable_sleep_proxy_client.local.disabled
/etc/rc.shutdown.d/80.save_nvram_plist.local
boot and power-off 1-2sec faster

Who need an emulator, when native NVRAM works fine?

**Comment by Sher1ocks** [comment]
Some board still need RC script with AptioMemoryFix

**Comment by vectorsigma72** [comment]
> Who need an emulator, when native NVRAM works fine?

The one who want a boot failure.

**Comment by SergeySlice** [comment]
Sometimes need sometimes no.
