### ISSUE TITLE
Release v5.0 r5122

### ISSUE THREAD

**Issue by nyhtml** [CloverHackyColor/CloverBootloader#242]
Release v5.0 r5122 is causing the GPU to display incorrectly on Mojave.
![5120](https://user-images.githubusercontent.com/2177262/94741948-f0f14280-0342-11eb-9707-d4d3692b8d49.png)
Replacing the BootX64.efi with CLOVERX64.efi from Release v5.0 r5114 fixes the issue.
![5114](https://user-images.githubusercontent.com/2177262/94742006-036b7c00-0343-11eb-9bc3-f011cba0cba3.png)

**Comment by SergeySlice** [comment]
Recheck please with 5125.

**Comment by nyhtml** [comment]
I'll test it now. Thank you.

**Comment by nyhtml** [comment]
It didn't help (which is fine) on the **Optiplex 9020 SFF** but I was able to move up to **Clover EFI v2.5k r5116**.
Since Mojave has no more updates coming from Apple, 5116 will be alright going forward on this system.
I still have my Z270XUG-CF that is running Catalina 10.15.7 on **Clover EFI v2.5k 5107** so I may need a SFF GPU.

If not off topic, a compatible GPU would be appreciated.
