### ISSUE TITLE
[5123] Failed to boot Mojave and Big Sur

### ISSUE THREAD

**Issue by stevezhengshiqi** [CloverHackyColor/CloverBootloader#246]
macOS Version: 10.14.6 & 11.0beta8
CPU & GPU: i5-8250U & UHD620
Laptop

Hi, thank you all for making the big changes. I have problems booting Mojave and Big Sur. It stucks in a very early stage. Here are my verbose log and EFI folder. Really appreciate it if someone could have a look.
![IMG_3054 03 06 34](https://user-images.githubusercontent.com/36894554/95012069-7276f800-0603-11eb-84f8-ddeb7e9f5062.jpg)
[CLOVER.zip](https://github.com/CloverHackyColor/CloverBootloader/files/5322938/CLOVER.zip)

P.S. The new config sample has two PanicNoKextDump. Maybe one of them is redundant?

**Comment by SergeySlice** [comment]
use 5125

**Comment by stevezhengshiqi** [comment]
https://github.com/CloverHackyColor/CloverBootloader/commit/5d91bbe25305104192160413b68f94955e7cb03a solves the problem, thank you guys.
