### ISSUE TITLE
r5122 fails to boot

### ISSUE THREAD

**Issue by Samnan** [CloverHackyColor/CloverBootloader#249]
Perfectly working Catalina 10.15.7 with clover 5119.
When upgraded to version 5122, immediately shows this error on top of screen and halts.
Tested also by installing a new usb stick and then updating config.plist and kexts from previously working copy.

getDict0 called on a tag of type Key.
A fatal error occured. System Halted.

EDIT: seems to be caused by this commit
https://github.com/CloverHackyColor/CloverBootloader/commit/efb3c44b0f0c7d34874887739b043cea12f091e6

It's probably a config.plist parsing issue, although not sure which tag is causing this.
Will try to figure out myself, but it would be good if the tag name is at least shown in error message.

**Comment by BearTS** [comment]
i m facing this too

**Comment by SergeySlice** [comment]
use 5125

**Comment by Samnan** [comment]
> i m facing this to
> can u tell me what changes u did to fix it?
> @Samnan
> edit: never mind, i successfully shifted to opencore

@BearTS congrats!
