### ISSUE TITLE
Still can't update Clover on Big Sur (r5123 & r5124)

### ISSUE THREAD

**Issue by flynn-buc** [CloverHackyColor/CloverBootloader#259]
Clover is still unable to be updated when booted in Big Sur. Installer throws error stating "This version of MacOS is not compatible". This is likely due to system not being in r/w mode. As a result, EFI Partitions are not showing in the installer, and it seems they are attempted to be installed at the root of the drive, instead of in EFI Volumes. Please advise on a solution

**Comment by zty199** [comment]
Then don't use pkg, just download CloverV2-5124.zip and get what you need. Might be a little complicated, but it works.

**Comment by SergeySlice** [comment]
Resolved in recent Clover.
