### ISSUE TITLE
VoodooI2c Still NOT WORK in Clover_r5124 !!

### ISSUE THREAD

**Issue by HandaTakuya** [CloverHackyColor/CloverBootloader#260]
I try update Clover 5122 to 5124 boot work BUT my touchpad (VoodooI2c) still NOR Work !! 

![Screen Shot 2563-10-13 at 09 53 42](https://user-images.githubusercontent.com/47761725/95809975-28e08880-0d3a-11eb-9291-f089eec99437.png)

**Comment by SergeySlice** [comment]
VoodooI2C many times reported. Test Clover 5125 or we will account the kext incompatibility with BigSur.

**Comment by stevezhengshiqi** [comment]
@SergeySlice Hi Slice, VoodooI2C not work is not because of the compatibility, but related to the kext load order. We need to specify the loading order to get it to work as VoodooI2C plugins have to load earlier than VoodooI2C. Detailed explanation is at here: https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?do=findComment&comment=2739712

**Comment by corint1** [comment]
same here

**Comment by HandaTakuya** [comment]
> VoodooI2C many times reported. Test Clover 5125 or we will account the kext incompatibility with BigSur.

5125 not work too. 

ps. my mackintosh use 10.15.7

**Comment by corint1** [comment]
the last version made voodooI2c load and work ... but the clover version is very unstable ... it boots 1 out of 10 ... and this after many changes, emotions and nerves ... reset nvram, changing the partition boot, changing boot from ssd to usb ... very unstable ....does anyone else have this problem?

**Comment by JHeartyP** [comment]
Same, Voodooi2c doesn't load. Catalina 10.15.7. In kernel log I only see Voodoogpio for some reason. Kextstat shows voodooi2cservices, voodoogpio, voodoo.driver.PS2Controller, voodoo.driver.PS2Keyboard as being loaded. Voodooi2chid, voodoo input and voodooi2c does not load.

In kernel log I see this:
`2020-10-19 02:47:28.426147+0300 0xb2       Default     0x0                  0      0    kernel: (kernel) VoodooGPIOCannonLakeLP::VoodooGPIO Initializing Community 0
2020-10-19 02:47:28.426400+0300 0xb2       Default     0x0                  0      0    kernel: (kernel) VoodooGPIOCannonLakeLP::VoodooGPIO Initializing Community 1
2020-10-19 02:47:28.426602+0300 0xb2       Default     0x0                  0      0    kernel: (kernel) VoodooGPIOCannonLakeLP::VoodooGPIO Initializing Community 2
2020-10-19 02:47:28.426962+0300 0x74       Default     0x0                  0      0    kernel: PMRD: PowerChangeDone: ON_STATE->ON_STATE
2020-10-19 02:47:28.426976+0300 0x74       Default     0x0                  0      0    kernel: PMRD: PowerChangeDone: ON_STATE->ON_STATE
2020-10-19 02:47:28.426983+0300 0xcf       Default     0x0                  0      0    kernel: (kernel) VoodooGPIOCannonLakeLP::GPIO Controller is already awake! Not reinitializing.
`

**Comment by corint1** [comment]
compile last version .... now working

**Comment by bangbaew** [comment]
I also have the problem, using Clover 5125 and macOS 10.15.7 but VoodooI2C won't load, it doesn't appear in Hackintool and no trackpad found in settings, making my touchscreen unusable, any fix?

**Comment by SergeySlice** [comment]
Resolved

**Comment by wsteelenyc** [comment]
I had the same problem....Looking at my log using the command...
log show --predicate "processID == 0" --debug
I noticed this message...
Refusing new kext com.alexandred.VoodooI2C, v2.6.3: already have prelinked v2.2.
This indicated that my updated VoodooI2C.kext which is needed for the updated clover, wasn't getting installed to the /Library/Extensions/ folder.
After deleting the kext file, rebuilding my cache and rebooting I was back in business! Hopefully this information will help someone else in the future.
