### ISSUE TITLE
STUCK ON EB#LOG:EXITBS

### ISSUE THREAD

**Issue by androidxda23** [CloverHackyColor/CloverBootloader#261]

**Comment by androidxda23** [comment]
![5C1AA6A9-F979-445B-BEE2-C652A7797628](https://user-images.githubusercontent.com/24587435/95820909-8afdb580-0d5b-11eb-819d-a10acae29934.jpeg)
![Uploading DEA44019-F3CF-44AB-AADA-00F4754596A5.jpeg…]()

**Comment by androidxda23** [comment]
Successfully Booted to Clover menu and Just stucks on EB EXITBS THING The inly OS IT BOOTS IS ONLY WINDOWS 10

**Comment by androidxda23** [comment]
![Uploading 235675A2-1C41-41F6-ABAD-4BBB0DF5E136.jpeg…]()

**Comment by mgrandinetti** [comment]
here a Fix reading some clover Forum
in "kernel and kext patch" patch that are similare to opencore for bigger

Patch per il bootloader
Clover: KernelPM e/o KernelXCPM
OpenCore: AppleCpuPmCfgLock e AppleXcpmCfgLock

**Comment by sn0wfL4ke98** [comment]
if EB#LOG:EXITBS, that means you're using the Quirks.
Try this
1. Enable SetupVirtualMap
2.
- EnableWriteUnprotector FALSE
- RebuildAppleMemoryMap TRUE
- SyncRuntimePermissions TRUE
if not, unprotector TRUE, both next are FALSE
3. Like mgrandinetti said, tick both KernelPM and KernelXCPM if your bios can't disable CFG-Lock
4. Also, tick ProvideConsoleGop

**Comment by SavageAUS** [comment]
Please update this issue if it’s solved or not. If solves mark it so.

**Comment by androidxda23** [comment]
still not working

**Comment by sn0wfL4ke98** [comment]
what is your laptop spec?

**Comment by androidxda23** [comment]
intel 8265u 
UHD 620 
SYNAPTIC TRACKPD

**Comment by androidxda23** [comment]
HOW TO FIX THAT?

**Comment by sn0wfL4ke98** [comment]
calm and turn off your caps lock...
- that cpu is gen 8th whiskey lake. Follow the quirks for coffee/whiskey here: https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake.html#booter
- about that issue: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start
- check your SSDTs and Kexts carefully. Also about that iGPU, you remember to fake id with device-id = 9B3E0000
my opinion: Always enable KernelPm and KernelXcpm. Then follow the quirks guide

**Comment by androidxda23** [comment]
I did enable the kernelPM and KernelXCPM and it works but I got this another error that stucks on APFS module I had only Lilu Whatever Green and my ethernet kext to be exact 
![Uploading 5267B0F6-62ED-44A7-9D87-3459BBEF581D.jpeg…]()

**Comment by androidxda23** [comment]
![Uploading 197727E1-5BF9-4381-AEFE-8FD105E1F5D4.jpeg…]()

**Comment by i0ntempest** [comment]
Thanks @sn0wfL4ke98 and @mgrandinetti, I can now successfully boot Catalina with 5124. The key seems to be KernelPM and KernelXCPM, at least on my system.

**Comment by SergeySlice** [comment]
You have to set quirks correctly. Clover has no issue.
