### ISSUE TITLE
Kernel panic "can't perform kext scan: no kext summary"

### ISSUE THREAD

**Issue by tahsinahmed2** [CloverHackyColor/CloverBootloader#265]
Edit: One of the the commits of the last few hours fixed my booting problem.
Clover now booting with the latest compile perfect on my PC.
Because of that I will now close this issue

Since the pre Release v5.1 r5123 and also the Release 5124 Clover doesn't boot anymore on my PC.

It always end in a kernel panic where it says
"can't perform kext scan: no kext summary"

But on OpenCore with the same quirks config what I use on Clover it boot.
Because of that I wouldn't say it has something to do with my configuration of the quirks settings.

I've also attached a log and screenshots, maybe it helps.

What I have forgot to mention it is a Asus P8Z77 V Premium with an Ivy Bridge Intel CPU and a NVIDIA GTX 680.
And I tryied to boot Catalina and Mojave and the Big Surr installer, but the all didn't boot

https://mega.nz/file/GJYEjLoS#h6a4ubT5oDFKnQEP2311K17EInKjLWVAFFSv49oOma4

![20201014_150224](https://user-images.githubusercontent.com/30934904/96003420-7f34f080-0e3a-11eb-9b7e-7035118e2318.jpg)
![20201014_150213](https://user-images.githubusercontent.com/30934904/96003432-82c87780-0e3a-11eb-884c-7226ffe459e8.jpg)
![20201014_150218](https://user-images.githubusercontent.com/30934904/96003448-865bfe80-0e3a-11eb-9752-c06a978c0a80.jpg)
![20201014_150227](https://user-images.githubusercontent.com/30934904/96003461-8825c200-0e3a-11eb-84d5-cd93f8c6ccf5.jpg)
![20201014_150204](https://user-images.githubusercontent.com/30934904/96003397-7ba16980-0e3a-11eb-8fea-c16d9aacb360.jpg)
![20201014_150228](https://user-images.githubusercontent.com/30934904/96003375-75ab8880-0e3a-11eb-9f8b-86c35c321679.jpg)

**Comment by Hoangpham89** [comment]
How did you fix it ?

**Comment by meimeiwe** [comment]
I've got the same problm, after I injected the another kext(for wifi driver) and snapshot by propertree
