### ISSUE TITLE
Boot Error

### ISSUE THREAD

**Issue by pratiknborkar** [CloverHackyColor/CloverBootloader#266]
Hey I have recently updated latest clover but after restart i got following error not even load the clover GUI also noted after 5122 my brightness level  always zero 
PS:NVRAM is fine. Also tried old boot0 error method but won't works 

![Screenshot_20201016-000544](https://user-images.githubusercontent.com/48144872/96172113-898ee180-0f43-11eb-986d-31907aae9c3e.jpg)

**Comment by SergeySlice** [comment]
Replace boot file by the same from old revision.

**Comment by SergeySlice** [comment]
Check 5125. If resolved close the issue.

**Comment by pratiknborkar** [comment]
@SergeySlice Thanks for the update :+1:  Issue is resolved with 5125 and rollback of old boot file both ways works
