### ISSUE TITLE
WHAT MEMORY FIX SHOULD I CHOOSE?

### ISSUE THREAD

**Issue by androidxda23** [CloverHackyColor/CloverBootloader#268]
Will I use the AptioMemoryFix or the Openruntime in clover ver 5125??

**Comment by mirsalimov** [comment]
I have the same question, please?

**Comment by MysticalOS** [comment]
openruntime/quirks will be future going forward (with also setting correct quirks applicable to opencore guide, so for example coffee lake builds would use these quirks https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#booter (I realize that's an opencore guide but effectively clover is now a 3rd party front end to opencore now but effectivevly runs off same core now)

aptiomemoryfix isn't maintained anymore and not likely to work forever, especially for newer versions of macOS or newer hardware builds.

**Comment by SergeySlice** [comment]
Only OpenRuntime will work for BigSur.
