### ISSUE TITLE
v2.5 kr5098 - Does not create EFI partition with Catalina, resulting media not bootable

### ISSUE THREAD

**Issue by alshdavid** [CloverHackyColor/CloverBootloader#27]
With the following settings, the resulting USB has no EFI partition and is not bootable.
The EFI folder appears on the main data partition.

![image](https://user-images.githubusercontent.com/12656294/68102500-23be6b00-ff27-11e9-8e56-86c733f13794.png)

I have a Macbook Pro 13 2019 running Mojave
![image](https://user-images.githubusercontent.com/12656294/68102613-aa734800-ff27-11e9-9b26-5979eb52a953.png)

**Comment by t14462** [comment]
Is it real MacBook, or just SMBios? You don't need Clover for real Apple devices, because it's unsupported and can damage your mac

**Comment by alshdavid** [comment]
I'm running the clover installer on a MacBook but targeting a USB drive to make it bootable.

So I create the installer on a USB with:
```
sudo /Applications/Install\ macOS\ Mojave.app/Contents/Resources/createinstallmedia --volume /Volumes/MYUSBDRIVE
```

Then ran the aforementioned configuration on the USB

**Comment by alshdavid** [comment]
Ah, I had to format the USB with a GUID partition map
