### ISSUE TITLE
Stuck in Clover r5125 

### ISSUE THREAD

**Issue by Airtonjunior54** [CloverHackyColor/CloverBootloader#272]
When I choose Catalina, clover stucks here. Don't know what might be.
Works perfectly in r5123. Issue started in r5124
I already added the new OC Quirks in my Config.plist

![IMG_0500](https://user-images.githubusercontent.com/63178162/96377013-65ecb680-1150-11eb-8757-97cc75b72f56.jpeg)

**Comment by nikhil19rathore99** [comment]
Same thing happens to me please help!!

**Comment by sn0wfL4ke98** [comment]
try and go 5125
5124 bugs a lot

**Comment by SergeySlice** [comment]
Replace AptioMemoryFix to OpenRuntime

**Comment by chatelp** [comment]
@SergeySlice I'm using OpenRuntime and I have exactly the same issue.

**Comment by arabesc** [comment]
@chatelp, have you added the new quirks section to the config.plist?

**Comment by chatelp** [comment]
@arabesc yes, unfortunately it changes nothing. Also, I have the latest version of OpenRuntime and Clover (r5126)

**Comment by juliantoledo** [comment]
I was having issues with r5126, I was able to fix them by replacing AptioMemoryFix with OpenRuntime
and Enabling Quirks:
RebuildAppleMemoryMap, ProtectMemoryRegions

**Comment by chatelp** [comment]
Hi @SergeySlice, I see you closed the issue, has it been corrected in a newer release? Thanks for the help.

**Comment by chatelp** [comment]
I still have no idea what's happening and I've tried multiple suggested solutions, including replacing Aptio by OpenRuntime. @SergeySlice did the logs provided any insight onto what is happening? I'm still on v5120 today 👎
