### ISSUE TITLE
UNKOWN CPU

### ISSUE THREAD

**Issue by bugraduz** [CloverHackyColor/CloverBootloader#273]
I am using BİG SUR beta 10. My cpu name is unkown
![Ekran Resmi 2020-10-18 22 39 49](https://user-images.githubusercontent.com/39997863/96378454-b38b1280-1194-11eb-8f9d-e37d8f93ac2e.jpeg)

**Comment by SergeySlice** [comment]
My CPU is known.

**Comment by jesusosx** [comment]
![Sin título](https://user-images.githubusercontent.com/31964654/96524399-c6a5ed00-123d-11eb-81da-e935b30e1812.png)

Mismo Error

**Comment by SergeySlice** [comment]
Any info?

**Comment by SergeySlice** [comment]
Check if you have CPU section in config.plist. It must be present else this issue.

**Comment by xma** [comment]
ok - adding an empty key CPU in config.plist solve the 'About this Mac' issue 
closed here : https://github.com/xma/T480-Clover/issues/26#issuecomment-713759606 
Thank you @SergeySlice
