### ISSUE TITLE
Unable to boot BigSur Beta 10 Installer

### ISSUE THREAD

**Issue by nooretk** [CloverHackyColor/CloverBootloader#274]
When I boot to macOS BigSur Beta 10 Installer it's stuck on this:

![Screen Shot 2020-10-19 at 3 59 49 PM](https://user-images.githubusercontent.com/60878261/96454145-21324f80-1224-11eb-8a77-7f42b43001c5.png)

**Comment by MysticalOS** [comment]
https://github.com/CloverHackyColor/CloverBootloader/issues/271

**Comment by SergeySlice** [comment]
No reason to open an issue.
