### ISSUE TITLE
How to use the version 5125?

### ISSUE THREAD

**Issue by wdrich** [CloverHackyColor/CloverBootloader#276]
I am using version 5122 well, OS 10.15.7. When upgrading to version 5125, a black screen starts. Is there any documentation for the new version of Clover?

error info:
[EB|#LOG:EXITBS:START]

**Comment by corint1** [comment]
try to give more details ... what configuration do you have, what did you try to do and you didn't succeed, what didn't you understand ... and first of all try to read the forum for clover bootloader ....
https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/

**Comment by octoforce** [comment]
You need add quirks settings into config.plist from config sample and turn on/off some items according to your computer.

**Comment by octoforce** [comment]
BTW my computer is i3 9100f and rx570.
Here are my quirks settings which is changed.
AvoidRuntimeDefrag: YES

DevirtualiseMmio: YES

DisableSingleUser: NO

DisableVariableWrite: NO

DiscardHibernateMap: NO

EnableSafeModeSlide: YES

EnableWriteUnprotector: YES

ForceExitBootServices：NO

ProtectMemoryRegion：NO

ProtectSecureBoot：NO

ProtectUefiServices：NO

ProvideCustomSlide：YES

RebuildAppleMemoryMap：YES

SetupVirtualMap： NO

SignalAppleOS： NO

SyncRuntimePermissions：YES

**Comment by Ales999** [comment]
Same problem, - black screen. Current not possible to load, - no more info who is bad. :-(
Trying to restore ...
ps sorry for my bad english.

**Comment by corint1** [comment]
nobody cares what processors you have ... the problem is the motherboard ... the chipset ... z370? z390? plus I gave you the support forum as a reference ...

**Comment by corint1** [comment]
> psps System is Mojave

for mojave no need update clover ...use the old one ...

**Comment by wdrich** [comment]
I can't see the newest user guide？

**Comment by Ales999** [comment]
> > psps System is Mojave
> for mojave no need update clover ...use the old one ...
Oh, last supported version for Mojave ?
I can't even imagine now how to go back to the old version :-(

**Comment by MysticalOS** [comment]
> [EB|#LOG:EXITBS:START]

https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start Quirks problem. People using new clover have to also learn how to use the opencore quirks settings correctly based on their board and cpu type.

**Comment by octoforce** [comment]
My motherboard is ASROCK H310cm itx

**Comment by Ales999** [comment]
I'm recovery to previous clover with this post: https://www.tonymacx86.com/threads/report-issue-with-clover-4586-macos-10-13-5.255268/post-1771526

**Comment by SergeySlice** [comment]
I also have to propose to change AptioMemoryFix to OpenRuntime.efi driver.
