### ISSUE TITLE
Strange Issue after swapping WiFi card

### ISSUE THREAD

**Issue by aleixjf** [CloverHackyColor/CloverBootloader#277]
Hey! I'm having a very strange issue:
I’ve just swapped my Intel 8265 card to the Fenvi BCM94360NG M.2 (which works great both on Windows and macOS, by the way!). However, after doing so, when I boot my HP, Clover displays the "Scan entries" message, but after doing so, it freezes on the next screen —> No F1 for help, no entries displayed, no nothing, only my theme logo.

The strangest things is that if I boot my HP, press ESC to display different options (like access BIOS config), and then press Enter (continue to normal boot), this issue doesn’t happen, Clover boots as usual with no issues, macOS and Windows appear, the F1 help label and the Clover version appear, etc. (see attached picture)
![screenshot0](https://user-images.githubusercontent.com/43652477/96707516-4051ee00-1398-11eb-9385-c4623f54ac3e.png)

I've tried not to load the DSDT.aml, using the old patched DSDT.aml and using a new patched DSDT.aml. Same results for all cases. I’m using Clover version5122 by the way, thank you very much!
Attach there is the .log file after booting with debug mode... (By the way, after checking the .log file I've only seen 1 message error, regarding audio and not devices found... so, I've tried to remove AudioDXe.efi as suggested but still, same result)
Thank you for your work!
[debug.log](https://github.com/CloverHackyColor/CloverBootloader/files/5415148/debug.log)

**Comment by SergeySlice** [comment]
You should open issue as new issue with recent Clover version because old errors are fixed.
