### ISSUE TITLE
m_cloverdirpathasxstringw.endswith('\')

### ISSUE THREAD

**Issue by zhang-wenchao** [CloverHackyColor/CloverBootloader#278]
Failed to start boot

**Comment by rikool050** [comment]
I have the same thing after I updated to r5125

**Comment by SergeySlice** [comment]
I think there is a syntax error in config.plist. Check more careful.

**Comment by paulopera** [comment]
I'm facing the same problem as @rikool050 with the r5126 and I had the same problem with the r5125 as well.
Rolling back to r5122 fix the boot.
![IMG_6288](https://user-images.githubusercontent.com/7115215/97979276-a0d82680-1dad-11eb-824d-5a0f7138dc07.jpg)

**Comment by SergeySlice** [comment]
It seems Quirks you set is not appropriate for your hardware which I don't know
