### ISSUE TITLE
Clover r5125 black screen after selection for the first time in 2 years with the same config

### ISSUE THREAD

**Issue by dogaoz** [CloverHackyColor/CloverBootloader#281]
Clover r5125 update dell xps 13 9350 black screen after selection for the first time in 2 years with the same config.
When I use -v verbose, I see this:

![image](https://user-images.githubusercontent.com/4470240/97096311-28d86680-161f-11eb-84fe-b5caec598cbb.jpeg)

**Comment by FrEaK-git** [comment]
Same for me... :(

**Comment by wqhyw** [comment]
Me too.... :(

**Comment by DecadentIpsum** [comment]
Same for me...

**Comment by cyberfunk** [comment]
Return to release 5122 if you want peace of mind😁

**Comment by arabesc** [comment]
show your EFI folder structure and attach config.plist

**Comment by denvergeeks** [comment]
> Return to release 5122 if you want peace of mind😁 Release 5123 and up introduce all kinds of issues with existing Clover setups. They're trying to integrate OpenCore I think and it's been a disaster for me. I'm sticking with 5122 until things are ironed out.

Thank you!!! Using 5122 worked for me, using this tutorial https://github.com/wmchris/DellXPS15-9550-OSX/blob/10.15/Tutorial_10.15.md and associated files at https://github.com/wmchris/DellXPS15-9550-OSX

**Comment by jief666** [comment]
OpenCore integration starts at 5124, not 5123.
To jump to 5124+ you have to define a Quirks section in your config.plist with a bit more quirks than if you were using OcQuirks.efi.
Unfortunately, you can find some forum posts but no real documentation.
Ask here : https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?page=982, you'll get help.
If you're willing to help with documentation (or anything else), tell us.
Thanks.

**Comment by paulopera** [comment]
> OpenCore integration starts at 5124, not 5123.
> To jump to 5124+ you have to define a Quirks section in your config.plist with a bit more quirks than if you were using OcQuirks.efi.
> Unfortunately, you can find some forum posts but no real documentation.
> Ask here : https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?page=982, you'll get help.
> If you're willing to help with documentation (or anything else), tell us.
> Thanks.

I'm facing the same problem as the OP with r5125 and r5126 but I'm not using OpenCore.
What information do you need?
![IMG_6288](https://user-images.githubusercontent.com/7115215/97981098-8e132100-1db0-11eb-816f-8adffcbac732.jpg)

**Comment by jief666** [comment]
If you have a working OpenCore or a working 5124 or 5125, follow this : https://jief-machak.gitbook.io/cloverhelp/.
If not, ask here : https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?page=982, you'll get help.
