### ISSUE TITLE
Unable to view the macOS Installer USB in the clover menu

### ISSUE THREAD

**Issue by ManasMalla** [CloverHackyColor/CloverBootloader#284]
I am trying to boot the macOS Big Sur USB which i created with the latest public beta 10 and when trying to boot the USB with clover UEFI i am unable to see the macOS installer, I can just see the Windows 10 partitions. I am tried booting the clover usb uefi with my old pc which already has macOS Big Sur installed and even in that i am unable to find the installed macOS big sur hdd nor the installer!

**Comment by SergeySlice** [comment]
We are not producing clover usb. Ask the author of the fabric. May be you forget APFS driver?
