### ISSUE TITLE
Mac Os Big Sur Clover bootloader not showing up

### ISSUE THREAD

**Issue by LakshitMalla** [CloverHackyColor/CloverBootloader#285]
I am trying to boot the macOS Big Sur USB which i created with the latest public beta 10 and when trying to boot the USB with clover UEFI i am unable to see the macOS installer, I can just see the Windows 10 partitions. I am tried booting the clover usb uefi with my old pc which already has macOS Big Sur installed and even in that i am unable to find the installed macOS big sur hdd nor the installer!

**Comment by SergeySlice** [comment]
And what is Clover issue here?

**Comment by LakshitMalla** [comment]
I am not able to find the installer during the boot.
Clover 5125
