### ISSUE TITLE
stuck at root

### ISSUE THREAD

**Issue by Makeroot911** [CloverHackyColor/CloverBootloader#287]
![IMG_20201030_134326 (3)](https://user-images.githubusercontent.com/61171264/97670313-86096780-1ab8-11eb-80fa-25ed2b35e669.jpg)

I tried clover version 5123 and above, but it's still like that
I tried it in catalina and installer big sur
sorry I'm not good at English

my specs :
acer e5-475g
intei i5 7200u
ram 16 gb
nvidia gt940mx
ssd adata xpg 8200pro 512gb

**Comment by SergeySlice** [comment]
Try Clover 5126 and show us what Quirks you set.

**Comment by ngdanghau** [comment]
I also have this problem and my Laptop is DELL E7490:  
- Intel i7 8650U  
- UHD 620 
- DW1560 (BCM94352z)

Quirks:
![Screen Shot 2020-11-12 at 12 30 16 PM](https://user-images.githubusercontent.com/33993567/98899777-e3eb7580-24e2-11eb-9ff1-4ed0c575c6c9.png)

**Comment by 451725563** [comment]
I have the same problem when I use version 5126, though it is work perfectly in 5123.1.
My laptop is DELL XPS 9360
- intel i5 7200u
- UHD 620
- DW1820a
here is my Quirks:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/20039197/98955987-7f5c0500-253a-11eb-8236-ec28bcf94257.png">

**Comment by riskyrismawan** [comment]
> I have the same problem when I use version 5126, though it is work perfectly in 5123.1.
> My laptop is DELL XPS 9360
> 
> * intel i5 7200u
> * UHD 620
> * DW1820a
>   here is my Quirks:
> 
> <img alt="image" width="951" src="https://user-images.githubusercontent.com/20039197/98955987-7f5c0500-253a-11eb-8236-ec28bcf94257.png">

This happened to me too, your quirk didn't work,

**Comment by OnlyWumbo** [comment]
i think i'm going back with OC again for now, before this issue fixed :(

**Comment by im-v** [comment]
Did anyone found solution for this as it's happening on latest version also

**Comment by Makeroot911** [comment]
after I updated to version 5127, the problem has been resolved
