### ISSUE TITLE
get panic after updating to 5126

### ISSUE THREAD

**Issue by vincentchen666** [CloverHackyColor/CloverBootloader#292]
My laptop is running 10.15.7 with Clover 5125, it works perfect. After I updating it to 5126, it got  panic as the screenshooting.
Please Check!

[https://ftp.bmp.ovh/imgs/2020/10/774739e76b2623c8.jpg](url)

**Comment by SergeySlice** [comment]
Reduce picture size and attach here. I see no it.

**Comment by nooretk** [comment]
I’m also have 10.15.7 and after updating to 5126 i got Memory Panic

![DA466318-8ED3-4D37-80F0-B94D0A889DAE](https://user-images.githubusercontent.com/60878261/97949749-55b61780-1d9d-11eb-8a33-f01c335ec873.jpeg)

**Comment by SergeySlice** [comment]
Use PanicNoKextDump=YES for more informative screen.
Also show your hardware specification.

**Comment by nooretk** [comment]
![Uploading 8742B424-E8D6-4BD2-80DD-7FE2A912746F.jpeg…]()

Got this on BigSur Installer Any Fix ?
r5126

**Comment by mouness2020** [comment]
i solved Memory Panic by replacing openruntime.sc
![Screenshot at Nov 06 23-21-54](https://user-images.githubusercontent.com/4884141/98415954-e71bd700-2086-11eb-93dc-b189fc468fe2.png)
 with OsxAptioFix3Drv.efi

**Comment by SergeySlice** [comment]
Different people reported different problems in one issue.
Please open own issues, provide hardware specification and debug.log.
