### ISSUE TITLE
Internal HD sata/sas not appearing

### ISSUE THREAD

**Issue by ioriyagami2020** [CloverHackyColor/CloverBootloader#295]
I've installed 5126,still on catalina 10.15.7. Internal sata and sas drive is not appearing. Using disk utility still it doesnt appear.
From 5122 all was normal.

**Comment by SergeySlice** [comment]
Any proof?

**Comment by ioriyagami2020** [comment]
![85FB75A6-64AF-444A-90EF-D0FD62F17938](https://user-images.githubusercontent.com/74103069/98672490-dc1bbc00-2390-11eb-8c10-e536edce23dc.jpeg)

![B5D03397-3DDF-45DF-AD7B-3E8C95D0C73B](https://user-images.githubusercontent.com/74103069/98672518-e3db6080-2390-11eb-835d-eeb2e569d532.jpeg)

In bios it detect the internal drives. In terminal it only list the boot drive

**Comment by SergeySlice** [comment]
Is your SATA controller in AHCI mode? The system will not see drives in ATA mode.

**Comment by ioriyagami2020** [comment]
Sata mode is in ahci. Tried with a clean install from catalina, everything was ok, sata, usb3 everything was perfect. After big sur update, it seems to mess up the config.plist.

**Comment by SergeySlice** [comment]
Do you have apfs driver installed?

**Comment by ioriyagami2020** [comment]
Yes, apfs driver is loaded. Or is it because im on intel c600 chipset?

**Comment by Mory5** [comment]
did you fix it i have the same issue

**Comment by ioriyagami2020** [comment]
After tinkering a few days, i was able to get sata/sas & dvd recognized by clover. Somehow S/L/E was lock from admin, had to use another machine to put sata unsupport kext into that folder. Boot up and now it detect everything. What puzzles me is i cant directly alter that folder. Even after entering my admin password.

**Comment by Mory5** [comment]
you but kext for your efi or what ? what kext you but

**Comment by ioriyagami2020** [comment]
Sata.unsupported.kext - inside S/L/E . When inside clover kext folder it will not detect my internal sas/sata. Its weird, because in catalina everything was ok

**Comment by Mory5** [comment]
not working too you use ssd or m.2 samsung ?

**Comment by ioriyagami2020** [comment]
It was a nomal wd hard drive, the boot drive is Samsung ssd

**Comment by SergeySlice** [comment]
There is SATA problem for Hackintoshes in BigSur. It is not Clover affair.
