### ISSUE TITLE
FakeSMC not working anymore after update from 5122 to 5126

### ISSUE THREAD

**Issue by alessaba** [CloverHackyColor/CloverBootloader#296]
After I updated to r5126 FakeSMC doesn't report readings anymore. I am creating the issue here since it was caused by the Clover update (tried to boot a 5122 release and it works again). Is there any change related to the OpenCore integration I need to adjust? Quirks seem all right. Didn't work in Catalina neither BigSur

**Comment by SergeySlice** [comment]
I am using FakeSMC in Mojave and BigSur with Clover 5126.
