### ISSUE TITLE
AptioMemoryFix and AptioInputFix missing from Recommended Drivers

### ISSUE THREAD

**Issue by malhal** [CloverHackyColor/CloverBootloader#3]
<img width="732" alt="Screenshot 2019-09-24 at 11 27 56" src="https://user-images.githubusercontent.com/916912/65504212-6a4b8f00-debe-11e9-806e-cdcc5fa0895c.png">

I believe they should be under Recommended Drivers. I had to get them manually from their own project page [here](https://github.com/acidanthera/AptioFixPkg/releases) which I believe didn't use to be necessary.

**Comment by SergeySlice** [comment]
These drivers are not part of the project.
