### ISSUE TITLE
Clover 5125/5126 bug loading kexts

### ISSUE THREAD

**Issue by ludoxIS** [CloverHackyColor/CloverBootloader#302]
Hello everyone
I encountered a problem when it concerns loading some kexts with the clover 5125/5126 especially on the "11" folder, while if they are placed on the "Olther" folder they are loaded.
In particular, there are 2 kexts that are not loaded on the folder "11" AirPortAtheros40 and HS80211Family that are used to activate WiFi notebook, I had to do a lot of tests to understand the problem and solve.
If I start with Clover 5122 Catalina with the 2 kexts in folder 10.15 it loads them correctly and wifi is enabled, while if I start with Clover 5125 or 5126 folder 11 no Wifi hardware is detected, it only works if they are copied to the Olther folder.
To enable wifi on Big Sur I have to copy to the "Olther" folder
Hope this problem is fixed in the next updates.
Hi

**Comment by Niresh12495** [comment]
The folder must be 11.0 for big sur.
