### ISSUE TITLE
No Big Sur recovery found

### ISSUE THREAD

**Issue by Aldo97** [CloverHackyColor/CloverBootloader#303]
Hi,
I'm happily using clover on both my hack.
First of all as now the system can be booted only via preboot I think it should be the case to disable/hide automatically the other boot entry.
Then, I see there is no recovery in clover even showing the hidden boot entries. Is there a way to use the recovery?
Thanks.

**Comment by HandaTakuya** [comment]
same

**Comment by Niresh12495** [comment]
Ah I'm not alone
https://github.com/CloverHackyColor/CloverBootloader/issues/313

**Comment by dateno1** [comment]
Same result

Boot well but can't find Recovery Menu

**Comment by Israel1971** [comment]
The same happened to me

**Comment by iCanaro** [comment]
fixed Clover 5129 RC1
