### ISSUE TITLE
can't install Clover 5126 in Big Sur

### ISSUE THREAD

**Issue by HandaTakuya** [CloverHackyColor/CloverBootloader#304]
I can't install Clover in Bug Sur 11.0.1 and my recovery is lose.

![Screen Shot 2563-11-17 at 22 44 20](https://user-images.githubusercontent.com/47761725/99416626-a136fc80-292b-11eb-9144-b852ef6b4951.png)
![Screen Shot 2563-11-17 at 23 21 21](https://user-images.githubusercontent.com/47761725/99416631-a300c000-292b-11eb-8327-452293c872ed.png)

**Comment by SergeySlice** [comment]
Resolved with latest commits.
If you can't compile new package by yourself then wait for release 5127.
