### ISSUE TITLE
Help creating icelake config

### ISSUE THREAD

**Issue by mouadcherkaoui** [CloverHackyColor/CloverBootloader#306]
Hi everybody, 
I'm new to the hackintosh world, and recently decided to hackintosh a Thinkbook 14 10th gen, but I faced errors using opencore, and now I'm trying to find help and informations about hackintoshing this nice machine and maybe help others in the same situation!

thanks in advance!

**Comment by SergeySlice** [comment]
It is issue tracker and not a school for beginners.
Go to one of forums, for example insanelymac.com

**Comment by mouadcherkaoui** [comment]
https://www.reddit.com/r/hackintosh/comments/jmp9td/thinkbook_14_iil_opencore_error/

I already did all the steps and troubleshooting in the guide but there is no way to resolve the issues!!
