### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by deverassilva** [CloverHackyColor/CloverBootloader#307]
since version 5124 to 5126 is crashing, only version 5123.1 worked after the 5122 that I had.

**Comment by deverassilva** [comment]
5124 to 5126 is crashing locking at boot

**Comment by SergeySlice** [comment]
May be some more info? Thousand people use 5124-5126 without problem.

**Comment by deverassilva** [comment]
after hours of configuration tests, it worked after enabling the DisableIoMapper (quircks) option, started to boot normally. grateful for the attention.
