### ISSUE TITLE
How to upgrade clover to 5126. My current number is 5121

### ISSUE THREAD

**Issue by 17639608291** [CloverHackyColor/CloverBootloader#308]
有人帮忙回答一下吗，谢谢

**Comment by tnwss** [comment]
我也不知道  顶一下！

**Comment by xkeyC** [comment]
download new .efi File form https://github.com/CloverHackyColor/CloverBootloader/releases page,and replace to you EFI partition.

**Comment by bangbaew** [comment]
the version is defined in EFI/BOOT/BOOTX64.EFI, not EFI/CLOVER/CLOVERX64.EFI, so you need to install with the installer package.

**Comment by SergeySlice** [comment]
not an issue
