### ISSUE TITLE
r5126 does not auto-detect ESXI 6.5 volume, F3 reveals volume, boots ok 

### ISSUE THREAD

**Issue by mjur3191** [CloverHackyColor/CloverBootloader#310]
Dell R820 Server with internal SD card slot 1 - running R5126 Clover Bootloader 
Additional Driver loaded: NVME 

Does not autodetect ESXI 6.5 U3 partition. When pressing F3 (show hidden) it will appear. Boots normally. 
Would like to boot without keyboard intervention. Currently have to press F3 and then select volume and press enter. 
Running Windows 10 workstation.

**Comment by SergeySlice** [comment]
Do you have any Hide in your config.plist?

**Comment by mjur3191** [comment]
> Do you have any Hide in your config.plist?

Default files only. Nothing has been modified. Only the NVME driver was copied from the OFF folder. All of the other files are the same as they were installed. 

Volume is HIDDEN by default - I am sure there is many ways of fixing this issue. I  do not know where the instruction manual is located.

**Comment by SergeySlice** [comment]
Provide please preboot.log

**Comment by mjur3191** [comment]
I would need instructions on how to create this file. I didnt see anything like this on my flash storage.

**Comment by SergeySlice** [comment]
Press F2 in the Clover GUI.
Then look for the file /EFI/CLOVER/misc/preboot.log

**Comment by mjur3191** [comment]
Thank you. Here is the log flile 
[preboot.log](https://github.com/CloverHackyColor/CloverBootloader/files/5664708/preboot.log)

**Comment by SergeySlice** [comment]
Test latest commit.

**Comment by SergeySlice** [comment]
looks like resolved

**Comment by rojarrolla** [comment]
Hi, I have the same thing, my NVME is not hidden, I can only boot if I press "F3". How can I have Clover to show it to me? Thanks!

**Comment by zikuan-wang** [comment]
> Hi, I have the same thing, my NVME is not hidden, I can only boot if I press "F3". How can I have Clover to show it to me? Thanks!

same issue. clover ver : 5151

**Comment by LYAN0526** [comment]
same issue. clover ver : 5152
