### ISSUE TITLE
Gigabyte GA-H61M-DS2 reset bios on reboot

### ISSUE THREAD

**Issue by hectorgrom** [CloverHackyColor/CloverBootloader#311]
Gigabyte GA-H61M-DS2 - v1.0 - BIOS F4
I5 3330
NVidia GTX650 2gb
MacOS Catalina 10.15.7

Apparently the current version is not able to run the patch "fixRTC" or "AppleRTC", because when the PC is restarted, the bios resets

Thanks..

Great job....   :)

**Comment by peterkkk366** [comment]
Maybe driver issue, if you are using HfsPlus.efi, try to use HfsPlusLegacy.efi to instead.

**Comment by SergeySlice** [comment]
FixRTC or AppleRTC? What patch did you use?

**Comment by hectorgrom** [comment]
Hi ... I always used "FixRTC" ... but started to reset the bios in the new versions of Clover (5120+), I tried to use "AppleRTC", but also reset the bios ... I tried to use both together ... unsuccessful ... I removed the old drivers from the "BIOS" folder ... unsuccessful ... deleted EFI and reinstalled Clover ... unsuccessful ... I'm currently using "RTCMemoryFixup.kext" + Clover 5127. .. and apparently solved it ....
