### ISSUE TITLE
Big Sur Boot issue when not selecting Preboot

### ISSUE THREAD

**Issue by Niresh12495** [CloverHackyColor/CloverBootloader#313]
When i boot Big Sur from the partition "Big Sur" it crashes with kernel panic. and I cant see like kexts are not being injected correctly.
It works when i boot from Preboot "Big Sur"?

Is there anything am i missing on Config?

**Comment by WiedNug86** [comment]
Same

**Comment by JoyZgq** [comment]
it works well by booting "via Preboot",and I've upgraded to macos 11.1 beta. Try F3 if you didn't find recovery

**Comment by kumakumalina** [comment]
currently most everyone who's still using Clover only can boot to BS with Preboot entry. "Big Sur partition" seems not worked now (the issues you said, problem with kext loading). It happened since 5126

**Comment by SergeySlice** [comment]
OpenCore always boot from Preboot saying nothing about this.

Always boot from Preboot!
