### ISSUE TITLE
How to Make Preboot as Default Selection in Clover

### ISSUE THREAD

**Issue by Niresh12495** [CloverHackyColor/CloverBootloader#315]
Is there any special option to make boot from Preboot as default?
I have “Mac” as Default partition to boot from, How to use Preboot of Mac as Default?

**Comment by GoodBoris** [comment]
I would say, how to move 'preboot' data to the main partition? To make it possible to boot OSx as usual?

**Comment by Niresh12495** [comment]
@GoodBoris Bad idea because
Preboot is how apple boots its OS. So It is the native way.

**Comment by edwardbelotserkovsky** [comment]
Well, previously I always have been choosing "Boot MacOS from OSx partition". I don't know what's was happening under the hood, but I've never seen the "Preboot" option before. I sent some time to extract that option by pressing F3. My main concern is to return the booting flow to the usual way.
Even more, OC doesn't display "Preboot" option in any case and can boot OSx from the "main" partition.

**Comment by GoodBoris** [comment]
> @GoodBoris Bad idea because
> Preboot is how apple boots its OS. So It is the native way.

Well, previously I always have been choosing "Boot MacOS from OSx partition". I don't know what's was happening under the hood, but I've never seen the "Preboot" option before. I sent some time to extract that option by pressing F3. My main concern is to return the booting flow to the usual way.
Even more, OC doesn't display "Preboot" option in any case and can boot OSx from the "main" partition.

**Comment by Niresh12495** [comment]
Yes open core only shows the main volume of the APFS container, a similar method would be highly appreciated

**Comment by SergeySlice** [comment]
> Is there any special option to make boot from Preboot as default?
> I have “Mac” as Default partition to boot from, How to use Preboot of Mac as Default?

Sorry, but it works.
I set a system to start in System Preferences and push "Restart". It works and it works next reboot.
See your mistakes.

**Comment by Erictoby** [comment]
What we want is a method to hide the "Mac" system volume and display only "Preboot" when preboot volume has been installed correctly since Big Sur use Preboot as a default volume to boot now. Can we hide "Mac" system volume as we could hide the preboot volume in config.plist/GUI/Hide? PS: I also had to remove config.plist/Boot/DefaultVolume as it points not the preboot but the "Mac" system volume.

**Comment by LeeBinder** [comment]
> Sorry, but it works.
> I set a system to start in System Preferences and push "Restart". It works and it works next reboot.

@SergeySlice Does this also work for you booting Big Sur? Have you tested and verified this on one of your hack-Macs?

**Comment by SergeySlice** [comment]
Yes, it is not possible to reboot to BigSur from Mojave because of different apfs systems.
Anyway what do you want? The issue is wrong. Preboot works as default selection.

**Comment by LeeBinder** [comment]
@SergeySlice yes, I had learned that in the meantime, thanks for clarifying it.

@Niresh12495 simply write `Preboot` into Clover config.plist > Boot > Default Boot Volume, and Big Sur should boot automatically. At least that works for me (even though I personally have `Mojave` in there)
