### ISSUE TITLE
r5127 stuck at [EB LOG:EXITBS:START] (still)

### ISSUE THREAD

**Issue by adaml75** [CloverHackyColor/CloverBootloader#317]
I have the same issue since 5122 (this is the last one that works for me). Quirks are configured. After Clover update, booting hangs at
[EB LOG:EXITBS:START]
++++++++++++++++++++++++
No configuration changes seem to fix the problem. I would love to try Big Sur, and configuring Open Core is a PITA. My Clover installation works perfectly well for me.

**Comment by franky920920** [comment]
Me too.

**Comment by Niresh12495** [comment]
Probably bad Quirks configuration, try tweaking them.

**Comment by peterkkk366** [comment]
Disable CFG Lock in Bios, if no this option, check Quirks to be set to Yes: AppleCpuPmCfgLock and AppleXcpmCfgLock.

**Comment by darrenkhouston** [comment]
Maybe try this solution, it worked for me.

https://github.com/CloverHackyColor/CloverBootloader/issues/309#issuecomment-740180694
