### ISSUE TITLE
Error Installing Big Sur with StartOSInstall Command

### ISSUE THREAD

**Issue by Niresh12495** [CloverHackyColor/CloverBootloader#320]
when i try to Install Big Sur with StartOSInstall command it fails with Clover.
It works with Open Core.
Am i doing anything wrong? I have tried several time with Clover & OC.

![macOS Update Assistant](https://user-images.githubusercontent.com/2318878/101670794-a5ad8b80-3a79-11eb-9d3e-a5a5152255d2.jpg)

`/Applications/Install macOS Big Sur.app/Contents/Resources/startosinstall" --volume "/Volumes/Apple SSD" --agreetolicense  --nointeraction`

**Comment by chris1111** [comment]
Clover as nothing to do with StartOSInstall command
