### ISSUE TITLE
Can't update 11.0.1 to 11.1

### ISSUE THREAD

**Issue by HandaTakuya** [CloverHackyColor/CloverBootloader#322]
![Screen Shot 2563-12-15 at 01 56 48](https://user-images.githubusercontent.com/47761725/102122974-db3ae600-3e78-11eb-9fed-1707aa780178.png)

![Screen Shot 2563-12-15 at 01 56 39](https://user-images.githubusercontent.com/47761725/102122999-e55ce480-3e78-11eb-86a6-73dc9e008c21.png)

Clover 5127

**Comment by kwangle912** [comment]
Same as me
![image](https://user-images.githubusercontent.com/46493927/102285507-01d84a00-3f69-11eb-8fb8-e3139d32652b.png)

**Comment by DecadentIpsum** [comment]
Same here. Is it possible to download this update manually. I checked the [downloads section](https://support.apple.com/downloads/macos) on Apple's site but it seems that it's available.

**Comment by ryulove3** [comment]
Can't download 'installer app' with clover.
I used the 20C69 source on another Mac.
The update itself went well.
However, I found out that the disk structure of Big Sur installed using Clover is different from that of Open Core. You cannot download the app from the App Store, nor can it be updated with software update.
Is it because of this?

**Comment by HandaTakuya** [comment]
> Can't download 'installer app' with clover.
> I used the 20C69 source on another Mac.
> The update itself went well.
> However, I found out that the disk structure of Big Sur installed using Clover is different from that of Open Core.
> There is no SSV(signed system volume).
> You cannot download the app from the App Store, nor can it be updated with software update.
> Is it because of this?

I can download and update app in App store but can't update macOS in setting

I try download macOS 11.1 from App store and install update 11.1 with macOS installer.

**Comment by albertoacj** [comment]
I can download and start the update, but there is a error in process something in apfs  timeout

**Comment by serdeliuk** [comment]
I was able to install big sur 11.0.1 and update to 11.1, i don't think it is related to Clover bootloader...... However, using Clover only though preboot partition (install and later boot) works....

**Comment by HandaTakuya** [comment]
> I was able to clean install big sur 11.0.1 and update to 11.1, i don't think it is related to Clover bootloader...... However, using Clover only though preboot partition (install and later boot) works....
> At this stage...

I boot Big sur with preboot but can't download macOS update in setting

**Comment by SergeySlice** [comment]
No problem with download and update.
