### ISSUE TITLE
I can't boot the system (watchdog error)

### ISSUE THREAD

**Issue by JamesIslan** [CloverHackyColor/CloverBootloader#327]
Hello. I have a hackintosh on an Asus X512FJ with macOS Big Sur 11.1 and Clover r5127 and I am experiencing an error. I use a tp-link wifi adapter TL-WN725N but I can't boot the system with it on USB. In verbose mode it shows the error "HalDmWatchDogn set RFChangeInProgress" repeatedly, making it impossible to enter the system. When I unplug it from USB, the system starts up occasionally, but when it starts up, I can't access my EFI folder for any reason.

**Comment by SergeySlice** [comment]
I can't understand how you was going to boot a system from unsupported WiFi adapter.
