### ISSUE TITLE
Kernel Panic - panic cpu2 caller ...initproc exited --exit reason namespace 2subcode 0x4 description:none

### ISSUE THREAD

**Issue by ManasMalla** [CloverHackyColor/CloverBootloader#330]
I have created a Clover EFI with r5127, with help of the guide given for big sur and added the necessary kexts, drivers and made the efi to match settings from my old EFI. I am on Pentium G4600, i was able to boot the macOS Catalina installer on r5122, but running big sur installer gives kernel panic -
panic cpu2 caller ...initproc exited --exit reason namespace 2subcode 0x4 description:none.
I gave the FakeCPUID 0x0306A0 in the config.plist with the help of clover configurator, added the FakePCIID.kext. Any help at the earliest is highly appreciatable.
I have been able to boot it using OpenCore but I wanted Clover as it helps me with my development process.

**Comment by SergeySlice** [comment]
May be debug.log will show what is happen?

**Comment by SergeySlice** [comment]
abandoned

**Comment by mikvas63** [comment]
См
