### ISSUE TITLE
New Version Not work well with Pre Bootloader

### ISSUE THREAD

**Issue by dateno1** [CloverHackyColor/CloverBootloader#332]
I was used https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk to bypass Secureboot for clover

bootx64.efi (shim) → grubx64.efi (preloader) → grubx64_real.efi (grub2) → Clover (bootx64.efi)

It work well with old version (tested with clover 5122) but lastest version (5127) has problem

I can't find macOSXs on boot menu (they are disappeared from menu)

**Comment by SergeySlice** [comment]
Anyway debug.log may show what is absent and what is present.

**Comment by dateno1** [comment]
> 
> 
> Anyway debug.log may show what is absent and what is present.

How can i get log?

**Comment by dateno1** [comment]
> 
> 
> Anyway debug.log may show what is absent and what is present.

How can i get 'debug.log'?

I tried 'GUI-DebugLog' but i can't found any file on misc

also i was pushed F2 but 'preboot.log' not saved

**Comment by SergeySlice** [comment]
Clover will save debug.log if the folder "CLOVER" is located on FAT32 partition, EFI partition.

**Comment by dateno1** [comment]
> 
> 
> Clover will save debug.log if the folder "CLOVER" is located on FAT32 partition, EFI partition.

I was installed Clover on EFI partition (FAT32) but log not saved

If i success to boot by direct boot (without another boot loader) i can found 'preboot.log' on 'misc' from 'push F2 key'

**Comment by stevezhengshiqi** [comment]
@dateno1 You need to enable Debug in config.plist.

**Comment by dateno1** [comment]
> 
> 
> @dateno1 You need to enable Debug in config.plist.

Is that 'GUI' - 'DebugLog' - 'True'?

but That not worked (no 'debug.log' on 'misc')

**Comment by stevezhengshiqi** [comment]
@dateno1 I don't think that's the one you need. It should be Boot - Debug, see https://github.com/CloverHackyColor/CloverBootloader/blob/master/CloverPackage/CloverV2/EFI/CLOVER/config-sample.plist#L384

**Comment by dateno1** [comment]
> 
> 
> @dateno1 I don't think that's the one you need. It should be Boot - Debug, see https://github.com/CloverHackyColor/CloverBootloader/blob/master/CloverPackage/CloverV2/EFI/CLOVER/config-sample.plist#L384

I want to Bypass Secureboot

Parameter changed?

I tried https://sourceforge.net/p/cloverefiboot/wiki/FAQ/#q-i-installed-clover-but-i-just-get-a-black-screen

I will Test New parameter with v5128 after few hours after

**Comment by dateno1** [comment]
![Debug](https://user-images.githubusercontent.com/12645246/104010874-8fb5f680-51f0-11eb-96d0-8a31647be0ac.png)
I was added 'Debug' option but can't found any file on 'misc' (Tested with v5128)

https://blog.dateno1.com/?p=2072
My EFI fullset on here (sorrry korean only) (please download 'E3-1230_GA-B75M-D3H_EFI_BigSur_210107')

I was install pre-loader on boot (rename Clover's bootx64.efi and install that)

Can i use clover with Secureboot without Pre-Loader?

**Comment by SergeySlice** [comment]
No, always use Preboot.

**Comment by dateno1** [comment]
> 
> 
> No, always use Preboot.

What do you mean?

I can't find any macOSx entry from menu (normal&preboot) with pre-bootloader (Even press F3)
