### ISSUE TITLE
Can't Boot Big Sur if clean installed

### ISSUE THREAD

**Issue by dateno1** [CloverHackyColor/CloverBootloader#343]
i3-7100 + GA-B150M-D3H + RX570/Big Sur 11.1/Clover 5178

Catalina -> Big Sur Upgrade work well

but I try to Clean Install big sur on same system i can't boot it (Endless Process hang with 'apfs_get_firmlink_target_vnode')

I can boot MacOSX from 'preboot' but not from 'normal'

**Comment by SergeySlice** [comment]
Always boot from Preboot as OpenCore does too.

**Comment by dateno1** [comment]
> 
> 
> Always boot from Preboot as OpenCore does too.

If you upgrade from old version to big sur you can boot it from normal menu (not preboot only)
