### ISSUE TITLE
Вопрос. У меня вначале вначале в меню значки из Custom и за ними значки из Scan.

### ISSUE THREAD

**Issue by dialmak** [CloverHackyColor/CloverBootloader#347]
У меня вначале вначале в меню значки из Custom и за ними значки из Scan. Как сделать наоборот? 

First, I have in the menu icons from Custom, and then from Scan. How do you do the opposite?

**Comment by SergeySlice** [comment]
Наверно никак.
Custom так пускай все будут кастом.

**Comment by dialmak** [comment]
Жаль. У меня 15 Custom. В rEFInd сканированные добавляются в начале.
Еще одно. А можно ли загрузить пользовательский config_user.plist из config.plist?
К примеру я так гружу пользовательскую конфу efitools.conf в rEFInd из refind.conf (ключ -c), [тут гифка](https://137615.selcdn.ru/NuttyBoot/efitools.gif)
```
menuentry "Management UEFI Boot Loaders" {
	volume "NUTTYBOOT"
	icon   \EFI\BOOT\icons\efiboot.png
	loader \EFI\tools\shellx64.efi
	options "-nostartup -noversion -nomap -exit \EFI\BOOT\refindx64.efi -c \EFI\BOOT\efitools.conf"
}
```

**Comment by SergeySlice** [comment]
Видимо нужно создавать Custom Entry для этого. Там тоже есть и иконки и названия. При чем тут config_user? В какой момент вы собираетесь загружать его? До входа в ГУИ? Если после, то уже поздно, ГУИ уже нарисовано.
Всегда? Тогда можно просто включить в конфиг.

**Comment by dialmak** [comment]
Вы меня не поняли, в гифке вроде бы все понятно. 

> ГУИ уже нарисовано.

Да, нарисовано. Если б можно было запускать config_user.plist из основного config.plist, то я сократил бы число Custom в основном меню перенеся их в config_user.plist, как и показано в гифке.

**Comment by SergeySlice** [comment]
Зачем плодить файлы? Оно что, в один файл не помещается?
Вот зачем мне вводить новые, глючные алгоритмы в Кловере по такому странному запросу?
