### ISSUE TITLE
Scan entries issue on r5070

### ISSUE THREAD

**Issue by Riko-Shet** [CloverHackyColor/CloverBootloader#35]
I have a freez on Scan entries. I figured out it's one of the 4 hdd that I have in raid0 in OS using SoftRaid software. It was working fine before update from r4xxx. What I'm doing: take off the data cable from that hdd, when clover gui is loaded I insert back the data cable and hit enter. So, once I'm on desktop the SoftRaid software shows me SMART status without any error on any of 4 hdds.
What can I provide guys to show you the problem? The problem with logs is that clover is freezed so have no idea what to do.
Thank you!

**Comment by SergeySlice** [comment]
If Clover started then debug.log can be produced
config.plist->Boot->Debug=YES

**Comment by SergeySlice** [comment]
Closed as abandoned
