### ISSUE TITLE
Only minimum CPU frequency in r5129

### ISSUE THREAD

**Issue by viniciusmi00** [CloverHackyColor/CloverBootloader#353]
After I upgraded to the Clover r5129, my CPU is only at the minimum frequency. I don't know if this is a bug or it was a planned change on the Clover r5129, so I will leave the log and a print screen here, if they help you.
It stopped operating the normal 3.2Ghz frequency and the Turb Booster 3.8Ghz. 
At r5128 or less, it works well. 
Note: I have an SSDT created by "ssdtPRGen" injecting the correct information from my CPU 
CPU: i7 3930k
MB: Asus Rampage IV Extreme
Big Sur 11.1

[bootlog.txt](https://github.com/CloverHackyColor/CloverBootloader/files/5899299/bootlog.txt)

![Captura de Tela 2021-01-30 às 21 43 21](https://user-images.githubusercontent.com/14878542/106376874-cc03ef00-6377-11eb-949d-29fa61777d86.png)

**Comment by SergeySlice** [comment]
Check commit e24ceaa. Should resolve the issue.

**Comment by viniciusmi00** [comment]
> Check commit [e24ceaa](https://github.com/CloverHackyColor/CloverBootloader/commit/e24ceaa47036b1b22de765a667641c9f3ae21d10). Should resolve the issue.

Did not work
I compiled using the "buildme" (SHA e24ceaa47). I used the option "7) build all". I installed it through "Clover_r5129.pkg" that was generated in the CloverPackage -> sym folder.
Is correct? 

![Captura de Tela 2021-02-10 às 21 36 27](https://user-images.githubusercontent.com/14878542/107591210-e7c58b80-6be8-11eb-8426-7132059f0c70.png)

**Comment by SergeySlice** [comment]
But if you do 
~~~
Note: I have an SSDT created by "ssdtPRGen" i
~~~

then it is not a Clover issue.
Anyway I have to propose to check latest commit.
As well I may recommend to set FakeCPUID=0x0306A2

**Comment by viniciusmi00** [comment]
> But if you do
> 
> ```
> Note: I have an SSDT created by "ssdtPRGen" i
> ```
> 
> then it is not a Clover issue.
> Anyway I have to propose to check latest commit.
> As well I may recommend to set FakeCPUID=0x0306A2

Slice, Clover r5130 release solve the problem, without me having to put FakeCPUID.
Problem solved!
