### ISSUE TITLE
VoodooRMI kext order issue (Clover v5129)

### ISSUE THREAD

**Issue by kushwavez** [CloverHackyColor/CloverBootloader#356]
Hi!

VoodooRMI is not working properly because of kext loading order issue. Sometimes it's working, sometimes it's not. Mostly luck's question.
Could you please add these to the order's code?
inside VoodooRMI there are two kexts: VoodooSMBus, VoodooRMI
According to @1Revenger1 and [VoodooRMI](https://github.com/VoodooSMBus/VoodooRMI) readme, VoodooSMBus.kext needs to be loaded before VoodooRMI/RMISMBus.kext.
Quote from the dev:

> VoodooSMBus needs to be loaded before RMISMBus - this is a Clover bug
> If you look at the log, it attempts to inject RMISMBus before VoodooSMBus. Order should be as followed:
> SMBus: VoodooSMBus/VoodooRMI -> RMISMBus
> I2C: VoodooI2C/VoodooRMI -> RMII2C
> Afaik, where VoodooInput goes doesn't really matter that much

_Originally posted by @1Revenger1 in https://github.com/VoodooSMBus/VoodooRMI/issues/103#issuecomment-773645285_

**Readme/Installation**
> 1. Add the required kexts to your bootloader
> 2. Disable VoodooPS2Mouse, and if applicable, VoodooInput from within the PS2 kext.
> - Note that VoodooPS2Trackpad should be injected if using Acidanthera's VoodooPS2 2.2.0 or greater
> - Injecting VoodooPS2Trackpad is not a strict requirement
> 3. For OpenCore users, make sure to add VoodooInput, VoodooTrackpoint and RMISMBus/RMII2C to your Config.plist.
> - RMISMBus/RMII2C should be after VoodooRMI
> - All dependencies are found under VoodooRMI.kext/Contents/PlugIns/

**Log**
[2021-2-4_21-27-28_CLOVERX64.efi.log](https://github.com/CloverHackyColor/CloverBootloader/files/5931008/2021-2-4_21-27-28_CLOVERX64.efi.log)

Should be like this in rEFIt_UEFI/refit/main.cpp: 
```
[...]
pos = setKextAtPos(&kextArray, "VoodooI2CHID.kext"_XS8, pos);
pos = setKextAtPos(&kextArray, "VoodooSMBus.kext"_XS8, pos);
pos = setKextAtPos(&kextArray, "VoodooRMI.kext"_XS8, pos);
[...]
```

Thanks in advance.

**Comment by SergeySlice** [comment]
OK, accepted.

**Comment by kushwavez** [comment]
Thank you!
