### ISSUE TITLE
Unable to load clover boot screen through refindplus chainload

### ISSUE THREAD

**Issue by jzrodriguez98** [CloverHackyColor/CloverBootloader#358]
[RefindPlus_x64-DBG.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/5939355/RefindPlus_x64-DBG.efi.zip)

[21d05v5653.log](https://github.com/CloverHackyColor/CloverBootloader/files/5939353/21d05v5653.log)
[21d05v5621.log](https://github.com/CloverHackyColor/CloverBootloader/files/5939354/21d05v5621.log)

I used to load clover boot screen through a refindplus chainload but it no longer work since clover v5128.![image](https://user-images.githubusercontent.com/10348976/107151840-2c2bff80-693b-11eb-9a50-c185a7944f3c.jpeg)
The logs from refindplus debug version are attached here.

**Comment by SergeySlice** [comment]
It is refind problem.

**Comment by jzrodriguez98** [comment]
I opened a ticket with refindplus repo and they were willing to research it but they will need to know what was changed exactly in Clover which is causing refind not to load CLOVERx64 efi properly. Maybe you may provide some tips to them (git user is dakanji).

**Comment by dakanji** [comment]
@SergeySlice 

Any hints on what might need to change on the other side?

**Comment by jzrodriguez98** [comment]
@dakanji . I did a test copying refindplus version AN to my EFI and also copied Clover to the same EFI where OpenCore and refindplus files reside. REFIndPlus loaded Clover booting screen without any issues.

**Comment by jzrodriguez98** [comment]
I will do another test this time copying Clover to a third EFI partition different from the one previously used.

**Comment by dakanji** [comment]
if you identify that the issue is specific to a RefindPlus version since you say 0.12.0.AN works, then raise an issue back on the project and provide the pertinent information.

**Comment by dakanji** [comment]
Not tested as I don't run Clover, but the issue with booting 3rd party boot managers such as Clover, should be resolved in [RefindPlus 0.13.2.AA](https://github.com/dakanji/RefindPlus/releases/tag/v0.13.2.AA).

**Comment by jzrodriguez98** [comment]
@dakanji . I checked and this release did not work since it showed a white screen without boot entries to choose.

**Comment by dakanji** [comment]
Please use the actual current release and raise an issue on the project page.
The issue template has the relevant information needed.
Thanks
