### ISSUE TITLE
Service did not exit... then rebooting after pass first installation stage

### ISSUE THREAD

**Issue by oldman20** [CloverHackyColor/CloverBootloader#359]
![08D7684E-147D-4265-855A-9C9DBB2A9109](https://user-images.githubusercontent.com/39668756/107849281-d240a380-6e2c-11eb-99a6-244bb768ebbe.jpeg)
![4596E750-7FD5-4653-B028-9A6ED8D8C766](https://user-images.githubusercontent.com/39668756/107849287-d8368480-6e2c-11eb-9e1b-620582c42bbd.png)
Hello, clover 5219 is boot normal big sur (which is already installed with open core) but when i installation with clover5219, first stage is fine, then machine reboot, i choose install from preboot, then loading here and reboot itself. Any idea What's missing? Thank you

**Comment by SergeySlice** [comment]
Something missing. Clover 5129 does loading BigSur Install.

**Comment by oldman20** [comment]
> Something missing. Clover 5129 does loading BigSur Install.

yes, I think so. It's just boot from preinstall macOS Big Sur, that's all this time!

**Comment by SergeySlice** [comment]
There must be more information to say something.
I just can tell that there is no proof of the Clover gilty

**Comment by SergeySlice** [comment]
Abandoned
