### ISSUE TITLE
Instant reboot after upgrading clover from r4961 to r5098 (AptioMemoryFix missing)

### ISSUE THREAD

**Issue by rgaufman** [CloverHackyColor/CloverBootloader#36]
I posted a ticket here: https://www.tonymacx86.com/threads/instant-reboot-after-upgrading-to-clover-5098-asus-prime-z370-a-8700k.287131

It seems the instant reboot is happening because AptioMemoryFix is missing. Any ideas why this was removed from the standard installation?

**Comment by SergeySlice** [comment]
Because old location is
/EFI/CLOVER/drivers64UEFI
while new location is
EFI/CLOVER/drivers/UEFI

**Comment by rgaufman** [comment]
No, no, there was no old location, this was a clean install on a blank USB flash drive, AptioMemoryFix is missing by default.
