### ISSUE TITLE
Clover 5130 issue 

### ISSUE THREAD

**Issue by himeshsam93** [CloverHackyColor/CloverBootloader#361]
I have update to latest version from clover 5120 to 5130 but  when I reboot my hackintosh it says malformed plist A fatal error happened system halted 
How to solve this problem?

**Comment by stevezhengshiqi** [comment]
You certainly need to adjust your config when updating from old version Clover.
[config-sample.plist](https://github.com/CloverHackyColor/CloverBootloader/blob/master/CloverPackage/CloverV2/EFI/CLOVER/config-sample.plist) provides an example, and `Quirks` section is something new starts from Clover r5123.

**Comment by himeshsam93** [comment]
Ok but I adjust my config but no luck still I can't boot into my system. can you define the quirks and drivers and all the fixes that allowed to install Big Sur , can you  upload a EFI folder that can update Big Sur . 
here the message when I boot into my machine can you tell how to fix this?
![0](https://user-images.githubusercontent.com/79123434/108023399-73f00c80-7048-11eb-97fe-a1319b9187a4.jpeg)

here's the my config.plist can you readjust the plist and give to me or give me a full compatible efi folder

[config.plist.zip](https://github.com/CloverHackyColor/CloverBootloader/files/5986391/config.plist.zip)

**Comment by stevezhengshiqi** [comment]
According to the error log, I will say the issue is on `Anime` dict in your theme.plist. I am not sure what exactly happens but you might need to change a theme. An upload of your theme.plist is welcome.

**Comment by himeshsam93** [comment]
OK , can you please fix this to me!!!
[themes.zip](https://github.com/CloverHackyColor/CloverBootloader/files/5986429/themes.zip)

**Comment by himeshsam93** [comment]
is my config.plist is correct? if it is incorrect can you please recorrect and give me? its a huge help!

**Comment by stevezhengshiqi** [comment]
Could you change a theme and test again? Anime part needs @jief666 to have a look.

**Comment by himeshsam93** [comment]
hello, @stevezhengshiqi here's my EFI folder also.
[EFI.zip](https://github.com/CloverHackyColor/CloverBootloader/files/5986479/EFI.zip)

**Comment by himeshsam93** [comment]
can you give me theme.plist because I didn't have ant theme.plists

**Comment by stevezhengshiqi** [comment]
theme.plist is located in your theme folder. What you can do is to change theme in config.plist - GUI - theme and test, for example, set theme value to `embedded`.

**Comment by himeshsam93** [comment]
ok wait ill test it now

**Comment by himeshsam93** [comment]
But no luck still it’s the same 
![F2B46223-A284-49AF-A05A-00C74BC78D36](https://user-images.githubusercontent.com/79123434/108025931-638e6080-704d-11eb-9906-ec1a0827f0d8.jpeg)

**Comment by himeshsam93** [comment]
I have 3 themes under my theme folder in efi 
I change embeded folder :- theme.plist 
:- theme :- embedded

**Comment by stevezhengshiqi** [comment]
You just need to change `config.plist - GUI - theme` to `embedded` as I said before. No other actions are needed. Or you can just delete the faulty theme folder `hackintoshzone`

**Comment by himeshsam93** [comment]
Ok thank you wait I’ll check.

**Comment by himeshsam93** [comment]
Yes it’s loaded the clover r5130 thank you for that 👌🏻🔥😍 but another error occurred can’t log into Mac OS 
![Uploading A3EE1D9C-65F7-437D-9B5D-4C80489E8CDD.jpeg…]()
It’s stuck on this

**Comment by himeshsam93** [comment]
![51C29891-2001-4962-AFAA-1C0D777C8685](https://user-images.githubusercontent.com/79123434/108027008-76a23000-704f-11eb-9632-26694856db40.jpeg)
It’s stuck on this 
What’s the reason for this ???
Is that drivers I change drivers that are need to install Big Sur is that the problem?

**Comment by himeshsam93** [comment]
is this config.plist values are correct ?
[Archive.zip](https://github.com/CloverHackyColor/CloverBootloader/files/5986620/Archive.zip)

**Comment by stevezhengshiqi** [comment]
The drivers in your kexts folder are not loaded because same kexts existed in the S/L/E or /L/E. You need to
 - update these kexts in your S/L/E (/L/E) 
 - or set `InjectKexts` to `Yes`
 - or remove these kexts in S/L/E (/L/E)

**Comment by himeshsam93** [comment]
is it this?
![Screenshot 2021-02-16 at 12 18 35](https://user-images.githubusercontent.com/79123434/108028024-24faa500-7051-11eb-8ce9-067e187b9d3e.png)

**Comment by himeshsam93** [comment]
It’s fixed thank you for helping ❤️🤩

**Comment by stevezhengshiqi** [comment]
@SergeySlice Hi Slice, I can confirm that starts from r5122, the `Anime` setting in `theme.plist` would cause the error
```log
MALFORMED PLIST in 'Anime' : TagArray:dictElementAt(1) -> trying to get a dict element at 1, but element is Key
```
Relevant code should at here: https://github.com/CloverHackyColor/CloverBootloader/blob/master/rEFIt_UEFI/libeg/XTheme.cpp#L676

I don't see apparent errors and it would be nice if you can take a look.

Here's an archive of a sample theme that can cause the error by @himeshsam93 
[themes.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6006948/themes.zip)

**Comment by SergeySlice** [comment]
The theme.plist is malformed
![Снимок экрана 2021-02-19 164502](https://user-images.githubusercontent.com/485515/108512249-ff300300-72d1-11eb-953d-252d5a0d081c.png)
CharWidth, Path, Type must be out of Anime array.
