### ISSUE TITLE
black screen after wake up catalina

### ISSUE THREAD

**Issue by mbatrawi** [CloverHackyColor/CloverBootloader#362]
Attached EFI Clover 5130 for i7 4790 Intel Hd 4600 IGPU only which  gives black screen after wake up
please help me to fix

**Comment by mbatrawi** [comment]
[EFI.zip](https://github.com/CloverHackyColor/CloverBootloader/files/5996352/EFI.zip)

**Comment by SergeySlice** [comment]
Wake up depends on drivers and ACPI. So you have to make big investigation about your DSDT and how different kexts influence on OS stability.
But there is no Clover issue.
