### ISSUE TITLE
[Solved] Catalina cannot be used on Clover 5129+5130+5131.

### ISSUE THREAD

**Issue by kwmlman** [CloverHackyColor/CloverBootloader#368]
[Image-01]
![Screen Shot 2021-02-24 at 13 43 34](https://user-images.githubusercontent.com/76897014/108950189-25c2b500-76a9-11eb-8348-fe9b3297d8ba.jpg)

[Image-02]
![Screen Shot 2021-02-24 at 13 50 11](https://user-images.githubusercontent.com/76897014/108950265-44c14700-76a9-11eb-8af6-e2ca93ae39d8.jpg)

Clover 5123-5128 worked well for both Catalina and Big Sur,
In Clover 5129-5130, Big Sur works fine, but Catalina does not work because of [in memory panic stackshot succeeded].

**Is there any way this can be solved?**

**Comment by kwmlman** [comment]
(( My System))

MSI B360M Mortar / i5-9400F / Sapphire rx570 4GB ( 1660 Ti 6GB )

**Comment by kwmlman** [comment]
[Image-03]
![Screen Shot 2021-02-25 at 5 51 07 AM](https://user-images.githubusercontent.com/76897014/109064985-6a446400-772e-11eb-9c56-70a3c646cadd.jpg)

Just removing the SSDT-PLUG-ME.aml in the patched folder solved this problem. 
This solution worked on clover 5129+5130+5131.

Clover Team's hopes will be accomplished wonderfully... (^-^)

**Comment by SergeySlice** [comment]
Well but the SSDT-PLUG-ME has no relation to Clover team.
