### ISSUE TITLE
r5130+ stopped booting completely on esxi-vm, r5129 working perfectly (reverted)

### ISSUE THREAD

**Issue by kcj83** [CloverHackyColor/CloverBootloader#369]
5129 working perfectly, no issue at all on esxi-osx-vm. as soon as i upgrade to 5130 or newer, the loader crashes/shuts down the vm right after boot selection menu. could be due to the datahubdxe embedded driver causing issues with the vm/esxi hypervisor. please fix/revert this if possible?! let me know if i can provide anything to help. note: it does boot recovery OK, but will not boot any actual live osx partition. Thanks SS. @SergeySlice

**Comment by SergeySlice** [comment]
It is not a news that Clover N+1 is not working while Clover N works fine.
May be you have to wait a version 5132 which will not work while 5131 will be perfect?
Anyway can you provide any proof of your trouble?

**Comment by kcj83** [comment]
both 5130 and 5131 are NOT working, while 5129 and below are working just fine.  What changes have been made that would negatively impact booting osx vm from esxi hypervisor in this way? the only thing ive seen thus far is the datahubdxe embedded driver changes... and there is no way to disable this driver since it is now embedded directly, correct?

**Comment by SergeySlice** [comment]
Some logs will be more informative.

**Comment by kcj83** [comment]
Of course Sergey, which logs would you like? Or can I just attach the entire EFI Clover directory?

**Comment by papasax** [comment]
I don't know if this is related, but since r5130, my MacOS entry just disappeared from the clover boot menu. I can still boot linux however. I had to revert to r5128 to get my hackintosh running again (did not try r5129).

**Comment by SergeySlice** [comment]
Both Clover 5130 and 5131 works showing macOS entry. 
Provide, please logs, screenshot or other proof of your observations.

**Comment by kcj83** [comment]
please dont close this, i will provide logs ASAP.
