### ISSUE TITLE
Building instructions leave out submodule initialisation

### ISSUE THREAD

**Issue by nabijaczleweli** [CloverHackyColor/CloverBootloader#373]
The [wiki](https://github.com/CloverHackyColor/CloverBootloader/wiki/Building) says to `git clone https://github.com/CloverHackyColor/CloverBootloader.git`, but that won't initialise submodules. Running `git clone --recursive $URL` instead will work (as will `git submodule update --init --recursive` afterward). Mayhap a good idea to include?

**Comment by SergeySlice** [comment]
Edited
