### ISSUE TITLE
[REGRESSION] r5131 breaks CFGLock.efi by Brumbaer - fine with r5130

### ISSUE THREAD

**Issue by LeeBinder** [CloverHackyColor/CloverBootloader#377]
![photo](https://user-images.githubusercontent.com/39203497/110779078-6b63ae00-8263-11eb-9aad-f53fcfda4c41.jpg)

after replacing 5131 `EFI/BOOT/BOOTX64.efi` with the previous 5130 `BOOTX64.efi`, functionality is back to what it's supposed to be:
![Screenshot](https://user-images.githubusercontent.com/39203497/110780283-d2ce2d80-8264-11eb-928f-5eda2ae163ee.jpg)

[my sample Clover EFI with CFGLock.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6122617/my.sample.Clover.EFI.with.CFGLock.efi.zip)

Asus VivoBook S15 S510UA BQ514T, BIOS x510UAR 310. Let me know if you need any logs.

Link to topic @ insanelymac: [CFGLock - unlock (MSR 0xE2)](https://www.insanelymac.com/forum/topic/344035-cfglock-unlock-msr-0xe2/) by Brummbär

**Comment by mackonsti** [comment]
Hi @LeeBinder you are launching this via an interactive UEFI Shell correct?

I have downloaded the latest CFG Unlock tool from https://github.com/utopia-team/opencore-debug/releases and it works fine with OpenCore 0.6.6 just tested, it as I just updated my NUC10 BIOS and MSR was re-locked. Perhaps worth trying it?

Brumbaer's (excellent) work was taken over by this team, it seems.

**Comment by LeeBinder** [comment]
@mackonsti 

> Hi @LeeBinder you are launching this via an interactive UEFI Shell correct?

No - it's not supposed to be necessary to do so, esp. with Brummbär's original CFGlock.efi because it does not even use (let alone require) any params to be added interactively. It's like: the bug is that the car does not drive forward anymore, so let's drive it backwards via reverse gear, so at least it runs .. that's not how to solve an issue ;)

> I have downloaded the latest CFG Unlock tool from https://github.com/utopia-team/opencore-debug/releases
> [..]
> Brumbaer's (excellent) work was taken over by this team, it seems

yes, OC debugs's "utopia team" took over Brummbär's `CFGlock.efi` code, re-labeled it `ControlMsrE2.efi` and made it interactive, requiring one of three arguments to be passed over. Unfortunately not even that is working in Clover, see Issue #376 :(

I'm confident team Clover will manage to at least get one of the MSR E2 unlock tools working (again) 🥇

**Comment by LeeBinder** [comment]
What's needed is some other users who test this on their hack and report back if they can get CFGlock.efi to work via Tools in Clover 5131, and on what hardware + BIOS.

**Comment by SergeySlice** [comment]
There is no CFGLock sources so I can't check what is happen.
Is there any problem with an open-source project?

**Comment by LeeBinder** [comment]
> There is no CFGLock sources so I can't check what is happen.

unfortunately you're right

> Is there any problem with an open-source project?

sorry, I don't understand your question. Can you please re-phrase what you mean?`ControlMsrE2.efi` does not appear to be open-source either (Issue #376)

**Comment by SergeySlice** [comment]
Some similar observation with other efi application? Which can be controlled.

**Comment by LeeBinder** [comment]
None I'm aware of.

BTW, I got it working with the latest Clover with a trick:

- right after turning on or rebooting my VivoBook, press the ESC key to intercept booting and to enter the built-in Boot Menu
- chose the partition with Clover, in my case the ESP
- run CFGLock.efi via Tools

BINGO, working!

Somehow this initiation via the boot menu is necessary.

**Comment by cecekpawon** [comment]
@SergeySlice I hope this point to the right sources, please check: Active [pull-request](https://github.com/acidanthera/OpenCorePkg/pull/167) | [Original source](https://github.com/zhen-zen/OpenCorePkg/tree/ControlMsrE2/Application/ControlMsrE2) under review.

**Comment by LeeBinder** [comment]
thank you @cecekpawon for your link to the source - I'll also add to #376

**Comment by SergeySlice** [comment]
Anyway I didn't confirm the title problem
![IMG_0479](https://user-images.githubusercontent.com/485515/111895005-c003e780-8a20-11eb-8389-97b38dbd4cfc.jpeg)

**Comment by SergeySlice** [comment]
ControlMsrE2.efi works as well in Clover 5131 with Shell provided with the Clover.
![IMG_0480](https://user-images.githubusercontent.com/485515/111895895-cb5a1180-8a26-11eb-82ee-2cdbb7912bd8.jpeg)

**Comment by LeeBinder** [comment]
> Anyway I didn't confirm the title problem

yes, `CFGLock.efi` works fine if run via shell even with r5131.

Even though you closed this issue, I re-labeled the title more appropriately to "_[REGRESSION] r5131 breaks CFGLock.efi (by Brumbaer) if run via 'Tools' entry - fine with r5130_".

@SergeySlice what happens when you run `CFGLock.efi` from `Tools` on your computer? Does it work from there for you yes/no?

`ControlMsrE2.efi`: I'll shift the conversation about it over to #376

**Comment by jief666** [comment]
Hi, is this really solved ? Or just not needed ?
Because the problem depicted in #376 wasn't new. So if it was working on 5130, there must be something else...

**Comment by LeeBinder** [comment]
CFGLock is outdated, and as per quote slice from here re. ControlMsrE2:

> The application is now compiled with Clover and will be included into next Clover release. 

I'd say let's wait and see how that turns out to be. From my side we can forget about CFGLock and anything related to it.

**Comment by jief666** [comment]
I still like to find regressions (and not only because I'm the one to cause them:-) ! Another tool maybe broken by that.
I'll integrate your "config-custom-tools_sample.plist" and compare. I'll post the result here.
Thanks for your "my.sample.Clover.EFI.with.CFGLock.efi.zip".

**Comment by jief666** [comment]
I tried with 5130 and it said "Can't find any Variable with cfg in name.
As you said, let's forget about that. If an other tool doesn't work, let's open a new issue.

**Comment by LeeBinder** [comment]
Okee-doke - seems like the most economic decision for now.

**Comment by jief666** [comment]
Economic !!! Yes, exactly right. And I need it :-)
Thanks for your understanding.
