### ISSUE TITLE
Hibernate mode 25/3 doesn't work

### ISSUE THREAD

**Issue by t14462** [CloverHackyColor/CloverBootloader#38]
Catalina 10.15.1, AptioMemoryFix, working NVRAM, latest Clover

CpuPM, SpeedStep, TurboBoost, Power Nap is OK

But why Hibernation 3 / 25 doesn't work on Catalina – I dunno.

**Comment by t14462** [comment]
I think, sleepimage not saved

**Comment by SergeySlice** [comment]
Because of Catalina.

**Comment by t14462** [comment]
Oh... I see. (I am Set440 on AppleLife)

:)
