### ISSUE TITLE
r5130+ stopped booting completely on esxi-vm, r5129 working perfectly (reverted)

### ISSUE THREAD

**Issue by kcj83** [CloverHackyColor/CloverBootloader#381]
will provide logs for this ASAP. please do not close.

5129 working perfectly, no issue at all on esxi-osx-vm. as soon as i upgrade to 5130 or newer, the loader crashes/shuts down the vm right after boot selection menu. could be due to the datahubdxe embedded driver causing issues with the vm/esxi hypervisor. please fix/revert this if possible?! let me know if i can provide anything to help. note: it does boot recovery OK, but will not boot any actual live osx partition. Thanks SS. @SergeySlice

both 5130 and 5131 are NOT working, i've tried them both while upgrading the OS to 11.2.2 this past week, while 5129 and below are working just fine, no issues at all.

What changes have been made that would negatively impact and totally crash/panic the loader when booting osx-vm from esxi hypervisor in this way? the only major change i've seen thus far is the datahubdxe embedded driver changes... and there is no way to disable this driver in 5130+ since it is now embedded directly in the loader, correct? @SergeySlice

ps. thanks for your excellent work.

**Comment by SergeySlice** [comment]
Check the latest commit. I think the bug is already resolved.

**Comment by kcj83** [comment]
Will check it today and upload logs from latest build.

**Comment by SergeySlice** [comment]
I think it resolved
