### ISSUE TITLE
The Model Identifier is not correct in Clover 5132

### ISSUE THREAD

**Issue by rex-lapis** [CloverHackyColor/CloverBootloader#382]
Hi Clover team,
First at all, thank you for your hard work for Clover 5132 version.
I found a small issue with model identifier after upgrading to Clover 5132. The model identifier is not correct. My SMBIOS is MacBookPro15,1 but it shows MacBook only in System Infomation, also in the Hackintool.
Hope you will fix it soon.
![Screen Shot 2021-03-30 at 14 46 50](https://user-images.githubusercontent.com/59220499/112953422-acb2f380-9167-11eb-9c75-1e5771645a7a.png)
![Screen Shot 2021-03-30 at 14 47 57](https://user-images.githubusercontent.com/59220499/112953447-b0df1100-9167-11eb-8908-3b36c975b263.png)

**Comment by kushwavez** [comment]
hmm mine is okay, but I set the SMBIOS using Clover Configurator. example:
![Képernyőfotó 2021-03-31 - 16 23 31](https://user-images.githubusercontent.com/33935034/113160099-73e54e00-923d-11eb-9de0-c8f5a4995e6f.png)
![Képernyőfotó 2021-03-31 - 16 20 13](https://user-images.githubusercontent.com/33935034/113159758-279a0e00-923d-11eb-9906-42d5c35f30e3.png)

Did you set SMBIOS info manually or automatically by Clover?

**Comment by kushwavez** [comment]
@rex-lapis If the fields are set in Clover Configurator -> SMBIOS by the two arrows and select (or clicking generate), then it's not automatic, but manual. It's just Clover Configurator generating a new SMBIOS.

**Comment by rex-lapis** [comment]
> @rex-lapis If the fields are set in Clover Configurator -> SMBIOS by the two arrows and select (or clicking generate), then it's not automatic, but manual. It's just Clover Configurator generating a new SMBIOS.

hmm... i will try. Thank you

**Comment by rex-lapis** [comment]
@kushwavez seems not work for me... when Clover 5131 everything is fine. Also in my Clover Configurator, I cant click to arrow button to select SMBIOS, seems like it's broken or freeze, I dont know @.@
