### ISSUE TITLE
two problems

### ISSUE THREAD

**Issue by vincentchen666** [CloverHackyColor/CloverBootloader#386]
Clover: 5133
1.Can not mount EFI partition.
2.if loading intel wifi driver and bluetooth driver to enter Big Sur , it will spend over 4 minutes to enter Big Sur.

**Comment by kushwavez** [comment]
Those are not related to Clover. 
As for 2., ask in OpenIntelWireless GitHub.

**Comment by SergeySlice** [comment]
1.
sudo diskutil mount disk1s1

**Comment by SergeySlice** [comment]
no answer more then 10 days. Closing.
