### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by Savio-Brazil** [CloverHackyColor/CloverBootloader#387]
The latest release of Clover (r5133) is freezing right on startup on my macbook pro (early 2011).
I downloaded the ISO, burned it to a DVD and the boot freezes in "Done6", as shown in the photo.

![Freeze](https://user-images.githubusercontent.com/82893837/115425635-2cb40280-a1d6-11eb-84dd-0af54e8fc1b2.jpeg)

**Comment by SergeySlice** [comment]
I didn't test CD boot several years...

**Comment by jief666** [comment]
Please try this : 
[Clover-5133-X64.iso.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6359740/Clover-5133-X64.iso.zip) and tell what you see on the screen.

**Comment by Savio-Brazil** [comment]
Thank you very very much, jief666! I'll try and post the result here.

**Comment by Savio-Brazil** [comment]
Hi Jief666. I just tested it. He went through "Done6" but then clean the screen and stay that way (with the screen completely black).

**Comment by jief666** [comment]
What is the latest version that worked ?

**Comment by Savio-Brazil** [comment]
I only tested from r5070 to here and none worked.
I did not test none before r5070.

**Comment by jief666** [comment]
If Clover never ever worked, it'll be hard to debug without the hardware I'm afraid.
Anyway, knowing that's it's made for Hackintosh, have you considered trying refind (http://www.rodsbooks.com/refind/) instead. It seems more what you need...

**Comment by jief666** [comment]
Closing because it looks like there is nothing we can do, but feel free to continue using the conversation thread.

**Comment by CE1CECL** [comment]
same issue here on vmware workstation 16.1.2 pro build 17966106

**Comment by azazar** [comment]
Same for VMware® Workstation 15 Player 15.5.7 build-17171714

**Comment by jiessiezhang** [comment]
VMware® Workstation 15 Pro using image Clover-5167-X64.iso

<img width="422" height="114" alt="Image" src="https://github.com/user-attachments/assets/653a3cd1-c114-460e-a606-d332ca997f64" />
