### ISSUE TITLE
Boot Error on 5134, 5133 is working great.

### ISSUE THREAD

**Issue by kcj83** [CloverHackyColor/CloverBootloader#390]
boot error attached for 5134, reverting back to 5133 for the time being.
![clover-5134-booterror](https://user-images.githubusercontent.com/79729347/116774383-2f51fb80-aa11-11eb-9420-05268030e2eb.PNG)

**Comment by yeucodonvn** [comment]
same my issue. macos 11.1

**Comment by SergeySlice** [comment]
Can you provide any information to localise the bug?

**Comment by kcj83** [comment]
ill do the best i can to provide any/all info i can, but it is literally crashing on boot right after splash screen/preboot selection screen.  what other type of information do you require?

**Comment by SergeySlice** [comment]
Test this version
[CLOVERX64.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/6442949/CLOVERX64.efi.zip)

**Comment by SergeySlice** [comment]
Is the issue valid for 5135?

**Comment by SergeySlice** [comment]
abandoned - means resolved
