### ISSUE TITLE
[INCOMPLETE/ OUTDATED]: please include two missing SIP values in Clover boot GUI

### ISSUE THREAD

**Issue by LeeBinder** [CloverHackyColor/CloverBootloader#391]
Right now still as of r5133 (5134 not tested yet):
```
Allow Untrusted Kexts
Allow Unrestricted FS
Allow Task For PID
Allow Kernel Debugger
Allow Apple Internal
Allow Unrestricted DTrace
Allow Unrestricted NVRAM
Allow Device Configuration
Allow Any Recovery OS
Allow Unapproved Kexts
```
Missing even though known since at least 2021-02-18 (corresponding hex value after each #):
```
# since Mojave:
CSR_ALLOW_EXECUTABLE_POLICY_OVERRIDE		# 0x0400
# since Big Sur:
CSR_ALLOW_UNAUTHENTICATED_ROOT       	 	# 0x0800
```
Source: https://bbs.archlinux.org/viewtopic.php?pid=1956991#p1956991

It would be awesome if you include the missing values so SIP can again be tweaked fully via Clover GUI as per user preference.

Also, for reference: [ink-splatters CsrDecode branch](https://github.com/ink-splatters/CsrDecode) (branched from corpnewt), nicely generating hex values in both "flavors" for both, Clover and OC:

![Screenshot](https://user-images.githubusercontent.com/39203497/116796706-01d38380-aadf-11eb-9490-3eab228b2b75.jpg)

![Screenshot Values to HEX](https://user-images.githubusercontent.com/39203497/116796660-7954e300-aade-11eb-801f-c9c688b0f923.jpg)

![Screenshot Hex To Values](https://user-images.githubusercontent.com/39203497/116796742-46f7b580-aadf-11eb-93ae-9f1735fa41b6.jpg)

.. and hey, I find Clover GUI 100 x more powerful than OpenCanopy. I think they're going an inefficient route, disregarding the fact that Apple is Apple, and hackintosh is hackintosh. Just my two cents..

**Comment by SergeySlice** [comment]
Accepted

**Comment by SergeySlice** [comment]
Done in commit 9c6e5ce

**Comment by LeeBinder** [comment]
Very nice, that was fast - thank you Sergey!

![screenshot0](https://user-images.githubusercontent.com/39203497/117057918-4f89ff00-ad1e-11eb-834b-ac01015df794.jpg)
