### ISSUE TITLE
Can't boot after update 5134

### ISSUE THREAD

**Issue by HandaTakuya** [CloverHackyColor/CloverBootloader#392]
![IMG_20210503_153704](https://user-images.githubusercontent.com/47761725/116857256-b3310100-ac26-11eb-95db-0b4e475c879c.jpg)
![IMG_20210503_153811](https://user-images.githubusercontent.com/47761725/116857521-25094a80-ac27-11eb-945f-f6c07371a734.jpg)

**Comment by SergeySlice** [comment]
Correct your config.plist according to first screen.
If you'll still have a problem then open new issue and attach debug.log.
