### ISSUE TITLE
build 5094 doesn't start on my legacy hackintosh

### ISSUE THREAD

**Issue by N-R-G** [CloverHackyColor/CloverBootloader#4]
I have this old notebook hackintosh with legacy bios:

CPU Intel core 2 duo 2,53 ghz, GPU: NVidia Geforce 9800m GTS 1024MB, SRAM 6GB, SSD Samsung 860 EVO 1TB, macOS 10.13.6 High Sierra+Windows 10 64bit, Smbios MacBook Pro 7,1

it works with all previous version of clover since 5093 but with 5094 it doesn't start
It stop at the cursor in the left angle and never show the clover's gui

**Comment by SergeySlice** [comment]
Was debug.log created?
Is it a problem of boot file or CloverX64.efi? Test by replacing.

**Comment by SergeySlice** [comment]
Closed as abandoned.
