### ISSUE TITLE
How to open xcpm in Ivy

### ISSUE THREAD

**Issue by mjs520** [CloverHackyColor/CloverBootloader#401]
Is there any specific method for Ivy to start xcpm

**Comment by mjs520** [comment]
MacOS 11.4

**Comment by 5T33Z0** [comment]
It requires a kernel-specific Patch (each macOS has its own) and additional steps to enable it. I only managed to enable it in OpenCore in Cataline for now: https://tinyurl.com/pm9bxzy7
In my experiences from testing there are no benefits to re-enable this feature. It performs worse than using the legacy plugin.

**Comment by SergeySlice** [comment]
No benefits.
