### ISSUE TITLE
wishlist: shortcut to skip partition scanning

### ISSUE THREAD

**Issue by examachine** [CloverHackyColor/CloverBootloader#403]
when corrupt hfs+ partitions are present, scanning sometimes hangs. an option to skip scanning when it freezes would he useful, for instance if the only way to fix the fs is through mac os!

**Comment by SergeySlice** [comment]
Your proposition, how it should be looking?

**Comment by examachine** [comment]
I really don't know. I think it was a configuration error on my end, I'm through it but it does happen. Not really sure what caused it, probably a corrupt filesystem.

**Comment by jief666** [comment]
If it hangs in the HFS driver, there is nothing we can do...

**Comment by examachine** [comment]
damn you're right :(
