### ISSUE TITLE
NVME SSD is not recognized anymore in Legacy mode

### ISSUE THREAD

**Issue by InZan3** [CloverHackyColor/CloverBootloader#405]
I have used a very old version (4152) of clover to boot my NVME SSD on Legacy Laptop, now I updated to 5134 with Mac OS X installer package and checked NVMe driver to be installed. Clover doesn't find the SSD anymore, any help for that?

**Comment by SergeySlice** [comment]
Some messages or logs?

**Comment by SergeySlice** [comment]
No logs - no issue
