### ISSUE TITLE
Update to 5135 But Can't Boot

### ISSUE THREAD

**Issue by HandaTakuya** [CloverHackyColor/CloverBootloader#409]
I update Clover version 5133 to 5135 but Can't boot to Desktop

![IMG_20210521_122325](https://user-images.githubusercontent.com/47761725/119089648-adb02500-ba34-11eb-86d4-f41cd9872d77.jpg)

I check config.plist with CloverConfigPlistValidator is say "Your plist looks so wonderful. Well done!"

![Screen Shot 2564-05-21 at 13 02 57](https://user-images.githubusercontent.com/47761725/119089765-df28f080-ba34-11eb-9f90-b2314a2e77c8.png)

**Comment by mjs520** [comment]
卡内存了吧

**Comment by jief666** [comment]
Can you boot with this efi file : https://github.com/jief666/CloverCommits/blob/master/C-20210411074317-fd3b09c-5133.efi ?
If not, send a the log file.

**Comment by HandaTakuya** [comment]
Yes, I can boot efi from 5133

**Comment by jief666** [comment]
And this one : https://github.com/jief666/CloverCommits/blob/master/C-20210429211313-fb86ee1-5134.efi

**Comment by SergeySlice** [comment]
> Yes, I can boot efi from 5133

IIs there the same EFI folder with the same files but Clover?
What EFI/CLOVER/drivers/UEFI installed?

**Comment by HandaTakuya** [comment]
> > Yes, I can boot efi from 5133
> 
> IIs there the same EFI folder with the same files but Clover?
> What EFI/CLOVER/drivers/UEFI installed?

in EFI/CLOVER/drivers/UEFI
![Screen Shot 2564-06-10 at 19 28 28](https://user-images.githubusercontent.com/47761725/121524984-1120e780-ca22-11eb-9e19-78743d9d3e25.png)

now I new create config from 5136 simple-config and success to boot in Clover 5136 But... my Laptop is Black Screen. Can login to Desktop and connect extend Display to use Hackintosh. Then another 5-10 minutes My Laptop Display is Back to work again.

**Comment by HandaTakuya** [comment]
> > > Yes, I can boot efi from 5133
> > 
> > 
> > IIs there the same EFI folder with the same files but Clover?
> > What EFI/CLOVER/drivers/UEFI installed?
> 
> in EFI/CLOVER/drivers/UEFI
> ![Screen Shot 2564-06-10 at 19 28 28](https://user-images.githubusercontent.com/47761725/121524984-1120e780-ca22-11eb-9e19-78743d9d3e25.png)
> 
> now I new create config from 5136 simple-config and success to boot in Clover 5136 But... my Laptop is Black Screen. Can login to Desktop and connect extend Display to use Hackintosh. Then another 5-10 minutes My Laptop Display is Back to work again.

After update 5136 my Laptop is Black Screen. Can login to Desktop and connect extend Display to use Hackintosh

![IMG_20210610_193640](https://user-images.githubusercontent.com/47761725/121526778-eb94dd80-ca23-11eb-872d-a727128d68f8.jpg)

Then another 5-10 minutes My Laptop Display is Back to work again.

![IMG_20210610_193919](https://user-images.githubusercontent.com/47761725/121526808-f51e4580-ca23-11eb-9be0-313ecf1c7446.jpg)

**Comment by HandaTakuya** [comment]
Update : I can FIXED ! 

Thank for Help ! ><

**Comment by jief666** [comment]
Could you explain what was the problem and how you solved it. It might help others...

**Comment by HandaTakuya** [comment]
> Could you explain what was the problem and how you solved it. It might help others...

create new config from 5136 simple-config and remove other key
