### ISSUE TITLE
Could you package Itlwm into an EFI driver?

### ISSUE THREAD

**Issue by 1457384613gh** [CloverHackyColor/CloverBootloader#415]
Could you package [Itlwm](https://github.com/OpenIntelWireless/itlwm)  into an EFI driver ?
As is known to us, Macintosh can connect to the WiFi when user choose to boot a choice, which is used for booting from wireless network.
If [Itlwm](https://github.com/OpenIntelWireless/itlwm) could be packaged into an EFI driver, Hackintosh would be superior and more similar to Macintosh.
[Itlwm](https://github.com/OpenIntelWireless/itlwm)
https://github.com/OpenIntelWireless/itlwm/issues/608

**Comment by SergeySlice** [comment]
We are not including outside software into our package. We include only those that can be compiled from our sources.

**Comment by 1457384613gh** [comment]
> We are not including outside software into our package. We include only those that can be compiled from our sources.

Thanks for your reply and how earnest you are !
