### ISSUE TITLE
Can you write a hd4000 patch

### ISSUE THREAD

**Issue by mjs520** [CloverHackyColor/CloverBootloader#418]
Hello, clover developer, can you write a driver patch of hd4000 guided by clover under macos12 to drive hd4000, thank you.

**Comment by SergeySlice** [comment]
This is the same script https://github.com/dortania/OpenCore-Legacy-Patcher which do:
1. unlock system volume
2. copy 6 kext and bundles from BigSur to /System/Library/Extensions dealing with HD4000
3. remake snapshot
4. voila
Nothing about a bootloader.
