### ISSUE TITLE
To load Clover after enabled secure boot, could you give a secure boot key ?

### ISSUE THREAD

**Issue by 1457384613gh** [CloverHackyColor/CloverBootloader#421]
To load Clover after enabled secure boot, could you give a secure boot key ?
It cannot load Clover unless disabled secure boot.

**Comment by SergeySlice** [comment]
If you mean Apple Secure Boot then it is disabled in Clover forever as not compatible with latest Monterey.
If you mean UEFI Secure Boot then you should sign Clover with some utility and write the signature into your BIOS that is not same as mine.
Be a developer to use the secure boot or forget it.
