### ISSUE TITLE
How to turn off SIP under macos12, thank you

### ISSUE THREAD

**Issue by mjs520** [CloverHackyColor/CloverBootloader#422]
How to check when patching, whether SIP is closed, and how to close SIP under clover

**Comment by kushwavez** [comment]
`csrutil status`

0xFEF : Disable SIP

**Comment by SergeySlice** [comment]
If you check and modify SIP UNDER CLOVER then enter Clover GUI, choose "Options" and then foollow the screenshots
![screenshot10](https://user-images.githubusercontent.com/485515/124001286-22d02c00-d9dd-11eb-8381-ddcce4d6ed75.png)
![screenshot9](https://user-images.githubusercontent.com/485515/124001320-2c599400-d9dd-11eb-870a-2b94e484962f.png)
![screenshot8](https://user-images.githubusercontent.com/485515/124001351-34193880-d9dd-11eb-9eda-241add360fea.png)
Some questions remain?
This is issue tracker and not a school how to use Clover
