### ISSUE TITLE
GetOS  Wrong value if updating from an older OS to Monterey (tested from 11.4 and 11.5 beta3)

### ISSUE THREAD

**Issue by fabiosun** [CloverHackyColor/CloverBootloader#424]
as requested here : 
https://github.com/CloverHackyColor/CloverBootloader/issues/283#issuecomment-869458846
I open a new thread with a pretty same old problem in GetOS detection

this problem is particularly serious for users who have a system with an AMD CPU, as by the correct recognition of the system in use it is possible to load the necessary kernel patches .. and which may be different from one OSX release to another

**Comment by SergeySlice** [comment]
I see no wrong GetOS detection. Check again and provide actual debug.log.

**Comment by fabiosun** [comment]
Thank you SergeySlice
Problem is there from an old 5124 version and was present also in latest 5142
As soon I can I put back an high sierra 12.13.6 OS to update to a new one and see
From which commit you have solved this problem?

**Comment by SergeySlice** [comment]
There are too many changed in sources related to switch from C to C++.
With latest Clover and latest macOS I see good detection.

**Comment by fabiosun** [comment]
> I see no wrong GetOS detection. Check again and provide actual debug.log.
<img width="423" alt="Screenshot 2022-02-06 at 12 10 10" src="https://user-images.githubusercontent.com/6358373/152678019-45c28c57-255a-40a6-8f74-b5d630a02c55.png">
[Archive.zip](https://github.com/CloverHackyColor/CloverBootloader/files/8009999/Archive.zip)

Installed on a clean disk High Sierra 
updated fine to Mojave and then to Catalina
trying to update to Big Sur from Catalina
First stage of updating in OSX Catalina is ok
the on Clover Boot menu I have two options
Boot from macOS OS data and boot from macOS
first one hangs 
second one boot in Catalina 
in debug log of first one I see OS X detected as 10.5.2.... but I started with this actual update:
<img width="538" alt="Screenshot 2022-02-06 at 12 14 50" src="https://user-images.githubusercontent.com/6358373/152678172-4fccd0a7-1e71-459e-96d3-47c6eaadad58.png">
a bit different problem but always a getOS detection problem here
