### ISSUE TITLE
help debugging installation failure

### ISSUE THREAD

**Issue by toranb** [CloverHackyColor/CloverBootloader#425]
I've tried a few different versions of the pkg installer on 2 different macs (both BigSur and Catalina) that ran into the same error "The installation failed" - any location I can look on device to see the logs for this type of failure? 

thanks in advance

**Comment by SergeySlice** [comment]
![Screenshot 2021-06-11 at 22 18 56](https://user-images.githubusercontent.com/485515/124622830-1d169280-de84-11eb-8158-4d732e676231.png)
