### ISSUE TITLE
Hd4000 patch software for clover under Mac OS 12

### ISSUE THREAD

**Issue by mjs520** [CloverHackyColor/CloverBootloader#428]
Can we develop a patch for clover hd4000 under Mac OS 12? OC's OpenCore-Legacy-Patcher doesn't work

**Comment by mjs520** [comment]
![Screenshot_20210706_024427](https://user-images.githubusercontent.com/26852845/124509225-206a3980-de04-11eb-904d-9f43e7ff5204.jpg)

**Comment by mjs520** [comment]
![Screenshot_20210706_024600](https://user-images.githubusercontent.com/26852845/124509365-66bf9880-de04-11eb-8219-a79fef72241e.jpg)

**Comment by z3DD3r** [comment]
Patch for HD4000 is not related to clover or any other boot loader. You can use OpenCore Legacy Patcher to install required kexts into system. Then u need to disable SIP (CsrActiveConfig=0xFEF in case of Clover) and add amfi_get_out_of_my_way=1 flag into boot options.

**Comment by SergeySlice** [comment]
Nothing bootloader specific.
