### ISSUE TITLE
Slides Error

### ISSUE THREAD

**Issue by OblivionGhoul** [CloverHackyColor/CloverBootloader#429]
Hello, 

I got this error and I was wondering how to fix it. I read somewhere that I can change the slides or something. Thank you.

```
AMF: Only 247/256 slide values are usable!
Valid slides: 9-255
```

**Comment by SergeySlice** [comment]
AMF is AptioMemoryFix, deprecated now. Use OpenRuntime.efi instead.

**Comment by OblivionGhoul** [comment]
Sorry I am new to this, is there a guide on how to use OpenRuntime.efi instead?
