### ISSUE TITLE
gRAM structure isn't deleted when loading a different config file

### ISSUE THREAD

**Issue by Florin9doi** [CloverHackyColor/CloverBootloader#43]
Switching form a config file which has SMBIOS>Memory>Modules to a config file without SMBIOS>Memory and booting will still inject the memory modules from first file. 
The same thing happens when switching from a config file with more memory modules (eg: 2x16GB, slot:0+1) to a config file with fewer modules (eg: 1x32GB, slot:0). In this case it will inject 1x32+1x16GB

**Comment by SergeySlice** [comment]
We have many issues with config switching. Most of them caused by conflict with Custom Entries possibility each of them can have own config. We have to disable CustomEntries possibility or there is a large field for investigations.
