### ISSUE TITLE
Installation fails on macOS 11.4

### ISSUE THREAD

**Issue by chyqichyqi** [CloverHackyColor/CloverBootloader#430]
Am I missing something or doing something wrong? I disabled SIP, and still no luck.

<img width="619" alt="Screen Shot 2021-07-14 at 3 31 55 PM" src="https://user-images.githubusercontent.com/69228687/125682657-20ea0bb1-3d5a-4d94-b8a7-0de52610d5ae.png">

Thanks!

**Comment by mjs520** [comment]
安装类型选择一下

**Comment by chyqichyqi** [comment]
i tried to customize the installation type, but still have the same error

**Comment by SergeySlice** [comment]
sudo spctl --master-disable

**Comment by chyqichyqi** [comment]
disabled gatekeeper. same issue, unfortunately

**Comment by SergeySlice** [comment]
See Security pref panel.

**Comment by SergeySlice** [comment]
abondoned
