### ISSUE TITLE
Release 5138 does not display video cards in "options -> Graphics Injector"

### ISSUE THREAD

**Issue by hectorgrom** [CloverHackyColor/CloverBootloader#432]
First, congratulations on the excellent work being done...

However, I'm reporting a bug that I found, after the last updates, the video cards are no longer displayed in the menu "options -> Graphics Injector", even though the settings are in the "config.plist".
I'm not sure which version of Clover the bug appeared in, I'm just sure that in version 5133 the video cards were displayed normally.

Congratulations again for the great work....

**Comment by SergeySlice** [comment]
Provide please preboot.log for this situation.
In my case discrete video card is shown correctly. Embedded graphic is not used and not shown.

**Comment by SergeySlice** [comment]
abondoned
