### ISSUE TITLE
Run Windows 11 on unsupported devices.

### ISSUE THREAD

**Issue by modaifallah** [CloverHackyColor/CloverBootloader#435]
If clover could emulate macOS devices and drivers to run MacOS on non Apple devices, now the same can be done for Windows 11.

What about emulating a supported Intel/AMD cpu and a virtual/dummy TPM chip? It will just inject another CPU UUID and also a TPM clover driver can be written easily.

**Comment by LeeBinder** [comment]
Now wouldn't that be juicy 👍

**Comment by LeeBinder** [comment]
@SergeySlice @modaifallah -> https://forums.mydigitallife.net/threads/win-11-boot-and-upgrade-fix-kit-v2-0.83724/ :)

**Comment by SergeySlice** [comment]
If any news then inform me
