### ISSUE TITLE
The clover EFI startup page does not display the hard disk of the system, but only the mobile hard disk. What's the problem.

### ISSUE THREAD

**Issue by boyGdm** [CloverHackyColor/CloverBootloader#440]
There is no system hard disk display

**Comment by SergeySlice** [comment]
debug.log may shed some light on the problem.

**Comment by akisame-reiu** [comment]
did you tick Entries option in GUI section?

**Comment by kushwavez** [comment]
ensure you have these in drivers/UEFI: ApfsDriverLoader.efi, VboxHfsPlus.efi

**Comment by boyGdm** [comment]
Thank you for your answers. The UFI was updated to 5139 to solve the problem.
