### ISSUE TITLE
This is a very dangerous signal

### ISSUE THREAD

**Issue by mjs520** [CloverHackyColor/CloverBootloader#448]
I noticed that OC config is the most recently merged project of clover, and only the miscellaneous items of T2 model are added in it. Why not add a miscellaneous extension in the config.plist option, just like adding a quirk. Clover boot has two files, config.plist and OC plist, which is very chicken and dangerous.

**Comment by SergeySlice** [comment]
Clover has one config.plist.

**Comment by mjs520** [comment]
ok
