### ISSUE TITLE
Documemntation and installation instructions

### ISSUE THREAD

**Issue by BodgeMaster** [CloverHackyColor/CloverBootloader#449]
Before I begin: I am not trying to build a Hackintosh and I use neither Windows nor MacOS. That may be the reason why I couldn’t find anything useful. Maybe, the `.exe` files are self-explanatory or there are some resources in Hackintosh specific forums. If that is the case, I would appreciate it if someone were to point me where I can find more information (or tell me that Windows is absolutely required to set up Clover Bootloader).

I have spent a few hours trying to get Clover Bootloader to work but so far, the only thing that worked for me was burning the ISO to a CD and booting into it that way. That would work for my use case but it is definitely not the preferred option for a permanent solution. My use case is probably one of the weirder ones but I think it should be possible, I just can’t figure out how to do it or even if it is actually really possible because I can’t find any useful documentation. I want to boot with a BIOS-GPT setup to get into UEFI and from there boot into a UEFI OS, preferably all contained on a single drive.

I have looked at the file `Installation.txt` but it seems to either be outdated or missing information (and also Mac specific). I have also tried following [this](https://opensourcelibs.com/lib/cloverefi-4mu) with the release version provided here which also didn’t work. Maybe, that’s because it doesn’t work with the version provided here, Idk. I couldn’t even get far enough to find out if these instruction are for BIOS or UEFI or both (even though I suspect they are for UEFI only) because it broke the FAT on the ESP I created.

Both more documentation and help with my specific use case would be appreciated.

**Comment by BodgeMaster** [comment]
Okay, turns out I am blind and the resource I linked to above actually links to an installer that can be found [here](https://github.com/m13253/clover-linux-installer).

Not sure if I should just close this issue again because the actual issue still persists but my problem is solved.

**Comment by akisame-reiu** [comment]
Actually, Clover now is easy to configure than before, because you only need to focus on Quirks section. Other sections you should make it clean first then add what you need, like DeviceProperties, hotpatch rename, etc...
I made a post about new Clover but it is for Vietnamese person. If you don't mind I can share, you can use Google Translate to translate it.

**Comment by BodgeMaster** [comment]
I am referring to setting it up in the first place. How to put it into the boot sector etc.

**Comment by akisame-reiu** [comment]
just do it like OpenCore. If it runs correctly, in UEFI BIOS, you should create a new boot entry, the path is directly to CLOVERx64.efi (/EFI/CLOVER/CLOVERx64.efi). If your bios doesn't have add new boot entry, but it still has choose entry boot, you can use the app called EasyUEFI, then add it to the boot list in BIOS, move it to the 1st order. Now you can boot into Clover first when power on the machine

**Comment by BodgeMaster** [comment]
Please read my original post again. I don’t have UEFI. That’s why I need clover.

**Comment by SergeySlice** [comment]
Consider to use windows application [Bootdisk Utility](https://www.insanelymac.com/forum/topic/283190-bootdisk-utility/) 
It will create a bootable USB stick with Clover and macOS installation.

**Comment by BodgeMaster** [comment]
> Consider to use windows application [Bootdisk Utility](https://www.insanelymac.com/forum/topic/283190-bootdisk-utility/)
> It will create a bootable USB stick with Clover and macOS installation.

As I said, I am not trying to build a hackintosh. I am trying to make UEFI available on a BIOS system by loading Clover from disk.
I found a tool that allowed me to install Clover from Linux (also mentioned above) which allowed me to boot into Clover and even launch a UEFI shell but that’s about everything that worked.

I will pull another PC off the PC pile and try again when I have the time and write down the steps I took once I get something fully working.

**Comment by SergeySlice** [comment]
I didn't understand if you successfully started Clover what is the issue?
Yes, we have no such enthusiasts who will create such site as Dortania. There are documentation in Russian and several translations to English, for example:
https://sourceforge.net/p/cloverefiboot/wiki/Home/
https://github.com/Drovosek01/CloverBootloader-documentation/
Google may find other sites which I never hear.
