### ISSUE TITLE
12beta 7 installation bug

### ISSUE THREAD

**Issue by mjs520** [CloverHackyColor/CloverBootloader#450]
When will clover fix the unlimited restart problem of 12beta 7 installation? Look forward to clover 5140 update

**Comment by SergeySlice** [comment]
The problem is resolved but not committed yet. Wait please 5140.

**Comment by mjs520** [comment]
Fortunately, thank you

**Comment by alessaba** [comment]
I keep having the same problem when installing beta 7 and 8. Is there some setting i need to enable?
I think i read on OpenCore you have to enable "AdviseFeatures" but there is no such option in Clover, it seems
