### ISSUE TITLE
Windows 11 Support

### ISSUE THREAD

**Issue by DarkPheonix2122** [CloverHackyColor/CloverBootloader#452]
So. I'm updating to windows 11 and this looks like a great way to have all my boots to just one bootloader. so i was wondering if this supports windows 11.

**Comment by SavageAUS** [comment]
Yes. I am booting windows 11, macOS and Linux all with clover on both my non Apple hardware machines.

**Comment by DarkPheonix2122** [comment]
Okay! Thanks for clearing that up!
