### ISSUE TITLE
Release 5139 Kext injection broken

### ISSUE THREAD

**Issue by fbongcam** [CloverHackyColor/CloverBootloader#455]
Release 5139 broke kext injection for me. I upgraded from 5122 so I don't know if this is the specific version that introduced the problem. However, I downgraded back to 5122 and everything worked per usual.

FakeSMC plugins for instance, would refuse to load.

OS: 10.14.6 (Mojave)

**Comment by SergeySlice** [comment]
Show please preboot.log. The injection must work.
