### ISSUE TITLE
r5141 Upgrade did not go Smoothly

### ISSUE THREAD

**Issue by alessaba** [CloverHackyColor/CloverBootloader#459]
Good morning. I updated from the rev2 of 5140 to 5141, using the Clover App. Now when i reboot, this shows up. Can i at least get some guidance on what parameter that’s giving errors? I also updated OpenRuntime.efi just in case.

Thanks in advance

![FC8C88F1-9280-4610-8AD7-214B499EA4D6](https://user-images.githubusercontent.com/2400384/137370807-457e4988-aa0a-4fe5-bf94-2a75e85e498e.jpeg)

**Comment by alessaba** [comment]
what do you mean by adding HWFeature?

**Comment by 5T33Z0** [comment]
> what do you mean by adding HWFeature?

https://www.insanelymac.com/forum/topic/304530-clover-change-explanations/?do=findComment&comment=2768898

**Comment by viniciusmi00** [comment]
I put the HWFeature but to no avail. Same error as the guys above.
Comparing the Sample-Config.plist with the functional config.plist I noticed the following:

![1](https://user-images.githubusercontent.com/14878542/137609492-bbb5f151-6ec0-4f61-a025-0bdc37f255e8.png)

![2](https://user-images.githubusercontent.com/14878542/137609501-af6f14b7-c3b4-4925-b6ef-d11684851336.png)


When there is Memory key with 4 Channel, this error appears.
When I remove the SMBIOS Memory key, my mac always reboots at boot.

**Comment by SergeySlice** [comment]
AFAIK the issue resolved by latest commit?
