### ISSUE TITLE
Resize bar bios option support

### ISSUE THREAD

**Issue by fabiosun** [CloverHackyColor/CloverBootloader#461]
Is it possible to add this feature to Clover?
OpenCore booloader devs have added it from 075 release
If users have Resize bar option flagged in BIOS, Clover hangs in early stage before PCI configuration begin

Thank you

**Comment by fabiosun** [comment]
Do you know new Bios feature (Resize Bar)?
I think you have a lot o f beta testers , no one of them is using this feature?

**Comment by fabiosun** [comment]
However, attached here a Clover Digital Debug log
And also Quirk used in Opencore to have system booting well if you have Resize Bios Option enabled in Bios (motherboard
![Screenshot 2021-10-20 at 09 21 03](https://user-images.githubusercontent.com/6358373/138046541-43cf58e6-f555-4167-b4e4-34a92b5b58ad.png)
)
[2021-10-20_07-16_BOOTX64.EFI.log](https://github.com/CloverHackyColor/CloverBootloader/files/7378994/2021-10-20_07-16_BOOTX64.EFI.log)

**Comment by jief666** [comment]
> OpenCore booloader devs have added it from 075 release

This is no 075 release yet !

Done. Could you test and close this issue if it's ok ?

**Comment by fabiosun** [comment]
Thank for answering!
> > OpenCore booloader devs have added it from 075 release
> 
> This is no 075 release yet !
Opencore master had that feature in that period starting from their 075 named release

> 
> Done. Could you test and close this issue if it's ok ?
Have you added that quirk now?
If you could post a clover test version I could happily try it! :)

Meanwhile I have found a temporary workaround,
it is possible to have Resize Bar option in bios, but we have to disable in it 4G option
both option in Clover release I have tested fails to boot on pci configuration begin stage

**Comment by jief666** [comment]
> Opencore master had that feature in that period starting from their 075 named OpenCore

It's not yet released. Even though they change the version string to 075.

> OpenCore booloader devs have added it from 075 release

The "from" made me think that the release was already done, while it's still in development.

> With both options enabled in BIOS, Clover release...

To test, you have to compile the master branch of Clover. Could you test ? I can't.

**Comment by fabiosun** [comment]
[2021-10-30_14-17_BOOTX64.EFI.log](https://github.com/CloverHackyColor/CloverBootloader/files/7446770/2021-10-30_14-17_BOOTX64.EFI.log)
<img width="614" alt="Screenshot 2021-10-30 at 16 18 48" src="https://user-images.githubusercontent.com/6358373/139536883-9d1166a3-11de-40cd-a1f4-2ce2353b027b.png">
