### ISSUE TITLE
r5141  (710b2dcee to 162150e5b)  rEFIt_UEFI/Settings/ConfigPlist/SMBIOSPlist.h

### ISSUE THREAD

**Issue by matxpa** [CloverHackyColor/CloverBootloader#462]
@jief666 @SergeySlice 
 r5141 (162150e5b)

boot log
...
0:153  0:053  === [ Starting Clover ] =========================
0:153  0:000  Now is 22.10.2021,  12:22:48 (GMT)
0:153  0:000  Starting Clover revision: 5141 (master, commit 162150e5b) on American Megatrends EFI
0:153  0:000  Build id: 20211022094009-162150e-dirty
...
0:154  0:000  === [ GetUserSettings ] =========================
0:156  0:002  Using config.plist at path: \EFI\CLOVER
0:157  0:001  There are problems in plist '\EFI\CLOVER\config.plist'
0:157  0:000  Info: BiosReleaseDate '06/04/2021' is the same as default ('06/04/2021') -> ignored. Dict '/SMBIOS:736'.
0:158  0:000  Info: EfiVersion '422.0.0.0.0' is the same as default ('422.0.0.0.0') -> ignored. Dict '/SMBIOS:736'.
0:158  0:000  Use CloverConfigPlistValidator or look in the log
3:159  3:000  Cannot find smbios.plist at path '\EFI\CLOVER' : Not Found
3:159  0:000  '\EFI\CLOVER\smbios.plist' not loaded. Efi error Not Found
3:159  0:000  Using latest BiosVersion from config instead of default 'MBP102.88Z.F000.B00.2106041717'
3:159  0:000  BiosVersion: MBP102.88Z.F000.B00.2106041717
3:159  0:000  BiosReleaseDate: 06/04/2021
3:159  0:000  EfiVersion: 422.0.0.0.0
...

 Those 3 Key values in config.plist SMBIOS section for ProductName = MacBookPro10,2

        BiosVersion        = MBP102.88Z.F000.B00.2106041717    same as default without Info message and config.plist value kept
        BiosReleaseDate = 06/04/2021                        same as default value but with Info message (...same as default ...-> ignored. Dict...) and config.plist value is overwritten by the default one (which one has same value)
        EfiVersion        = 422.0.0.0.0                             same as default value but with Info message (...same as default ...-> ignored. Dict...) and config.plist value is overwritten by the default one (which one has same value)
 

Different rules between BiosVersion BiosReleaseDate and EfiVersion values check ?
    - BiosVersion     !is2ndBiosVersionGreaterThan1st (Greater or GreaterOrEqual) if Equal config.plist value is kept (ie. no reset)
    - BiosReleaseDate compareReleaseDateResult == 0 (ie. Equal Default value but config.plist value is reset and replaced by the same value, the Default one)
    - EfiVersion        AsciiStrVersionToUint64... == (ie. Equal Default value and config.plist value is NOT reset but replaced by the same value, the Default one)
 
So why a value extracted from config.plist with same content as the default value generates an Info message considered as an Error one (xmlLiteParser->addInfo(generateErrors...) and the Default value overwrites the config.plist value for BiosReleaseDate and EfiVersion even if they have the same content.
This value replacement doesn't happen with BiosVersion for identical values between config.plist value and Default value.

An attached screenshot to show the messages at boot before CloverBootMenu is displayed

Regards

![r5141 CCPV boot message](https://user-images.githubusercontent.com/70573409/138478843-bc2efe9b-665d-4ed0-acb5-3c99c8065e33.jpg)

**Comment by matxpa** [comment]
Fixed

**Comment by jief666** [comment]
> To show an Info as an Error is useless (BiosReleaseDate and EfiVersion when their values are the same as the default values)

Disagree : One took the time to define a value that has no effect, it might be a mistake and it's worth to have it as an info

> reset a good (same as the default one) value is useless

Sure, wasn't obliged to do that....
 
> Line 517 USELESS in the text
> // This is just 'info'. It's useless but fine to define the same as default.

What is useless, is for the user to have taken the time to set that value in his config.plist. Not the code that checks that.

> Line 518 addInfo(generateErrors --> Info or Error ?
> xmlLiteParser->addInfo(generateErrors, S8Printf("BiosReleaseDate '%s' is the same as default ('%s') -> ignored. Dict '%s:%d'.", BiosReleaseDate.value().c_str(), GetReleaseDate(getModel()).c_str(), xmlPath.c_str(), keyPos.getLine())); // Do not set b to false : we don't want to invalidate the whole dict

xmlLiteParser->addInfo : addInfo means info, not error.

> Line 519 Why reset a value even when it's right
> BiosReleaseDate.reset();

The reset has no functional effect. Same as before. Doesn't mean that reporting it as info is useless.

> Line 531 addInfo(generateErrors --> Info or Error ?

addInfo : addInfo means info, not error.

In short : there is the same checks for the 3 vars. A wrong value gives a warning. An equal value gives an info.

 
> Those Info or pseudo-Error Messages are no more shown at screen before BootLoaderMenu is displayed.
> Those Info or pseudo-Error Messages are no more written in boot log.
> This fact since 07b993b commit where you deactivate lines 2768 to 2772 in rEFIt_UEFI/refit/main.ccp this pseudo-Errors are no more visible so it's a visible improvement.

Info are only visible with --info in ccpv

> !is2ndBiosVersionGreaterThan1st : not GT (so LE) but what happens value is Equal

There is an else starting with is2ndBiosVersionEqual(...)

> but I can't find where "is2ndBiosVersionGreaterThan1st" code is defined in CloverBootloader.

is2ndBiosVersionGreaterThan1st is define in platformdata.cpp
