### ISSUE TITLE
Ignoring kextcache invocation from early boot

### ISSUE THREAD

**Issue by artickc** [CloverHackyColor/CloverBootloader#463]
Need a option to disable TRIM like on OpenCore _SetApfsTrimTimeout_
for NVME SSD without trim support, according to this post https://github.com/dortania/bugtracker/issues/192

The boot stuck for 10 seconds with message: 
_Ignoring kextcache invocation from early boot_ because my NVME don't support TRIM

**Comment by SergeySlice** [comment]
Done in release 5142. Test please and report.

**Comment by LeeBinder** [comment]
Do I add it in the quirks section like in OC?

```
<key>Quirks</key>
   <dict>
        <key>SetApfsTrimTimeout</key>
	<integer>4294967295</integer>
   </dict>
```

**Comment by SergeySlice** [comment]
> Do I add it in the quirks section like in OC?
> 
> ```
> <key>Quirks</key>
>    <dict>
>         <key>SetApfsTrimTimeout</key>
> 	<integer>4294967295</integer>
>    </dict>
> ```

No, Clover has no such key. It just disable TrimTimeout as a bad function. See testing results at dortania bug 192.

**Comment by xma** [comment]
Well, in OC it's configurable : user can choose values => likely for a samsung I would like to have 4294967295 (read: trim enabled and big timeout)

looks like in CLOVER it's fixed to '999' by reading sourcecode : https://github.com/CloverHackyColor/OpenCorePkg/blob/f0926840864a5538782e53eae465c3c409dfbb8e/Include/Acidanthera/Library/OcConfigurationLib.h#L281


log on the machine : clover 5142 

$ log show --last boot | grep -A20 "launchd: Doing boot task: bootroot"
2021-11-05 22:16:03.475602+0100 0x1b3      Default     0x0                  1      0    launchd: Doing boot task: bootroot
2021-11-05 22:16:59.384680+0100 0x592      Default     0x0                  0      0    kernel: (apfs) spaceman_scan_free_blocks:3153: disk1 scan took 18446744073709.497498 s, trims took 63.812215 s

**Comment by SergeySlice** [comment]
You are really wait for 18446744073709.497498 s,?

**Comment by xma** [comment]
well:
https://github.com/dortania/bugtracker/issues/192
999 means "minimal timeout, means TRIM is disabled". seems that's you've hardcoded in clover

What does 999 means ?
that looked more like a magic number and not a time value to me

On dortania it's said "minimal timeout" and people provider result based on experiment.

result for example:


SetApfsTrimTimeout | time (s)
-- | --
999 | 44.84                        
-1 | 53.05
4294967295 | 56.26

=> For me I would really like that the trimming phase could complete : and not being aborted at all.

**Comment by SergeySlice** [comment]
Check after loading the OS that the trim is enabled no matter of a bootloader.
