### ISSUE TITLE
Clover 5141 on esxi-7.0U2 Fatal Error - System halted

### ISSUE THREAD

**Issue by kcj83** [CloverHackyColor/CloverBootloader#464]
Getting the following error on 5141 running on ESXi7.0U2 - MAX_RAM_SLOTS value too big. Please see screen shot attached.
![Screenshot 2021-10-26 072527](https://user-images.githubusercontent.com/79729347/138899523-d033ca2f-d271-4f95-b0bb-032750de6791.png)

**Comment by kcj83** [comment]
@SergeySlice is OpenRuntime.efi required, even if i'm running this on virtual (ESXi) host?

**Comment by kcj83** [comment]
@SergeySlice got it to boot and my K5000 is recognized and drivers loaded, but no display output using Lilu/WG. Any thoughts? Working perfectly on 11.6.1 with Kexts in the 'Other' folder.

**Comment by SergeySlice** [comment]
Monterey doesn't work with Nvidia. You have to stay with 11.6.1

**Comment by kcj83** [comment]
@SergeySlice i'm using https://github.com/chris1111/Geforce-Kepler-patcher to re-enable the .bundle drivers and kexts for Nvidia. 

Does this workaround package not work with Monterey?

**Comment by kcj83** [comment]
@SergeySlice The Virtual Chassis is now being seen in Big Sur 11.6.1 with 64 memory slots on r5141. 

Please patch Clover for this accordingly for future releases.

Thanks!

**Comment by SergeySlice** [comment]
What to patch?

**Comment by kcj83** [comment]
64 ram-slot chassis support for ESXi Chassis

**Comment by SergeySlice** [comment]
It is only case breaking all other cases.

**Comment by kcj83** [comment]
@SergeySlice what do you mean Sergey? don't follow you...  We just need the max_available_slots to reflect 64 instead of whatever it is today... 8?

**Comment by kcj83** [comment]
issue is resolved in 5142 - thank you @SergeySlice !!!
