### ISSUE TITLE
12.1 boot bug

### ISSUE THREAD

**Issue by mjs520** [CloverHackyColor/CloverBootloader#468]
Clover boot 12.1 beta 1 card code. System versions before 12.1 can boot. Please solve it
![-275a2042de739bd8](https://user-images.githubusercontent.com/26852845/139418633-9427aa90-f026-4a29-b27d-6d83241fd1d7.jpg)

My configuration is the third generation I3. At present, 12.1 seems to need rdrand support. My I3 doesn't seem to support rdrand. Can you add some parameters or simulate rdrand support? Thank you

**Comment by mjs520** [comment]
> It's impossible to simulate. We have alternatives
> 
> 1. Create some opcode emulator to catch the instruction at CPU interrupt level. For example 	[Opcode Emulator (OPEMU) Plug-in Project](https://www.insanelymac.com/forum/topic/329704-opcode-emulator-opemu-plug-in-project/)
> 2. Patch the kernel and may be kexts and may be frameworks to not use this instruction.
> 3. Not use this new system on such computers.

How to add this kernel under clover, thank you
https://forums.macrumors.com/threads/monterand-probably-the-start-of-an-ongoing-saga.2320479/

**Comment by SergeySlice** [comment]
Please test, KernelToPatch
~~~~
			<dict>
				<key>Comment</key>
				<string>Monterey RDRAND instruction #1</string>
				<key>MatchOS</key>
				<string>12</string>
				<key>Disabled</key>
				<false/>
				<key>Procedure</key>
				<string>_work_interval_port_type_render_server</string>
				<key>RangeFind</key>
				<integer>3900</integer>
				<key>Find</key>
				<data>D8fxc/sh8TnRc/WJyUiLlM3Q/f//</data>
				<key>Replace</key>
				<data>McmQkJAh8TnRc/WJyUiLlM3Q/f//</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Monterey RDRAND instruction #2</string>
				<key>MatchOS</key>
				<string>12</string>
				<key>Disabled</key>
				<false/>
				<key>Procedure</key>
				<string>_panic_with_thread_context</string>
				<key>RangeFind</key>
				<integer>10100</integer>
				<key>Find</key>
				<data>D8fyc/uD4g+D+gd38w+3NEE=</data>
				<key>Replace</key>
				<data>MdKQkJCD4g+D+gd38w+3NEE=</data>
			</dict>

~~~~

**Comment by mjs520** [comment]
> Please test, KernelToPatch
> 
> ```
> 			<dict>
> 				<key>Comment</key>
> 				<string>Monterey RDRAND instruction #1</string>
> 				<key>MatchOS</key>
> 				<string>12</string>
> 				<key>Disabled</key>
> 				<false/>
> 				<key>Procedure</key>
> 				<string>_work_interval_port_type_render_server</string>
> 				<key>RangeFind</key>
> 				<integer>3900</integer>
> 				<key>Find</key>
> 				<data>D8fxc/sh8TnRc/WJyUiLlM3Q/f//</data>
> 				<key>Replace</key>
> 				<data>McmQkJAh8TnRc/WJyUiLlM3Q/f//</data>
> 			</dict>
> 			<dict>
> 				<key>Comment</key>
> 				<string>Monterey RDRAND instruction #2</string>
> 				<key>MatchOS</key>
> 				<string>12</string>
> 				<key>Disabled</key>
> 				<false/>
> 				<key>Procedure</key>
> 				<string>_panic_with_thread_context</string>
> 				<key>RangeFind</key>
> 				<integer>10100</integer>
> 				<key>Find</key>
> 				<data>D8fyc/uD4g+D+gd38w+3NEE=</data>
> 				<key>Replace</key>
> 				<data>MdKQkJCD4g+D+gd38w+3NEE=</data>
> 			</dict>
> ```



> Please test, KernelToPatch
> 
> ```
> 			<dict>
> 				<key>Comment</key>
> 				<string>Monterey RDRAND instruction #1</string>
> 				<key>MatchOS</key>
> 				<string>12</string>
> 				<key>Disabled</key>
> 				<false/>
> 				<key>Procedure</key>
> 				<string>_work_interval_port_type_render_server</string>
> 				<key>RangeFind</key>
> 				<integer>3900</integer>
> 				<key>Find</key>
> 				<data>D8fxc/sh8TnRc/WJyUiLlM3Q/f//</data>
> 				<key>Replace</key>
> 				<data>McmQkJAh8TnRc/WJyUiLlM3Q/f//</data>
> 			</dict>
> 			<dict>
> 				<key>Comment</key>
> 				<string>Monterey RDRAND instruction #2</string>
> 				<key>MatchOS</key>
> 				<string>12</string>
> 				<key>Disabled</key>
> 				<false/>
> 				<key>Procedure</key>
> 				<string>_panic_with_thread_context</string>
> 				<key>RangeFind</key>
> 				<integer>10100</integer>
> 				<key>Find</key>
> 				<data>D8fyc/uD4g+D+gd38w+3NEE=</data>
> 				<key>Replace</key>
> 				<data>MdKQkJCD4g+D+gd38w+3NEE=</data>
> 			</dict>
> ```

thanks

**Comment by mjs520** [comment]
> Please test, KernelToPatch
> 
> ```
> 			<dict>
> 				<key>Comment</key>
> 				<string>Monterey RDRAND instruction #1</string>
> 				<key>MatchOS</key>
> 				<string>12</string>
> 				<key>Disabled</key>
> 				<false/>
> 				<key>Procedure</key>
> 				<string>_work_interval_port_type_render_server</string>
> 				<key>RangeFind</key>
> 				<integer>3900</integer>
> 				<key>Find</key>
> 				<data>D8fxc/sh8TnRc/WJyUiLlM3Q/f//</data>
> 				<key>Replace</key>
> 				<data>McmQkJAh8TnRc/WJyUiLlM3Q/f//</data>
> 			</dict>
> 			<dict>
> 				<key>Comment</key>
> 				<string>Monterey RDRAND instruction #2</string>
> 				<key>MatchOS</key>
> 				<string>12</string>
> 				<key>Disabled</key>
> 				<false/>
> 				<key>Procedure</key>
> 				<string>_panic_with_thread_context</string>
> 				<key>RangeFind</key>
> 				<integer>10100</integer>
> 				<key>Find</key>
> 				<data>D8fyc/uD4g+D+gd38w+3NEE=</data>
> 				<key>Replace</key>
> 				<data>MdKQkJCD4g+D+gd38w+3NEE=</data>
> 			</dict>
> ```

Hello, clover can't seem to work with the patch. Thank you
![Uploading IMG_20211101_104542.jpg…]()

**Comment by mjs520** [comment]
thank
