### ISSUE TITLE
r5141 Can't boot <A fatal error happened. System halted>

### ISSUE THREAD

**Issue by HandaTakuya** [CloverHackyColor/CloverBootloader#469]
error display :
![IMG_0323](https://user-images.githubusercontent.com/47761725/139421103-785420dd-f2af-4ebd-b1c3-9485aed0e78d.jpeg)

Lenovo L340 Gaming Intel i7 9750H Intel UHD 630

**Comment by HandaTakuya** [comment]
> This is wrong config.plist. Show please it.

This >
[config.plist.zip](https://github.com/CloverHackyColor/CloverBootloader/files/7446426/config.plist.zip)

**Comment by SergeySlice** [comment]
Try this version
[config.plist.zip](https://github.com/CloverHackyColor/CloverBootloader/files/7446915/config.plist.zip)

**Comment by HandaTakuya** [comment]
> Try this version
> 
> [config.plist.zip](https://github.com/CloverHackyColor/CloverBootloader/files/7446915/config.plist.zip)
> 
> 
> 
> 

New error ![image](https://user-images.githubusercontent.com/47761725/139549146-959b74be-572a-410a-9862-e7457811066d.jpeg)

**Comment by HandaTakuya** [comment]
> > Try this version
> > [config.plist.zip](https://github.com/CloverHackyColor/CloverBootloader/files/7446915/config.plist.zip)
> 
> New error ![image](https://user-images.githubusercontent.com/47761725/139549146-959b74be-572a-410a-9862-e7457811066d.jpeg)

I Try Install macOS 12 again and use SergeySlice fix config to boot normal. Thank you.
