### ISSUE TITLE
Questions about adding rdrand patch to clover

### ISSUE THREAD

**Issue by mjs520** [CloverHackyColor/CloverBootloader#472]
<dict>
				<key>Comment</key>
				<string>Monterey RDRAND instruction #1</string>
				<key>MatchOS</key>
				<string>12</string>
				<key>Disabled</key>
				<false/>
				<key>Procedure</key>
				<string>_work_interval_port_type_render_server</string>
				<key>RangeFind</key>
				<integer>3900</integer>
				<key>Find</key>
				<data>D8fxc/sh8TnRc/WJyUiLlM3Q/f//</data>
				<key>Replace</key>
				<data>McmQkJAh8TnRc/WJyUiLlM3Q/f//</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Monterey RDRAND instruction #2</string>
				<key>MatchOS</key>
				<string>12</string>
				<key>Disabled</key>
				<false/>
				<key>Procedure</key>
				<string>_panic_with_thread_context</string>
				<key>RangeFind</key>
				<integer>10100</integer>
				<key>Find</key>
				<data>D8fyc/uD4g+D+gd38w+3NEE=</data>
				<key>Replace</key>
				<data>MdKQkJCD4g+D+gd38w+3NEE=</data>
			</dict>

Under the clover kerneltopatch option, adding the above kernel patch does not seem to work.

Does clover lack any dynamic patch support? Thank you

**Comment by mjs520** [comment]
ok

**Comment by mjs520** [comment]
![58cb874ac79d0755](https://user-images.githubusercontent.com/26852845/140257824-ac63c208-f42e-41cb-8d7e-05aaa4c57a1c.png)
My CPU does not support rdrand

**Comment by SergeySlice** [comment]
Users confirmed the patch working.

**Comment by mjs520** [comment]
> Users confirmed the patch working.

At present, the feedback seems to be from OC users. Clover didn't find it successful. Thank you

**Comment by mjs520** [comment]
![3fdf325d9bfe6644](https://user-images.githubusercontent.com/26852845/141109025-9038f90c-7016-45a4-afd9-558ff77bfbc5.jpg)
The rdrand restriction was removed from 12.1 beta 2

**Comment by mjs520** [comment]
thanks
