### ISSUE TITLE
Clover R5142 and lower (multiple config error)

### ISSUE THREAD

**Issue by fabiosun** [CloverHackyColor/CloverBootloader#476]
<img width="922" alt="Screenshot 2021-11-26 at 8 14 48 AM" src="https://user-images.githubusercontent.com/6358373/143541646-d9d8bfba-8bfc-4051-84ba-db43360b62b3.png">
Only changing config.plist in bootmenu outputs this warning (System boots fine the same)

Config.plist and config_1.plist are the same (if different same problem)
[Archive.zip](https://github.com/CloverHackyColor/CloverBootloader/files/7606959/Archive.zip)

**Comment by SergeySlice** [comment]
Resolved by last commit.

**Comment by fabiosun** [comment]
Thank you!
