### ISSUE TITLE
Clover 5142 Monterey 12.1 beta 3 (Black screen in login page)

### ISSUE THREAD

**Issue by fabiosun** [CloverHackyColor/CloverBootloader#477]
Monterey 12.01 is perfectly booting
Monterey 12.1 beta 3 no, black screen (system is there but no signal on display)
Same attached EFI
[EFI.zip](https://github.com/CloverHackyColor/CloverBootloader/files/7606965/EFI.zip)

Logs:
[2021-11-26_06-57_BOOTX64.EFI.log](https://github.com/CloverHackyColor/CloverBootloader/files/7606966/2021-11-26_06-57_BOOTX64.EFI.log)
[2021-11-26_06-58_BOOTX64.EFI.log](https://github.com/CloverHackyColor/CloverBootloader/files/7606967/2021-11-26_06-58_BOOTX64.EFI.log)

**Comment by SergeySlice** [comment]
Monterey 12.1 beta 3 booted fine
![Screenshot 2021-11-28 at 13 03 31](https://user-images.githubusercontent.com/485515/143763570-649c6bd6-11c0-4f40-aba8-eafa2a17ad16.png)
.
Your system is Ryzen, so ask Shunny for a set of Ryzen patches for the new system. It is not Clover issue.

**Comment by fabiosun** [comment]
@SergeySlice 
It is not a Ryzen problem
Same patches work in Opencore
And your boot loader I think "fails" in 12.1 in New ResizeBar quirk!
I am one of the maintainer of AMD clover patches..so I have to ask to you :)

**Comment by fabiosun** [comment]
I would like to explain better
And kernel patches are the same for Monterey 12.01 and latest 12.1 betas...

**Comment by Shaneee** [comment]
> Monterey 12.1 beta 3 booted fine
> ![Screenshot 2021-11-28 at 13 03 31](https://user-images.githubusercontent.com/485515/143763570-649c6bd6-11c0-4f40-aba8-eafa2a17ad16.png)
> .
> Your system is Ryzen, so ask Shunny for a set of Ryzen patches for the new system. It is not Clover issue.

Patches are fine. They are applied from Clover without issue but still black screen. Same patch set works without issues in OpenCore.

**Comment by fabiosun** [comment]
![Screenshot 2021-11-28 at 2 49 22 PM](https://user-images.githubusercontent.com/6358373/143770787-66214800-f544-4b32-b727-b1c7f32614c5.png)
problem solved!
