### ISSUE TITLE
ACPI Exception Errors on Intel ci7-11800H Laptop

### ISSUE THREAD

**Issue by kcj83** [CloverHackyColor/CloverBootloader#479]
Trying to get Clover latest release to boot Monterey 12.0.1 on my tiger-lake based laptop, it gets about half way and hangs mid-boot with the errors attached.

Can someone assist me in diagnosing or steps to resolve this issue? I'm sure this has been seen before by the community, but first time i have seen it personally.

Thank you!!
![acpi issue Screenshot 2021-12-02 124103](https://user-images.githubusercontent.com/79729347/144499976-ecabbf35-bd5f-4034-b37f-2c4e0a59e3a0.png)

**Comment by SergeySlice** [comment]
ACPI errors looked like user error. We can't say something not seeing your config.plist and set of ACPI additional tables.
The stop may be inited by wrong config or by some other error which I can't predict having no informations.
This is not a Clover issue.
