### ISSUE TITLE
RDRAND not patching so can't update to 12.1

### ISSUE THREAD

**Issue by urrickhunt** [CloverHackyColor/CloverBootloader#483]
![Screen Shot 2021-12-17 at 5 13 11 PM](https://user-images.githubusercontent.com/96319944/146618563-ffa01c8d-3d9f-4698-97e1-120a2cffa8dd.png)

**Comment by SergeySlice** [comment]
And what is MatchBuild in your config?

**Comment by urrickhunt** [comment]
![Screen Shot 2021-12-20 at 12 11 59 PM](https://user-images.githubusercontent.com/96319944/146813443-e3256810-7972-4f87-9109-f14927b196ed.png)
i believe that fixed it thank you

**Comment by SergeySlice** [comment]
It is a bug that MatchBuild is not working by default. Thank you for finding.

**Comment by SergeySlice** [comment]
Resolved
