### ISSUE TITLE
5143 .ISO does not boot with or without boot6 upd - how to regen Bootable CD/DVD (Linux cmdline for generating proper .ISO)

### ISSUE THREAD

**Issue by succeedmr123** [CloverHackyColor/CloverBootloader#495]
BUG: 5143 .ISO does not boot with or without boot6 upd, is flat out defective product.

Next step/Question: how to regen Bootable CD/DVD (Linux cmdline for generating proper .ISO)?

What was done for now  (reproducibility);

Tried just burning 5143 and booting - stalls after cdboot: done6 msg
(DIAG: as cdboot undeniably booted the DVD , stall is further down the chain)

Extracted .ISO to HDD, replaced boot6, tried to make bootable CD

Req:
if this all is done in Linux, it would be beneficial just to state the correct commandline to generate Bootable .ISO properly in any of the standard tools like xorriso, mkisofs, genisoimage

Pointing the source and howto use cases of applying various bootloaders under /usr/standalone/i386/ would benefit contributors and devs helping the project tremendously as well

Thanks a bunch!

**Comment by SergeySlice** [comment]
Yes, this is a bug of 5143. Use 5142 or wait for 5144.
