### ISSUE TITLE
Monterey 12.2 - Clover Bootloader v5144 - Required firmware update could not be installed.

### ISSUE THREAD

**Issue by SeanBlahovici** [CloverHackyColor/CloverBootloader#497]
Hello, first off I am not entirely sure this belongs here. Apologies if this has nothing to do with the Clover Bootloader.

So I tried doing a fresh install using a stable EFI (Tested on Mojave with updated drivers and kexts), but I am running into an issue during the installation of Monterey 12.2.

I tried following the steps here for people using Clover:
https://www.tonymacx86.com/threads/a-required-firmware-update-could-not-be-installed.316570/

But mostly the issue was apparently about AdviseFeatures not being enabled. I saw that AdviseFeatures appended the an "8" to ExtendedFirmwareFeatures and ExtendedFirmwareFeaturesMask in the config.plist/smbios.

However, I noticed that refreshing the firmware on my smbios added these ExtendedFirmwareFeatures with the bit correctly appended.

This is the relevant part of my plist:
    
```
        <key>ExtendedFirmwareFeatures</key>
        <string>0x8FD0FF576</string>
        <key>ExtendedFirmwareFeaturesMask</key>
        <string>0x8FF1FFF3F</string>
        <key>FirmwareFeatures</key>
        <string>0xFD0FF576</string>
        <key>FirmwareFeaturesMask</key>
        <string>0xFF1FFF3F</string>
```

However no matter what I try, I still get the message
A required firmware update could not be installed

One thing I didn't mention is the way I am installing a fresh macos installation:

1. I Cloned my current stable macOS Mojave installation on an external SSD (with my stable EFI).
2. I booted from the external ssd after disabling my Mojave disk in the BIOS.
3. It booted correctly. I then installed the latest bootloader, updated the drivers (verified they were updated), updated all kexts via Clover Configurator (and the updated 3rd party kexts I could find on the web)
4. I updated the SMBios firmware.
5. Now I disconnected the external SSD, booted from my main Mojave disk, and downloaded the macOS installer (vanilla installation). I then plugged in, backed up the updated EFI and formatted the external drive to Macos Extended Journaled = GUID. Then, with the installer, I pushed the installation to the external ssd. 
6. Before rebooting, I mounted the efi partition of the external ssd and copied the updated EFI there. I then rebooted, disconnected my Mojave drive in BIOS, rebooted and loaded the Clover Bootloader (from external ssd)
7. In the Clover bootloader boot screen, I verified the version (5144), I also pressed F11 to clear VRAM, rebooted one last time, then booted from the external ssd with the install media and updated EFI. 
8. After one reboot, the Apple loading screen shows up and then I get The required firmware could not be installed message.

Thanks again for any help provided!

**Comment by SergeySlice** [comment]
The issue looks like you have wrong ExtendedFirmwareFeatures but you shown right value. May be your working config.plist is not same as you look?

**Comment by SergeySlice** [comment]
No answer. Seems to be resolved.
