### ISSUE TITLE
Monterey 12.2 update does not appear for Macmini8,1 (T2) model

### ISSUE THREAD

**Issue by kiryanov** [CloverHackyColor/CloverBootloader#498]
Macmini8,1 seems to be a model with T2 chip, which requires SecureBootModel set to "Default" as per this document:

https://dortania-github-io.thrrip.space/OpenCore-Install-Guide/extras/monterey.html#ota-updates

However in Clover this value seems to be hardcoded as "Disabled". It would be great if Clover allowed to override this.
PS: I realize that moving from Macmini8,1 to iMacX without T2 would've solved the issue but I cannot simply do this without being either locked out from imessage or regenerating the whole smbios completely and losing local configuration.

**Comment by SergeySlice** [comment]
Not a problem. T2 chip model doesn't require SecureBootModel whatever dortania may say.
~~~~
	<key>RtVariables</key>
	<dict>
		<key>HWTarget</key>
		<string>J174AP</string>

~~~~
And see new commit where the value will be default.
