### ISSUE TITLE
cant get system updates

### ISSUE THREAD

**Issue by taqieallah** [CloverHackyColor/CloverBootloader#504]
hi .. why i cant get any system update on my lover efi while oc working good ? i enabled sip to no action happend

**Comment by SergeySlice** [comment]
It depends on SMBIOS model and HWTarget.
But Clover new version does this automatically. Check if you have latest version.

**Comment by taqieallah** [comment]
Which version ? im using mbp 16.4 as i have 10750h processor ... and version 5144 doesnt do it

**Comment by SergeySlice** [comment]
Latest version is 5145.
What do you have in
~~~~
        <key>RtVariables</key>
        <dict>
            <key>HWTarget</key>
            <string>
~~~~
?
If you have no such key then Clover will automatically set J215AP
As well SIP you said enabled. Good.

**Comment by SergeySlice** [comment]
Abandoned == resolved
