### ISSUE TITLE
Clover doesn't load themes

### ISSUE THREAD

**Issue by AudioPC** [CloverHackyColor/CloverBootloader#516]
Clover Release 5146, no theme is loaded. All volumes, tools, etc. icons are represented with a "broken picture" icon. Using EFI installation with correct folder structure, operating system is macOS Catalina 10.5.7

[Clover Boot Log.txt](https://github.com/CloverHackyColor/CloverBootloader/files/8838333/Clover.Boot.Log.txt)
![screenshot](https://user-images.githubusercontent.com/106882613/172018387-169deebd-e2a0-4026-98dd-a87e0e1fc707.png)

**Comment by SergeySlice** [comment]
As far as I understand you are trying to load theme with name "default". Looks like it is absent. Change to "embedded".
