### ISSUE TITLE
Problems related to MacOS Ventura under Ivy Bridge systems

### ISSUE THREAD

**Issue by mjs520** [CloverHackyColor/CloverBootloader#518]
AvoidRuntimeDefrag is a must to boot Ivy Bridge systems. 
How to solve, do not close the AvoidRuntimeDefrag button install MacOS Ventura, thank you.

**Comment by SergeySlice** [comment]
Test please recent codes.

**Comment by mjs520** [comment]
> > AvoidRuntimeDefrag is a must to boot Ivy Bridge systems.
> > How to solve, do not close the AvoidRuntimeDefrag button install MacOS Ventura, thank you.
> 
> Were you able to install it on Ivy Bridge? I have a 3930K, when I enter the system after all the installation steps, when the system is loading the computer is restarting. Not complete to enter in system in first time. Are you having the same problem?

Please refer to this article：https://www.insanelymac.com/forum/topic/351969-pre-release-macos-ventura/page/50/

**Comment by SergeySlice** [comment]
Check release 5147.

**Comment by SergeySlice** [comment]
It works.
