### ISSUE TITLE
Ventura stuck at NVMe?

### ISSUE THREAD

**Issue by alessaba** [CloverHackyColor/CloverBootloader#521]
Hi,
I know this is not really a support page, but I tried to update Monterey to Ventura using the latest build, and the installation indeed went ahead. (before it would just reboot loop at the first update reboot)

The problem I am finding, though, is that at the third (I believe that's the final reboot, at the end of which you have access to the system) reboot, it got stuck, I think at the NVMe step of the boot. I remember reading somewhere that Ventura got a new NVMe driver or something like that, but I can't find that information anymore. Did somebody have the same problem or knows a solution, perhaps?

I am using the latest Lilu, Whatevergreen kexts, am on Coffee Lake (8700k)

UPDATE: I tried installing on a external SSD and booting from there, and now instead oof hanging at NVMe steps, it panics:

`panic(cpu 2 caller 0xffffff80062ebd02): "could not authenticate personalized root hash! (0, 0)\n" @apfs_vfsops.c:538
Panicked task 0xffffff902923a9c8: 1 threads: pid 1: launchd
Backtrace (CPU 2), panicked thread: 0xffffff9028b2d590, Frame : Return Address
0xffffffd5efefb3c0 : 0xffffff800312489d 
0xffffffd5efefb410 : 0xffffff8003298d36 
0xffffffd5efefb450 : 0xffffff8003287fc0 
0xffffffd5efefb4a0 : 0xffffff80030bf951 
0xffffffd5efefb4c0 : 0xffffff8003124b7d 
0xffffffd5efefb5b0 : 0xffffff8003124229 
0xffffffd5efefb610 : 0xffffff800391603b 
0xffffffd5efefb700 : 0xffffff80062ebd02 
0xffffffd5efefb730 : 0xffffff800630776e 
0xffffffd5efefb910 : 0xffffff8003352e1d 
0xffffffd5efefb960 : 0xffffff8003326f7b 
0xffffffd5efefbf40 : 0xffffff800378e93b 
0xffffffd5efefbfa0 : 0xffffff80030bfd96 
      Kernel Extensions in backtrace:
         com.apple.filesystems.apfs(2138.0)[FC309478-F566-38EC-AC9C-F0643A11DB67]@0xffffff8006254000->0xffffff80063e0fff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[00733D40-D81A-36A3-BBFA-EB9DCCB0EF9F]@0xffffff80045a9000->0xffffff80045b2fff
            dependency: com.apple.driver.AppleEffaceableStorage(1.0)[C13A899D-AB07-3E38-9EA7-DDCD4E8A2C71]@0xffffff80045bf000->0xffffff80045c4fff
            dependency: com.apple.iokit.CoreAnalyticsFamily(1)[BFD75EEC-7361-3AE7-9F1F-E48DCD76ADC4]@0xffffff8004afa000->0xffffff8004b03fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[6310B184-A516-36DE-957C-AA4548D2B811]@0xffffff8005d45000->0xffffff8005d5bfff
            dependency: com.apple.kec.corecrypto(12.0)[17D6AB8F-6D4A-3B8A-8452-F01D0BBE162A]@0xffffff8006425000->0xffffff80064a7fff
            dependency: com.apple.security.AppleImage4(5.0.0)[5D31965D-6D6B-34AB-A46A-FD3BB13547D1]@0xffffff800464a000->0xffffff8004667fff

Process name corresponding to current thread (0xffffff9028b2d590): launchd
Boot args: dart=0 igfxonln=1 -igfxblr -v debug=0x100 -disablegfxfirmware alcid=1 

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 22.0.0: Thu Jun 16 20:32:32 PDT 2022; root:xnu-8792.0.92.121.3~2/RELEASE_X86_64
Kernel UUID: 25104E73-60D9-397D-85D4-F22256A4ED0E
roots installed: 0
KernelCache slide: 0x0000000002e00000
KernelCache base:  0xffffff8003000000
Kernel slide:      0x0000000002e10000
Kernel text base:  0xffffff8003010000
__HIB  text base: 0xffffff8002f00000
System model name: Macmini8,1 (Mac-7BA5B2DFE22CDD8C)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization
Hibernation exit count: 0

System uptime in nanoseconds: 6028495054
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000001688ed3d3
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000001449b52d78 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff8027212000 - 0xffffffa027212000
  . PGZ   : 0xffffff8027212000 - 0xffffff802b213000
  . VM    : 0xffffff802b213000 - 0xffffff84f7546000
  . RO    : 0xffffff84f7546000 - 0xffffff8690bac000
  . GEN0  : 0xffffff8690bac000 - 0xffffff8b5cedf000
  . GEN1  : 0xffffff8b5cedf000 - 0xffffff9029212000
  . GEN2  : 0xffffff9029212000 - 0xffffff94f5545000
  . GEN3  : 0xffffff94f5545000 - 0xffffff99c1878000
  . DATA  : 0xffffff99c1878000 - 0xffffffa027212000
  Metadata: 0xffffffc08bb64000 - 0xffffffc0abb64000
  Bitmaps : 0xffffffc0abb64000 - 0xffffffc0b7b64000

last started kext at 5221879245: |IOAHCIBlock!S	343 (addr 0xffffff80057c0000, size 94208)
loaded kexts:
org.hwsensors.driver.LPCSensors	1800
com.insanelymac.RealtekRTL8111	2.4.2
org.hwsensors.driver.ACPISensors	1800
org.hwsensors.driver.SMMSensors	1800
org.hwsensors.driver.CPUSensors	1800
org.acidanthera.NVMeFix	1.1.0
as.vit9696.!AALC	1.7.2
as.vit9696.WhateverGreen	1.6.0
as.vit9696.Lilu	1.6.1
org.netkas.driver.FakeSMC	1800
>!UODD	546
|SCSITaskUserClient	476
>AirPort.BrcmNIC	1400.1.1
>!AAHCIPort	361
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.lifs	1
@filesystems.apfs	2138.0.0
@filesystems.hfs.kext	606
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@private.KextAudit	1.0
>!ARTC	2.0.1
>!AACPIButtons	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AUserConsent	1
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	402
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@Dont_Steal_Mac_OS_X	7.0.0
@kec.Compression	1
@kec.!AEncryptedArchive	1
|IOAHCIBlock!S	343
>usb.!UHub	1.2
>!AXsanScheme	3
|IOSCSIMultimediaCommandsDevice	476
|IOBD!S!F	1.8
|IODVD!S!F	1.8
|IOCD!S!F	1.8
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IO80211!FLegacy	1200.12.2b1
>corecapture	1.0.4
|IONVMe!F	2.1.0
|IOAHCI!F	301
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!ABSDKextStarter	3
|IOSurface	330
@filesystems.hfs.encodings.kext	1
>!ASyntheticGame!C	10.1.30
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
|IOHID!F	2.0.0
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOTimeSync!F	1100.34
|IOSkywalk!F	1.0
>mDNSOffloadUserClient	1.0.1b8
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	9.0.0
|IOReport!F	47
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	546
|IOUSBMass!SDriver	229
|IOSCSIBlockCommandsDevice	476
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	476
>!AMobileFileIntegrity	1.0.5
$!AImage4	5.0.0
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
|CoreAnalytics!F	1
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	12.0`

**Comment by SergeySlice** [comment]
I also encounter such panic and not resolve the origin of the problem.
But I resolved this by changing SMBIOS to model iMac17,1. The last installation stage was continued.
Try and report.

**Comment by alessaba** [comment]
I can't get the disk to boot with that SMBIOS, it just reboots as soon as i press the boot entry
using iMac19,2 shows a slightly different result. I think the problem is related to the new "Cryptex" disk feature, and the panic when using iMac19,2 is caused by libsystemb.dylib, which libignition can't apparrently find. 

![IMG_9018 Grande](https://user-images.githubusercontent.com/2400384/175810020-7028f8be-a783-4b2a-b306-f3300c3b1c46.png)

**Comment by SergeySlice** [comment]
Check release 5147

**Comment by alessaba** [comment]
The external SSD now boots, great!
I am going to try redoing the upgrade procedure on the internal NVMe, since there it got stuck but not panicked
