### ISSUE TITLE
Wrong CPU core and threads number

### ISSUE THREAD

**Issue by bili-360nemz** [CloverHackyColor/CloverBootloader#522]
Hello Clover Bootloader developers, 
I run Clover Bootloader on my Dell Vostro 230 PC, and the CPU is Intel Pentium E5400, it has 2 cores and 2 threads ,but CPU tuning page said my CPU has 4 cores and 4 threads.It's wrong.
Please fix it!
![IMG_20220623_194530](https://user-images.githubusercontent.com/67849417/175519421-371f557c-d2bb-4f33-89b3-82cca3e99139.jpg)

**Comment by SergeySlice** [comment]
Provide please preboot.log obtained by F2.

**Comment by SergeySlice** [comment]
abandoned
