### ISSUE TITLE
Clover 5147 - Boot chime does not work

### ISSUE THREAD

**Issue by najeebanwer** [CloverHackyColor/CloverBootloader#524]
The boot chime for Clover works in version 5146. After upgrading to version 5147 it not longer works.
The options menu in version 5147 shows that no audio devices are recognized by the bootloader.

**Comment by phoenixbk** [comment]
Me too :((((

**Comment by SergeySlice** [comment]
Check 5148. The issue resolved.

**Comment by najeebanwer** [comment]
Yes, it is fixed in r5148. Thanks.
