### ISSUE TITLE
Clover 5147, 5148 NO Ventura Beta 3 update

### ISSUE THREAD

**Issue by HandaTakuya** [CloverHackyColor/CloverBootloader#526]
I currently in use macOS Ventura Dev Beta 2 and I check for update Dev Beta 3 ... BUT no update.
If it is Open Core : check Secure Boot Model
For Clover ... How to fix ?

![Screenshot 2565-07-11 at 00 19 41](https://user-images.githubusercontent.com/47761725/178155403-ff66bc03-8c5d-4f9c-8f7c-34825c6f509f.png)

**Comment by SergeySlice** [comment]
What is your SMBIOS model?

**Comment by HandaTakuya** [comment]
> What is your SMBIOS model?

MacBook Pro 16,1 and I Try iMac17,1 but not boot

**Comment by jief666** [comment]
Do you still need this issue ?

**Comment by dateno1** [comment]
No update on Ventura is not clover's problem (OC is same result)

It bug on MacOSX

Some of Intel Mac has problem

**Comment by jief666** [comment]
Ok. Closing.

**Comment by dateno1** [comment]
Add RestrictEvents.kext and Boot-Args - revpatch=sbvmm

Plese test it (It maybe fix problem)
