### ISSUE TITLE
install err

### ISSUE THREAD

**Issue by Vsion** [CloverHackyColor/CloverBootloader#53]
![QQ20191212-015115](https://user-images.githubusercontent.com/11804448/70701921-0f863000-1c82-11ea-9cda-6f6e42bbda4f.png)
![76C97866-D7E1-4B2E-838D-CAAD8D2D3C55](https://user-images.githubusercontent.com/11804448/70701924-10b75d00-1c82-11ea-8830-e54355971613.png)
![image](https://user-images.githubusercontent.com/11804448/70702003-30e71c00-1c82-11ea-81a1-643fd77bad87.png)

**Comment by SergeySlice** [comment]
Use Clover.app instead.
