### ISSUE TITLE
WIKI: Tables are not formatted correctly

### ISSUE THREAD

**Issue by 5T33Z0** [CloverHackyColor/CloverBootloader#530]
**Examples**:

https://github.com/CloverHackyColor/CloverBootloader/wiki/Configuration#ig-platform-id
https://github.com/CloverHackyColor/CloverBootloader/wiki/Configuration#smartups
https://github.com/CloverHackyColor/CloverBootloader/wiki/Configuration#fbname
https://github.com/CloverHackyColor/CloverBootloader/wiki/Configuration#chassistype

**Comment by SergeySlice** [comment]
Mostly fixed.
Look please any else formatting mistakes.

**Comment by 5T33Z0** [comment]
All fixed. 

A small suggestion:  I wouldn't put tables in fenced code, otherwise they are not formatted correctly. Instead, I would format them like this:

```
Value |  Type  | Power Supply Type
------|------- | ----------------- 
1   |  Desktop  | AC 
2  |  Mobile   | Battery 
3  | Server    | SmartUPS
```

Which results in a nice Table:

Value |  Type  | Power Supply Type
------|------- | ----------------- 
1  |  Desktop  | AC 
2  |   Mobile   | Battery 
3  | Server   | SmartUPS
