### ISSUE TITLE
Add support for patching or replacing DSDT when loading Linux (or chainloading other bootloader)

### ISSUE THREAD

**Issue by arbv** [CloverHackyColor/CloverBootloader#531]
I have been trying to load a patched DSDT table via Clover and then chainload systemd-boot to make Linux detect a piece of hardware. However, the patched DSDT.aml (`\EFI\Clover\ACPI\patched\DSDT.aml` on the EFI system partition `HP_TOOLS`) appears being ignored by Clover. What am I doing wrong? And is what I am trying to do is achievable with Clover at all? (using Clover mostly as an ACPI patcher for Linux)

```
<dict>
	<key>ACPI</key>
	<dict>
		<key>DSDT</key>
		<dict>
		<key>DropOEM_DSM</key>
		<false/>
		</dict>
	</dict>
	<key>Boot</key>
	<dict>
		<key>Debug</key>
		<false/>
		<key>DefaultVolume</key>
		<string>HP_TOOLS</string>
		<key>DefaultLoader</key>
		<string>\EFI\archlinux\systemd-boot\systemd-bootx64.efi</string>
		<key>Fast</key>
		<false/>
		<key>Timeout</key>
		<integer>5</integer>
	</dict>
	<key>GUI</key>
	<dict>
		<key>Custom</key>
		<dict>
			<key>Entries</key>
			<array>
				<dict>
					<key>Hidden</key>
					<false/>
					<key>Disabled</key>
					<false/>
					<key>Image</key>
					<string>os_arch</string>
					<key>Volume</key>
					<string>HP_TOOLS</string>
					<key>Path</key>
					<string>\EFI\archlinux\systemd-boot\systemd-bootx64.efi</string>
					<key>Title</key>
					<string>Arch Linux</string>
					<key>Type</key>
					<string>Linux</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
````

I have tried to do the same by placing an updated DSDT inside initramfs, but it works only until hibernation attempt.

**Comment by SergeySlice** [comment]
No. There is a policy that Clover will patch DSDT only for macOS and keep it untouched for Linux and Windows.
You have two way:
1. Make patched DSDT by Clover, press F5, take it from EFI/CLOVER/ACPI/origin/. Then you can apply it to Linux by some procedure unknown for me.
2. Take Clover sources and modify them to apply patched DSDT for otherOS. Some programmer ability needed.

**Comment by arbv** [comment]
Oh, that is unfortunate to hear. I hope that you might consider adding an option to support ACPI patching for non macOS as well. You see, there are computers that might benefit from patching ACPI for Linux, e.g. to enable sleep modes, disabled by manufacturer or, like me, to enable a device otherwise not accessible from Linux. Your bootloader already has an extensive and very established framework for exactly that.

Regarding dumping/modifying/applying a patched DSDT - Linux does provide an ability to load a modified DSDT stored in initramfs. The problem is that when this method is used, the modified DSDT will not survive hibernation, as the kernel performs DSDT patching during early stages of the boot. As you can imagine, it causes many sorts of trouble (e.g. the most visible problem on mine is that I cannot see battery status after resumption). That problem could have been solved if the bootloader does manipulations on ACPI tables, before the OS is started or resumed from hibernation.

So, as you can see, there is a need for extensive ACPI manipulation outside the scope of booting macOS on non-Apple computers. I hope that you might consider to make Clover fill this important niche.

**Comment by SergeySlice** [comment]
It is not an issue. It is a request for new bootloader.
