### ISSUE TITLE
Can't boot on disk connected to usb3 extension card, XhciDxfe.efi driver not working

### ISSUE THREAD

**Issue by vinceFR7528** [CloverHackyColor/CloverBootloader#536]
Hi,

My old GA-E7AUM-DS2H BIOS mobo has only USB2 and when it boots on a USB live disk it uses the fullspeed 12Mb (not Hi-Speed, strange?) so booting a linux ISO takes a long long time. I added a PCIe USB3 extension card, this card is seen by the bios but not used so the disk connected to it is not seen from the boot loader. I installed CLOVER 5148 and tried to load the XhciDxfe.efi driver, but it doesn't work as CLOVER doesn't detect the usb disk.

My PCIe USB3 extension card is compliant with USB standard, so no specific driver is needed, chipset Renesas µPD720201.

**Comment by SergeySlice** [comment]
The question requires debugging which can be provide by the controller owner.

**Comment by vinceFR7528** [comment]
ok, how can I do debbugging?

**Comment by SergeySlice** [comment]
Compile your own version of XhciDxe with additional DEBUG() at every line you want to see. 
Then dlete these lines and add new lines. Try again.
Again and again until the problem will be localized.

**Comment by SergeySlice** [comment]
See Release 5151, may be it helps.

**Comment by SergeySlice** [comment]
abandoned
