### ISSUE TITLE
In does not support N card installed

### ISSUE THREAD

**Issue by jackacc** [CloverHackyColor/CloverBootloader#537]
Clover patch installation NVIDIA GeForce CARDS, the SIP testing banned AMFI, disable Metal and open NVIDIA GeForce CARDS the Arguments added
（Geforce-Kepler-patcher  ） ，（ Opencore-Legacy-Patcher ）
		<key>CsrActiveConfig</key>
		<string>0xFEF</string>
		<key>Arguments</key>		
<string>amfi_get_out_of_my_way=0x1 ngfxcompat=1 ngfxgl=1 nvda_drv_vrl=1</string>

There is no effect

Opencore boot - args added 
csr-active-config FF0F0000
                    <key>boot-args</key>
                    <string>amfi_get_out_of_my_way=0x1 ngfxcompat=1 ngfxgl=1 nvda_drv_vrl=1</string>
successful

**Comment by SergeySlice** [comment]
Give me a link what are you trying to do. What is "N CARDS"?

**Comment by jackacc** [comment]
> 给我一个链接你想做什么。什么是“N卡”？

NVIDIA GeForce GT220M， 320M， 8500GT，8600GT，9500GT，9600GT，GT210,GT220，GT240 
Geforce-Kepler-patcher 与Opencore-Legacy-Patcher打补丁

**Comment by SergeySlice** [comment]
https://github.com/chris1111/Geforce-Kepler-patcher

**Comment by SergeySlice** [comment]
It is for Clover.

**Comment by SergeySlice** [comment]
> > 给我一个链接你想做什么。什么是“N卡”？
Is it Chinese? I can't even translate.

**Comment by jackacc** [comment]
> > > 什么是“N卡”？
> > > 是中文的吗？我连翻译都不会。

你会中文，我就不用工具翻译英文了
![20220821235456417](https://user-images.githubusercontent.com/43131867/185800341-2da03b5a-25f2-4fe9-adf8-ad0a6cc817ee.jpg)

禁用AMFI在clover怎么做呢？上面图是opencore设置
![20220821235428672](https://user-images.githubusercontent.com/43131867/185800414-1bca5476-79f7-4d7b-9051-209162d6fdf9.jpg)
不禁用AMFI上图按钮灰色无法安装显卡驱动补丁

**Comment by SergeySlice** [comment]
Again, do not write in chinese.

**Comment by jackacc** [comment]
> Again, do not write in chinese.

My notebook is a generation of motherboard without nvram hardware, a BBS someone reply me using nvram. The plist to launch parameters inside, he said that the Arguments does not support long code amfi_get_out_of_my_way = 0 x1 beyond number
