### ISSUE TITLE
N clover - Patcher gray can't patch card driver

### ISSUE THREAD

**Issue by jackacc** [CloverHackyColor/CloverBootloader#538]
![360截图20220817012615470](https://user-images.githubusercontent.com/43131867/185220124-27918b9b-c1c8-4474-834e-b0b092a26cf8.jpg)

Enter in the boot parameters  （amfi_get_out_of_my_way=0x1 ngfxcompat=1 ngfxgl=1 nvda_drv_vrl=1）They are testing banned AMFI, disable Metal and open N card，There is need to write in the csr-active-config FF0F0000 to disable the SIP

OpenCore- Misc-Security-SecureBootModel:Disabled
![360截图20220818025709078](https://user-images.githubusercontent.com/43131867/185220606-3f47a19b-78e8-45d6-9f9b-76108c6dc1f4.jpg)

clover SecureBootModel?

**Comment by SergeySlice** [comment]
I can't read chinese. Make the screenshot with english interface,

**Comment by jackacc** [comment]
> 我看不懂中文。用英文界面制作截图，
OpenCore- Misc-Security-SecureBootModel:Disabled
![20220821235428672](https://user-images.githubusercontent.com/43131867/185799745-d9a2a148-69cb-47d5-934c-28baa69915e0.jpg)
![20220821235456417](https://user-images.githubusercontent.com/43131867/185799748-7132dcac-eb46-4b3b-a54b-674f1d01d39f.jpg)

Where is the clover options?

**Comment by SergeySlice** [comment]
The secure boot model in Clover is always "disable".

**Comment by jackacc** [comment]
> The secure boot model in Clover is always "disable".
My notebook is a generation of motherboard without nvram hardware, a BBS someone reply me using nvram. The plist to launch parameters inside, he said that the Arguments does not support long code amfi_get_out_of_my_way = 0 x1 beyond number
