### ISSUE TITLE
English translation for this precious guide

### ISSUE THREAD

**Issue by 1alessandro1** [CloverHackyColor/CloverBootloader#54]
As done by acidanthera for Opencore, they improved their documentation providing a PDF where they can group all knowledge spread across multiple forums and describe all the changes from commit to another

Is it possible an english (and/or Italian as could be done by vectorsigma72?) version for future releases of this previous guide in order for us to better understand? I'm referring to this document:
https://github.com/CloverHackyColor/CloverBootloader/releases/download/5097/Clover.of.Hacky.Color_5097_rus.pdf

It would also be perfect to have a "Differences.pdf" - if it's possible to maintain this guide up-to-date. I strongly believe that this project will benefit whether if is going to happen 

Thank you

**Comment by NyaMisty** [comment]
Google translate?
Seems that google translate is enough to understand this document

**Comment by 1alessandro1** [comment]
@NyaMisty 
Unfortunately I cannot rely on the errors done by Google Translate to have a precise understanding of the document. 
By now, everything on the internet should be exposed to the public in English, so everyone can benefit and understand what's going on.

Also, there's no clear trace on what features are either implemented or removed, as Differences.pdf does with acidanthera. 

https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Differences/Differences.pdf

**Comment by asava** [comment]
We prefer not to have documentation as part of open issues. It was tagged as documentation, and will be taken care of, when we get it to it. Thank you for your concern.
