### ISSUE TITLE
Updating Clover 5142, no bootable drive

### ISSUE THREAD

**Issue by guidocioni** [CloverHackyColor/CloverBootloader#543]
I've been trying to update Clover 5142 to something new.
I've tried both 5146 and 5149 but every time I try to update the disk does not boot anymore and I see the message "Insert bootable drive" after the BIOS screen; I don't even get to the Clover screen. 

What kind of component was changed from 5142 that could cause this? Or is the BIOS version too old? 

I have a Gigabyte Z370M D3H with an i7-8700 running MacOs Catalina. I'm not planning on running Ventura but I may update to Monterey in the future (still not sure about it as Catalina is working just fine).

**Comment by allegrox** [comment]
The problem I encountered is similar to yours. Since the clover 5146, the installer cannot update the files of the EFI partition, but it will delete the UEFI boot entry, so I only manually replace the files to update.

**Comment by guidocioni** [comment]
> The problem I encountered is similar to yours. Since the clover 5146, the installer cannot update the files of the EFI partition, but it will delete the UEFI boot entry and CLOVERX64.efi, so I only manually replace the files to update.

Thanks, so you basically did the update and then used these two files from the old installation?

**Comment by SergeySlice** [comment]
Two files? Why I will use files from old installation?

**Comment by guidocioni** [comment]
> Two files? Why I will use files from old installation?

I'm just trying to understand how can I update the clover bootloader while still having a bootable system at the end 😉

**Comment by allegrox** [comment]
I compiles clover at my pc, and then overwrites several files such as CLOVERX64.efi and ApfsDriverLoader.efi in the compilation result into the EFI partition to complete the update.

**Comment by allegrox** [comment]
> > Two files? Why I will use files from old installation?
> 
> I'm just trying to understand how can I update the clover bootloader while still having a bootable system at the end 😉
> 
> @allegrox could you please specify exactly the steps that you had to take to update clover but still being able to boot? thanks

I compiles clover at my pc, and then overwrites several files such as CLOVERX64.efi and ApfsDriverLoader.efi in the compilation result into the EFI partition to complete the update.

**Comment by SergeySlice** [comment]
It must work

**Comment by SergeySlice** [comment]
I see no Clover issue.
