### ISSUE TITLE
In memory Panic Stackshot Succeeded

### ISSUE THREAD

**Issue by gawinwong** [CloverHackyColor/CloverBootloader#544]
I'm using Catalina 10.15.7, when I use clover 5145, everything is working well. But when I update to 5146 or newer versions, boot will fail and occur this error "In memory Panic Stackshot Succeeded". By the way, I only update the "BOOTX64.efi" and "CLOVERX64.efi".

**Comment by SergeySlice** [comment]
Use 5149 and update OpenRuntime.efi

**Comment by m3skall** [comment]
Install: https://github.com/cloverhackycolor/cloverbootloader/releases/download/5134/clover.app_v1.24.pkg
Finally to the utimate release from app

**Comment by gawinwong** [comment]
> Use 5149 and update OpenRuntime.efi

After updating OpenRuntime.efi, still occur this error.

**Comment by SergeySlice** [comment]
I see no error and no reports.

**Comment by SergeySlice** [comment]
Abandoned
