### ISSUE TITLE
But also I have problems with AMFI boot-arg in Clover, isn´t working too

### ISSUE THREAD

**Issue by jackacc** [CloverHackyColor/CloverBootloader#549]
Me too, here is my Ivy Bridge laptop i7 3632QM HD 4000 working very well surprisingly, I need to do a lot of tries and intense research, firstly with os.dmg from M1, then KDK, and finally the OCLP 0.5.0. But also I have problems with AMFI boot-arg in Clover, isn´t working too, so I do a quite simple thing, nvram boot-args="amfi_get_out_of_my_way=1" in Terminal, and after that check if it prints the line with nvram -p | grep "amfi" and voila. This is because NVMRAM isn´t working.

The only problem I have currently, is other browser than Safari, all hangs and crash such as Chrome, Firefox and Opera.

I remember that with Monterey 12.3 there was happened this, with OC I couldn´t repair it, so I went back to Clover and the problem was solved in a moment, but currently I have also Clover but doesn´t work as past as OC.

All is working, HD 4000, Ethernet, WiFi, BT, Sound, USB 3.0, ACPI.

Thanks for the OCLP team, with your work we can give to our machines a little bit more of life.

Cheers.
![20220907132630853](https://user-images.githubusercontent.com/43131867/188797502-12c08cf8-45fc-4779-a29c-5427c7c594b8.jpg)

**Comment by SergeySlice** [comment]
IvyBridge laptop always have working NVRAM.
