### ISSUE TITLE
Can't boot in virtualbox after 5108

### ISSUE THREAD

**Issue by shilkazx** [CloverHackyColor/CloverBootloader#559]
I use clover iso as a optical boot device for a long run. But release 5115(and any newer release after 5108), clover iso malfunction just as the screenshot attached.
![VirtualBox_Win10_01_10_2022_16_32_50](https://user-images.githubusercontent.com/18651519/193401295-1cee0413-91d6-4412-bd0a-f680eb75d4f5.png)

OS: Archlinux x86_64
VirtualBox version: 6.1

**Comment by jackacc** [comment]
VMware Workstation Pro

**Comment by abaumgaertner** [comment]
Tested on Windows 10 22H2 x64, VirtualBox 6.1.40, Clover-5150

Clover GUI starts normally.

Check your settings for VM:
General / Type can be set to any OS BUT needs to be 64bit variant.

eg.

![grafik](https://user-images.githubusercontent.com/11097052/200752275-1566d1b2-cb07-442d-add6-7c5f08836cee.png)
