### ISSUE TITLE
clover 5150 does not inject hw.target in macOS Ventura

### ISSUE THREAD

**Issue by jonasw8** [CloverHackyColor/CloverBootloader#574]
Hi! I have Monterey and Ventura in dualboot, but clover does not inject hd.target in macOS Ventura. Because of this I don't receive system updates. My SMBIOS is iMac 20,1 and HW.Target used is J185AP. My SIP Value is 0x00000000

MacOS Monterey

![Captura de Tela 2022-11-10 às 19 03 56](https://user-images.githubusercontent.com/53247355/201218367-835c4136-d90a-48c6-8df6-c6c44542f914.png)

macOS Ventura
![Captura de Tela 2022-11-10 às 19 15 51](https://user-images.githubusercontent.com/53247355/201218572-05729422-d2b8-4ec8-bedd-531fa5891f8f.png)

Thank you for your attention

**Comment by SergeySlice** [comment]
Yes, HWTarget is not injected for Ventura.

**Comment by alessaba** [comment]
What's the proper way to get OTA updates then? is there a proper way to have the hw.target variable set?

**Comment by 5T33Z0** [comment]
There's a better workaround for this but (requires macOS Big Sur 11.3 or newer):

- Add `RestrictEvents.kext` and  boot-arg `revpatch=sbvmm`. Frces VMM SB model, allowing OTA updates for unsupported models on macOS 11.3 or newer.

**Comment by alessaba** [comment]
uhm... i can try this, but i tried with OpenCore and it injects the variable in Ventura too (and the OTA works) 
i had compatible hw targets for both my laptop and desktop pc when on Monterey.

**Comment by 5T33Z0** [comment]
It's not about the targets – it's just that [HWTarget no lonnger works in Ventura](https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?do=findComment&comment=2800185)…

**Comment by alessaba** [comment]
Oh ok. I wonder how OpenCore does it then. i am pretty sure i checked and the hw.target variable was set to a T2 Enabled MacBook Pro and OTA works.

I will try with your workaround :-)
