### ISSUE TITLE
Clover Bootloader file system is not writable 

### ISSUE THREAD

**Issue by Emanuele-1998** [CloverHackyColor/CloverBootloader#58]
the application cannot be run without making sure the file system is writable

![A1709D0B-56AD-48D7-9649-54F53AF655C1](https://user-images.githubusercontent.com/36453007/71090602-b77c8b80-21a3-11ea-8abf-a7c750f3d97f.jpeg)

**Comment by roddy20** [comment]
Use Clover.app, not Install***.pkg
Or copy EFI folder

**Comment by Emanuele-1998** [comment]
> Use Clover.app, not Install***.pkg
> Or copy EFI folder to its place

why can't i use the .pkg but clover.app?

**Comment by roddy20** [comment]
you may use anything, but Clover.app is more suitable for new versions of macOS

**Comment by Emanuele-1998** [comment]
> you may use anything, but Clover.app is more suitable for new versions of macOS

and from the clover bootloader releases what should I download to find the Clover.app?

**Comment by roddy20** [comment]
> what should I download to find the Clover.app?
the first link on that page
https://github.com/CloverHackyColor/CloverBootloader/releases/download/5100/Clover.app-v1.11-5100.zip

**Comment by roddy20** [comment]
> the application cannot be run without making sure the file system is writable
> 
try `sudo mount -uw /`
to make it writable

**Comment by Emanuele-1998** [comment]
thanks 😊
