### ISSUE TITLE
Bootmenu GUI: csr-active-config changes are not applied when switching configs.

### ISSUE THREAD

**Issue by 5T33Z0** [CloverHackyColor/CloverBootloader#580]
## Problem description:
I have 2 configs for my Ivy Bridge Notebook: one for running macOS Catalina (config.plist) and one for Monterey (config_Monterey.plist). There are only 2  differences between them; the Monterey config uses `-no_compat_check` and a different value for CsrActiveConfig (`0x867`) so the patched-in HD4000 drivers can be loaded.

When switching from `config.plist` to `Monterey.plist` from the bootmenu the value for CsrActiveConfig is not applied. 

Used Clover build: https://github.com/CloverHackyColor/CloverBootloader/actions/runs/3584745686

**Comment by SergeySlice** [comment]
I will check.

**Comment by 5T33Z0** [comment]
Hmm, doesn't work for me. Maybe it's because I am using Bootloader Chooser to pick Clover? I have to test it again with Clover's bootx64.efi file.

**Comment by SergeySlice** [comment]
Resolved?
