### ISSUE TITLE
ThinkCentre M8500T boots WIN7 and cannot shut down normally

### ISSUE THREAD

**Issue by tudoull** [CloverHackyColor/CloverBootloader#582]
Hello, I am using Lenovo ThinkCentre M8500T, the operating system is Windows 7 SP2, in order to add NVME SSD (WD BLUE SN570), I use CLOVER 5150 to boot. Everything works fine, but the fan does not stop running after normal shutdown, please help me to solve it.
![Motherboard](https://user-images.githubusercontent.com/7512018/206894359-b1d52d89-bd9d-4809-bebd-f9d4db95cee0.jpg)
[preboot.log](https://github.com/CloverHackyColor/CloverBootloader/files/10201743/preboot.log)
[config.zip](https://github.com/CloverHackyColor/CloverBootloader/files/10201745/config.zip)

**Comment by SergeySlice** [comment]
Windows is not affected by Clover's config.

**Comment by SergeySlice** [comment]
abandoned
