### ISSUE TITLE
How to use text mode for specific entry as standard

### ISSUE THREAD

**Issue by solisinvictum** [CloverHackyColor/CloverBootloader#584]
hi,

i use clover as bootloader to choose between windows and linux.

both on separate ssds, both encrypted (linux luks, windows veracrypt).

for some reason, my notebook or veracrypt have a bug, there the screen is black/didnt show the "Password:" dialog on the windows/veracrypt installation (this have nothing todo with clover, i have this problem already a year), but it still works and i can blind put the password in. 

but if i press space and choose "boot XYZ in text mode" on the windows entry, it works and the dialog is shown. 

So, on my config.plist i have two custom entrys. And want to change the windows entry in this way, that it boots everytime in textmode.

But didnt find information about that how to do that.

Thanks for help.

**Comment by SergeySlice** [comment]
Don't use custom entries and set TextOnly = true.
