### ISSUE TITLE
Question about CsmVideoDxe.efi

### ISSUE THREAD

**Issue by 1457384613gh** [CloverHackyColor/CloverBootloader#592]
`CsmVideoDxe.efi` can make `Arrandale GPU` support more resolutions.

I wonder whether `CsmVideoDxe.efi` is a generic EFI driver or not, because I want to use `CsmVideoDxe.efi` for `UEFI Grub2`, `rEFInd Boot Manager` and `GRUB4DOS for UEFI`.

**Comment by SergeySlice** [comment]
Yes, it is written as a standard UEFI driver. Anyway take precautions using it. It has limited compatibility with different hardware, not universal.
