### ISSUE TITLE
Poweredge R630 & PCI Express NVME pro

### ISSUE THREAD

**Issue by princesimong** [CloverHackyColor/CloverBootloader#596]
Hi,

when I boot up using Clover on a USB drive, my NVME drive is not detecting. I already move the "NvmExpressDxe.efi" file into BIOS/UEFI folders but it couldn't work in my case.  The strange issue I have is that I have two other R630S and this model/nvme combination of drive works. What did I miss? I know the PCIe worked because I was able to install VMware on it. Just could not see it after the install/reboot.

**Comment by SergeySlice** [comment]
You should provide boot.log to know what is the issue.
