### ISSUE TITLE
RestrictEvents boot-args not working in r5151

### ISSUE THREAD

**Issue by 5T33Z0** [CloverHackyColor/CloverBootloader#598]
Hi. After adding RestrictEvents kext, the added boot-args don't work when using Clover.

**Example**:

Setting `revpatch=memtab` in OpenCore enables RAM Tab in "About this Mac" Section (MBP10,1 SMBIOS):

![Bildschirmfoto 2023-04-29 um 16 04 29](https://user-images.githubusercontent.com/76865553/235307872-ef99b39d-df79-4a2c-86e5-01419021c83b.png)

When injecting RestrictEvents via Clover, the RAM Tab is missing:

![Bildschirmfoto 2023-04-29 um 16 15 08](https://user-images.githubusercontent.com/76865553/235307674-e9cbb2f3-93e4-404d-bc9c-8d15bf8eeb47.png)

But, the boot-arg is present and the kext is loaded. I verified it by running `extstat | grep -v com.apple`:

![Bildschirmfoto 2023-04-29 um 16 20 40](https://user-images.githubusercontent.com/76865553/235307743-f5a3310e-e53f-432c-ac42-f48b2c971304.png)

My guess is that other options associated with `revpatch=value` are also affected. It's just not as easy to test.

**Comment by SergeySlice** [comment]
AFAIK RAM tab depends on MacModel or some SMBIOS settings but without RestrictEvents
![Screenshot 2023-06-03 at 12 55 51](https://github.com/CloverHackyColor/CloverBootloader/assets/485515/6e2b1ce7-3cfc-40e6-841d-101bd7b77e7e)
