### ISSUE TITLE
How can I make DUET load USB disks?

### ISSUE THREAD

**Issue by 1457384613gh** [CloverHackyColor/CloverBootloader#599]
I am using DUET of Clover.

`MBR=>PBR=>boot=>CLOVERX64.efi`

DUET cannot load FAT32 from USB disk.

What I used is `boot6`.
I haven't added any EFI drivers of USB.

The DUET can only load internal SSD but USB disks.
How can I make DUET load USB disks?

**Comment by SergeySlice** [comment]
[UsbBusDxe.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/11642264/UsbBusDxe.efi.zip)
[UsbMassStorageDxe.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/11642266/UsbMassStorageDxe.efi.zip)
[UsbMouseDxe.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/11642267/UsbMouseDxe.efi.zip)
[XhciDxe.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/11642268/XhciDxe.efi.zip)
[UhciDxe.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/11642269/UhciDxe.efi.zip)
[EhciDxe.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/11642271/EhciDxe.efi.zip)
But I am not sure if it helps.

**Comment by SergeySlice** [comment]
yes boot6 already contains USB drivers but boot7.
