### ISSUE TITLE
Black screen when try to boot into windows 11

### ISSUE THREAD

**Issue by Q8Xbox** [CloverHackyColor/CloverBootloader#604]
Hello,

I have restore mac recovery on my pc which have Navidia Graphics Card and now i can not boot mac 13.4 or boot windows 11 as for windows 11 it seems like boot drive been deleted somehow. Any help to fix this issue. please ?

**Comment by SergeySlice** [comment]
Provide please more info else I see no what is the problem.

**Comment by LeeBinder** [comment]
I can boot into Windows 11 just fine (Clover 5152)

**Comment by SergeySlice** [comment]
Close as abandoned.
