### ISSUE TITLE
r5152 does not auto-detect ESXI 6.7/8.0.1 volume, F3 reveals volume, boots ok

### ISSUE THREAD

**Issue by LYAN0526** [CloverHackyColor/CloverBootloader#605]
The Esxi boot option is not displayed by default and I had to press F3 to see the boot option
The reason seems to be that Esxi uses BOOTX64.EFI to boot causing Clover to think it should be hidden, but I don't know how to fix it..

**Comment by SergeySlice** [comment]
Clover may work from file /EFI/BOOR/BOOTX64.EFI as for many of us.
The problem is Esxi which is not intended for Clover.
