### ISSUE TITLE
esxi bios mode iso boot issue R5152

### ISSUE THREAD

**Issue by kcj83** [CloverHackyColor/CloverBootloader#608]
Can someone please point me in the right direction with diagnosing/debugging this BIOS mode iso boot issue shown below on esxi8.0c virtual machine? It just hangs directly after bios initialization and booting from the latest clover iso.

![image](https://github.com/CloverHackyColor/CloverBootloader/assets/79729347/4f91a640-9ecf-401c-871d-6d7afeb20348)

![image](https://github.com/CloverHackyColor/CloverBootloader/assets/79729347/c71aa247-f2d3-49b2-9ca5-554edb95fb43)

and then just sits and hangs infinitely...

virtual machine vmware.log attached
[vmware.log](https://github.com/CloverHackyColor/CloverBootloader/files/11709519/vmware.log)

**Comment by kcj83** [comment]
vmware.log attached
[vmware.log](https://github.com/CloverHackyColor/CloverBootloader/files/11709500/vmware.log)

**Comment by SergeySlice** [comment]
Sorry, I am understanding zero in VMWare. Become developer and tell us what to do with vmware.
