### ISSUE TITLE
Hide / Disable the options button

### ISSUE THREAD

**Issue by ryanrudolfoba** [CloverHackyColor/CloverBootloader#614]
Is there a way to hide / disable the options button?

Using clover 5151

![233867354-4d554a4e-1e1f-42f7-968a-31a8c0b677b2~2](https://github.com/CloverHackyColor/CloverBootloader/assets/98122529/fdfd8adc-90c4-4d07-810a-a51be16830dd)

**Comment by SergeySlice** [comment]
You may comment out the line in main.cpp
~~~~
      MainMenu.AddMenuEntry(&MenuEntryOptions, false);
~~~~

But I am not going to do this at regular base.
