### ISSUE TITLE
Problem with loading Clover

### ISSUE THREAD

**Issue by PlushPersik** [CloverHackyColor/CloverBootloader#617]
I wanted to put a hackintosh on my PC. But for some reason, when I did everything right, namely: I inserted a USB flash drive, downloaded BDUtility, wrote the latest version Clover to the USB flash drive, then write the .rdr image with macOS High Sierra to the free partition through the R-Drive image program.

I rebooted the PC, booted from the flash drive, then a white flashing bar appeared in the up right area. Then the number 6 appeared, and a screen with red letters came out.

My pc:
Intel Xeon x3460
GeForce GTX 750 Ti
8 GB RAM 1333 MHz
No any boost
Hard disk 320 GB
Legacy bios

**Comment by PlushPersik** [comment]
![IMG20230726003538](https://github.com/CloverHackyColor/CloverBootloader/assets/70471344/4fe71e42-293f-405c-8def-9295ad203f04)

**Comment by SergeySlice** [comment]
Choose different boot6 or boot7 file and rename it to boot.
Replace the file on your USB drive.

**Comment by SergeySlice** [comment]
abandoned
