### ISSUE TITLE
Where can I get the source codes of boot5 and set the default entry?

### ISSUE THREAD

**Issue by 1457384613gh** [CloverHackyColor/CloverBootloader#618]
Where can I get the source codes of boot5 and set the default entry?

## I happen to get `boot5` of DUET of Clover.
Then I find,

Device|`boot5`|`boot6`|`boot7`
--|--|--|--
SATA disks|__supported__|__supported__|__supported__
NVMe SSDs|_Not tested_|_Not supported_|__supported__
USB disks|__supported__ Taken as `EFI USB Device`|_Not supported_|__supported__ Taken as `EFI Hard Drive2`
USB 3+|_Not tested_|__supported__|__supported__
USB mouse|__supported__|__supported__|_Not supported_
PS/2 keyboard|__supported__|__supported__|__supported__

`boot5` seems better than `boot6`.
However, it cannot  load `/EFI/CLOVER/CLOVERX64.efi` automatically.
So we should select `boot from file` and select an efi file.

## I want to adapt `boot5` for loading an efi file automatically.
Where can I get the source codes of boot5 and set the default entry?

## Question
Now that `boot5` can take USB disks as `EFI USB Device`, why this function was deleted from `boot6` and `boot7`?

**Comment by SergeySlice** [comment]
Boot5 is old variant of boot6 differing by use of EBDA.
boot5 uses compilation key --low-ebda which is now by default. Binary size is 450kb
boot6 uses --std-ebda. Binary size is 486kb.
Modern compilation script chooses the key automatically.
Anyway you can you can try to set it manually
./ebuild.sh -gcc53 -fr --std-ebda -n 5 -D NO_GRUB_DRIVERS_EMBEDDED
to compare the result. 
The key --low-ebda is absent now. It is assumed if not --std-ebda.

**Comment by SergeySlice** [comment]
If your system is Ventura then I recommend to use toolset -gcc131 which produce more compact codes.
Or just take boot6 from recent release.

**Comment by SergeySlice** [comment]
1. I also have PS2Mouse, PS2Keyboard and PS2Trackpad efi modules. The problem is multiple hardware which requires different drivers. For example Trackpad can be Alps, Synaptic, Sentelic, Elan and more. While we have very limited space inside DUET. OK, 40kb is acceptable but not megabytes for each model.
2. For the same reason I am not going to make multilanguage support.
For both cases you may create own version of DUET with your specific drivers and working only on your language,

**Comment by SergeySlice** [comment]
Yes, there is a size limit because of legacy memory assignment. low_ebda full size is 450kb and std-ebda size can be 483kb. Not more.
External drivers work in clean EFI space and has limit 4Gb.
Near boot? What is the sense? boot5, boot6 and boot7 are different entities of the same DUET.

**Comment by SergeySlice** [comment]
DUET works other way. It is loaded in Real Mode with BIOS procedures without drivers. Then it is unpacked by itself and started in Protected mode. Then it is able to load something and it does this. It loads Clover.efi and let it does other work.

**Comment by SergeySlice** [comment]
Wrong issue
