### ISSUE TITLE
After update motheboard bios won´t boot

### ISSUE THREAD

**Issue by RicGervasoni** [CloverHackyColor/CloverBootloader#619]
Hello!
After update motherboard bios Clover 5154 won´t boot. Can you helpe me? 
Motherboard MSI ICE Z790 - bios version E7D27IMS.1B0.
Thanks. 

![image](https://github.com/CloverHackyColor/CloverBootloader/assets/50720986/33cf28e3-32a5-4554-99e3-2679e2160668)

**Comment by SergeySlice** [comment]
Most probably you have locked MSR 0xE2 in the new BIOS.
Set KernelPM=true

**Comment by SergeySlice** [comment]
Abandoned
