### ISSUE TITLE
Block IOSkywalkFamily under Sonoma 

### ISSUE THREAD

**Issue by anonymous-writer** [CloverHackyColor/CloverBootloader#625]
Hello everyone and thanks for working on the Clover Bootloader.

Is there a way to block the kext IOSkywalkFamily under Sonoma so that the Ventura version of the IOSkywalkFamily can be injected?
The info plist patch doesn't want to work and the kext always loads.

![Bildschirmfoto 2023-08-12 um 08 53 12](https://github.com/CloverHackyColor/CloverBootloader/assets/35840715/d4b73318-d169-479f-9d5f-af86b414a944)

![Bildschirmfoto 2023-08-12 um 08 51 47](https://github.com/CloverHackyColor/CloverBootloader/assets/35840715/c62ba31a-9d2a-4ccb-9325-d0bf4470ad75)

**Comment by SergeySlice** [comment]
Made since commit 2711170df4f60b2ae5aa20add3e00f35cf57b7e5

**Comment by anonymous-writer** [comment]
I have seen and tested this. Unfortunately it doesn't work and gets stuck at the picture as soon as you set the BlockSkywalk to true. 

![IMG_2474](https://github.com/CloverHackyColor/CloverBootloader/assets/35840715/2bf29a34-7d90-4f86-8223-0251b1aef2a8)
