### ISSUE TITLE
L380 Yoga does not allow MacOS Monterey+ to boot past loading screen, and Big Sur gets stuck halfway through install loading process.

### ISSUE THREAD

**Issue by Kxsumi** [CloverHackyColor/CloverBootloader#645]
Hello, I've been struggling to find a way to use any form of MacOS, as they all fail to boot in one way or another. For example, Sonoma recognizes my computer as not being a genuine Mac and therefore does not let me continue in the MacOSX install process (shows the X). Big Sur has an issue where halfway into its installer loading it will just freeze, and I have to restart the computer which does not fix it.

**Comment by SergeySlice** [comment]
But yes, macOS can't be installed on non-Apple computers without special efforts. May be you should ask for tutorial on some forum like https://www.insanelymac.com/forum/?
