### ISSUE TITLE
Latest commit causes weird issues with controls in boot menu.

### ISSUE THREAD

**Issue by 5T33Z0** [CloverHackyColor/CloverBootloader#650]
The last [commit](https://github.com/CloverHackyColor/CloverBootloader/actions/runs/6959929654) somehow messes up the boot menu. No matter which key I press, it results in Booting the highlighted OS entry!

**Examples**:
-  Windows is pre-selected (left), I click the right arrow to select macOS – boom, Windows starts
- Same thing happens when using the mouse:  Windows is pre-selected (left). I move the mouse cursor to the right to select macOS and click. Boom: Windows boots.

This happens with the default "Clovy" theme as well.

Reverting to the previous [commit](https://github.com/CloverHackyColor/CloverBootloader/actions/runs/6921325173) resolved the issue

**Comment by asepms92** [comment]
Same here.. my laptop have 3 OS installed, when click F3, F1, F2, arrow left, arrow right, up and down, always booting to Windows, like issues in GUI Clover or source codes refit GUI..

**Comment by 5T33Z0** [comment]
I also noticed that this commit has a negative impact on WIndows 11 as well for some reason. The trackpad doesn't work when booting with this build.

**Comment by asepms92** [comment]
The latest commit, Clover just recognizing Ctrl+Alt+Del and Space

**Comment by asepms92** [comment]
![Screen Shot 2023-11-25 at 21 02 02](https://github.com/CloverHackyColor/CloverBootloader/assets/43111808/fecb109a-bd0c-4e86-8e6d-bcdd27414114)
But the trick boot with USB Installer OC, select USB Boot Installer, select Recovery or macOS Partition and Restart to Boot Clover

**Comment by asepms92** [comment]
![Screen Shot 2023-11-25 at 21 02 02](https://github.com/CloverHackyColor/CloverBootloader/assets/43111808/765567aa-0c36-4e8e-a403-60891ac160a2)
But the trick of boot with USB Installer OC, select USB Boot Installer, select Recovery or macOS Partition and Restart to Boot Clover

**Comment by SergeySlice** [comment]
Same here....
