### ISSUE TITLE
Early Kernel panic in macOS Sonoma with latest commit. Possibly related to `BlockSkywalk` Quirk 

### ISSUE THREAD

**Issue by 5T33Z0** [CloverHackyColor/CloverBootloader#651]
I get an early Kernel Panic in macOS Sonomo on my Laptop that requires **BlockSkywalk** Quirk. Since I don't use this Quirk on my other machines and since someone else has the same issue, I think there might be related to BlockSkywalk.

Issue starts with this commit (and is still present in the latest commit):

- https://github.com/CloverHackyColor/CloverBootloader/actions/runs/6996153456

I've created a debug log:

[2023-11-27_15-30_CLOVERX64.efi.log.zip](https://github.com/CloverHackyColor/CloverBootloader/files/13477143/2023-11-27_15-30_CLOVERX64.efi.log.zip)

- Last working commit is from November 16th: [Clover beta-bdb7a95d9](https://github.com/CloverHackyColor/CloverBootloader/actions/runs/6895381668)

**Comment by 5T33Z0** [comment]
Last commit I tested was this and it worked fine: https://github.com/CloverHackyColor/CloverBootloader/actions/runs/7398572951

**Comment by jief666** [comment]
Seems resolved.

**Comment by LeeBinder** [comment]
macOS Sonoma booting fine with `BlockSkywalk` Quirk + latest Clover beta from CircleCI, and Broadcom Wi-Fi working fine as already with latest OC.

Thanks @jief666 , well done 👍 

(So yes, the GUI freeze with 0094e0c is definitely a new and separate bug.)
