### ISSUE TITLE
[REGRESSION] Custom entry of Type 'OSXInstaller' (e.g. for macOS Update) in Clover GUI broken since r5130

### ISSUE THREAD

**Issue by LeeBinder** [CloverHackyColor/CloverBootloader#654]
I've been wanting to post this bug introduced with [r5130](https://github.com/CloverHackyColor/CloverBootloader/releases/tag/5130) for a looong time, and today is finally the day - better late than never :/

In my Clover config.plist, I've always had this entry:
```
<dict>
	<key>Disabled</key>
	<false/>
	<key>FullTitle</key>
	<string>macOS Monterey Update</string>
	<key>Hidden</key>
	<false/>
	<key>Image</key>
	<string>software-update_128.png</string>
	<key>InjectKexts</key>
	<true/>
	<key>NoCaches</key>
	<false/>
	<key>Path</key>
	<string>\92E2D915-A0A6-4562-ACA6-236826A4E819\com.apple.installer\boot.efi</string>
	<key>Type</key>
	<string>OSXInstaller</string>
	<key>Volume</key>
	<string>D7323763-CF5E-4C9F-B51C-C1234BC3D22C</string>
	<key>VolumeType</key>
	<string></string>
</dict>
```
				
If an OS update was pending, this entry would result into the entry with the Software Update icon on the very left:

![screenshot_5129](https://github.com/CloverHackyColor/CloverBootloader/assets/39203497/2413212a-ee69-48f8-9b39-0d725efc3701)

This worked up to [r5129](https://github.com/CloverHackyColor/CloverBootloader/releases/tag/5129) (source code only - my BOOTX64 binary originates from CircleCI). Unfortunately, [r5130](https://github.com/CloverHackyColor/CloverBootloader/releases/tag/5130) broke this and the entry no longer shows up:

![screenshot_5130](https://github.com/CloverHackyColor/CloverBootloader/assets/39203497/e5eeebb1-9628-43ca-9742-00de56ff4e65)

It does show up again, though, after pressing F3, so Clover still finds it but simply now fails to display it in the regular/ default GUI.

The custom entry also shows up again immediately as soon as I swap any recent BOOTX64 in EFI/BOOT with the one from r5129 and reboot, so the regression must be in Clover BOOTX64 directly, _NOT_ in OpenRuntime.efi.

I've attached preboot logs from both, r5129 and r5130.

This being a regression I have hopes this looks like a rather quick fix.

Thanks for looking into this. As before, I'm open for beta-testing.

[5129-preboot.log.zip](https://github.com/CloverHackyColor/CloverBootloader/files/13732904/5129-preboot.log.zip) |&nbsp;[5130-preboot.log.zip](https://github.com/CloverHackyColor/CloverBootloader/files/13732906/5130-preboot.log.zip)

@SergeySlice @jief666

**Comment by SergeySlice** [comment]
First, construction like <string></string> is not allowed in Clover. Write here something.
Second, no sense to create an entry for update. Clover will create the entry during real update dynamically. It works and always was working.

**Comment by LeeBinder** [comment]
Hi Sergey, thanks for replying. All right - I removed the thumb up above.

Fair enough if you don't feel like reestablishing that feature.

Do you remember if it was removed on purpose or by accident?
