### ISSUE TITLE
Incorrect orientation after replacing the screen with a better version.

### ISSUE THREAD

**Issue by AllevatoreAnonimo** [CloverHackyColor/CloverBootloader#659]
After replacing the stock LCD screen with its improved version (a DeckHD to be precise) it is rotated as in the attached image.
![IMG_20240108_154240](https://github.com/CloverHackyColor/CloverBootloader/assets/4853816/2168a916-6d90-4d06-bd54-f3b4a29bf069)

**Comment by SergeySlice** [comment]
Huh! What is the device?

**Comment by jief666** [comment]
wow, clover ends up in unexpected places ! :-)
Once booted, do you have the correct orientation ? Can you get a log from that ?

**Comment by AllevatoreAnonimo** [comment]
> Huh! What is the device?

I can guarantee that under the hood it still has the heart of a Steam Deck.
I think the problem came up when it switched to 1900x1200 resolution.




> wow, clover ends up in unexpected places ! :-)
> Once booted, do you have the correct orientation ? Can you get a log from that ?

Yes, once started the screen is in the right orientation.
What logs do you need?

![IMG_20240110_104131](https://github.com/CloverHackyColor/CloverBootloader/assets/4853816/933cba28-40bc-4ca9-871a-2a10621a590c)

**Comment by jief666** [comment]
There is a key that you can add to enable debug log. Then send me that. If you're not sure what key is that, ask on the forum.

**Comment by AllevatoreAnonimo** [comment]
I found within Clover-Toolbox a dedicated function for those with the DeckHD mod that forces the correct resolution to 1900x1200 instead of 1200x1900.
Closing the issue.
![IMG_20240110_183048](https://github.com/CloverHackyColor/CloverBootloader/assets/4853816/f0aa52ff-a542-4bc1-91a2-06c26b4f5c6c)
![IMG_20240110_183946](https://github.com/CloverHackyColor/CloverBootloader/assets/4853816/841fae9d-df0b-47ed-931f-157109c138d9)

**Comment by jief666** [comment]
Can you tell what does that tool do ? Setting a parameter in config.plist ?

**Comment by jief666** [comment]
I found the script source, I think.
I can see inside that it add this key to config.plist :
<key>ScreenResolution<key><string>1920x1200<string>
I've no idea why that would rotate the screen 90 degrees !

**Comment by AllevatoreAnonimo** [comment]
> I found the script source, I think.
> I can see inside that it add this key to config.plist :
> `<key>ScreenResolution<key><string>1920x1200<string>`
> I've no idea why that would rotate the screen 90 degrees !

I don't know, I saw that it is also possible to modify through this tool the timeout for the automatic choice and even the type of theme to be used. 
It's probably going to tweak some parameters in that file.
