### ISSUE TITLE
The starting sound disappeared.

### ISSUE THREAD

**Issue by ybronst** [CloverHackyColor/CloverBootloader#666]
The starting sound  (Ta-Da) disappeared. Clover revision: 5157 ALC897 used by AppleALC.kext layout-id: 0C000000
HdaCodecDump:
[HdaCodecDump.txt](https://github.com/CloverHackyColor/CloverBootloader/files/13980705/HdaCodecDump.txt)
Screenshot:
![](https://www.insanelymac.com/uploads/monthly_2024_01/Screenshot2024-01-1820_48_40.png.4fb413ba11d283fe4acb32cfee71c687.png)

**Comment by SergeySlice** [comment]
There is no Clover issue. May be you forgot something?

**Comment by ybronst** [comment]
> There is no Clover issue. May be you forgot something?
What exactly could I have forgotten? In Release 5156 the startup sound still worked. The BlockSkywalk quirk did not work.

**Comment by jief666** [comment]
Try this : [CloverX64-2024-01-19-15-43-13-64e7d98-dirty-jief.zip](https://github.com/CloverHackyColor/CloverBootloader/files/13990680/CloverX64-2024-01-19-15-43-13-64e7d98-dirty-jief.zip), please ?

**Comment by ybronst** [comment]
> Try this : [CloverX64-2024-01-19-15-43-13-64e7d98-dirty-jief.zip](https://github.com/CloverHackyColor/CloverBootloader/files/13990680/CloverX64-2024-01-19-15-43-13-64e7d98-dirty-jief.zip), please ?

The sound appeared again, but when I try to select another output, instead of turning off the sound, it either freezes or suddenly reboots.

**Comment by fabiosun** [comment]
Same result, it reboots when i choose another device

**Comment by fabiosun** [comment]
[Archive.zip](https://github.com/CloverHackyColor/CloverBootloader/files/13990950/Archive.zip)
in misc folder it prints these files

**Comment by jief666** [comment]
And this : [CloverX64-2024-01-19-16-58-31-64e7d98-dirty-jief.zip](https://github.com/CloverHackyColor/CloverBootloader/files/13991391/CloverX64-2024-01-19-16-58-31-64e7d98-dirty-jief.zip) ?

**Comment by fabiosun** [comment]
@jief666 thank you also for this tests
[Archive.zip](https://github.com/CloverHackyColor/CloverBootloader/files/13991487/Archive.zip)
My system now in Option has two AMD audio sources (i cant see internal USB audio)
No error but no sound from hdmi/Dp devices

**Comment by ybronst** [comment]
> And this : [CloverX64-2024-01-19-16-58-31-64e7d98-dirty-jief.zip](https://github.com/CloverHackyColor/CloverBootloader/files/13991391/CloverX64-2024-01-19-16-58-31-64e7d98-dirty-jief.zip) ?
No error but no sound from any audio outputs.

**Comment by jief666** [comment]
Try this, please : [CloverX64-2024-01-19-17-56-58-64e7d98-dirty-jief.zip](https://github.com/CloverHackyColor/CloverBootloader/files/13991995/CloverX64-2024-01-19-17-56-58-64e7d98-dirty-jief.zip)

**Comment by fabiosun** [comment]
No audio here
and selecting AMD audio as output after some tries it reboots

**Comment by jief666** [comment]
You got audio with CloverX64-2024-01-19-16-58-31-64e7d98-dirty-jief.zip but not with CloverX64-2024-01-19-17-56-58-64e7d98-dirty-jief.zip ?

**Comment by fabiosun** [comment]
No Jief my results are different i do not see internal audio device as ybronst did with a version
i have USB internal audio on my motherboard.
His audio is different
instead from GPU audio (HDMI/DP) maybe there is a problem for both

**Comment by jief666** [comment]
@SergeySlice : instead of renaming gEfiAudioIoProtocolGuid, I completely disabled OcAudioLib.
Can you have a look to see if it works for you ?

**Comment by ybronst** [comment]
> @SergeySlice : instead of renaming gEfiAudioIoProtocolGuid, I completely disabled OcAudioLib. Can you have a look to see if it works for you ?

Yes, everything is great.
