### ISSUE TITLE
Vulnerable for logofail?

### ISSUE THREAD

**Issue by technout** [CloverHackyColor/CloverBootloader#667]
Quick question: Is Clover vulnerable for logofail?

More info: https://arstechnica.com/security/2023/12/just-about-every-windows-and-linux-device-vulnerable-to-new-logofail-firmware-attack/

**Comment by YBronst** [comment]
Why not? Any attacker can create and distribute a malicious theme for Clover. Users will install it themselves if it looks attractive. Everything we put in UEFI can theoretically overwrite the BIOS. If we can still analyze open source code, then it is unlikely that we can also easily analyze any logo.

**Comment by SergeySlice** [comment]
Nonsense. We have own picture parcer which has no vulnerability and will not cause infected code execution.
