### ISSUE TITLE
Clover r5157 - No startup sound

### ISSUE THREAD

**Issue by najeebanwer** [CloverHackyColor/CloverBootloader#669]
The Clover startup sound works correctly in r5156, but not in r5157. 
In r5157 there is no output device listed and the volume is set to 0.

**Comment by YBronst** [comment]
Try this version.
[CLOVERX6451571c2acffed.efi.zip](https://github.com/CloverHackyColor/CloverBootloader/files/14045526/CLOVERX6451571c2acffed.efi.zip)

**Comment by najeebanwer** [comment]
Yes, that fixed it. I reinstalled r5157 and replaced EFI/CLOVER/CLOVERX64.efi with the one you provided.
