### ISSUE TITLE
[Feature implementation Request] Add block kext feature in config.plist

### ISSUE THREAD

**Issue by fabiosun** [CloverHackyColor/CloverBootloader#670]
It's not really an issue but a request or my wish list for Clover :)
Clover has a very interesting possibility when you're at the boot menu level
Pressing the space button allows you to access this section:
![Kext block](https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/d175b044-a48d-48b9-b0fc-3983c3390c71)
![Kext block 1](https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/a725a3cb-2ca1-4673-bfd8-80fba131af19)
![Kext block 2](https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/8a2f5969-6f23-436d-811d-f4cf9966178e)
It is also possible to lock in another section of the config.plist of OSX internal kexts as we do with SkywalkFamily:
![OSX blocked kext](https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/33dbb63e-a798-4bb6-a525-01d07a42ed91)

@jief666 , @SergeySlice 

I'd like to understand if it's possible to implement kext locking that we have in the various folders in Clover/Kexts by editing the config.plist, as after all it's already possible to do at the bootmenu level.
Or does that possibility already exist?

**Comment by YBronst** [comment]
As far as I know, such a similar function is available in the OС because all kexts there are stored in a common folder, so each aded kext is entered into the config in a certain order, and the ability has been added not to delete a line, but to disable it. 
which is not very convenient if there is no way boot to desktop.
Unlike the OS, a problematic kext can be blocked once by a space or permanently moved to the off folder, which can be done even from the Clover shell.
In Clover, unlike the OS, a problematic kext can be blocked once with a space or permanently moved to a disabled folder, which can be done even from the Clover shell. Therefore, I guess that this function will be duplicate.

**Comment by fabiosun** [comment]
> permanently moved to a disabled folder

i do not need to disable it permanently but only when i have to update Sonoma
As you know it is not possible to use Delta update if you have patched Sonoma with OCLP (OpenCore Legacy patcher)
so my request or wishlist if you prefer

I would like to change my config .plist and not the entire EFI or as i wrote, changing with a proper config i could disable only the kext i need to disable, configuring in it proper SIP and all features i need to use Apple delta OS update
then once uon a time i have updated the system and patched again with OCLP to use my previous confg.plist with all the kexts i need for sonoma
I hope is more clearer for you my request
to say in a shorter way:

1) with OCLP applied delta Update in sonoma is not availabe because SIP and others mandatory oprion useful to OCLP
2) preparing a good config-1.plist with all parameters useful for OS delta update as SIP, No kext blocked or all i need for a NO OCLP installation and in this way update the system
3) use a proper config.plist to use OCLP to start root patching (in my case only for Modern network patching)
4) end

i know and i wrote above how clover can do with boot menu block kext option, but it could be faster if it was possible only changing a config.plist as we can do in Clover now

**Comment by YBronst** [comment]
> > permanently moved to a disabled folder
> 
> i do not need to disable it permanently but only when i have to update Sonoma As you know it is not possible to use Delta update if you have patched Sonoma with OCLP (OpenCore Legacy patcher) so my request or wishlist if you prefer
> 
> I would like to change my config .plist and not the entire EFI or as i wrote, changing with a proper config i could disable only the kext i need to disable, configuring in it proper SIP and all features i need to use Apple delta OS update then once uon a time i have updated the system and patched again with OCLP to use my previous confg.plist with all the kexts i need for sonoma I hope is more clearer for you my request to say in a shorter way:
> 
> 1. with OCLP applied delta Update in sonoma is not availabe because SIP and others mandatory option useful to OCLP
> 2. preparing a good config-1.plist with all parameters useful for OS delta update as SIP, No kext blocked or all i need for a NO OCLP installation and in this way update the system
> 3. use a proper config.plist to use OCLP to start root patching (in my case only for Modern network patching)
> 4. end
> 
> i know and i wrote above how clover can do with boot menu block kext option, but it could be faster if it was possible only changing a config.plist as we can do in Clover now

For what? I moved the kexts and disabled them, updated the system, patched it, returned the kexts and everything was OK. I don’t even do this by hand, but through a command file.

**Comment by fabiosun** [comment]
Hello @YBronst ,
Forgive me but I don't quite understand the meaning of these posts of yours
Do you think this request of mine is already there or is it unnecessary?
If it is present as I am requesting it, can you show it to me?
If you think it is useless, it is your opinion and as such I respect it ;)

**Comment by YBronst** [comment]
> Hello @YBronst , Forgive me but I don't quite understand the meaning of these posts of yours Do you think this request of mine is already there or is it unnecessary? If it is present as I am requesting it, can you show it to me? If you think it is useless, it is your opinion and as such I respect it ;)
I'm sorry, but you don't understand.
You are trying to offer a conceptually incompatible solution from OpenCore to Clover.
The only thing common to both boot loaders is the OpenRuntime driver.
Developers will never agree to greater integration and this is not a question of technical feasibility, but a question of historically formed program ideology.
I can't even convince the developers to move the CsrActiveConfig parameter from the RtVariables section to the SMBIOS section. I'm sorry! ;)

**Comment by fabiosun** [comment]
> You are trying to offer a conceptually incompatible solution from OpenCore to Clover.

Is it possible with Opencore to choose a different config.plist?
I do not think so and i am not comparing or asking for a greater integration! :)

Clover has inside this features
My request is to use them in config.plist as we can do for patches, ssdt and so on (enabling / disabling them in boot menu)

offtopic here:
Your request to move CsrActiveConfig in SMbios section for you is usefull but you cand do with a different config or manually chanching SIP values in Bootmenu Option

> I'm sorry! ;)

Why? :)
let the devs to express their thoughts about this whishlist if they have some spare time to read all this :) :)

**Comment by YBronst** [comment]
Slice has already expressed his opinion about this on applelife.ru :)

**Comment by fabiosun** [comment]
so i have to hope in Jief for an answer :PP

**Comment by YBronst** [comment]
Slice and I previously discussed my request to block kexts, but he only did BlockSkywalk.
He told me that this is not necessary, since there is a folder that Clover does not process.

**Comment by fabiosun** [comment]
> He told me that this is not necessary, since there is a folder that Clover does not process.

Let see
It seems a bit different, one OSX only. Sonoma needs are different for delta update using OCLP

**Comment by YBronst** [comment]
Yes, I understand this, but it is all the more difficult to implement. Most likely, this will not be done through the config. Why? Here's why: https://www.applelife.ru/threads/clover.42089/page-1538#post-1045185
"The story goes like this: Asindanthera saw Clover as a useful technique. After scratching my head a little, we did something similar, but in a completely different way.
Then people come to us with a baggage of axioms from Dortania, and begin to ask how to do this in Clover.
You don’t need this in Clover, you’d better read KCH.
I don’t have the strength to write a site similar to Dortanya; in this they are undoubtedly ahead. Not everything is right there, but it is useless to fight the parishioners.
For them, this is a bible that needs to be bowed to the waist." :(

**Comment by fabiosun** [comment]
i dont read Dortania but Configuration.pdf
Not interested in a war about Clover and OpenCore
I use both
For this reason i am asking this "feature"
If I didn't use OCLP (OpenCoreLegacy Patcher for My wifi in SONOMA) I would not have opened this issue/whishlist
@jief666 solved recently a big proble for AM5 platform so...i can hope!
 :)

**Comment by jief666** [comment]
@YBronst 
> I can't say that this will never happen, but OpenCore is written in C, and Clover is written in C++.
> I'd love to do this myself, but I don't know enough C++.

Clover is _compiled_ by C++, but 90% of it is still C.

> CsrActiveConfig from RtVariables to SMBIOS.

Any technical reason ?

@fabiosun 
I'm not sure to understand the request. You want to block an extension prelinked into the kernel ?

**Comment by fabiosun** [comment]
> @fabiosun
> I'm not sure to understand the request. You want to block an extension prelinked into the kernel ?

No jief, thank you for your answer
i would like to block using a config.plist mode kexts i use in Kext/other
<img width="504" alt="image" src="https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/3f5fcd02-34b7-401c-9cc9-a639a7975d6e">

And this is possible to do in boot menu pressing space and block kext

**Comment by jief666** [comment]
Hum, like YBronst, I'm not sure to understand why you want this. Because changing of config.plist from the menu seems the same as untick a kext from that menu.
Sorry to say that. I'm judging the features you'd like to have. But just draw your attention to something you may not have thought of.
And because that wouldn't be something quick to add, and Slice seems against it, I'm not too sure you'll see that soon.
But maybe you can convince us...

**Comment by fabiosun** [comment]
> why you want this
I use OCLP (opencore legacy patcher) to use my wireless/bt in macOS Sonoma
OCLP needs for this:

1) sip disabled
2) block a kext
3) adding some old kexts in kext/other

In this condition is not possible to update macOS via delta update (i update my system often)

So in Opencore I create a second EFi with:
1)SIP Enabled
2) unblock the kext
3)disabling old kexts (untick in config.plist)
I choose this with your Bootloader chooser
clear Nvram
Start Sonoma and i do the delta update from system/Software update

restart the system
relaunch OCLP (opencore legacy patcher)
and then with Bootloader chooser 
i use the EFi with sip disabled and kext blocked and old Kexts injected in Kext folder.

In Clover is more simple (but it could be simpler with my whishlist feature)

I have only an EFi with 2 config.plist
one useful to update so with sip enabled, unblocked kext and with old kext in CLOVER/Kext folder which i untick in bootmenu option

One EFI  useful to start root patching with  OCLP with the specs i said before for opencore bootloader

So to have it working well with clover i do this steps
1) change config.plist to config-1.plist
2) reset Nvram
3) untick manually those kext prelinked one and the two in Other folder

from here my wish list
It seems from a no expert programmer point of view  Clover has this "feature" , it is only not exposed and available in config.plist

obviusly i am not able to understand if this is a big job to do 
I have only asked to you (Slice and you) if this opportunity is there or i too much complex to do 

> But maybe you can convince us...

I cannot do better of above lines! :)

**Comment by jief666** [comment]
> block a kext
> adding some old kexts in kext/other

Which one ?

> delta update

What is "delta update" ? The normal update process from inside macOS ?

> In this condition is not possible to update macOS via delta update (i update my system often)

Shouldn't we instead find why you can't update ? Is this a know unsolvable problem ?

> 2) unblock the kext

Which one ?


Do you know that there is a feature I did a long time ago (yeah, I know, we don't really have a documentation)  which allow you to enable kext only for install or recovery.
If you want a kext to only be enabled for Sonoma install, just put it in a folder called 14_install. If it's for recovery, use 14_recovery. If you want a kext be used for only "normal" boot, use 14_normal. Any kext in 14 will be used for all boots.
NOTE : it's even possible to use folder like 14.1, 14.1_normal, 14.1_install, 14.1_recovery if you need a kext for a very specific version. You can even use 14.1.2 for a very very specific version.

**Comment by fabiosun** [comment]
> Which one ?

IO80211FamilyLegacy.kext
IOSkywalkFamily.kext

> What is "delta update" ? The normal update process from inside macOS ?

Yes from here:
<img width="721" alt="image" src="https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/519e3c44-c6f7-4b91-acac-bd65484ccf52">

> Shouldn't we instead find why you can't update ? Is this a know unsolvable problem ?

I think is a known problem when people use some config.plist parameter (SIP,SecureBoot ) and OCLP Root Patching
I think also is "unsolved"

> Which one ?

<img width="479" alt="image" src="https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/1eb4ef54-f633-4752-9e6a-aba1ee799682">

and this is yet possible to uncheck via config.plist

> Do you know that there is a feature I did a long time ago (yeah, I know, we don't really have a documentation) which allow you to enable kext only for install or recovery.

No and it seems a very good undocumented feature :)
But it seems to me that it can't satisfy my wishlist or am I wrong?

basically, without the root patch running the OCLP app, I can't use WIFI in macOS Sonoma
The patch allows (by breaking the operating system seal) to blockSkywalk, as we can now also do properly in CLover bootloader and use the macOS Ventura kexts useful for wifi
these kexts mentioned just above:
IO80211FamilyLegacy.kext
IOSkywalkFamily.kext

so, the solution of having two config.plist seems to me the only one at the moment
Or continue as I am doing
I prepare the two configs with the options I can already do , i.e. SIP, BlockSkywalk, and then manually change the config during the boot menu and complete what is needed by pressing space and then the option to block kexts in the Clover/Kext/xxx folder

thank you again for your listening

PS I am trying everything to convince you :) :)
Am I succeeding? :)

**Comment by jief666** [comment]
If I understood well, you need to add this 2 kexts for wifi :
- IO80211FamilyLegacy.kext
- IOSkywalkFamily.kext
but doing so prevent you from updating.

Again, if I understood well, you'd like to block these 2 kexts and unblock the original one to be able to update. Am I right ?

**Comment by fabiosun** [comment]
Yes :)
but internal OSX kext is yet possible to block and to unblock
see here
https://github.com/CloverHackyColor/CloverBootloader/issues/670#issuecomment-1913137648

**Comment by jief666** [comment]
> but internal OSX kext is yet possible to block and to unblock

prelinked kext (the one on macOS drive) can be block or unblock. The one in Clover kext folder cannot. The idea is : if you don't need a kext, you put it in there.

> so, the solution of having two config.plist seems to me the only one at the moment

Yes, I can't see how you would get around that.

Do you have to restore original IOSkywalkFamily to be able to see the update ? I'm still not sure when you need to restore the original IOSkywalkFamily.

What about 2 Clover folders and BootloaderChooser ? Wouldn't that be the simplest anyway ?

**Comment by fabiosun** [comment]
> Do you have to restore original IOSkywalkFamily to be able to see the update ? I'm still not sure when you need to restore the original IOSkywalkFamily.

it is an OCLP procedure (root patching and revert it when you have to update the system)
And it is not that..also differences in SIp and i SecureBootModel





> What about 2 Clover folders and BootloaderChooser ? Wouldn't that be the simplest anyway ?

Yes in this way it is the same i do in Opencore bootloader
I thought with option we have in Clover Bootloader at the boot menu stage this was possible to achieve in a different way with only 2 config.plist and 1 EFI

I will go on to do this how i do know
press space bar and untick stuff i cant untick in config.plist with a plist editor

**Comment by YBronst** [comment]
Okay, you block these kexts, but how will you download delta updates? Over a wired connection? Or do you have a USB WiFi stick? If via an apvo connection, then I don’t see a problem with temporarily moving old kexts to the off folder. Then there is no need to fence the garden.

**Comment by fabiosun** [comment]
@YBronst with the original Sonoma ones

**Comment by fabiosun** [comment]
> then I don’t see a problem with temporarily moving old kexts to the off folder.

Probably i cant transfer well my thoughts 
or you do not use OCLP to patch modern wifi wireless in SOnoma

**Comment by YBronst** [comment]
To begin with, you placed the old kexts in the wrong place.
Еhe old kexts should be in the folder 14 from which they are loaded only in Sonoma.
RestrictEvents.kext solves problem  the new unknown processors and number of memory banks, with SMBIOS Mac Pro. It can be in the  folder others and you don’t need to disable it for delta updates.

I don’t understand what doesn't give you just do this?

1. Сhange config.plist to config-1.plist;
2. Disabling old kexts (by pressing space);
3. Start macOS;
3. Do the delta update from system/Software update and just restart the system (when she asks);

If only Wi-Fi is not working, then no one forbids to you connect a USB Wi-Fi dongle stick, or wired connection.

There is no need to edit config, or reset the NVRAM.

Before Shabbat, I regularly updated Sonoma and Ventura that way. :)

I have 3 physical drives, each of which has its own set of operating systems and bootloaders. The first one has Windows and Sonoma + Clover installed. On the Second Ventura + Clover. On the third there is only file storage + OpenCore for emergency cases.
I asked Slice to move the CsrActiveConfig parameter from the RtVariables section to the SMBIOS section, which could reduce the number of Clovers, but was refused.
I have already found how to do this myself, even without being a great expert in C++ and C but this will take some time. If this modification will be completed, I'll make my own fork of Clover.

**Comment by jief666** [comment]
> it is an OCLP procedure (root patching and revert it when you have to update the system)
> And it is not that..also differences in SIp and in SecureBootModel

I'm still not sure : you have to revert the root patching before downloading the update ?

**Comment by fabiosun** [comment]
> > it is an OCLP procedure (root patching and revert it when you have to update the system)
> > And it is not that..also differences in SIp and in SecureBootModel
> 
> I'm still not sure : you have to revert the root patching before downloading the update ?

YES

**Comment by fabiosun** [comment]
> To begin with, you placed the old kexts in the wrong place.
> Еhe old kexts should be in the folder 14 from which they are loaded only in Sonoma.
> RestrictEvents.kext solves problem the new unknown processors and number of memory banks, with SMBIOS Mac Pro. It can be in the folder others and you don’t need to disable it for delta updates.

Please read well what i have written and please do not a lesson to me
i use only Sonoma
and i use kext in Other
and, i have no problem
if in a future i will have i create again the right folder for me

**Comment by fabiosun** [comment]
> But in this case, your WiFi will turn off.

yes as it shoul be because sonoma does not support wifi with broadcom and fenvi card (and others)
Tou are akways saying about Sip and move it in other place
here is a bit offtopic
i change SIP easily in my second config.plist

**Comment by jief666** [comment]
@fabiosun 
I understand you'd like only one Clover folder. Copies are a pain to sync.
Having only one Clover folder makes you go the the menu to change the config.plist, right ?

**Comment by fabiosun** [comment]
yes

**Comment by fabiosun** [comment]
@YBronst 
Or, or can you tell me and teach me how to do delta i OSX updates (no updates with a full installer but full) having OCLP installed
Or it is useless for you to repeat these things to me
Without any controversy
My initial question was mainly to see if I was doing something wrong or if it was a feature already available

we now understand that it is not available
The methods suggested in this peaceful discussion I know and apply them

**Comment by YBronst** [comment]
> > To begin with, you placed the old kexts in the wrong place.
> > Еhe old kexts should be in the folder 14 from which they are loaded only in Sonoma.
> > RestrictEvents.kext solves problem the new unknown processors and number of memory banks, with SMBIOS Mac Pro. It can be in the folder others and you don’t need to disable it for delta updates.
> 
> Please read well what i have written and please do not a lesson to me i use only Sonoma and i use kext in Other and, i have no problem if in a future i will have i create again the right folder for me

If you are stupid and don’t know the purpose of folders in Clover, then you don’t need to blame others for being stupid. Folder 14 is intended for those kexts that may turn out to be problematic in Sonoma, so that it is easier to block them by space, and others are placed in the folder that have been verified.
In short, I am categorically against the innovations you propose. This may break the kext injection logic.

**Comment by fabiosun** [comment]
> Having only one Clover folder makes you go the the menu to change the config.plist, right ?

double Yes
And this is a unique Clover Bottloader feature

**Comment by jief666** [comment]
@YBronst I think you should not use that tone...

**Comment by jief666** [comment]
@fabiosun Ok, so currently, you have to go in the menu to change config.plist and untick the 2 kexts you added in Other. Is it that correct ?

**Comment by YBronst** [comment]
> @YBronst I think you should not use that tone...

I am very sorry. He just annoyed me with his stubbornness. I will try to be correct in my statements.

**Comment by fabiosun** [comment]
I don't seem to have offended either you or jief who is trying to understand my request

Whether or not you are in favor of my proposal doesn't change that much
Since it's not law and it's just a wish list

whether or not there will be this news I will continue to use Clover

and you will probably continue to ask for something that they rejected and interfere in a discussion that wasn't controversial without your intervention

i love you anyway
Shalom

**Comment by jief666** [comment]
@YBronst That for the apology. Please do not answer when you are annoyed.

**Comment by jief666** [comment]
@fabiosun Ok, so currently, you have to go in the menu to change config.plist and untick the 2 kexts you added in Other. Is it that correct ?

**Comment by fabiosun** [comment]
yes

**Comment by jief666** [comment]
So that feature would be to avoid you having to untick 2 kexts in a menu, but that you would still have to go into the Clover menu.

**Comment by YBronst** [comment]
> @YBronst That for the apology. Please do not answer when you are annoyed.

Fine! I didn’t like the way you started arguing with me. I won't answer anymore. But I am against bringing options from OpenCore into Clover.

**Comment by jief666** [comment]
> Fine! I didn’t like the way you started arguing with me. I won't answer anymore. But I am against bringing options from OpenCore into Clover.

I never said I agreed. I'm trying to understand exactly. I also learn about this thing about IOSkyWalk that I didn't know few days ago.

**Comment by fabiosun** [comment]
> So that feature would be to avoid you having to untick 2 kexts in a menu, but that you would still have to go into the Clover menu.

sorry maybe i have not understood well
if feature is there 
i would press O and then only change the config to the right one (sip, and others) and the press Fkey to clear nvram (this to change the sip to the right value)

**Comment by jief666** [comment]
And if the feature is not there, you would press O and then change the config to the right one (sip, and others), then untick the 2 kexts and the press Fkey to clear nvram (this to change the sip to the right value).

I don't think this feature would change much for you. It'll save you 2 unticks in the kexts menu.

**Comment by fabiosun** [comment]
> I don't think this feature would change much for you. It'll save you 2 unticks in the kexts menu.

unticking could be usuful if you have also other kext to untick as ie here:
<img width="1106" alt="image" src="https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/959c1b7c-b1e9-4a6e-a695-4739d339d3e3">
this is a real Mac Pro 5.1 i am trying to use in it your chooser and clover (and i am dfailing for now)
I will close this issue and sorry for your tie lost ;)

**Comment by jief666** [comment]
@fabiosun Don't close. It's fine. Let's try to understand. There is something you don't know or something I don't know. Let's try to find out.
I don't know what it the software on this screenshot. When I say untick kexts, I'm saying untick that in Clover menu. Do you know that you can untick kexts from the Clover menu ?

**Comment by fabiosun** [comment]
Do you mean as i show in originate post in first message of this issue?

> Don't close. It's fine. Let's try to understand.

I don't like misunderstandings even though this time I don't seem to have said anything
one can agree or disagree with opinion without "bombarding" the other with a "stupid" epithet

**Comment by YBronst** [comment]
@fabiosun Don't close. 

> > I don't think this feature would change much for you. It'll save you 2 unticks in the kexts menu.
> 
> unticking could be usuful if you have also other kext to untick as ie here: <img alt="image" width="1106" src="https://private-user-images.githubusercontent.com/6358373/300191484-959c1b7c-b1e9-4a6e-a695-4739d339d3e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNzM5MzEsIm5iZiI6MTcwNjM3MzYzMSwicGF0aCI6Ii82MzU4MzczLzMwMDE5MTQ4NC05NTljMWI3Yy1iMWU5LTRhNmUtYTY5NS00NzM5ZDMzOWQzZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMTY0MDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhiZTA2ODM0NGQ0YzZjYWY1N2I3ZjBkOWM2ZTZkZGNhYzc4NDc0NDNlZGFjNGExYzA5Zjg2ZDhhNTczZjY2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.USopg9gVxdbdDmGOtUOKKSyx37uBBbIlktotHkz8yUQ"> this is a real Mac Pro 5.1 i am trying to use in it your chooser and clover (and i am failing for now) I will close this issue and sorry for your time lost ;)

This may be helpful for understanding. As for the real Mac, I can assume that the failure was due to the order of the kexts in the table. Here is the right order that allowed my old Mac Pro 6.1 to boot into Sonoma.

**Comment by jief666** [comment]
> Do you mean as i show in originate post in first message of this issue?

Yes, what's wrong with that ? Because we know that you have to go into some Clover menu anyway.

**Comment by jief666** [comment]
What's this editor you are using for config.plist ?

**Comment by fabiosun** [comment]
> was due to the order of the kexts in the table.

See  @YBronst , that's what I expect from you being an experienced user.
Not the personal attacks <3

On that mac I can't run sonoma because I have mounted an RX6600 graphics card which is not supported by OCLP for the time being
In a Hack it works well also in sonoma
In Mac Pro 5.1 only till Monterey (it is a CPU feature list).
but here a bit off topic
i try to convince @jief666 using all my arrows :)

@jief it i a graphical plist Editor (OCAT) it is only OpenCore compatible

**Comment by YBronst** [comment]
> What's this editor you are using for config.plist ?

I usually use PlistEdit Pro.app, but in the case of the OC - OCAuxiliaryTools.app

**Comment by YBronst** [comment]
> > was due to the order of the kexts in the table.
> 
> See @YBronst , that's what I expect from you being an experienced user. Not the personal attacks <3
> 
> On that mac I can't run sonoma because I have mounted an RX6600 graphics card which is not supported by OCLP for the time being In a Hack it works well also in sonoma In Mac Pro 5.1 only till Monterey (it is a CPU feature list). but here a bit off topic i try to convince @jief666 using all my arrows :)
> 
> jief it i a graphical plist Editor (OCAT) it is only OpenCore compatible

Never mind, I wasn't offended. And don't be offended by me.
But here I don’t agree with you. Radeon RX 6650 XT works fine for me in Mac pro 6.1 and in other hacks.

**Comment by jief666** [comment]
There is 2 conversations going on at the same time at that doesn't make it easy.
YBronst : you seems to speak about disable kexts by modifying your Clover folder prior to reboot.
It seems to me that fabiosun would like to be able to reboot without having to modify his clover folder.

**Comment by jief666** [comment]
Let's not add a conversation about graphic cards, please.

**Comment by YBronst** [comment]
> There is 2 conversations going on at the same time at that doesn't make it easy.
> YBronst : you seems to speak about disable kexts by modifying your Clover folder prior to reboot.
> It seems to me that fabiosun would like to be able to reboot without having to modify his clover folder.

Probably yes!

**Comment by jief666** [comment]
@fabiosun so far, it seems to me that this feature would only save you to go in the kext Clover menu. Am I correct ?

**Comment by fabiosun** [comment]
> t seems to me that fabiosun would like to be able to reboot without having to modify his clover folder.



> It seems to me that fabiosun would like to be able to reboot without having to modify his clover folder.

correct
but also correct order could be a good point to discuss :)
with those two kexts i would like to untick we have a great fortune in Clover
Inside one of these kext there is a plugin folder
with inside another kext
Clover add automatically in the right order and all the patches work
with opencore we have to declare the correct order (please dont get it wrong i am not comparing two booloaders)

**Comment by fabiosun** [comment]
> But maybe you can convince us...

I am losing in this convincing work :)

**Comment by jief666** [comment]
The principle of Clover is to handle everything that exists in folders. ACPI, Kext, Drivers.
The principle of OC is to redundantly have the kext (acpi and drivers as well) declared and enabled in config.plist. The benefit of this redundancy is to be able to choose the order manually.
I don't think we will change that principle. So being able to block a kext that you put in the right folder seems to counteracting settings. It's true that you have to manually delete the plugins you don't want. Which is annoying to remember when you update a kext that contains plugins. So a feature like you propose would allow to disable once for all a plugin.

And there is still this order problem. The truth is that the order can be deduced from dependency that's in kext plist. I really don't know why OC didn't do that. I was planning to do that in Clover but ran out of time. So now, some order is hard-coded in Clover (for example lilu first, etc).

> I am losing in this convincing work :)

Not sure. I like the idea that it'll fix the plugins problem. 

I didn't follow about the order of kexts. Is it another problem ?

Have you tried to reboot, allowing the Sonoma IOSkyWalk, without disabling the kexts in the Clover menu ? The IOSkyWalk from Clover should be ignored because of a kernel link problem.

**Comment by fabiosun** [comment]
> Have you tried to reboot, allowing the Sonoma IOSkyWalk, without disabling the kexts in the Clover menu ? The IOSkyWalk from Clover should be ignored because of a kernel link problem.

you mean two kexts in Others or in 14 folder or the one i could block in clover config,plist?

**Comment by fabiosun** [comment]
<img width="491" alt="image" src="https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/cf95d796-1336-43f1-99a2-18508782eb63">
these two kext or the other inside the config.plist?

and this is for the order (not a problem luckily in this case)
<img width="399" alt="image" src="https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/2587f2fc-5746-4718-9c24-ed89453789d1">

**Comment by jief666** [comment]
Having kexts in Other or in 14, when you boot Sonoma, doesn't make a difference at all. Both folder contents will be added to the list of kext to add.
You said you have to unblock the original IOSkywalkFamily (by changing the quirks in config.plist), therefore you have to disable OSSkywalkFamily that you have in kets/Other.
Did you try to unblock the original IOSkywalkFamily boot with all kexts you have in Other ?

**Comment by fabiosun** [comment]
> Did you try to unblock the original IOSkywalkFamily boot with all kexts you have in Other ?

No i try by now

by the way
a stupid idea
is it possible to create a folder xx with inside some kext and then untick them in config.plist?
so the original idea of CLover stay as devs studied in the past..and i and maybe others will be happy :)

iknow....it is the same things to do in other forms :)

**Comment by fabiosun** [comment]
<img width="514" alt="image" src="https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/521db82e-e337-4584-bc24-acb1e721862f">
first step 
now rebooting

**Comment by jief666** [comment]
Then can you update ? (Problem may be : there is no update available to test)

**Comment by YBronst** [comment]
I have now launched the installation on a third computer identical to mine from a flash drive that was created before the release of Sonoma 14.1 and will try to go through all the steps sequentially.
I have another Wi-Fi card, Fenwi T-919.
And I’ll write what happens.

**Comment by fabiosun** [comment]
> Then can you update ? (Problem may be : there is no update available to test)

[2024-01-27_17-39_CLOVERX64.efi.log.zip](https://github.com/CloverHackyColor/CloverBootloader/files/14073243/2024-01-27_17-39_CLOVERX64.efi.log.zip)
it hangs immediatey
![WhatsApp Image 2024-01-27 at 18 44 29](https://github.com/CloverHackyColor/CloverBootloader/assets/6358373/78da2a3c-7130-45e2-a50d-e942b1d51523)

**Comment by fabiosun** [comment]
It seems Clover considers the same kexts and they conflict with unblocked system one that is newer

**Comment by jief666** [comment]
From your log, it looks like OC linked that kext even though it already exist in the kernel.
So I guess you'll have to deactivate these kext for now.

**Comment by fabiosun** [comment]
it is a similar error we have before you adjusted skywalk block in configplist

**Comment by YBronst** [comment]
The first stage is completed. WiFi doesn't work. The USB dongle stick wor
![Снимок экрана 2024-01-27 в 20 03 17](https://github.com/CloverHackyColor/CloverBootloader/assets/157227982/41aaf4ea-1892-4052-a01c-6481cd76ab88)
![Снимок экрана 2024-01-27 в 20 02 37](https://github.com/CloverHackyColor/CloverBootloader/assets/157227982/c9628a52-f075-470a-b523-aec3c465d6d8)
ks. Now I'll use OCPL and try to rollback.

**Comment by YBronst** [comment]
Booted with these settings:
![Снимок экрана 2024-01-27 в 20 16 42](https://github.com/CloverHackyColor/CloverBootloader/assets/157227982/b4c0b72f-8c6d-4155-a0e6-e8c0ae3e036e)
![Снимок экрана 2024-01-27 в 20 15 19](https://github.com/CloverHackyColor/CloverBootloader/assets/157227982/4bd41fdd-7700-4ee5-bc5d-6fb34b4e19bb)
![Снимок экрана 2024-01-27 в 20 17 52](https://github.com/CloverHackyColor/CloverBootloader/assets/157227982/f99b0297-7de2-4f9d-b796-cdccfeee2eb3)

**Comment by fabiosun** [comment]
@YBronst if i am not wrong Jief asked to try with those two kexts in your 14 folder

in condition you show in pictures it works and you are updating as it should be also for me blocking those kexts

**Comment by YBronst** [comment]
> @YBronst if i am not wrong Jief asked to try with those two kexts in your 14 folder
> 
> in condition you show in pictures it works and you are updating as it should be also for me blocking those kexts

Now I will try your method. But first you need to update to 14.2 :)

**Comment by jief666** [comment]
> it is a similar error we have before you adjusted skywalk block in configplist

Ah yes sure. So yes, for now you'll have to disable these kext by untick them in Clover menu or by moving them out of the Other folder.
For the feature, I understood @SergeySlice is against it. Is it still the case ? Personally, I like the ability to disable plugins so I'm not 100% against it, but for sure I don't have time right now to implement it.

**Comment by YBronst** [comment]
> > it is a similar error we have before you adjusted skywalk block in configplist
> 
> Ah yes sure. So yes, for now you'll have to disable these kext by untick them in Clover menu or by moving them out of the Other folder. For the feature, I understood @SergeySlice is against it. Is it still the case ? Personally, I like the ability to disable plugins so I'm not 100% against it, but for sure I don't have time right now to implement it.

I'll try now, it says another 12 minutes.

**Comment by jief666** [comment]
> @YBronst if i am not wrong Jief asked to try with those two kexts in your 14 folder

I thought the link would fail if 2 IOSkywalkFamily.kext were present. But no, it is still linked, therefore crash. Thanks for the test.

**Comment by fabiosun** [comment]
> I'm not 100% against it, but for sure I don't have time right now to implement it.

'm glad I caught your attention

in Italy let's say I put the flea in your ear! :)

**Comment by jief666** [comment]
> in Italy let's say I put the flea in your ear! :)

I'm not sure I like the idea of flea in my ears :-)

**Comment by YBronst** [comment]
And so, now I have Sonoma 14.2 and I can apply OCPL and do a rollback.

**Comment by YBronst** [comment]
All. We've arrived. KP! At the same stage. :(

**Comment by fabiosun** [comment]
> > in Italy let's say I put the flea in your ear! :)
> 
> I'm not sure I like the idea of flea in my ears :-)

annoyance will make you plan, in the case, more quickly :)

**Comment by YBronst** [comment]
Hm. The second reboot was successful. I probably forgot to do something in Clover's menu.

**Comment by YBronst** [comment]
I'm done. 2 KP and 4 reboots. It is very difficult to catch the moment when you need to press the key (O). But I still installed the update. I applied OCPL and Wi-Fi also worked.
