### ISSUE TITLE
Failure boot Clover-5152 ?

### ISSUE THREAD

**Issue by Acid0hacK** [CloverHackyColor/CloverBootloader#676]
![IMG_6876](https://github.com/CloverHackyColor/CloverBootloader/assets/161499624/fbfab5f8-5b9a-4ec4-b085-484b46d894f8)
Who know whats happening ? After create with BDU bootable flash drive, booting only this and i don't see standard graphic interface.
See only this interface, like on screen.

MB: Gigabyte P55-USB3
CPU: i7-870

**Comment by SergeySlice** [comment]
It means you booted llegacy way BIOS->MBR->PBR->boot (CloverEFI) and see the screen. But next step should be /EFI/CLOVER/CLOVERX64.EFI which is absent.

**Comment by sambow23** [comment]
I'm having the same issue but CLOVERX64.efi is present 
![image](https://github.com/CloverHackyColor/CloverBootloader/assets/14916663/8eee5b57-8eb2-41dc-b614-ff23c2b02673)

**Comment by SergeySlice** [comment]
Then you booted one drive while Clover located on other drive.

**Comment by sambow23** [comment]
> Then you booted one drive while Clover located on other drive.

It's booted directly off the USB with no other drives in the system. There is only 1 FAT32 partition with clover on it

**Comment by SergeySlice** [comment]
I know the screen from topic starter. It is an interface of boot6 (reduced DUET) and it appears if CLOVERX64.EFI is not found.
You may navigate through the menu and see where is the file.
