### ISSUE TITLE
Why use 7z to compress CLOVERX64.efi

### ISSUE THREAD

**Issue by xxxzc** [CloverHackyColor/CloverBootloader#69]
`CLOVERX64.efi` was compressed to 7z in release 5102, why not just attach an `.efi` or compress to zip?

**Comment by vectorsigma72** [comment]
It is a file,  so I guess it can be released as is, without any compression.

**Comment by SergeySlice** [comment]
OK, let it be zip

**Comment by xxxzc** [comment]
Thanks!
