### ISSUE TITLE
CANT SEE  efi boot from efi option in clover bootloader

### ISSUE THREAD

**Issue by Rammy4438** [CloverHackyColor/CloverBootloader#700]
Hi , I am trying to add a nvme drive to an old pc, after watching a couple of tutorials I managed to make a USB a boot drive using clover , but the problem is I can not see the EFI BOOT FROM EFI option, hence I still can't use my nvme ...... please help...###

**Comment by SergeySlice** [comment]
You have to add NvmExpressDxe.efi to /EFI/CLOVER/drivers/BIOS/ as far as I understand you have old computer with BIOS and without UEFI.

**Comment by SergeySlice** [comment]
abandoned
