### ISSUE TITLE
Can't boot into Clover GUI when PCIe USB has an external HDD plugged in

### ISSUE THREAD

**Issue by eugenesvk** [CloverHackyColor/CloverBootloader#704]
After much trial and erorr I've managed to find a working version of clover Clover (old 5070) to boot Windows off an NVMe drive connected via the first PCIe→NVMe card for some rather old PC (as well as maintaining bootability via Clover into the old SSD)! Thanks!

But then I've discovered a strange bug: if I have an old HDD MBR NTFS plugged into that second PCIe→USB3 card, clover fails to boot into its GUI, it gets stuck at the `ScanVolumes` stage even without any NVMe drivers, so in the log it doesn't even see the connected drives

Interestingly enough, after reformatting the HDD into the same MBR NTFS, but without the extra exFAT partition, Clover loads fine. And then reformatting it into the same MBR NTFS and with an extra exFAT partition it also loads fine. Weird!

Do you know why this non-bootable drive blocks Clover GUI?

The config and debug logs
- [config](https://gist.github.com/eugenesvk/608e255c341c438fe3c5489272c6d6c5#file-config-plist)
- [failed debug](https://gist.github.com/eugenesvk/608e255c341c438fe3c5489272c6d6c5#file-debugfail-exthdd-usb-c-pcie) the only difference is that it just stops after enumerating all the drives, otherwise identical
- [successful debug](https://gist.github.com/eugenesvk/608e255c341c438fe3c5489272c6d6c5#file-debug-ok-no-external-hdd)

<details>
<summary>Some system details</summary>

- Clover: v5070 burned USB Flash drive (MBR FAT32 via BDUtility) with not extra drivers added (for testing, not even NvmExpressDxe)
- BIOS is set to boot from HDD first and USB with Clover is manually selected first from the list (BIOS doesn't see any of these PCIe drives, neither the NVMe nor the USB3 ones)
- MB : BIOS/legacy only (no UEFI option) Gigabyte GA-EX58-UD5 (2008) [lnk](https://www.gigabyte.com/Motherboard/GA-EX58-UD5-rev-10/sp#sp)
- CPU : Intel Core i7-920 (2008) [lnk](https://www.intel.com/content/www/us/en/products/sku/37147/intel-core-i7920-processor-8m-cache-2-66-ghz-4-80-gts-intel-qpi/specifications.html)
- NVMe M.2 SSD: Samsung 980 500G (2001), GPT UEFI 3 partition (EFI system, Windows, data)
- old SATA SSD, MBR 2 partitions (system and recovery)
- external HDD that blocks Clover when connected via PCIe USB3: also old MBR with 2 paritions: NTFS and exFAT, not bootable, no secret EFI system partition
  - same dirve NTFS MBR without exFAT partition doesn't block
- PCIe card for **NVMe**
- PCIe card for **USB3**

</details>

**Comment by SergeySlice** [comment]
When someone report a possible bug he should use latest Clover version because all bugs already resolved.

**Comment by eugenesvk** [comment]
That's not true because the new versions don't work at all, so its supposedly resolved bugs are even worse
