### ISSUE TITLE
Question: dual boot, hiding drives + drive emulation

### ISSUE THREAD

**Issue by fu8765** [CloverHackyColor/CloverBootloader#706]
Please excuse me if the question is silly. 

1) Is it possible with Clover to configure a dual boot but hide the non booted OS drive from the booted OS, so there is no possible access whatsoever?

This would be very useful for things like malware disassembly and analysis

2) I'm sure this is not possible but would love this feature. 
Mapping a partition for the OS to see it as a whole disk.

Could be useful for installing OSs that can be dual booted from the same drive, such as chromeOS that creates a ton of partitions.

Just my 2c

Thanks for the hard work

**Comment by SergeySlice** [comment]
1. Not possible. Clover see or not see drives and partitions on drives but OS has own opinion what to show or not.
2. Same. The task is for OS but not for Clover
