### ISSUE TITLE
Package Clover.app-v1.14-5103.zip is damaged.

### ISSUE THREAD

**Issue by papasax** [CloverHackyColor/CloverBootloader#71]
And can't be opened.
![Capture d’écran 2020-01-07 à 11 30 23](https://user-images.githubusercontent.com/8015117/71888769-1ac56200-3141-11ea-8388-cbc7221a18a0.png)

**Comment by esetnik** [comment]
I saw the same thing but was able to fix it using

`❯ xattr -cr /Applications/Clover.app`

**Comment by roddy20** [comment]
it is normal behavior for unsigned app by unknown deleloper
xattr -cr /Applications/Clover.app
or 
Ctrl+Open to start it

**Comment by papasax** [comment]
I tried again today and now it's working. Still don't know what happened. (@roddy20 and esetnik : It was not the unknown developer message but the broken app message).
I'm closing the issue anyway.

**Comment by esetnik** [comment]
@papasax I had the broken app message the same as your screenshot in the original bug. I think this should be left open as I’ve experienced it with every version of Clover.app.

**Comment by papasax** [comment]
@esetnik As far as I'm concerned, I can not reproduce the issue so I'm closing it. 
It could be a github bug. Feel free to re open it if you want.

**Comment by NiklasBr** [comment]
@esetnik Are you *sure* the app is broken? Are you sure you are simple not experiencing [this](https://support.apple.com/en-us/HT202491 "How to open an app that hasn’t been notarized or is from an unidentified developer")?

**Comment by roddy20** [comment]
> @esetnik As far as I'm concerned, I can not reproduce the issue so I'm closing it.
> It could be a github bug. Feel free to re open it if you want.

it s not a bug, it is system protection feature

**Comment by esetnik** [comment]
@niklasbr it is being detected as a malicious app as per the link you provided. So we should at least update the Readme with instructions for bypassing the issue as the Clover app won’t work on any Catalina system straight from a Github download.

![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macos/Mojave/macos-mojave-maiicious-app-alert-dark.jpg)
