### ISSUE TITLE
I can't see the clover gui menu on my legacy motherboard.

### ISSUE THREAD

**Issue by improbir** [CloverHackyColor/CloverBootloader#713]
![IMG-20241108-WA0005](https://github.com/user-attachments/assets/c042c5b1-8cbd-4ac0-b89d-258f8b58c1f2)

as soon as i am trying to enter into clover bootloader manager gui menu its just showing this menu.

**Comment by SergeySlice** [comment]
This screen means that /EFI/CLOVER/CLOVERX64.EFI is not found.
