### ISSUE TITLE
Clover only installs efi-backup folder and nothing else

### ISSUE THREAD

**Issue by leifadev** [CloverHackyColor/CloverBootloader#72]
I am following the Clover Setup portion of the Vanilla Hackintosh guide. I checked all the options that I needed to in the Customize menu. It only installs a folder named "EFI-Backups". I have tried to format my USB according to the guide and tried again. Here are the instructions below I followed.

I will link the guide [here](https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/building-the-usb-installer)
And the clover setup page [here](https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/clover-setup)

The portion of what options to check is quoted here:
> Install Clover for UEFI booting only
Install Clover to the ESP
Under UEFI Drivers:
AptioMemoryFix (the new hotness that includes NVRAM fixes, as well as better memory management)
Note: You can use OsxAptioFix3Drv located in UEFI Drivers -> Memory fix drivers if using the official Clover installer from SourceForge.  Optionally, you can download the final release of AptioMemoryFix from here 
HFSPlus (or VBoxHfs) - one of these is required for Clover to see and boot HFS+ volumes.  If you see the option to enable it in the installer, make sure it's selected - if you don't see it in the installer, verify that one of them exists in your Clover installs efi drivers folder
ApfsDriverLoader - (Available in Dids' Clover builds - or here) this allows Clover to see and boot from APFS volumes by loading apfs.efi from the ApfsContainer located on block device (if using AptioMemoryFix as well, ensure you have R21 or newer)
> 
If you could tell me what I should do that would be great!

**Comment by real-cereal-boy** [comment]
You want to map your USB to a diffrent type

**Comment by real-cereal-boy** [comment]
Also uncheck one one the options

> HFSPlus (or VboxHFS)

> ApfsDriverLoader

** These options are two different partions ONLY SELECT 1, Depending on your system type you want to choose one **
![DB0B784E-CC02-4B86-BBE4-E8A5DB7E491E](https://user-images.githubusercontent.com/57405158/72535932-36f68c80-382e-11ea-8f94-c380f92a535c.jpeg)

**Comment by SergeySlice** [comment]
Just a user mistake. There is no Clover issue.
