### ISSUE TITLE
r5103 hangs at "scan entries"

### ISSUE THREAD

**Issue by richardklingler** [CloverHackyColor/CloverBootloader#76]
Good morning

Trying to do a fresh Catalina install on a AsRock H270-Pro4 mainboard I get the "scan entries" message in Clover which stays forever....this is also true for r5102.....on an older release r4961 it scans fine...

Neither using VfsBox.efi nor HfsPlus.efi help...

Attached debug.log....which looks fine to me...

**Comment by richardklingler** [comment]
Hmm...see nothing to attach the logs...so put it here:

https://pastebin.com/1iR2JvPS

**Comment by richardklingler** [comment]
[debug.log](https://github.com/CloverHackyColor/CloverBootloader/files/4113295/debug.log)

**Comment by SergeySlice** [comment]
The hang is after 
13:364  0:391  found AppleSMC protocol
which is controlled by VirtualSMC.efi. 
It is not Clover issue.
