### ISSUE TITLE
Wrong FSB Speed After Bootup

### ISSUE THREAD

**Issue by scorpius** [CloverHackyColor/CloverBootloader#78]
At the boot prompt the FSB is 133Mhz, but once the OS loads the FSB is 533Mhz. This results in the OS running at half speed. I have an i7-860 cpu.

**Comment by SergeySlice** [comment]
Show log, please.

**Comment by scorpius** [comment]
[preboot.log](https://github.com/CloverHackyColor/CloverBootloader/files/4175196/preboot.log)
[debug.log](https://github.com/CloverHackyColor/CloverBootloader/files/4175198/debug.log)
![bootscr](https://user-images.githubusercontent.com/82129/74092300-e91d1f00-4a8f-11ea-8ba0-6259b603489e.png)
![sysinfo](https://user-images.githubusercontent.com/82129/74092302-efab9680-4a8f-11ea-8870-4f200ad74696.png)

Also enoch boots and the OS runs at normal speed, but various other things do not work, so I prefer clover. I must be missing some option or setting.

**Comment by SergeySlice** [comment]
System shows Bus Speed x4 compared to real.
Other issues should be reported separately.
