### ISSUE TITLE
Welcome to Clover 5096 --- scan entries --

### ISSUE THREAD

**Issue by G3NSVRV** [CloverHackyColor/CloverBootloader#8]
I've installed Clover into a Catalina media image created on a thumb drive from Mojave; I've selected install only EFI and select dark theme.

From this point I just got a black screen, someone recommends to me install Lilu kext, and before of that I finally saw something which is this message:

![ba4a40fe-ca23-49e8-9909-7c34eee8fdae](https://user-images.githubusercontent.com/11720535/67023617-756a9700-f0d9-11e9-9aa1-bc0628f0423d.jpg)

And is stuck forever.

I have a laptop ASUS FX504GE, secure boot disabled, virtualization too, boot on EFI.

```
Summary
		Operating System
			Windows 10 Home Single Language 64-bit
		CPU
			Intel Core i7 @ 2.20GHz	47 �C
			Coffee Lake 14nm Technology
		RAM
			16,0GB
		Motherboard
			ASUSTeK COMPUTER INC. FX504GE (U3E1)
		Graphics
			Generic PnP Monitor (1920x1080@60Hz)
			Intel UHD Graphics 630 (ASUStek Computer Inc)
			4095MB NVIDIA GeForce GTX 1050 Ti (ASUStek Computer Inc)	43 �C
			ForceWare version: 436.15
			SLI Disabled
		Storage
			119GB Hitachi HFM128GDJTNG-8310A (Unknown (SSD))
			931GB TOSHIBA MQ01ABD100 (SATA )	29 �C
			28GB SanDisk Ultra Fit USB Device (USB )
		Optical Drives
			No optical disk drives detected
		Audio
			Realtek High Definition Audio
```

**Comment by G3NSVRV** [comment]
I saw here that it was a bug in older versions:

https://www.tonymacx86.com/threads/solved-welcome-to-clover-4091-scan-entries-problem.225211/

**Comment by SergeySlice** [comment]
Set config.plist->Boot->Debug=YES
and attach here /EFI/CLOVER/misc/debug.log

**Comment by G3NSVRV** [comment]
This?

```
	<key>Boot</key>
	<dict>
        .....
		<key>Debug</key>
		<true/>
```

**Comment by SergeySlice** [comment]
The link is not working. Rename the file to txt and try again.
And use Clover 5097. May be the issue is already resolved.

**Comment by G3NSVRV** [comment]
That’s weird... I can download and open the file using incognito...

**Comment by SergeySlice** [comment]
OK.
I see the process stopped at line
`
23:034  0:044  === [ Found DSDT tables ] =================================
`
So this is the question what do you have in the folder
/EFI/CLOVER/ACPI/patched

**Comment by G3NSVRV** [comment]
oh, I haven't... I'm very new on this and I didn't saw any information out there to start everything from scratch, there's a lot of tutorials out there that basically comes with a preconfigured clover.plist files and other patches.

Thanks @SergeySlice I will try once and I will let you know if I found anything :)

**Comment by sprtm** [comment]
I'm stuck with the same error as OP. Trying to upgrade from Clover 5070 (works flawless). I've tried both 5097 and 5098, both stuck at the same place. debug.log attached.
[debug.log](https://github.com/CloverHackyColor/CloverBootloader/files/3790937/debug.log)

**Comment by SergeySlice** [comment]
The process stopped playing boot sound
`14:197  0:007  not found AudioIo to play
14:204  0:007  sound play end with status=Not Found
`
Exclude AudioDxe.efi as having problem with your hardware.

**Comment by bfitzgit23** [comment]
im getting sata HDD errors, here's my debug.log. I have no honest clue what it's saying, nor know how to fix/troubleshoot clover. I'm NOT skilled at hackintoshing either. 
[debug.log](https://github.com/CloverHackyColor/CloverBootloader/files/5102863/debug.log)

**Comment by asgmeonerandom** [comment]
> im getting sata HDD errors, here's my debug.log. I have no honest clue what it's saying, nor know how to fix/troubleshoot clover. I'm NOT skilled at hackintoshing either.
> [debug.log](https://github.com/CloverHackyColor/CloverBootloader/files/5102863/debug.log)

try. harder!

**Comment by bfitzgit23** [comment]
that isnt helpful, i've been dealing with this for weeks. i honestly cannot fix this on my own..

**Comment by bfitzgit23** [comment]
honestly you cannot expect someone to work with "try harder" and know what to do, that's literally telling them NOTHING, that's in no way helpful..regardless of skill level..
