### ISSUE TITLE
Add Better README.md

### ISSUE THREAD

**Issue by circutrider21** [CloverHackyColor/CloverBootloader#85]
## Explanation 
This Is a situation because I am a OS Developer for Peeled Fruit Studios. When I first came to this repository, I had no idea what this repository did a all. Neither did I know how to use this Bootloader. Most importantly, I won't understand until you write a README that explains how to use this Bootloader. I am currently working on Storm-OS which is our latest project, and I am looking for an alternative to GNU GRUB. I would be glad to use your Bootloader, but i don't know how to use it.

### Solution
I am willing to help you with this problem if you explain to me how this bootloader works

**Comment by CMMChris** [comment]
Clover is for running macOS on PC hardware. Why would you use such a bloated piece of software to not boot macOS but other OSes instead? Doesn't make any sense.

**Comment by circutrider21** [comment]
Now I understand **but other people won't unless you add a README**

**Comment by xstable** [comment]
I was piped to this repo by https://sourceforge.net/projects/cloverefiboot/files/
Can you tell me where to get the cloverefiboot here and how to use it?

A README with some basic-informations would definitely be a good Idea!

**Comment by circutrider21** [comment]
Exactly, that is how i feel

**Comment by RandomDSdevel** [comment]
@asava:  What resolved this issue, allowing you to close it?

**Comment by asava** [comment]
We prefer not to have documentation as part of open issues. It was tagged as documentation, and will be taken care of, when we get it to it. Thank you for your concern.
