### ISSUE TITLE
No pkg file for Release v5.0 r5105

### ISSUE THREAD

**Issue by Dodobibi** [CloverHackyColor/CloverBootloader#88]
All in title

**Comment by headkaze** [comment]
It's in a zip file ([Clover_r5105.zip](https://github.com/CloverHackyColor/CloverBootloader/releases/download/5105/Clover_r5105.zip))

**Comment by mruepp** [comment]
Clover Systems Preferences Updater still links to the pkg file. The link it opens after pressing update: https://github.com/CloverHackyColor/CloverBootloader/releases/download/5105/Clover_v2.5k_r5105.pkg

**Comment by vectorsigma72** [comment]
Solved
