### ISSUE TITLE
Clover hangs on Qemu

### ISSUE THREAD

**Issue by tensor5** [CloverHackyColor/CloverBootloader#90]
I'm new to Clover, so my way of running Clover might be incorrect.
I extract the `EFI` folder from `Clover-5105-X64.iso` into a GPT partitioned image disk named `clover.img`. The I run:

```sh
qemu-system-x86_64 -enable-kvm -m 2G -machine q35 -cpu host -drive if=pflash,format=raw,readonly,file=/usr/share/ovmf/x64/OVMF_CODE.fd -drive if=pflash,format=raw,file=OVMF_VARS.fd -drive if=virtio,file=clover.img,format=raw
```

From the EFI shell I can see the drive content, but when I type `fs0:\EFI\BOOT\BOOTX64.EFI` and it hangs. The OVMF files are provided by an Arch Linux package. Am I missing something?

**Comment by SergeySlice** [comment]
Never hands up! There are thousands nuance how to start QEMU.
One of possible way is to follow our way in the folder "qemu" in the Clover sources.

**Comment by tensor5** [comment]
It works if I set `-cpu Penryn`, but doesn't with `-cpu SandyBridge` or `-cpu host` (in my case host is an IvyBrigde). Any idea why?

**Comment by SergeySlice** [comment]
Because QEMU is not perfect.

**Comment by VictorGamer072YT** [comment]
> 
> 
> It works if I set `-cpu Penryn`, but doesn't with `-cpu SandyBridge` or `-cpu host` (in my case host is an IvyBrigde). Any idea why?

You probably want to use OpenCore to use the IvyBridge as host.

**Comment by tensor5** [comment]
@VictorGamer072YT I tried OpenCore but it has the same problem.

**Comment by SergeySlice** [comment]
I see no Clover issue. It is user issue how to use QEMU.
