### ISSUE TITLE
Clover Updater goes to the wrong web page to download r5105

### ISSUE THREAD

**Issue by najeebanwer** [CloverHackyColor/CloverBootloader#91]
When downloading the r5105 version of Clover, the updater goes to this URL:

https://github.com/CloverHackyColor/CloverBootloader/releases/download/5105/Clover_v2.5k_r5105.pkg

the download is actually located at:
https://github.com/CloverHackyColor/CloverBootloader/releases/download/5105/Clover_r5105.pkg

**Comment by SergeySlice** [comment]
You have to update the Updater.

**Comment by najeebanwer** [comment]
If you mean the Clover updater that is part of the Clover Preference Pane, I always upgrade the PrefPane when installing a new version of Clover.
![Screen Shot 2020-03-14 at 2 03 47 PM](https://user-images.githubusercontent.com/34123660/76688715-49f2c680-65fd-11ea-9794-71756f23fa3b.png)
If there is something else I need to do to update the Updater, please let me know.

**Comment by vectorsigma72** [comment]
> If you mean the Clover updater that is part of the Clover Preference Pane, I always upgrade the PrefPane when installing a new version of Clover.
> ![Screen Shot 2020-03-14 at 2 03 47 PM](https://user-images.githubusercontent.com/34123660/76688715-49f2c680-65fd-11ea-9794-71756f23fa3b.png)
> If there is something else I need to do to update the Updater, please let me know.

Bro, if you already Installed the last revision .... how can find a newer one if doesn't exist yet?

**Comment by najeebanwer** [comment]
@vectorsigma72 
Bro, the intent of this ticket is to report that there was a problem with updating from r5104 to r5105 because the Clover updater was attempting to download from the wrong URL. I was able to update to r5105 by manually downloading from the correct URL. 
The advice I was given is that "You have to update the Updater". I don't think that it is unreasonable to ask if just upgrading the Clover PrefPane is all that is required to "update the updater" so that this issue does not happen during the next Clover update.

**Comment by vectorsigma72** [comment]
> @vectorsigma72
> Bro, the intent of this ticket is to report that there was a problem with updating from r5104 to r5105 because the Clover updater was attempting to download from the wrong URL. I was able to update to r5105 by manually downloading from the correct URL.
> The advice I was given is that "You have to update the Updater". I don't think that it is unreasonable to ask if just upgrading the Clover PrefPane is all that is required to "update the updater" so that this issue does not happen during the next Clover update.

We discussed about this already [here](https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?do=findComment&comment=2710771) 15 days ago, so nothing to fix as was taken into account for the switch. In future will be no more this problem at every vx.xk.

**Comment by najeebanwer** [comment]
OK. Ticket Closed.
