### ISSUE TITLE
R5105 Dose not boot automatically 

### ISSUE THREAD

**Issue by Razor004** [CloverHackyColor/CloverBootloader#93]
R5105 Dose not boot automatically the default boot volume that i specify , had to downgrade to r5104 to fix the problem .

**Comment by SergeySlice** [comment]
No, they are the same.
Go to macOS, choose System Preferences -> StartupDisk and make restart from here.
Next restart will be automatic by timeout.

**Comment by Razor004** [comment]
I did that and the first restart works great then the second one doesn't boot by timeout .

**Comment by Razor004** [comment]
I have a update about this issue , on my pc usually dual boot with windows 10 so I have multiple drivers ( 2 ssds) on 1 ssd I have Mac OS 10.15.3 and on the other ssd I have windows 10 , if I unplug the ssd with windows, clover boots automatic by timeout , and if I plug it in clover sees the windows partitions and doesn't boot by timeout , I don't have this issue with 5104 , sorry for my bad English .

**Comment by SergeySlice** [comment]
5104 and 5105 are the same with this function.

**Comment by SergeySlice** [comment]
User's mistake

**Comment by brunoaduarte** [comment]
Not user's mistake. Problem still exists if user has another SSD with Windows 10 installed.
