### ISSUE TITLE
Stuck On Welcome To Clover 5102 scan entries on my Asus Tuf Gaming FX504

### ISSUE THREAD

**Issue by hax5434** [CloverHackyColor/CloverBootloader#95]
I did change the bios setting as said on guidelines and also booted normally but i always get the same error welcome to clover 5102 scan entries
![20200314_211735](https://user-images.githubusercontent.com/56289617/76706270-2ff3d980-670c-11ea-8e07-be121dc5838f.jpg)

**Comment by SergeySlice** [comment]
There is 5105 now.

**Comment by hax5434** [comment]
I'm new at this can you tell me how i can change it usb

**Comment by SergeySlice** [comment]
Download https://github.com/CloverHackyColor/CloverBootloader/releases and start Clover installation. Choose your bootable USB.
