### ISSUE TITLE
R5105 wrong instalation location

### ISSUE THREAD

**Issue by pagimamaun** [CloverHackyColor/CloverBootloader#97]
Hello 
I tried to update from 5104 from installer on catalina but r5105 was installed in wrong EFI folder
And there was no option to install clover (location and settings)
i had to update manually

**Comment by SergeySlice** [comment]
Installation log?

**Comment by pagimamaun** [comment]
Sorry my fault
i used Clover.app_v1.16_r5105.pkg 
With good package it's working fine (Clover_r5105.pkg)
Sorry again
