### ISSUE TITLE
Download URL on upgrade is wrong - 404

### ISSUE THREAD

**Issue by Macrisu** [CloverHackyColor/CloverBootloader#99]
On my Hackintosh, I get warning for the upgrade, but the link is wrong

ex:
https://github.com/CloverHackyColor/CloverBootloader/releases/download/5106/Clover_r5106.pkg

The correct link is:
https://github.com/CloverHackyColor/CloverBootloader/releases/download/5106/Clover.app_v1.16_r5106.pkg.zip

The problem started a few version ago.

**Comment by pit512** [comment]
You're almost right, lol, the correct link for Clover Bootloader should be :
https://github.com/CloverHackyColor/CloverBootloader/releases/download/5106/Clover_r5106.zip

**Comment by vectorsigma72** [comment]
> You're almost right, lol, the correct link for Clover Bootloader should be :
> https://github.com/CloverHackyColor/CloverBootloader/releases/download/5106/Clover_r5106.zip

Sorry no, the upload was wrong: https://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?do=findComment&comment=2712993
